### ISSUE TITLE
move stan/gm/arguments to some place sensible

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1015]
The `stan/gm/arguments` subdirectory is not strictly part of the language, so shouldn't be a subdirectory of `gm`.  I would suggest `command` or something that indicates it's for the command line.

Maybe it should go in `common`, but I'd prefer to rename `common` to something more descriptive that indicates it's something related to CmdStan/RStan/PyStan and not to generating models or any of our other libraries.

**Comment by syclik** [comment]
This will be taken care of with #1751.

**Comment by bob-carpenter** [comment]
No more `stan/gm` so this isn't relevant any more.  This will all get swept under the big refactor and tearing the repo apart issues.
