### ISSUE TITLE
head, tail, segment, and block operations for arrays

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1019]
It would be nice to be able to slice arrays the same way we can now slice matrices.  Ideally, this would work for arbtrary 1D and 2D arrays (int, real, other arrays, vectors, etc.)

My immediate use case is replacing

```
  real lp[T];
  lp <- rep_array(log_unif, T);
  for (s in 1:T)
    for (t in 1:T)
      lp[s] <- lp[s] + poisson_log(D[t], if_else(t < s, e, l));
```

with 

```
  real lp[T];
  for (s in 1:T)
    lp[s] <- log_unif
      + poisson_log(head(D,s-1), e)
      + poisson_log(tail(D,T - s + 1), l);
```

**Comment by jgabry** [comment]
I'm going to close this to reduce open issues and since this is essentially a non-issue.
