### ISSUE TITLE
densities for (inverse) Wishart over Cholesky factors

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1037]
It would be more efficient to have densities that can be used like

```
cholesky_factor_cov[K] L;
L ~ wishart_cholesky(..,L0);
Sigma <- L * L';
```

Where `Sigma` would then have a Wishart density and `L0` would be the cholesky factor of the parameter.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#43
