### ISSUE TITLE
de-spaghettify error_handling includes and reorgnize matrix directories

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1041]
The math error handling code is now defined in `math/error_handling/*.hpp` for basic tests and `math/error_handling/matrix/*.hpp` for matrix tests.

* [x] move `math/error_handling/matrix/*` to `math/matrix/error_handling/*`

* [x] make sure tests that only depend on ``std::vecto`r are in math/error_handling` and only those that really depend on matrices are in `matrix/error_handling`
    * [x] `check_matching_sizes.hpp`
    * [x] `check_size_match.hpp`
    * [x] `check_nonzero_size.hpp`
    * [x] `check_ordered.hpp` needs to either be made generic so it can handle `std::vector` and Eigen row vectors and column vectors, or the `std::vector` version needs to be pulled out; if they are going to remain specialized, `std::vector` error message should say "array" to match Stan users and the others (column vector and optionally row vector) should say "vector" (and optionally "row vector");  it also needs to remove the `return false;` after the `return dom_err;` because it's unreachable.

* [x] add doxygen doc to all error-handling functions indicating what the arguments are, all the funny `%<yadayada>%` requirements and so on;  the exact conditions under which an error is raised should also be specified

Do we really need all that result setting stuff?  If so
* [ ] add versions without the result to make it easier to call it from the client side without specifying dummies
and if not
* [x] just get rid of te arguments to set and avoid having to call dom_err a la Boost

If we want to keep all the indexing flexiblity (index by 1 for Stan, index by 0 for API), then we need to
* [x] add tests for all of the indexing and add some top-level doc somewhere on how to set this value if you're using the API and how to set it if you're just using Stan's API
otherwise
* [x] keep everything on an index by 1 basis for the Stan language and let the API users lump it
As far as I know, we don't have any autodiff API users, but people have expressed interest.

**Comment by syclik** [comment]
Closing this issue. Most of this has been dealt with between 2.5 and now (pre 2.6).
