### ISSUE TITLE
vectorize _rng functions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1044]
It would be nice to include R-like versions that take a first argument for the number of draws to make and return an array of those draws.  There's an issue with array types not being assignable to vectors (yet, anyway).  I don't think it's worth having additional row vector and column vector versions --- it's usually just for constructing simulation draws for the output.

Although not strictly necessary, it would be most useful if the vectorized methods did the heavy lifting on things like solving systems of equations for generating multivariate normals only once.

A really ambitious version would also allow vectorized parameters and set everything up to work like the probability functions with repeated computations minimized.

This is a pretty simple modular project that doesn't get into any of Stan's complicated internal data types for automatic differentiation.  But there are a lot of distributions, so a lot of functions and tests to add.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#45
