### ISSUE TITLE
index composition for multilevel fiddling

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1054]
A typical situation is something like this, which Sean Raleigh just brought up on the stan-users list:

```
for (index in 1:n)
   y[index] ~ normal(mu[school[index]], sigma);
```

Currently, the only way to vectorize this is as:

```
 {
    vector[n] mu_school;
    for (i in 1:n)
      mu_school[i] <- mu[school[i]];
    y ~ normal(mu_school, sigma);
 }
```

What I would like to have is some kind of composition function, which would allow this to be written as

```
  y ~ normal(compose(mu,school), sigma);
```

So that `compose(x,y)[n]` is the same size as `y` with entries defined by `x[y[n]]`.  

A more descriptive name than `compose` would be nice.  Also, are there other use cases than this simple form of composition?  Is there a way to generalize to different input types than the following?

```
T[] compose(T[], int[])
```

Should we alternatively just allow an array of integers to act as an index.  For instance, just use `mu[school]` with the understanding that it means the same thing as `compose`, i.e., `mu[school][n] = mu[school[n]]`?  Maybe this should be rolled into a more general issue of flexible R-like indexing for arrays and vectors/matrices.

**Comment by bgoodri** [comment]
This was implemented in 2.9
