### ISSUE TITLE
move rep_array, etc. out of math and into functions and matrix

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1067]
Currently, `stan/math.hpp` directly includes these:

```
#include <stan/math/rep_array.hpp>
#include <stan/math/rep_vector.hpp>
#include <stan/math/rep_row_vector.hpp>
#include <stan/math/rep_matrix.hpp>
```

They're on the wrong path.  The first (for `std::vector`) should go into `math/functions` and the remaining three (for `Eigen::Matrix`) into `math/matrix`.  The tests will have to move, too.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#46
