### ISSUE TITLE
partial initialization

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1069]
Allow users to provide partial initializations and take the rest randomly.  

This should be done a variable at a time --- that is, we won't allow a multivariate quantity to be partially initialized.

It would also be nice to expose the transforms we use along with their Jacobians to users in applications.

**Comment by syclik** [comment]
@maverickg, it's merged -- feel free to update RStan to handle partial inits.

**Comment by maverickg** [comment]
@syclik  thanks. 

rstan has a branch to use it now.

**Comment by mathDR** [comment]
Was pystan ever updated to use partial inits?  Anyone know?
