### ISSUE TITLE
matrix power operator

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1073]
Extend the power operator (`^`) to signature `(matrix,int):matrix`, with definitions

* `A^0 = I`
* `A^n = A^(n-1) * A`  for `n > 0`

Throw an exception if `A` is not square or if `n` is not positive.

This should be easy to build.  Extra credit if there's something clever that can be done for the gradients of each `A^n[i,j]` with respect to each `A[i',j']`.  Just storing the gradients is going to be order `K^4` for a `K` by `K` matrix.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#47
