### ISSUE TITLE
untangle reverse-mode from forward-mode autodiff; include finite diffs

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1074]
As of Stan 2.4, the code in `agrad/fwd` has dependencies into `agrad/rev` and the finite diff code is spread all over.

What I propose is creating four directories under agrad:

* `finite-diff`:  for finite difference code
* `fwd`: forward mode only, no dependency on reverse mode
* `rev`: reverse mode only, no dependency on forward mode
* `fwd-rev`: mixed code that depends on both fwd and rev

and moving pieces into the appropriate place to remove the spaghetti dependencies.

* [ ] `src/stan/agrad/fwd/matrix/typedefs.hpp` includes rev

**Comment by syclik** [comment]
this was fixed with #1222.
