### ISSUE TITLE
Check Inputs In cholesky_decompose

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#1076]
At the moment cholesky_decompose assumes that the input matrix is positive-definite.  When it is not there is no error and the output is given values as if the factorization is incorrect.  Needless to say, this leads to some frustrating debugging.  Either cholesky_decompose needs to throw an error if the Eigen fail bit is set, check for positive-definiteness, or require cov_matrix inputs.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#48
