### ISSUE TITLE
Overaggressive Parsing

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#1077]
After instantiation, the parser is unable to use variables beginning with "for", "while", and "if" as it mistakes them for the corresponding language statements.  Variables beginning with "in", "repeat", "until", "then", "else", "true", and "false" seem to parse fine.

**Comment by jgabry** [comment]
Can this be closed? I assume this was fixed but never closed.

**Comment by bob-carpenter** [comment]
@jgagry is right --- it was fixed, but never closed.
