### ISSUE TITLE
remove functor generation bug for forward declarations

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1079]
Struct definitions for functors are being generated twice in the C++ code when there is a forward declaration, like this one:

```
functions {

  matrix matrix_pow(matrix a, int n);

  matrix matrix_pow(matrix a, int n) {
    if (n == 0)
      return diag_matrix(rep_vector(1, rows(a)));
    else 
      return a *  matrix_pow(a, n - 1);
  }

}
```

* [ ] clean up issue by not defining structs for forward declarations

**Comment by bgoodri** [comment]
This appears to have been fixed at some point.
