### ISSUE TITLE
next manual 2.6.0

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1081]
This is where issues for the manual after 2.5.0 go.

**Comment by bob-carpenter** [comment]
* [ ] add process description chapter

http://www.r-project.org/doc/R-FDA.pdf

Something along the lines of the SDLC section would be great to have in your user-manual. Basically this describes the software life-cycle as how Stan is programmed, released and managed.

**Comment by blindglobe** [comment]
regarding the "process description chapter", I think you mean, "Process for Software Development and Release", which would be wonderful for supporting corporate IT computer systems validation work by providing justification that "STAN is developed in a way which makes it fit for the purpose of the process of performing a Bayesian statistical analyses".   Sure it might seem obvious, but for dotting the i's and crossing the t's for a critical review, it makes things that much easier if the process for software development is described and followed.  I'd be happy to review and comment if you want before you release (speaking as co-ghost-writer of the R-FDA document cited).

**Comment by bob-carpenter** [comment]
* [ ] replace `lambda/sqrt(pi)` with `lambda/2` in `exp_mod_normal` doc (the implementation is correct, but our doc was wrong)

* [ ] thank Andrew Ellis in the manual for pointing it out

**Comment by bob-carpenter** [comment]
* [ ] add clarification that inverse Wishart and Wishart both take the scale matrix S as a parameter
* [ ] compare to BDA's notation `Sigma ~ Inv-Wishart(inv(S))`

**Comment by bob-carpenter** [comment]
*[ ] Fix this one (from Ben on stan-users)

Note that the next sentence of the manual is wrong. It should say

```
At $\nu = 1$, the LKJ correlation distribution reduces to the uniform distribution over correlation matrices of order $K$.
```

**Comment by bob-carpenter** [comment]
Contributed by Gokcen Eraslan via a patch to master #1227 that we haven't merged because it was to master:

* [ ] remove duplicate "externally" in programming.tex after soft k-means
* [ ] thank Gokcen in the acknowledgments

**Comment by bob-carpenter** [comment]
John Sutton mentioned on stan-users:

* [ ] append_row needs to have its own description, not just a cut-and-paste of append_col
* [ ] thank John in the acknowledgments

**Comment by bob-carpenter** [comment]
* [ ] undo the fix that went in for Andrew on cbind and rbind so as not to make the index confusing as to what is a function and what isn't

**Comment by bob-carpenter** [comment]
* [ ] thank Juan Sebastián Casallas for a doc patch

**Comment by bob-carpenter** [comment]
Krzysztof Sakrejda pointed out on stan-users that this is wrong:

```
Arrays, on the other hand, should be traversed in 
row-major (or first-index fastest) order.
```

* [ ] fix it

**Comment by sakrejda** [comment]
One more, in the section on "reparameterizing the Cauchy", pg. 182: The text "The inverse of the cumulative distribution function, F X −1 : (0, 1) → R, is thus" is followed by an equation for F^-1(y) specified in terms of x.  \pi(x-1/2) should be \pi(y-1/2) ...  (?)

**Comment by bob-carpenter** [comment]
* [ ] thank Alex Zvoleff for a code patch

**Comment by bob-carpenter** [comment]
Fixing some typos.

**Comment by bob-carpenter** [comment]
* [x] fix issue with normal typesetting in ragged arrays chapter
