### ISSUE TITLE
Stan Functions Can't Be Overloaded

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#1096]
According to the manual functions should be overload-able,

```
functions {
  real foo(real x) {
    ...
  }
  real foo(real x1, real x2) {
    ...
  }
}
```

but the parser uses the same name when creating the underlying functor (``functor_foo`` in this case), creating a conflict at compile time.

Either the functor name needs to be mangled with the signature or the parser needs to fail with an appropriate error message.

**Comment by jgabry** [comment]
I'm going to close this since this issue is stagnant and the manual no longer says something incorrect about overloading being allowed.
