### ISSUE TITLE
Initialize transformed data to NaN

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#1099]
Apply the same initialization to parameters defined in transformed data as is currently applied to transformed parameters.

**Comment by beyondpie** [comment]
Hi, my program will say,  at the beginning of warmup,  like variables (defined in transformed parameters) are nan, and then disappeared after several steps in warm-up.  That should be this issue,right?  Is there anyway to stop this warning?

**Comment by bob-carpenter** [comment]
@beyondpie:  No, there is no way to turn those warnings off (well, they catch them and save them until the end in RStan).  What you're talking about would be a feature request, but I'm not sure what behavior it is you want.  Right now, Stan's doing as advertised and reporting illegal inputs to functions when it finds them.  Sometimes initialization or adaptation will hit bad values before finding a more stable region of parameter space to explore.  If you're having these problems, you might want to try reparameterizing the model---this can happen when scales get off.  Or it can also happen in something like a logistic regression if there are a lot of coefficients randomly initialized and the scales don't match those of the inputs.

**Comment by beyondpie** [comment]
@bob-carpenter 
Thank you very much! I use cmdStan, and it's quite great together with makefile and R.  Actually, I've reparameterize the parameters with normal distribution as priors, except two variables, which use  inv-gamma distribution as prior.  But I limit their scale in the parameter block.  Maybe I need to see what happens. But currently, I just ignore the warning since my sampling process looks well, no any warnings.
Thank you again!

**Comment by bob-carpenter** [comment]
It's almost never a good idea to add hard upper and lower bounds to parameters unless they're logically constrained to that interval (like a correlation parameter is constrained to (-1, 1)).  It'll bias the point estimates away from the boundaries if the data's consistent with one or both of the boundaries.

**Comment by beyondpie** [comment]
@bob-carpenter 
Thank you for your reply.  BTW, I did a test. I simualte the data y ~ Normal (0, 1).   And estimate its mean and variance.  

```
data {
    int N;
    vector[N] y;
    real<lower=0> sigmu;
}

parameters {
    real mu;
    real<lower=0> sigma;
}

model {
    /* mu ~ normal(0.0, sigmu); */
    mu ~ normal(0.0, sigma);
    sigma ~ inv_gamma(1,1);
    print("sigma is: ", sigma);
    y ~ normal(mu, sigma);
}

```
The final result looks fine, but still some warning on the extreme values.
```
sigma is: 0.799795

sigma is: 0.799795


Gradient evaluation took 1.5e-05 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.15 seconds.
Adjust your expectations accordingly!


sigma is: 0.799795

sigma is: 5463.57

sigma is: 0.799795

sigma is: 3464.5

sigma is: 0.799795

sigma is: 6.46918

sigma is: 0.799795

sigma is: 1.49085

sigma is: 0.799795

sigma is: 1.02092

Iteration:    1 / 2000 [  0%]  (Warmup)
sigma is: 0.799795

sigma is: 1.02596

sigma is: 0.961693

sigma is: 1.00067

sigma is: 1.02596

sigma is: 0

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: normal_lpdf: Scale parameter is 0, but must be > 0! (in '/Users/beyondpie/git-recipes/scRNAseqDEA/test/reparameterization/rtest.stan', line 21, column 4 to column 26)
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

sigma is: 1.02596

sigma is: 1.23625e-27

sigma is: 1.02596

sigma is: 0.622943

sigma is: 742.261

Iteration:    5 / 2000 [  0%]  (Warmup)
```

**Comment by beyondpie** [comment]
I also try a reparameterization version. 
```
data {
    int N;
    vector[N] y;
    real<lower=0> sigmu;
}

parameters {
    real muraw;
    real<lower=0> sigma;
}

transformed parameters {
    /* real mu = sigmu * muraw; */
    real mu = sigma * muraw;
}

model {
    muraw ~ std_normal();
    sigma ~ inv_gamma(1,1);
    print("sigma is: ", sigma);
    y ~ normal(mu, sigma);
}
```

I still face the extreme value warning 
```
sigma is: 0.799795

sigma is: 5463.57

sigma is: 0.799795

sigma is: 3464.5

sigma is: 0.799795

sigma is: 6.46918

sigma is: 0.799795

sigma is: 1.49085

sigma is: 0.799795

sigma is: 1.02092

Iteration:    1 / 2000 [  0%]  (Warmup)
sigma is: 0.799795

sigma is: 1.02596

sigma is: 0.961693

sigma is: 1.00067

sigma is: 1.02596

sigma is: 0

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: normal_lpdf: Scale parameter is 0, but must be > 0! (in '/Users/beyondpie/git-recipes/scRNAseqDEA/test/reparameterization/rtest.stan', line 21, column 4 to column 26)
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

sigma is: 1.02596

sigma is: 1.23625e-27

sigma is: 1.02596

sigma is: 0.622943

sigma is: 742.261

```

Is this reasonable ?

**Comment by bob-carpenter** [comment]
> Is this reasonable ?

The standard thing to do is use a fixed prior for `mu` rather than duplicating the scale for the data.  That is,

```
mu ~ normal(0, 10);  // value 10 (or whatever is appropriate) is fixed
y ~ normal(mu, sigma);
```

This kind of discussion is better carried out on the [Stan forums](https://discourse.mc-stan.org).

**Comment by beyondpie** [comment]
@bob-carpenter  Thank you!  Here, I just want to test a specific situation.  I will pay more attention to the forums.
