### ISSUE TITLE
stiff ode solver [was "throttle integrator with max steps"]

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1127]
It would be nice to have a way of limiting the number of steps used in the ODE integrator.  The integrator could throw an exception if it hasn't converged within tolerance within a preconfigured upper bound of steps.

As is, the integrator can effectively hang while trying to achieve a desired tolerance (now hardcoded at 1e-6 for both relative and absolute).

This looks like it may be difficult with Boost odeint, at least the way we're calling it now.  Maybe when we swap in an integrator that can handle stiffer systems, this problem will go away.

**Comment by syclik** [comment]
I'm hijacking this issue and renaming it to "stiff ode solver."

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#52
