### ISSUE TITLE
Dirichlet-multinomial density and (P)RNGs

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1130]
* [ ] density
    * [ ] `dirichlet_multinomial_log` function
    * [ ] distribution tests
    * [ ] model instantiation tests
    * [ ] doc for manual
    * [ ] (optional) example for manual in programming section;  perhaps a new chapter on overdispersion
* [ ] PRNG
    * [ ] `dirichlet_multinomial_rng` function
    * [ ] distribution and PRNG tests
    * [ ] doc for manual
    * [ ] model instantiation tests

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#54
