### ISSUE TITLE
Incorrect behaviour of CCDFs when there is a negative random variable

### ISSUE THREAD

**Issue by randommm** [stan-dev/stan#1142]
The following program:

    transformed data {
      int y[2];
      y[1] <- 0;
      y[2] <- 1;
      print(poisson_ccdf_log(0, 5));
      print(poisson_ccdf_log(1, 5));
      print(poisson_ccdf_log(y, 5));
    }
    parameters {
      real any;
    }
    model {
      any ~ normal(0, 1);  
    }

Outputs: 

   -0.00676075
   -0.0412676
   -0.0480283

(the last number is the sum of the first two as expected)

However, the following program:

    transformed data {
      int y[2];
      y[1] <- -1;
      y[2] <- 1;
      print(poisson_ccdf_log(-1, 5));
      print(poisson_ccdf_log(1, 5));
      print(poisson_ccdf_log(y, 5));
    }
    parameters {
      real any;
    }
    model {
      any ~ normal(0, 1);  
    }

Outputs: 

    0
    -0.0412676
    0

Which doesn't make sense: the last number should have been -0.0412676 too.

The way the CCDFs are currently designed makes them ignore everything when there is a negative random variable inside the vector of random variables:

      // Explicit return for extreme values
      // The gradients are technically ill-defined, but treated as neg infinity
      for (size_t i = 0; i < stan::length(n); i++) {
        if (value_of(n_vec[i]) < 0) 
          return operands_and_partials.to_var(0.0);
      }

**Comment by randommm** [comment]
What was the conclusion of the meetings and discussions about this? Will it raise an exception or will it return 0 (1 for ccdf) when out of bounds?

**Comment by bob-carpenter** [comment]
We decided they should raise exceptions.  Daniel's going through
and fixing all the bounds, I believe.

- Bob

**Comment by rtrangucci** [comment]
@bob-carpenter This seems like the right issue to take care of consistent bounds checking / handling of pdfs because we'll need to make the behavior consistent for the corresponding cdf / cdf_log / ccdf_log

**Comment by bob-carpenter** [comment]
Let's do the pdf/pmf and cdf in different issues --- they seem like
separate decisions to me of what to do with values outside of support.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#56
