### ISSUE TITLE
censored weibull function

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1153]
Aki Vehtari suggested building in a function that behaves like some R survival analysis packages:

```
real weibull_right_censored_log(real y, real sigma, real alpha, int z) {
  if (z == 0) return weibull_log(y,alpha,sigma);
  else return weibull_ccdf_log(y,alpha,sigma);
}
```

The int value `z` is used as an indicator as to whether the event was right censored at `y` or whether it was an ordinary outcome.

Aki also mentioned that it's common to have a vector of censored outcomes, all censored at the same place.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#57
