### ISSUE TITLE
Inverse CDF for normal

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/stan#1157]
- [ ] write doc
- [ ] add function to function signatures
- [ ] add function signature tests.

Written by @bgoodri: Stan has the CDF and inverse CDF of the logistic distribution, but lacks the inverse CDF of the standard normal distribution (and many other distributions) in C++. Remember that the derivative of the inverse CDF is the reciprocal of the density (including constants).

There is a rational approximation algorithm for the inverse of the standard normal CDF here:
http://home.online.no/~pjacklam/notes/invnorm/
which can be implemented (and tested) in Stan code with
```
/** Stan program to demonstrate useage of the standard normal inverse CDF.
* Algorithm first derived in 2003 by Peter Jon Aklam at 
* http://home.online.no/~pjacklam/notes/invnorm/
* @param p Number(s) on the (0,1) interval
* @param a Vector of constants defined in the transformed data block
* @param b Vector of constants defined in the transformed data block
* @param c Vector of constants defined in the transformed data block
* @param d Vector of constants defined in the transformed data block
* @param N Integer defining length of vector or array in non-scalar case
* @return Number(s) on the entire real line, almost equal to Phi^{-1}(p)
*/

functions {
  real invnorm(real p, vector a, vector b, vector c, vector d) {
    real x; real q; real r; real p_low;  real p_high; real e; real u;
    if( p <= 0 )     return(negative_infinity());
    else if (p >= 1) return(positive_infinity());
    p_low  <- 0.02425;
    p_high <- 0.97575; # 1 - p_low
    if ( (p_low <= p) && (p <= p_high) ) { # central region
      q <- p - 0.5;
      r <- square(q);
      x <- (((((a[1]*r+a[2])*r+a[3])*r+a[4])*r+a[5])*r+a[6])*q /
           (((((b[1]*r+b[2])*r+b[3])*r+b[4])*r+b[5])*r+1.0);      
    }
    else if (p < p_low) { # lower region
      q <- sqrt(-2.0*log(p));
      x <- (((((c[1]*q+c[2])*q+c[3])*q+c[4])*q+c[5])*q+c[6]) /
            ((((d[1]*q+d[2])*q+d[3])*q+d[4])*q+1.0);            
    }
    else { # upper region
      q <- sqrt(-2.0*log1m(p));
      x <- -(((((c[1]*q+c[2])*q+c[3])*q+c[4])*q+c[5])*q+c[6]) /
             ((((d[1]*q+d[2])*q+d[3])*q+d[4])*q+1.0);
    }

    # refinement
    e <- Phi(x) - p;
    u <- e * sqrt(2.0 * pi()) * exp(0.5 * square(x));
    x <- x - u / (1.0 + 0.5 * x * u);
    return x;
  }

  vector invnorm(vector p, vector a, vector b, vector c, vector d, int N) {
    real q; real r; real p_low;  real p_high; real e; real u;
    vector[N] x;
    p_low  <- 0.02425;
    p_high <- 0.97575; # 1 - p_low    
    for (i in 1:N) {
      if( p[i] <= 0 )     x[i] <- negative_infinity();
      else if (p[i] >= 1) x[i] <- positive_infinity();
      else if ( (p_low <= p[i]) && (p[i] <= p_high) ) { # central region
        q <- p[i] - 0.5;  
        r <- square(q);
        x[i] <- (((((a[1]*r+a[2])*r+a[3])*r+a[4])*r+a[5])*r+a[6])*q /
                (((((b[1]*r+b[2])*r+b[3])*r+b[4])*r+b[5])*r+1.0);
      }
      else if (p[i] < p_low) { # lower region
        q <- sqrt(-2.0*log(p[i]));
        x[i] <- (((((c[1]*q+c[2])*q+c[3])*q+c[4])*q+c[5])*q+c[6]) /
                ((((d[1]*q+d[2])*q+d[3])*q+d[4])*q+1.0);
      }
      else { # upper region
        q <- sqrt(-2.0*log1m(p[i]));
        x[i] <- -(((((c[1]*q+c[2])*q+c[3])*q+c[4])*q+c[5])*q+c[6]) /
                 ((((d[1]*q+d[2])*q+d[3])*q+d[4])*q+1.0);
      }
      # refinement
      e <- Phi(x[i]) - p[i];
      u <- e * sqrt(2.0 * pi()) * exp(0.5 * square(x[i]));
      x[i] <- x[i] - u / (1.0 + 0.5 * x[i] * u);
    }
    return x;
  }

  vector invnorm(real[] p, vector a, vector b, vector c, vector d, int N) {
    return invnorm(to_vector(p), a, b, c, d, N);
  }  
}

data {
  int<lower=1> N;
}
transformed data {
  vector[6] a; vector[5] b; vector[6] c; vector[4] d;
  
   a[1] <- -3.969683028665376e+01;
   a[2] <-  2.209460984245205e+02;
   a[3] <- -2.759285104469687e+02;
   a[4] <-  1.383577518672690e+02;
   a[5] <- -3.066479806614716e+01;
   a[6] <-  2.506628277459239e+00;

   b[1] <- -5.447609879822406e+01;
   b[2] <-  1.615858368580409e+02;
   b[3] <- -1.556989798598866e+02;
   b[4] <-  6.680131188771972e+01;
   b[5] <- -1.328068155288572e+01;

   c[1] <- -7.784894002430293e-03;
   c[2] <- -3.223964580411365e-01;
   c[3] <- -2.400758277161838e+00;
   c[4] <- -2.549732539343734e+00;
   c[5] <-  4.374664141464968e+00;
   c[6] <-  2.938163982698783e+00;

   d[1] <-  7.784695709041462e-03;
   d[2] <-  3.224671290700398e-01;
   d[3] <-  2.445134137142996e+00;
   d[4] <-  3.754408661907416e+00;
}
parameters {
  real<lower=0,upper=1> p[N];
}
model {
  // implicit i.i.d. uniform prior on p
}
generated quantities {
  vector[N] x;
  x <- invnorm(p, a, b, c, d, N); # should be ~ standard normal
}

```

**Comment by bgoodri** [comment]
Really we should implement the inverse CDF for all distributions where it is either available in closed-form or there is a numerically stable approximation for it.

**Comment by bob-carpenter** [comment]
We'd also like numerically stable approximations of
at least first-order derivatives, and ideally up to
third-order.

- Bob

**Comment by bgoodri** [comment]
For closed-form inverse CDFs, the derivatives should also be closed-form
and usually elementary. In the case of something like the inverse standard
normal CDF that has a rational approximation, the derivatives of the
approximation should be manageable.

For the CDFs where we are running into trouble with the derivatives wrt the
parameters, I don't think there are many inverse CDFs that have nice forms.

**Comment by betanalpha** [comment]
The inverses can be handled with the Implicit Function Theorem
and some calculus, but it’s nontrivial to build up a good set of
code to automate the numeral solver and the associated derivatives.

**Comment by hoanguc3m** [comment]
My code won't work, could you please show me why? I am using Stan 2.6

data2 <- list(N=10) # to be passed on to Stan
parameters2 <- c("p")  # parameters to be monitored
samples2 <- stan(file="inverse_norm.stan",   
                 data=data2, 
                 pars=parameters2,
                 iter=20000, 
                 chains=1, 
                 thin=1,
)

The error looks like this:
file1a165d1cfcde.cpp:163:8: error: redefinition of ‘struct model1a164959d76b_inverse_norm_namespace::invnorm_functor__’
 struct invnorm_functor__ {
        ^

**Comment by bgoodri** [comment]
When the capability to solve ODEs was introduced, it became essentially impossible to have user-defined functions with the same names but different signatures. So, either take out the versions of the invnorm function that you are not actually using or rename them so that they have unique names (invnorm_r, invnorm_r, invnorm_a, etc.)

**Comment by bob-carpenter** [comment]
That looks like a bug because we shouldn't allow programs
to parse and then not compile in C++.  

But we can't help you debug it if you don't send us the program
(or ideally a simplified version of the program) that caused
this error.

My guess is that you tried to define two functions with the
same name, which isn't allowed until I can figure out how to do it.
 
- Bob

**Comment by bob-carpenter** [comment]
Although Ben and I are uncannily good guessers, we'd
appreciate it if users went us the programs that are
causing their errors.  

- Bob

**Comment by bgoodri** [comment]
Although in this case, any .stan program that pasted in the original code
would cause this error, even if the functions weren't called.

**Comment by hoanguc3m** [comment]
Is that what I should send? Rstan works fine in my computer. Thanks for your comments and instructions.
https://github.com/hoanguc3m/Test-stan

**Comment by bgoodri** [comment]
In general, yes that is the most helpful thing. But in this case, the
solution is what we already guessed. In the functions block, change the
signatures

   - real invnorm(real p, ...) { to real invnorm_r(real p, ...) {
   - real invnorm(vector p, ...) { to real invnorm_v(vector p, ...) {
   - real invnorm(real[] a, ...) { to real invnorm_a(real[] p, ...) {

And then make sure your code is calling the appropriate function.

**Comment by bgoodri** [comment]
I meant

   - real invnorm(real p, ...) { to real invnorm_r(real p, ...) {
   - vector invnorm(vector p, ...) { to vector invnorm_v(vector p, ...) {
   - real[] invnorm(real[] a, ...) { to real[] invnorm_a(real[] p, ...) {

**Comment by hoanguc3m** [comment]
Awesome, when I change the function name as you suggested, It runs well. Could you please suggest me some reference for inserve student-t distribution. I will try to make a similar code with this one. Cheer.

**Comment by bgoodri** [comment]
http://www.mth.kcl.ac.uk/~shaww/web_page/papers/Tdistribution06.pdf

**Comment by bgoodri** [comment]
Or you could port

http://ascl.net/1403.010

to Stan code and use equation 24 of Shaw's paper

**Comment by hoanguc3m** [comment]
Thank bgoodri for your amazing help. I had translate the fortran code to R and check it. It runs well and return the same value with the R function. Then I add it into stan syntax but I had a problem here. Stan does not have break command for loop and I also cannot find goto syntax for stan (if there is, it would be a great news because the fortran code is the same). Do you think that is there any option to go around?

**Comment by bgoodri** [comment]
I think you have to use a while loop with a termination condition. There
are no break or goto statements in the Stan language.

**Comment by bob-carpenter** [comment]
I'm not so keen on goto because the code gets very
confusing, but we could add an unalabeled break statement if
people think it's a good idea.  It'd be a piece of cake to
add it.  

- Bob

**Comment by hoanguc3m** [comment]
Fantastic, It would be welcome by Stan user. I try to use 2 variables for the 2 while loop and check the condition but thing seems to be not as well as before.

**Comment by bob-carpenter** [comment]
If you want help translating something with breaks or gotos into
something without, let us know.  The right place to have this
discussion, since it seems to be about a Stan program, not about
contributing to Stan, would be on the stan-users mailing list.

- Bob

**Comment by bgoodri** [comment]
This issue should be moved to math and then we'll open an issue in stan when that is closed to expose these via `function_signatures.h`.
