### ISSUE TITLE
allow vector arguments for ordered_logistic

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1162]
We need to supply array first arguments for `ordered_logistic`.   We should have the mechanisms already in place to handle array of integer arguments (they should be in Poisson, etc.)

**Comment by chmullig** [comment]
A :+1: for this. For Gelman's survey course we're doing a bunch of mulitlevel ordered logistics and doing them one case at a time is painfully slow, even with n = ~800.

**Comment by tmalsburg** [comment]
FWIW, I would like to see this feature as well.

**Comment by rtrangucci** [comment]
@bob-carpenter I've found the current implementation to be pretty slow as well. Not good for our stan_lmer implementation. I'll create a branch for this.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#105
