### ISSUE TITLE
check nan input for matrix functions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1176]
- [ ] max_test.cpp: returns NaN if any input is NaN
- [ ] mdivide_left_ldlt_test.cpp
- [ ] mdivide_right_ldlt_test.cpp
- [ ] min_test.cpp
- [ ] ? fmin and fmax if they're vectorized
- [ ] sort_indices_test.cpp: if any input is NaN, then the first index will be that of the NaN (everything else that follows is what would normally be returned)
- [ ] sort_test.cpp: if any input is NaN, then the first argument in the vector return is NaN

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#59
