### ISSUE TITLE
Exponential distribution does not have the correct bounds checks

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1179]
It currently allows the left hand side to be <= 0.

* [ ] exponential()

**Comment by bob-carpenter** [comment]
Rob says there are more distributions with this problem. These should be added to the top-level issue as a checkbox and then we should fix them all.

**Comment by rtrangucci** [comment]
@bob-carpenter Upon further investigation, it looks like exponential is the only distribution with lower-bounded support that doesn't either throw an exception if the RV is less than the lower bound or return negative infinity if the RV is less than the support.

We're inconsistent on how we handle evaluation of a pdf outside its support, but I'll make a new issue for continuous lower-bounded cdfs that we can tackle together on a different branch.
