### ISSUE TITLE
generalize to_matrix to accept matrix arguments

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1193]
Seth Flaxman on stan-users suggested reshaping matrix methods (for applications to Kronecker products), as are available in R and MATLAB (see below).  One way to support this is to compose `to_matrix` and `to_vector`, but it'd be easier if we just accepted matrices in `to_matrix`, with:

```
to_matrix(matrix,m,n) 

  =def= to_matrix(to_vector(matrix),m,n)
```

This would require writing a `to_matrix` version that accepted a rows and column argument; as of now, it just creates a matrix with 1 row or 1 column depending on the input.

We should emphasize the column-majorness of this in the doc with an example.

The rest of this is from Seth's original post:

In R I'd do:

```
A = matrix(1:32,4,8) # initialize A
matrix(A, 16,2) # reshape it
```

And in matlab:

```
A = reshape([1:32],4,8); % initialize A
reshape(A,16,2) % reshape it
```

**Comment by flaxter** [comment]
We discussed this on stan-users, but my takeaway was that it'd be column-major, not row major, which is how matlab and R (and apparently Fortran) do it, at least by default. 

Also, don't know enough about the guts of Stan to know if it's relevant, but looks like there was some activity trying to get this into Eigen which has stalled (?):  https://bitbucket.org/eigen/eigen/pull-request/41/reshape/diff

**Comment by bob-carpenter** [comment]
@flaxter --- Thanks, I fixed the feature request.

It's an easy fix because we can just get the data array row major out of an Eigen matrix.  Stan's substantially simpler than Eigen in that we're not supporting their expression templates.

**Comment by jgabry** [comment]
Combined with https://github.com/stan-dev/stan/issues/1452
