### ISSUE TITLE
missing derivatives for += in fvar

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1198]
I was looking through the autodiff code for fvar and saw this in `fvar.hpp`:

```
      template <typename T2>
      inline
      fvar<T>&
      operator*=(const fvar<T2>& x2) {
        d_ = d_ * x2.val_ + val_ * x2.d_;
        val_ *= x2.val_;
        return *this;
      }

      template <typename T2>
      inline
      fvar<T>&
      operator*=(const T2& x2) {
        val_ *= x2;
        return *this;
      }
```

These are too general.  The only legal pattern to multiply an `fvar<T>` is with a `double` (including promoted integers) or another `fvar<T>`.

* [ ] Change signatures to

```
template <typename T>    
inline fvar<T>&
operator*=(const fvar<T>& x2);

template <typename T>
inline fvar<T>&
operator*=(double x2);
```

There is also a problem with the second version not propagating derivatives, so we need to

* [ ] add statement `d_ *= x2;` to propagate derivative
* [ ] add test to go with it

**Comment by rtrangucci** [comment]
@bob-carpenter Found the following lines which are now in stan/math/fwd/core/fvar.hpp:
```
      template <typename T2>
      inline
      fvar<T>&
      operator+=(const fvar<T2>& x2) {
        val_ += x2.val_;
        d_ += x2.d_;
        return *this;
      }

      template <typename T2>
      inline
      fvar<T>&
      operator+=(const T2& x2) {
        val_ += x2;
        return *this;
      }
```

So that should take care of the first problem. However, we do still need to make `operator*=()` and `operator/=()` less general, and make the derivatives right.
