### ISSUE TITLE
check_consistent_sizes not correct for 0-length vector-like arguments

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1201]
If you pass in a scalar and a 0-length vector, check_consistent_sizes fails.

I've got a patch for this on the branch for #685.

**Comment by bob-carpenter** [comment]
It makes sense to me to have the behavior of densities be
a no-op with a zero-length vector input. 

Will that actually happen in the implementations if check_consistent_sizes
is generalized?

- Bob

**Comment by syclik** [comment]
I believe all of our vectorized distributions check explicitly for
zero-length vector input and return 0.

But, if it did not, this would allow for the behavior described. Under the
current develop code, if a scalar was passed in and a zero-length vector,
then the distribution would throw an exception. After the fix, this will
not throw an exception and the computation would be done in a for loop over
0 elements, which would be the correct behavior.
