### ISSUE TITLE
refactor traits for dependencies

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1208]
Right now, `stan::math` fundamentally depends on `stan/meta/traits.hpp`, which brings in all of `agrad::var` and all of `agrad::fvar`.  

We want to break this apart so that there's a base meta that doesn't depend on anything in agrad or Eigen or whatever.  And then have separate traits files within `agrad/fwd` and `agrad/rev`

**Comment by syclik** [comment]
This was fixed with the math refactor.
