### ISSUE TITLE
remove scalar_type in favor of value_type

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1211]
Suggested by Joshua N Pritikin via stan-dev:

The traits metaprograms `stan::math::value_type` and `stan::scalar_type` are near duplicates and should be merged.

* The code layout for `stan::math::value_type` is the right one.  It goes in `math` and separates matrices from standard library uses.  It probably has the right test setup, too, since I wrote it recently.

* The extension to pointers in `stan::scalar_type` is going to have to go in the combined definition.

I'm not sure what all the helper-class complexity is for in `stan::scalar_type` but it'd be nice to understand before changing the behavior.

**Comment by jpritikin** [comment]
It seems the helper is only used for VectorViewMvt.

**Comment by randommm** [comment]
I think VectorViewMvt only uses scalar_type_pre which in turn only uses scalar_type_helper_pre which is independent code from scalar_type_helper. Therefore, it doesn't use scalar_type_helper nor scalar_type.

**Comment by jpritikin** [comment]
Wait, maybe there is a difference. I think the point of scalar_type is to unwrap std::vector, but it leaves Eigen::Matrix intact because a matrix is considered a "scalar" for the purposes of VectorView. See `test/unit/agrad/rev/error_handling/scalar/check_equal` line 144 where we find `check_equal(function,"a",a,b)` where both `a` and `b` are MatrixXd. Does that sound right?

If my analysis is correct, at a minimum, the purpose of scalar_type should be better documented.

**Comment by bob-carpenter** [comment]
Yes, we definitely need more doc.  Also, I don't think
the implementation needs to be as complex as it is.  We're
getting better at template metaprogramming and some of this
is old hacks because we couldn't figure out how to do things
properly.

Here's the rundown on what scalar_type does in case you
want to add some doc:

  scalar_type<int>::type            == int
  scalar_type<double>::type         == double
  scalar_type<Matrix<T,R,C> >::type == scalar_type<T>::type
  scalar_type<vector<T> >::type     == scalar_type<T>::type

So it just recursively pulls out until it gets to a base
type that's neither a vector nor a matrix and returns the
type.

It also needs to be factored into function-specific files.
traits.hpp is out of control.

- Bob

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#63
