### ISSUE TITLE
generalized interpolation function

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1214]
Jan Scholz (via e-mail) suggested implementing the general form of interpolation used in SciPy.

https://github.com/scipy/scipy/blob/v0.15.0/scipy/ndimage/interpolation.py#L230

It should be able to handle 2D and 3D structures.  Jan says the linear form (order 1) should be enough for his purposes.

For background, BUGS provides an interp.lin function for the 1D case:

 http://www.mrc-bsu.cam.ac.uk/wp-content/uploads/manual14.pdf

The goal would be to get the derivatives working properly in a way that encapsulates the index-fiddling relative to the user and takes care of error conditions.

This would be a nice standalone project.  

* [ ] example for model-examples
* [ ] documentation using example
* [ ] C++ function with tests
* [ ] plumbing into Stan's language
* [ ] tests in Stan programs to ensure compilability

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#64
