### ISSUE TITLE
Math and Autodiff Code Reorg

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1222]
## Current Code Features

I see five cross-cutting ways our math and autodiff code can be categorized:

#### Type
* primitive
* reverse mode autodiff
* forward mode autodiff
* mixed mode autodiff

#### Shape
* scalar
* array (std::vector)
* vector/matrix (Eigen::Matrix)

#### Purpose
* functions and operators
* error handling
* meta

#### Extension
* built-in operators (e.g., operator+ and operator+=)
* standard library functions (e.g., exp)
* special functions (what is now in math)
* probability functions (what is now in prob)
    - transforms
    - distribution functions: prob function, (c)cdf, rng

#### Dependencies
* None
* C++ std lib
* Boost
* Eigen
* ODE solver?
* RNG?

#### Directory Structure

I think what would make most sense is to have the following directory structure:

```
src/
    stan/
        math/
            prim/
                scalar/
                    fun/
                    functor/
                    err/
                    meta/
                    prob/
                array/
                    fun/
                    functor/
                    err/
                    meta/
                    prob/
                matrix/
                    fun/
                    functor/
                    err/
                    meta/
                    prob/
```

#### Include Files

We can start a new include directory parallel to `src` that has cross-cutting includes that clients might want.   For includes, we want the following properties:

* Every function (name, not signature) should be defined in its own file.
* Every source file should include only what it uses (there's another issue for just this).
* Every source file should be usable on its own as a header without requiring other includes.
* There should be no include order dependencies. 

#### Namespaces

I'm a little less clear on what would be ideal here.  At one extreme, everything can just go in `stan`, that is, just one top-level namespace.  That'd probably be enough for all of our argument-dependent lookup to work.  

At the other extreme, we could keep math, prob, and agrad namespaces separate, but that introduces issues with argument-dependent lookup for probability and math namespace functions that can take autodiff arguments.

#### ODE Solver and Dependencies

The ODE could go in with other functionals.  The problem is that this leads to a requirement that we include the ODE dependent libs (e.g., Sundials or lsoda) in order to build whatever they're contained in.

**Comment by betanalpha** [comment]
I think Extensions and Dependencies organization can be done concurrently,
(C++ and Eigen being base dependencies, then additional “plug-ins” for Boost,
ODE, etc) which leaves the question of the others.  

I personally like having Purpose be the main categorization (with basic scalar
functions/operators, special scalar functions/operators, matrix scalar/functions,
and distributions being separate “Purposes”), with the different implementations 
all being in the same location in order to make it easier on developers (all exp 
implementations are in one place, for example).

But that’s just me.

Also recall that the plan is to pull all of this out into a separate autodiff repo,
We can call is StanADE (the Stan Automatic Differentiation Engine ;-) ).

**Comment by syclik** [comment]
I'm going to start working on this with @rtrangucci's help. I think these are the steps we'll need to take:
- [ ] move files
    - [ ] create source directories (no files should be touched)
    - [ ] create test directories (no files should be touched)
    - [ ] move source files into directories, update includes (no other changes)
    - [ ] move test files into directories, update includes (no other changes)
    - [ ] commit after files have been moved
- [ ] change header guards
    - [ ] commit after all header guards have been updated
- [ ] separate functions into separate header files
    - [ ] break apart files that have multiple functions inside them
    - [ ] commit after all header files have single functions within them (multiple signatures ok)
- [ ]  separate functions into `prim`, `rev`, `fwd`, `mix`
    - [ ] THIS WILL BE HARD
    - [ ] commit after this is done
- [ ] write scripts
    - [ ] check that `prim` does not contain autodiff
    - [ ] check that `rev` does not contain `fwd`
    - [ ] check that `fwd` does not contain `rev`
    - [ ] check that `scalar` (???) does not contain `arr` or `mat`
    - [ ] check that `arr` does not contain `mat`
    - [ ] get these checks on Jenkins

**Comment by syclik** [comment]
@bgoodri, can you take a look at branch `feature/issue-1222-autodiff-reorg`? Make sure the folder depth isn't too deep before we move on?

**Comment by bgoodri** [comment]
Looks okay.

**Comment by syclik** [comment]
Thanks for looking into it!
