### ISSUE TITLE
Extraneous vars added to var_stack on call to normal_log

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/stan#1230]
On the current develop, the following code:

```
#include <iostream>
#include <stan/agrad/rev.hpp>
#include <stan/prob/distributions.hpp>

int main ()
{
	using stan::agrad::var;

  double lambda = 1.15;
  double mu = 1.1;
  double y = 1.5;

  var v_y(y);
  var v_mu(mu);
  var v_lambda(lambda);

	std::cout << "Instantiate 3 vars: y, mu, sigma \n" << std::endl;

	stan::agrad::print_stack(std::cout);

	std::cout << "Calling normal_log\n" << std::endl;

  var lp = stan::prob::normal_log(v_y, v_mu, v_lambda); 

	std::cout << "Called normal_log \n" << std::endl;

	stan::agrad::print_stack(std::cout);

  return 0;
}
```

Creates the following output:

```
Instantiate 3 vars: y, mu, sigma 

STACK, size=3
0  0x7f88e2801200  1.5 : 0
1  0x7f88e2801218  1.1 : 0
2  0x7f88e2801230  1.15 : 0
Calling normal_log

Called normal_log 

STACK, size=8
0  0x7f88e2801200  1.5 : 0
1  0x7f88e2801218  1.1 : 0
2  0x7f88e2801230  1.15 : 0
3  0x7f88e2801248  inf : 0
4  0x7f88e2801260  1.79769e+308 : 0
5  0x7f88e2801278  -1.79769e+308 : 0
6  0x7f88e2801298  1.79769e+308 : 0
7  0x7f88e28012e0  -1.11919 : 0
```

@syclik figured out that the extra vars on the stack are instantiated by the calls to ```check_finite(y)``` and ```check_not_nan(y)```. Simple to fix by adding ```value_of(value_of(value_of(y)))``` in the ```check``` functions for these respective checks and by modifying the version of ```get``` that takes a std::vector or Eigen::Matrix in src/stan/meta/traits.hpp.

**Comment by bob-carpenter** [comment]
We shouldn't have value_of(value_of()) if that wasn't
a typo.  

Shouldn't 

  value_of(fvar<fvar<double> >(fvar<double>(1,2), fvar<double>(3,4))

be 1?  Or is it setup to be fvar<double>(1,2)?

**Comment by syclik** [comment]
I agree with Bob. We shouldn't need to wrap value_of multiple times.

For double and var arguments, the return type is double. In
stan/agrad/fwd/functions/value_of.hpp, the return type is T, the type
within the fvar. We'll need to trace through where value_of is used and
perhaps create two functions: one that returns the double value and one
that has the current behavior.

**Comment by rtrangucci** [comment]
@bob-carpenter this wasn't a typo, in order to handle fvar<fvar<var> > we
need value_of 3 times (as value_of is currently written), but  I agree with
you both that this shouldn't be the case.



Rob
