### ISSUE TITLE
remove redundant Eigen typedefs

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1251]
Remove the redundant typedefs:

* [ ]  remove `src/stan/math/matrix/typedefs.hpp`
* [ ] replace uses of `size_type` with `int`
* [ ] replace `matrix_d`, etc. with `Eigen::MatrixXd`

There's more utility in these, but they should probably also go as they introduce inconsistent conventions and don't allow polymorphism:

* [ ]  remove `src/stan/agrad/rev/matrix/typedefs.hpp`
* [ ]  remove `src/stan/agrad/fwd/matrix/typedefs.hpp`
* [ ] replace `var`-based uses with the full types

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#68
