### ISSUE TITLE
remove anonymous namespaces

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1259]
The anonymous namespaces we're using don't provide any encapsulation because we're header only and they are visible to everything in the translation unit.

They're also causing compilation problems for MSVC (though there are workarounds, apparently).
- [ ] just remove anonymous namespace and drop into containing namespaces

**Comment by syclik** [comment]
After #1751 gets in, I'll sweep through and remove all anonymous namespaces in our code.
