### ISSUE TITLE
log_mix on the logit scale

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1260]
Now that we have log_mix defined on the natural probability scale:

```
log_mix(theta, lp1, lp2) 
  = log(theta * exp(lp1) + (1 - theta) * exp(lp2))
  = log_sum_exp(log(theta * exp(lp1)), log((1 - theta) * exp(lp2))
  = log_sum_exp(log(theta) + lp1, log(1-theta) + lp2)
```

it'd be nice to roll in the link function (inv_logit) and just work on the unconstrained log-odds scale with

```
log_mix_logit(alpha, lp1, lp2) 
  = log_mix(inv_logit(alpha), lp1, lp2)
  = log_sum_exp(log(inv_logit(alpha) + lp1, log(1 - inv_logit(theta)) + lp2)
```

Special functions `log_inv_logit` and `log1m_inv_logit` already exist.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#69
