### ISSUE TITLE
unify floating point properties usage

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1267]
We are currently mixing our own versions of `isinf` and `isnan` with ones called from Boost.  What I think we should do is define our own version of `isnan` and `isinf` in `stan::math`.  These will delegate to Boost's floating-point classifiers for primitive values and use `value_of_rec` to pull out primitives from our autodiff types.

The reason to call Boost for primitives is that it's more portable:

http://stackoverflow.com/questions/2249110/how-do-i-make-a-portable-isnan-isinf-function

At the same time, we don't just want to use Boost's with our own `numeric_limits`, because that will potentially overallocate `var` and `fvar` instances:

http://www.boost.org/doc/libs/1_57_0/libs/math/doc/html/math_toolkit/fpclass.html

This also clarifies that Boost uses the C99 macros if available, otherwise it uses `std::numeric_limits`.   The problem we've run into with `std::numeric_limits<var>` is that it puts an extra variable on the stack;  see issue #1263

**Comment by bob-carpenter** [comment]
We should skip the Boost versions and just use our own isnan and isinf functions that will pull out values with templating rather than trying to go through numeric_limits.

This one's going to be important for managing memory, especially in forward mode, where there's this

```
 fvar(const TV& val, const TD& deriv) : val_(val), d_(deriv) { 
        if (unlikely(boost::math::isnan(val)))
          d_ = val;
      }
```

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#71
