### ISSUE TITLE
Numerical accuracy of increment_log_prob()

### ISSUE THREAD

**Issue by gregorgorjanc** [stan-dev/stan#1270]
While testing several optimisations of a large ridge regression model, a seeming loss in accuracy was observed when using increment_log_prob() instead of normal(). Details of a sequence of the fitted models and the results are shown at

https://groups.google.com/forum/?fromgroups#!searchin/stan-users/ridge/stan-users/8V9kolNnHhM/nmDdAnYpsiMJ

<b>THIS NEEDS A SUMMARY</b>

**Comment by bob-carpenter** [comment]
Interesting.  Any idea of what's happening to the model parameters.

The only difference between 

  y ~ foo(theta);

and

  incement_log_prob(foo_log(y,theta));

is that foo_log does not drop constant terms.  

Your link sent me to a gmail signup page, so I didn't follow it.

- Bob

**Comment by gregorgorjanc** [comment]
ups, sorry about the wrong link. Here is the correct link to the post, where accuracy of increment_log_prob() seems to be failing:

https://groups.google.com/forum/?fromgroups#!searchin/stan-users/ridge/stan-users/8V9kolNnHhM/nmDdAnYpsiMJ

**Comment by bob-carpenter** [comment]
The problem is not with increment_log_prob() per se, but with using 

```
increment_log_prob(-0.5 * dot_self(y));
```

rather than

```
y ~ normal(0,1);
```

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#73
