### ISSUE TITLE
Test for lkj_cov

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/stan#1292]
No tests currently for lkj_cov, add var and double unit tests.

**Comment by jgabry** [comment]
Should this be closed and moved to math (if not already resolved)?

**Comment by rtrangucci** [comment]
Yeah we should move to math, though I think I took care of this already...will check when I'm back in front of a computer

Rob

**Comment by bob-carpenter** [comment]
Not a Stan issue.
