### ISSUE TITLE
forbid range constraints on local variables

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1295]
Right now, we allow range constraints in local variables but never check them.  They should not be allowed.  An example from a model being discussed on stan-users:

```
model {
  row_vector<lower=0,upper=1>[3] a[maxTrials+1]; // attention weights
  row_vector<lower=0,upper=1>[3] s[maxTrials]; // feedback signal
  vector<lower=0,upper=1>[maxTrials] prob; // Prob(chosenAction)a block that
```

**Comment by betanalpha** [comment]
So no constraints or adding a bunch of compiler magic to check the constraints
on each assignment?

**Comment by bob-carpenter** [comment]
No, we can't check constraints on each assignment because
the assignments might leave things in bad states.  If we
did that, it would then forbid code like this:

  simplex[K] theta; // oops, not allocated yet, make it uniform?

  for (k in 1:K)
    theta[k] <- foo[k] / sum_foo;

This'll be a simplex when the loop finishes, but not at
the intermediate stages.

That's also the motivation for having the transformed data,
transformed parameters and generated quantities block only
validate constraints at the end.

The alternative, which I considered, was to do exactly what
you suggested.  To be useful, we'd need to define a set of
operations under which constraints are closed.  For instance,
scaling a covariance matrix, or averaging two simplexes.

- Bob
