### ISSUE TITLE
allow access to propto template param as int in functions ending in _log / _lpdf / _lpmf

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1299]
Any function ending in `_log` provides a template parameter `propto`, just like any of our built-in probability functions.   For example,

```
 real foo_log(real x) {
    return x;
  }
```

generates the signature

```
template <bool propto, typename T0__>
inline
typename boost::math::tools::promote_args<T0__>::type
foo_log(const T0__& x, std::ostream* pstream__)
```
- [ ] (feature) the template parameter `propto` (perhaps mangled somehow?) should be accessible from within the function definition body as an int with value 0 or 1 to allow conditionals branching on proportionality.
- [ ] (bug fix) the template parameter should not be definable as a local variable;  either it is going to need to be mangled or `propto` will become a reserved variable _within functions ending in _lp_

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#76

**Comment by syclik** [comment]
This issue should have stayed in Stan and not moved to Math.

**Comment by rok-cesnovar** [comment]
See https://github.com/stan-dev/stanc3/issues/63 and https://github.com/stan-dev/stanc3/issues/253
