### ISSUE TITLE
Manual 2.6.0: 2PL IRT Model

### ISSUE THREAD

**Issue by christophergandrud** [stan-dev/stan#1300]
This may be a bug in the Stan Manual 2.6.0 version for the Multilevel 2PL IRT model example on pages 52-53. 

The parameters are defined as: 

```
parameters {
  real delta;                                      // mean student ability
  real alpha[J];                                 // ability for j - mean
  real beta[K];                                  // difficulty for k
  real<lower=0> gamma[K];            // discrimination of k
  real<lower=0> sigma_beta;          // scale of difficulties
  real<lower=0> sigma_gamma;     // scale of log discrimination
}
```

This is the same set up as in Manual version 2.5.0 with a `delta` parameter for mean ability.

However, in the model specification `delta` disappears and a `mu_beta` appears kind of in its place (but discussed in the text as the mean beta location). 

```
  model {
      alpha ~ normal(0,1);
      beta ~ normal(0,sigma_beta);
      gamma ~ lognormal(0,sigma_gamma);
      mu_beta ~ cauchy(0,5);
      sigma_alpha ~ cauchy(0,5);
      sigma_beta ~ cauchy(0,5);
      sigma_gamma ~ cauchy(0,5);
      for (n in 1:N)
        y[n] ~ bernoulli_logit(gamma[kk[n]]
                               * (alpha[jj[n]] - (beta[kk[n]] + mu_beta)));
}
```

`delta` is then again discussed in the text on page 54.

**Comment by bob-carpenter** [comment]
Thanks.  I'm goig to move that over to the next manual issue for tracking (See #1202).  I obviously messed it up when I revised it for 2.6 to identify the model.  I really need to take more time and run these, but we have soooo much to do.

**Comment by christophergandrud** [comment]
No worries. Stan is coming along great. I'm really glad that it is so actively developed.
