### ISSUE TITLE
Horseshoe and Horseshoe+ Priors

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1303]
From Andrew (via direct e-mail):

In implementing stan_lm and stan_glm, maybe we should have the horseshoe and horseshoe+ priors as precoded options:

http://andrewgelman.com/2015/02/17/bayesian-survival-analysis-horseshoe-priors/

That way the user can just use these prior routinely.  This could give a bit boost to Stan for the sort of many-predictors “machine learning” regression problems where people are now running lasso.

I also want hierarchical models, of course, but within the context of lm and glm this could be a very useful addition, no?

**Comment by brandonwillard** [comment]
I agree (but I'm a little biased)!  What sort of implementation would this be?  For instance, would it be at the level of specification we used (i.e. the high-level Stan grammar), or a low-level C++ for--say--some conditional posteriors?
I haven't dug into the implementation details of Stan, or even HMC, so I don't really know what the possibilities are, but I imagine that some more solvery could really improve things.
Anyway, always glad to discuss further.

**Comment by rtrangucci** [comment]
@jgabry this exists in rstanarm, no? Closing the issue.

**Comment by bob-carpenter** [comment]
Another good case study topic.  They never made it
into the manual.

**Comment by rtrangucci** [comment]
True; I have examples coded in an Rmd file for HS and HS+ priors; we can
add this as an issue in the example modes.


Rob

**Comment by jgabry** [comment]
On Fri, Mar 4, 2016 at 6:11 PM, Rob Trangucci <notifications@github.com>
wrote:

> @jgabry <https://github.com/jgabry> this exists in rstanarm, no? Closing
> the issue.
>

Yeah already in rstanarm
