### ISSUE TITLE
Feature request: log_minus_exp function

### ISSUE THREAD

**Issue by luccoffeng** [stan-dev/stan#1307]
In addition to the log_sum_exp(x1, x2, ...) function, it would be great to have an analogue that takes two arguments (x1, x2) and then performs log(exp(x1) - exp(x2)).

An important application would be for truncated densities, i.e. in case users want to model observations for which only the interval in which they lie is known. For instance, consider count data for which we know that 10 i.i.d. observations have values somewhere between 100 and 199 (including 199). The log-density of these data (up to a constant, assuming a NB distribution) can be currently expressed as:

increment_log_prob(10 * log( neg_binomial_2_cdf(199) - neg_binomial_2_cdf(99) ))

A log_minus_exp function might provide extra stability when combined with neg_binomial_2_cdf_log function:

increment_log_prob(10 * log_minus_exp(neg_binomial_2_cdf_log(199), neg_binomial_2_cdf_log(99)))

**Comment by luccoffeng** [comment]
Link to discussion on Google groups: https://groups.google.com/d/msg/stan-users/T3S9O-vvNX0/GLx-phMq-L8J

**Comment by betanalpha** [comment]
This is already implemented and exposed to the modeling language as log_diff_exp.  See also Section 25.3 (subsection "Truncated Distributions") for exactly this discussion.
