### ISSUE TITLE
Some stan-reference-2.6.0 errors

### ISSUE THREAD

**Issue by avehtari** [stan-dev/stan#1309]
stan-reference-2.6.0.pdf
p. 140 code has eta_sq ~ cauchy(0,5) and rho_sq ~ cauchy(0,5), but p. 141 recommends
           eta ~ cauchy(0,5) and  1/rho_sq ~ cauchy(0,5)
          (maybe the 1/rho_sq ~ is not correct syntax, but you know what I mean)
p. 141 rho is couple times as rho instead of \rho
p. 145 the code has extra "<" in the beginning of one line
p. 219 example code has min and max, but the following paragraph refers to fmin and fmax

**Comment by bob-carpenter** [comment]
Thanks!  I'm moving this to existing issue for manual, #1202.

**Comment by bob-carpenter** [comment]
Thanks.  There are two options that make it easy
for us:

1.  submit a pull request from a branch that branches
from develop (NOT master), or

2.  just add to the existing issue for the manual (listed
as CurrentVersion++)

I moved your comments to the current issue.

  https://github.com/stan-dev/stan/issues/1202

There's also a longer-term manual issue for bigger things
that aren't bugs or typos.

- Bob
