### ISSUE TITLE
prim/mat/meta/is_vector_like.hpp weirdness through check_finite.hpp

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/stan#1312]
matrix specialization for is_vector_like doesn't work as it should. In order for is_vector_like to work correctly, mat/meta/is_vector.hpp must be included, which shouldn't be the case.

**Comment by bob-carpenter** [comment]
Do you need help with this, and if so, could you create a branch with a test that fails that you think should pass?

**Comment by bob-carpenter** [comment]
Also, whenever creating an issue, please give it a milestone and labels, and ideally an assignee.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#79
