### ISSUE TITLE
analytic, vectorized derivatives in transforms and Jacobians

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1313]
The current code in `prob/transforms.hpp` just uses autodiff for the gradients.  

We should add custom derivatives for the transforms and the Jacobians of the transforms.

This should give us a modest boost in speed for any model with upper/lower-constrained scalar parameters, a bigger boost for upper/lower constraind vectors, and bigger still for multivariate constrained parameters like simplex.

**Comment by syclik** [comment]
- [ ] src/stan/math/prim/mat/fun/cholesky_corr_constrain.hpp
- [ ] src/stan/math/prim/mat/fun/cholesky_corr_free.hpp
- [ ] src/stan/math/prim/mat/fun/cholesky_factor_constrain.hpp
- [ ] src/stan/math/prim/mat/fun/cholesky_factor_free.hpp
- [ ] src/stan/math/prim/mat/fun/corr_matrix_constrain.hpp
- [ ] src/stan/math/prim/mat/fun/corr_matrix_free.hpp
- [ ] src/stan/math/prim/mat/fun/cov_matrix_constrain.hpp
- [ ] src/stan/math/prim/mat/fun/cov_matrix_free.hpp
- [ ] src/stan/math/prim/mat/fun/ordered_constrain.hpp
- [ ] src/stan/math/prim/mat/fun/ordered_free.hpp
- [ ] src/stan/math/prim/mat/fun/positive_ordered_constrain.hpp
- [ ] src/stan/math/prim/mat/fun/positive_ordered_free.hpp
- [ ] src/stan/math/prim/mat/fun/simplex_constrain.hpp
- [ ] src/stan/math/prim/mat/fun/simplex_free.hpp
- [ ] src/stan/math/prim/mat/fun/unit_vector_constrain.hpp
- [ ] src/stan/math/prim/mat/fun/unit_vector_free.hpp
- [ ] src/stan/math/prim/scal/fun/corr_constrain.hpp
- [ ] src/stan/math/prim/scal/fun/corr_free.hpp
- [ ] src/stan/math/prim/scal/fun/identity_constrain.hpp
- [ ] src/stan/math/prim/scal/fun/identity_free.hpp
- [ ] src/stan/math/prim/scal/fun/lb_constrain.hpp
- [ ] src/stan/math/prim/scal/fun/lb_free.hpp
- [ ] src/stan/math/prim/scal/fun/lub_constrain.hpp
- [ ] src/stan/math/prim/scal/fun/lub_free.hpp
- [ ] src/stan/math/prim/scal/fun/positive_constrain.hpp
- [ ] src/stan/math/prim/scal/fun/positive_free.hpp
- [ ] src/stan/math/prim/scal/fun/prob_constrain.hpp
- [ ] src/stan/math/prim/scal/fun/prob_free.hpp
- [ ] src/stan/math/prim/scal/fun/ub_constrain.hpp
- [ ] src/stan/math/prim/scal/fun/ub_free.hpp

I'm starting the work on branch: `feature/issue-1313-transforms`

**Comment by bob-carpenter** [comment]
I think a couple of those aren't used, like positive_constrain.
Or maybe we could test that the constraint was 0 and add it?  It'd
cut down on some autodiff.

I'm on the fence about adding syntactic sugar types like "positive_real" (in
part because of numerical issues causing it to be zero and in part because I
don't like multiple ways to say the same thing).

- Bob

**Comment by syclik** [comment]
We'll do this right as we fix this.

The first thing I'm doing is breaking apart tests. I'll push once that's
done.

On Apr 20, 2015 8:37 PM, "Bob Carpenter" <notifications@github.com> wrote:
>
> I think a couple of those aren't used, like positive_constrain.
> Or maybe we could test that the constraint was 0 and add it? It'd
> cut down on some autodiff.

I'll take a look. I'll remove the ones that aren't used.

> I'm on the fence about adding syntactic sugar types like "positive_real"
(in
> part because of numerical issues causing it to be zero and in part
because I
> don't like multiple ways to say the same thing).

We can think about that. If you treat it as an abstraction, I think it
makes sense. The code generator can stay the same with alternate transforms
(for research).

>
> - Bob
>
>
> > On Apr 21, 2015, at 1:33 AM, Daniel Lee <notifications@github.com>
wrote:

**Comment by rtrangucci** [comment]
Is it possible to do these one by one rather than all at once under one big
pull request? It might make it easier to manage, and review. Given that
nothing's changing from the end-user perspective, it's ok to make piecemeal
changes. That'd give us the opportunity to prioritize the most important
transformations for optimization.


Rob

**Comment by syclik** [comment]
All the tests have been split. We're still really spotty for tests on our transforms.
@rtrangucci, I think we need to think about creating a framework for testing transforms.

**Comment by rtrangucci** [comment]
Sounds good, we need an MV test framework anyway.


Rob

**Comment by bob-carpenter** [comment]
We should be able to test the lp increment using autodiff,
too --- it's just the log of the Jacobian determinant of
the transform itself.

- Bob

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#80
