### ISSUE TITLE
neg_binomial_2_cdf / neg_binomial_2_ccdf std::vector usage

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/stan#1315]
neg_binomial_2_cdf and ccdf use std::vector internally, while they should use the VectorBuilder template metaprogram

**Comment by randommm** [comment]
If I remember well, I used std::vector there because I call beta_cdf using those vectors, like in

      if (size_n == 1) {
        if (size_phi_mu == 1)
          return beta_cdf(phi_mu[0], phi, np1[0]);                       
        else
          return beta_cdf(phi_mu, phi, np1[0]);                                 
      }    

AFAIK, VectorBuilder wouldn't work this way.

**Comment by bob-carpenter** [comment]
For what it's worth, I think it'd be better to replace
> 
> 
> if (size_phi_mu == 1)
>   return beta_cdf(phi_mu[0], phi, np1[0]);                       
> else
   return beta_cdf(phi_mu, phi, np1[0]); 

with just the final line.  Then, if there's some reason to
treat a size-1 vector differently in beta_cdf, it can be
done inside that function in just one place.  

Also, why is there only ever np1[0] being used?  (I realize
I'm only looking at a fragment here.)

- Bob

**Comment by randommm** [comment]
It has to be this way because VectorView inside beta_cdf will treat phi_mu as size 1 vector instead of a scalar (if you look at neg_binomial_2_cdf, phi_mu was constructed using VectorView, therefore, a scalar phi and mu will become a vector phi_mu of size one) which will cause an error.

**Comment by betanalpha** [comment]
The error is in the checking of consistent dimensions — the current
metaprogram treats scalars and vectors of length 1 as inconsistent
which causes the error.  Dan and I argued about this a bit in December
but ended up leaving it as it is.

Really we shouldn’t be calling distributions from distributions — for
optimal performance we need to reimplement everything with the
manipulations needed for each specific parameterization.

**Comment by randommm** [comment]
On 2015-02-27 10:47 AM, Michael Betancourt wrote:
> The error is in the checking of consistent dimensions — the current
> metaprogram treats scalars and vectors of length 1 as inconsistent
> which causes the error. Dan and I argued about this a bit in December
> but ended up leaving it as it is.
IMHO, I find the current behavior (of not considering a vector of size 1 
a scalar) good and consistent, changing this might open a path for bad 
usage by users and unexpected behavior like what happens with R's vector 
types.

If one knows whats it's doing, then all one needs to do is call the 
first element of the vector like normal_log(y, mu[0], sigma), if one 
doesn't then normal_log(y, mu, sigma) will cause an error.


>
> Really we shouldn’t be calling distributions from distributions — for
> optimal performance we need to reimplement everything with the
> manipulations needed for each specific parameterization.
>
Maybe in this case, it would be better to have a beta function, and have 
both neg_binomial_2_cdf and beta_cdf call it?

**Comment by bob-carpenter** [comment]
> On Feb 28, 2015, at 7:12 AM, Marco Inacio <notifications@github.com> wrote:
> 
> 
> On 2015-02-27 10:47 AM, Michael Betancourt wrote:
> > The error is in the checking of consistent dimensions — the current
> > metaprogram treats scalars and vectors of length 1 as inconsistent
> > which causes the error. Dan and I argued about this a bit in December
> > but ended up leaving it as it is.

> IMHO, I find the current behavior (of not considering a vector of size 1 
> a scalar) good and consistent, changing this might open a path for bad 
> usage by users and unexpected behavior like what happens with R's vector 
> types.
> 
> If one knows whats it's doing, then all one needs to do is call the 
> first element of the vector like normal_log(y, mu[0], sigma), if one 
> doesn't then normal_log(y, mu, sigma) will cause an error.

That's my position, too.

> > Really we shouldn’t be calling distributions from distributions — for
> > optimal performance we need to reimplement everything with the
> > manipulations needed for each specific parameterization.
> 
> Maybe in this case, it would be better to have a beta function, and have 
> both neg_binomial_2_cdf and beta_cdf call it

On tis I agree with Michael.  And yes, that'd be the right
solution.  

In general, you don't want to call more client-facing functions
internally because they typically do a bunch of extra work
validating parameters, which if they fail, then produce error
messages from surprising places in functions the client code never 
called.

- Bob

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#81
