### ISSUE TITLE
custom derivatives for (scalar * matrix), etc.

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1325]
Right now, the code has this kind of ugliness in it (a holdover from my very first naive implementations):

`agrad/rev/matrix/multiply.hpp`:

```
   template<typename T1,typename T2,int R2,int C2>
    inline Eigen::Matrix<var,R2,C2> multiply(const T1& c, 
                                             const Eigen::Matrix<T2, R2, C2>& m) {
      // FIXME:  pull out to eliminate overpromotion of one side
      // move to matrix.hpp w. promotion?
      return to_var(m) * to_var(c);
    }
```

I believe (scalar + matrix) will have the same issues---there's not even an `agrad/rev` version of `math/matrix/add.hpp`.  

We should be able to pretty easily implement all of these along the same lines as dot product is implemented rather than promoting and calling Eigen.  And I believe they'll offer a substantial speedup to things like `alpha + x * beta` in GLMs.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#82
