### ISSUE TITLE
use our multiply overrides for matrix arithmetic

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1339]
For all of our internal matrix arithmetic, we should be using our own `multiply()` functions if there are autodiff variables involved rather than `operator*()` from Eigen.  There are currently instances in functions that are relying on implicit promotion.  One example is `lkj_cholesky_cor_log`

One approach is to:

* [ ] implement `operator*()` for all the `var` and `fvar` matrix types

The benefits are

* argument-dependent lookup would pull in the right definition
* this would be used by Eigen programs we autodiff through
* it'd be easier for users of our C++ API 

This one's important because I believe we're inadvertently promoting to var and using generic Eigen types algorithms ather than getting our more effficient specialized `multiply()` operators.  This has the potential to be a huge speedup for the implicated functions which we'll have to hunt down in the code.

**Comment by mbrubake** [comment]
There is also a third option, I believe there is a way to specialize Eigen's evaluation template.  I'd played with that a bit back when we were trying to get mixed operations working but didn't have much luck.

Anyway, I'd recommend translating arithmetic operators to explicitly named functions for consistency and to reduce code duplication.

**Comment by syclik** [comment]
How do we do that? I was searching for that solution last week and couldn't
find it online... I'm sure I was just searching incorrectly.

**Comment by bob-carpenter** [comment]
All we need to do is have the code generator produce "multiply(a,b)" instead of "a * b".
The downside of this approach is that it won't get picked up internally by Eigen 
algorithms we autodiff through and it's less syntactically convenient for users of 
our C++ API for autodiff.

What we need to do, I think, is produce a general enough definition of
operator* and then just rely on argument-dependent lookup.  I don't think
we can get away with an easy implementation using enable_if plus scalar
traits extraction because of the complexity around return types.

I think we need to just bite the bullet and implement each of the
operator* patterns in the doc.

I don't want to touch this until after the autodiff reorg lands (issue #1222,
pull request #1320).

- Bob

**Comment by bob-carpenter** [comment]
The first issue writeup was dead wrong.  We *are* compiling to `multiply()` in the language.  I rewrote the issue because the problem actually lies in functions like `lkj_cholesky_corr_log`, which are using Eigen `operator*` operators, which will inadvertently promote `double` values to `var` and then use Eigen's built-in operator definitions, which are much less efficient for autodiff than our specialized ones.

**Comment by syclik** [comment]
should we be using `multiply` everywhere inside our matrix operations? @mbrubake, how do we specialize Eigen to handle this for us?

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#83
