### ISSUE TITLE
Expose matrix_normal 

### ISSUE THREAD

**Issue by avehtari** [stan-dev/stan#1344]
Ben writes
> The function in the matrix_normal.hpp file is called matrix_normal_prec(). It is not exposed, although it has tests, so we should probably expose it and then maybe Seth or Aki can work on enhancing it and / or speeding it up.

This is related to the discussion of making autodiff faster for Cholesky, which would make following faster
  L <- cholesky_decompose(C);
  z ~ normal(0,1);
  f <- L * z;
  y ~ bernoulli_logit(f);
where C is a NxN covariance matrix, and y is a vector of length N.

**Comment by rtrangucci** [comment]
We still need first-order reverse-mode tests for matrix_normal_prec_log, unless I haven't found all the tests.

Right now there are three .cpp files that implement matrix_normal_prec_log tests:

- test/unit/math/prim/mat/prob/matrix_normal_test.cpp
- test/unit/math/mix/mat/prob/matrix_normal_test.cpp
- test/unit/math/fwd/mat/prob/matrix_normal_test.cpp

As far as I can tell, none of these files implement reverse-mode first order tests. The fwd and mix files run first-order fvar<var> and fvar<fvar<var>> tests. We need a test/unit/math/rev/mat/prob/matrix_normal_test.cpp that does the reverse-mode tests.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#86

**Comment by randommm** [comment]
I think this shouldn't have been moved to stan/math since it's a matter of exposing a function.

**Comment by rtrangucci** [comment]
There's a bit of work to be done on the stan/math side before we take care
of exposing the function in the stan language. Matrix normal doesn't yet
have finite-diff/gradient tests. It'd be good to get these in stan/math
like we've got for the other multivariate distributions.


Rob
