### ISSUE TITLE
Constraint Violations in Transformed Parameters Block

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#1345]
In the workshop today we were fitting an ODE model with positive states -- because the states were meaningful they were declared and then assigned in the `transformed parameters` block in order to be saved in the Markov chain output.  The problem was that during warmup the parameters induced ODE solutions sufficiently close to zero that the constraints were violated and exceptions thrown -- but these exceptions were not caught by the HMC sampler, hence instead of the proposal being rejected the chain terminated.

Should we have exceptions thrown in the transformed parameters block induce rejections?  One problem is that we can't guarantee that those exceptions would lead to poor likelihoods so it's not always clear what the statistical interpretation of a transformed parameter exception is.

**Comment by bob-carpenter** [comment]
Aha!  And yes, by all means!

I bet this is the root cause of the problems Daniel's
running into with that other issue that came up.  

Nice catch (pun intended).

- Bob

**Comment by bob-carpenter** [comment]
This problem was resolved at some point.  For example, this model

```
parameters {
  real y;
}
transformed parameters {
  real<lower=0> z = y;
}
model {
  y ~ normal(0, 10);
}
```
continues to cause rejection messages to be thrown when `z < 0` through sampling and still terminates normally.
