### ISSUE TITLE
append_col and append_row for scalars

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1347]
It would be nice to extend append_row and append_col to scalars, with signatures

```
vector append_row(vector, real);
vector append_row(real, vector);
```

and

```
vector append_col(row_vector, real);
vector append_col(real, row_vector);
```

I'd like to use them to define centered vectors, so that instead of

```
vector[K-1] beta_raw;
...
vector[K] beta;

for (k in 1:(K-1))
  beta[k] <- beta_raw[k];
beta[K] <- -sum(beta_raw);
```

I could define `beta` by

```
beta <- append_col(beta_raw, -sum(beta_raw));
```

This should be super simple as there are no gradient definitions required.

- [ ] add doc

**Comment by ariddell** [comment]
Just found myself wanting this (again).

**Comment by bob-carpenter** [comment]
Me, too --- it's for all those one-element-constrained vectors.  I'm bumping the milestone to 2.7.0++.  Marco --- any chance you can do this?  If not, please reassign to me.

**Comment by randommm** [comment]
I've completely forgotten about this. I'll do it. But should it be on stan-dev/stan or stan-dev/math?

**Comment by syclik** [comment]
I don't know where the code is, but my guess is math.

**Comment by elad663** [comment]
looking forward for v.2.9.0
btw, was a pleasure meeting you guys on Saturday.

**Comment by syclik** [comment]
stan-dev/math#188 implements the function in math. We need to add the function to the language and write doc.
