### ISSUE TITLE
print_progress() should input / output the chain ID

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#1348]
Currently, when you do chains in parallel the progress report does not look so good

```
Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  500 / 2000 [ 25%]  (Warmup)
Iteration:  500 / 2000 [ 25%]  (Warmup)
Iteration:  500 / 2000 [ 25%]  (Warmup)
Iteration:  500 / 2000 [ 25%]  (Warmup)
Iteration:  500 / 2000 [ 25%]  (Warmup)
Iteration:  500 / 2000 [ 25%]  (Warmup)
```

And it is even worse if the chains are not progressing at the same rate. It would be better if it said

```
Chain #, iteration: ...
```

but print_progress() currently does not have an argument to accept the chain ID.

**Comment by syclik** [comment]
@bgoodri, there's already a `prefix` argument for that purpose. I'm not sure if it's sufficient, but I'll try to create a pull request for RStan that'll fix it.

**Comment by bob-carpenter** [comment]
see #1166

**Comment by WardBrian** [comment]
Chain is now part of the output when `num_chains != 1`
