### ISSUE TITLE
add test for nan derivatives for distribution tests

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1358]
the distribution tests currently don't check if the derivatives are `nan`. I think they should.

**Comment by syclik** [comment]
I fixed the distribution tests. I located the distributions that have problems. We'll need to fix all of them by hand.

##### Warnings:
- [ ] neg_binomial

##### Failed tests:
- [ ] beta
- [ ] cauchy
- [ ] double_exponential
- [ ] exp_mod_normal
- [ ] exponential
- [ ] frechet
- [ ] gumbel
- [ ] lognormal
- [ ] neg_binomial_2
- [ ] normal
- [ ] pareto_type_2
- [ ] rayleigh
- [ ] skew_normal
- [ ] weibull

**Comment by bob-carpenter** [comment]
Awesome --- this should do wonders for robustness.

Is the plan to have them throw if they catch NaN values?
I think that'd be better than returning NaN values, which
would cause rejection, but then would fail in the double
case where you didn't care about gradients.

- Bob

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#87
