### ISSUE TITLE
append_row(vector, vector) returns the wrong type

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/stan#1366]
If I compile (with stan_model()) and run (with sampling()) the following model, the resulting fit object has mode=2, indicating an error that occurred before sampling:

    parameters {
      vector[3] x;
      vector[2] y;
    }
    transformed parameters {
      vector[5] z;
      z <- append_row(x, y);
    }
    model {
      z ~ normal(0, 1);
    }

The error message is 

    error in call to assign(Eigen::Matrix,Eigen::Matrix); shapes must match, but found R1=-1; C1=1; R2=-1; C2=-1

The error appears to be occurring in the assignment to z. Looking into the code for append_row in include/stansrc/stan/math/matrix/append_row.hpp, I see the following:

    template <typename T1, typename T2, int R1, int C1, int R2, int C2>
    inline Matrix<typename return_type<T1, T2>::type, Dynamic, Dynamic>
    append_row(const Matrix<T1, R1, C1> & A,
          const Matrix<T2, R2, C2> & B) {
        ...
    }
    
    template <typename T1, typename T2, int R1, int R2>
    inline Matrix<typename return_type<T1, T2>::type, Dynamic, 1>
    append_row(const Matrix<T1, R1, 1> & A,
          const Matrix<T2, R1, 1> & B) {          
        ...
    }

    template <typename T, int R1, int C1, int R2, int C2>
    inline Matrix<T, Dynamic, Dynamic>
    append_row(const Matrix<T, R1, C1> & A,
          const Matrix<T, R2, C2> & B) {
        ...
    }
    
    template <typename T, int R1, int R2>
    inline Matrix<T, Dynamic, 1>
    append_row(const Matrix<T, R1, 1> & A,
          const Matrix<T, R1, 1> & B) {          
        ...
    }

The signature for the last variant of append_row appears to be wrong: I think the type for B was meant to be const Matrix<T, R2, 1> & instead of const matrix<T, R1, 1>. It appears that, due to this error, a call to append_row() on two vectors ends up matching the second-to-last variant of append_row, returning a result of type Matrix<T, Dynamic, Dynamic> instead of Matrix<T, Dynamic, 1>.

**Comment by ksvanhorn** [comment]
Arg! That last paragraph got formatted wrong. Here it is again:

    The signature for the last variant of append_row appears to be wrong: I think the type for B was
    meant to be const Matrix<T, R2, 1> & instead of const Matrix<T, R1, 1> &. It appears that, due to
    this error, a call to append_row() on two vectors ends up matching the second-to-last variant of
    append_row, returning a result of type Matrix<T, Dynamic, Dynamic> instead of
    Matrix<T, Dynamic, 1>.

**Comment by syclik** [comment]
@ksvanhorn, what interface / version are you using? I think this was fixed with either #1241 or #1297. I don't see this in CmdStan v2.6.0 or the current development version.

**Comment by ksvanhorn** [comment]
I'm still using 2.5.0. Sorry, I didn't check to see if this had already been reported.

**Comment by syclik** [comment]
No problem.

On Fri, Mar 13, 2015 at 4:33 PM, Kevin S. Van Horn <notifications@github.com

**Comment by bob-carpenter** [comment]
There's another issue with return types for those functions
which will be fixed in 2.6.2 as soon as we can get the $%^&*-ing
__float128 issue worked out.

- Bob
