### ISSUE TITLE
nonnegativity of dimensions of matrices in model block is not checked

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#1367]
This parses, compiles, and fails at runtime:
```
parameters {
  real theta;
}
model {
  matrix[-1,-1] X;
  theta ~ normal(0,1);
}
```

**Comment by bob-carpenter** [comment]
The size declarations, in general, are expressions which can't be evaluated until run time.  You'll find the same issue if you try to allocate something too large.  Or use a data variable that's negative.
