### ISSUE TITLE
fixed matrices not promoted in model block

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#1368]
This parses but fails to compile
```
transformed data {
  vector[4] ones;
  ones <- rep_vector(1,4);
}
parameters {
  real theta;
}
model {
  matrix[4,4] X;
  X <- diag_matrix(ones);
  theta ~ normal(0,1);
}
```

**Comment by syclik** [comment]
Ben, I can't reproduce using CmdStan off the development branch of both
CmdsStan and Stan in Mac using clang++ and g++.

What compiler is giving you trouble?


Daniel

**Comment by bgoodri** [comment]
Hmm. I was using RStan. But I repulled the subrepository from develop and now the problem has disappeared. So, that is good.
