### ISSUE TITLE
src/stan/version.hpp should have numbers available to the preprocessor

### ISSUE THREAD

**Issue by jpritikin** [stan-dev/stan#1383]
Currently the version is stored in `const std::string`. These aren't available at preprocessor time. This means that it is impossible to write conditional code that compiles against more than 1 stan version with minor header incompatibilities.

----------------
* [x] add it to the language parser to check for reserved words
* [x] add to the manual's list of reserved words.
* [x] define `STAN_MAJOR`
* [x] define `STAN_MINOR`
* [x] define `STAN_PATCH`

**Comment by jpritikin** [comment]
Rationale: Currently there is a potential CRAN race condition. Suppose StanHeaders is upgraded first. Then OpenMx will fail to install until it is updated. Same problem is OpenMx is upgraded first. So both packages would need simultaneous upgrades on CRAN to avoid the situation where OpenMx was uninstallable for a short time.

**Comment by syclik** [comment]
@jpritikin, can you take it a step further and describe what macro should be defined? should we split it into 3 version numbers (major, minor patch) or a single version? or not?

**Comment by syclik** [comment]
this page lists a lot of existing macros:
http://nadeausoftware.com/articles/2012/10/c_c_tip_how_detect_compiler_name_and_version_using_compiler_predefined_macros

**Comment by jpritikin** [comment]
> should we split it into 3 version numbers (major, minor patch) or a single version?

Yes, given that the preprocessor can only make simple comparisons. You might want to follow something like, gcc with "`__GNUC__` and `__GNUG__` contain the major version number, and `__GNUC_MINOR__` and `__GNUC_PATCHLEVEL__` the minor version and patch level numbers (e.g. "4", "6", and "1" for version 4.6.1). The `__GNUC_PATCHLEVEL__` macro was introduced in version 3.0."

**Comment by bob-carpenter** [comment]
[re-subjected to grab Ben's attention]

I seem to recall Ben telling me that once we're on CRAN,
our hands are going to be tied in not letting us update versions
that break other packages.

Ideally, we'd not use "__" because it's reserved for system
variables in C++, but we might want to anyway because we do elsewhere
without problems anywhere and it's already built-in as a reserved
symbol in the language 

- Bob

**Comment by jpritikin** [comment]
> Ideally, we'd not use "__" because it's reserved for system variables in C++

Yeah, I think it would be fine without the _ prefix and postfix. Just STAN_VERSION, etc would be fine.

**Comment by bob-carpenter** [comment]
Without the "__" sufix, we'll also need to

* [ ] add it to the language parser to check for reserved words, and 
* [ ] add to the manual's list of reserved words.

- Bob

**Comment by jpritikin** [comment]
I see this still isn't addressed in stan 2.7. That is disappointing.

**Comment by syclik** [comment]
@jpritikin, I added a todo list to the top comment. Can you check and see if that's sufficient?

**Comment by bob-carpenter** [comment]
Also just a heads up that Daniel is going to be pulling the math library
into its own Git repo for the 2.7 release and we hope to keep the paths,
namespaces, etc., stable after this.  Sorry for all the disruption en route.
It's a general rule that it takes 3 tries to get a library right, so hopefully
this one will stick for awhile.

- Bob

**Comment by jpritikin** [comment]
@syclik Looks good.

> Daniel is going to be pulling the math library into its own Git repo for the 2.7 release

Sounds good. Will that be reflected in the R packaging too? Will you split StanHeaders into StanMathHeaders and StanHeaders?

**Comment by syclik** [comment]
@jpritikin, I hope not. Our plan is for Stan to package up everything it needs, which includes the math library.

**Comment by bob-carpenter** [comment]
It'd be nice to split out math.  I could imagine someone
writing a wrapper around Stan Math that let you define a C++
function and then wrapped it to provide evaluation and gradients
(or higher order) back to R.

- Bob

**Comment by jpritikin** [comment]
@bob-carpenter Yeah, that's what I was thinking. But it's not a big deal either way.

**Comment by jpritikin** [comment]
On Mon, Jun 08, 2015 at 09:44:44PM -0700, Bob Carpenter wrote:
>    It'd be nice to split out math. I could imagine someone
>    writing a wrapper around Stan Math that let you define a C++
>    function and then wrapped it to provide evaluation and gradients
>    (or higher order) back to R.

Yeah, that would be very cool :-)
