### ISSUE TITLE
write tests for advi

### ISSUE THREAD

**Issue by akucukelbir** [stan-dev/stan#1391]
### remove
- [x] variational/latent_vars_test.cpp

### simple tests (no associated stan model)
- [x] variational/advi_params_fullrank_test.cpp
- [x] variational/advi_params_meanfield_test.cpp

these will test basic member functions, accessors, mutators, etc.

### model-based tests (for ELBO)
- [x] variational/advi_univar_no_constraint_test.cpp
- [x] variational/advi_univar_with_constraint_test.cpp
- [x] variational/advi_multivar_no_constraint_test.cpp
- [x] variational/advi_multivar_with_constraint_test.cpp

these will test the ELBO computation.

### gradients
- [x] include gradient tests in the model-based tests.

**Comment by syclik** [comment]
Alp, did you need / want help?

**Comment by akucukelbir** [comment]
thanks dan. i haven't gotten around to writing them up (though it really shouldn't take me too much time.)

what would be most useful is: a) is there anything missing? and b) do you see any opportunities to "guard myself"?

i remember you saying a while back that tests are most useful if they make sure some change elsewhere doesn't break what i've written (and vice versa). since our algorithm interfaces rather lightly with the rest of stan (apart from the model and the autodiff stuff... if anything breaks there, so will HMC, optimize, etc.), i didn't know what else to consider. any recommendations?

**Comment by syclik** [comment]
Looks pretty good. Where it says add tests below, what you really want to do is:

1. make sure the functions work under situations where you know it'll work. Usually that means some calculation is correct. (Use `EXPECT_FLOAT_EQ` to check values.)
2. make sure the functions stop when the inputs are invalid. For each condition, just put in an example and make sure the functions stop.

With those general guidelines, it's really up to you to determine how much you want to test. For example, do you want to make sure Inf or NaN are caught? If they're not, do you expect bbvb to work? If so, let it through. If not, make sure it stops.

Specifics:
- [ ] src/stan/variational/advi.hpp
    - [ ] add tests for `calc_combined_grad` (src/stan/variational/advi.hpp)
        - [ ] check for each of the error conditions
    - [ ] `calc_ELBO`: if `n_monte_carlo_elbo_` is 0, things go to NaN.
    - [ ] `calc_ELBO`: should L_chol() be checked for success?
    - [ ] constructor: `n_monte_carlo_grad`: what happens with negative or zero values? do you want that to be ok?
    - [ ] constructor: `n_monte_carlo_elbo`: what happens with negative or zero values?
    - [ ] add tests for `do_robbins_monro_adagrad`
        - [ ] replace std::cout with stream passed in.
- [ ] test the entropy functions in both the parameters
- [ ] mutators on the parameters: make sure to validate! it would be easy to use `set_mu` to set a completely different size.

**Comment by akucukelbir** [comment]
thanks so much for all this dan. it's incredibly helpful to me.

i have a question about the "invalid" conditions (and testing conditions in general).

so let's say i have a constructor that has `stan::math::check_size_match();` and 
`stan::math::check_cholesky_factor();` in there. do you want me to write "invalid" tests that trip these two conditions? (i.e. construct with a vector of wrong size, construct with a non cholesky matrix?)

or can i trust the `stan::math::check_xyz` style things, as long as i am thorough and careful about where i put them?

**Comment by bob-carpenter** [comment]
Yes --- there should be tests for invalid arguments
that validate that the right exceptions get thrown and
ideally validate that the right message is getting thrown.

I don't think you need to check this on internal functions --- just
things beyond your control as a programmer.  That is if you define
a function

  foo(some_type x) {
    ... 
    bar(x);
    ...
  }

for a client and validate that x is the right sort of thing, then
bar() doesn't need to recheck x.

- Bob

**Comment by akucukelbir** [comment]
hi @bob-carpenter, @syclik,

thanks for the comments. i've been working on the tests, but i seem to have hit a hurdle when trying to test with a multivariate model.

specifically, when i try to run `./runTests.py src/test/unit/variational/advi_multivar_no_constraint_test.cpp` i get this strange error that seems to come out of check_finite:

```
src/stan/math/prim/scal/fun/value_of_rec.hpp:25:14: error: cannot convert 'const
      Eigen::Matrix<double, -1, 1, 0, -1, 1>' to 'double' without a conversion operator
      return static_cast<double>(x);
             ^~~~~~~~~~~~~~~~~~~~~~
src/stan/math/prim/scal/err/check_finite.hpp:36:42: note: in instantiation of function template
      specialization 'stan::math::value_of_rec<Eigen::Matrix<double, -1, 1, 0, -1, 1> >' requested
      here
            if (!(boost::math::isfinite)(value_of_rec(stan::get(y, n))))
                                         ^
src/stan/math/prim/scal/err/check_finite.hpp:66:11: note: in instantiation of member function
      'stan::math::<anonymous namespace>::finite<Eigen::Matrix<double, -1, 1, 0, -1, 1>,
      true>::check' requested here
        ::check(function, name, y);
          ^
src/stan/math/prim/mat/prob/multi_normal_log.hpp:98:9: note: in instantiation of function template
      specialization 'stan::math::check_finite<Eigen::Matrix<double, -1, 1, 0, -1, 1> >' requested
      here
        check_finite(function, "Location parameter", mu_vec[i]);
        ^
src/test/test-models/good/variational/multivariate_no_constraint.hpp:180:28: note: in instantiation
      of function template specialization 'stan::prob::multi_normal_log<false,
      Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>,
      Eigen::Matrix<double, -1, -1, 0, -1, -1> >' requested here
            lp_accum__.add(multi_normal_log<propto__>(mu, mu0, sigma));
```

could either of you (or any other kind soul) point me in the right direction? the univariate tests compile and run. and the model compiles and runs if i just compile it through cmdstan the regular way.

**Comment by bob-carpenter** [comment]
Sorry -- thought I'd answered this one.

This is because you're trying to convert a matrix to a double.

- Bob

**Comment by akucukelbir** [comment]
but where, why?

the error seems to originate from logprob, but if i just take
the model and compile it using cmdstan, it runs just fine?

(dan generously agreed to skype with me later today, so hopefully
he can catch whatever is escaping me here...)

**Comment by bob-carpenter** [comment]
I can't really add much helpful here without having the code
in front of me to trace through the template instantiations.
The problem is that each error message is using its own local
variables.  

- Bob

**Comment by akucukelbir** [comment]
alright guys, i think things are looking pretty good at this point.
