### ISSUE TITLE
replace std::cout in initialization 

### ISSUE THREAD

**Issue by maverickg** [stan-dev/stan#1399]
see L156 and L246 of https://github.com/stan-dev/stan/blob/develop/src/stan/services/init/initialize_state.hpp

Potentially, this could cause complain from CRAN.

**Comment by maverickg** [comment]
I can fix this in PR #1082

**Comment by maverickg** [comment]
and
```
./io/stan_csv_reader.hpp:327:          std::cout << "Warning: non-fatal error reading samples" << std::endl;
./math/prim/mat/fun/cholesky_corr_constrain.hpp:28:        std::cout << "k_choose_2 = " << k_choose_2 << " y.size()=" << y.size() << std::endl;
./math/prim/mat/fun/cholesky_corr_constrain.hpp:68:        std::cout << "k_choose_2 = " << k_choose_2 << " y.size()=" << y.size() << std::endl;
./services/init/init_adapt.hpp:34:          std::cout << "Exception initializing step size." << std::endl
```

**Comment by maverickg** [comment]
I fixed the two std::out's in the initialization code. 

Do we need to work on others?

**Comment by syclik** [comment]
Yes. What's the status of CRAN?

**Comment by bgoodri** [comment]
They want a new StanHeaders. Can we do a 2.6.4 with no std::cout or std::cerr in code that could be called by rstan?

**Comment by syclik** [comment]
Sure, but since this looks to be a back-and-forth process, how about just
packaging some git hash for StanHeaders, slap a "beta" or "alpha" version
on it, and after it gets accepted, we can then create a tag in Stan and you
can update StanHeaders with the tagged version?


I'm happy tagging with 2.6.4 if that's the last hurdle. We'd want to update
all our interfaces at that point too. If it's not the last hurdle, I'd
rather not roll out multiple versions in quick succession.

**Comment by bgoodri** [comment]
That is fine. Merge https://github.com/stan-dev/stan/pull/1419 and then I can do that. Since we have line numbers from the parser, it should probably be 2.7.0 in which case perhaps we should merge anything else that is imminent but safe.

**Comment by bob-carpenter** [comment]
> On Apr 7, 2015, at 2:49 AM, bgoodri <notifications@github.com> wrote:
> 
> That is fine. Merge #1419 and then I can do that. Since we have line numbers from the parser, it should probably be 2.7.0 in which case perhaps we should merge anything else that is imminent but safe.
> 

Agreed on all fronts.  The multiple issues are already
raising questions on the mailing list.  And we're behind
on updating the web site for PyStan. 

I would prefer as general practice to not be releasing
versions of Stan more frequently than quarterly.  Agile is
all well and good, but each release is overhead (mental and
manual updating) for both the devs and the users.

- Bob
