### ISSUE TITLE
add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1408]
This will add a link when creating issues or pull requests. Although we can't have a template pre-populated, we can put the template there and have it be one click away.

See this github blog post for more details:
https://github.com/blog/1184-contributing-guidelines

**Comment by bob-carpenter** [comment]
Sounds good.  I'll update the style guide, which is already
out of date w.r.t. size types (they're now template traits programs).

- Bob
