### ISSUE TITLE
fix types in check_equal so clients don't need to cast

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1410]
There's a problem with issue #1405 triggering compiler style warnings that are due to a problem in `check_equal`.  Those calls to `check_equal` should not be triggering warnings.

**Comment by bob-carpenter** [comment]
OK, I see what's going on now.    

The two options seem to be

* client code includes explicit static_cast<int>(...) or static_cast<size_t>(...)  when it knows it's comparing different size types

* `check_equal` and other error checking code handles the casting for us.  This would involve writing more complicated check code to suppress the warnings

I don't like either solution.  The first one overcomplicates client code and the second one potentially hides errors.  

Daniel, if you can't live with the second option, just close this issue.

**Comment by syclik** [comment]
I think we can close this. We have a separate check function called
"check_size_match" that handles the casting for us.

**Comment by syclik** [comment]
It's in: src/stan/math/prim/scal/err/check_size_match.hpp

**Comment by bob-carpenter** [comment]
Daniel provided the solution in the last comment.  Thanks.
