### ISSUE TITLE
Order of checks in matrix functions

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/stan#1415]
Checks in matrix functions not ordered correctly; e.g.

mdivide_left_spd.hpp:

```
stan::math::check_symmetric("mdivide_left_spd", "A", A);
stan::math::check_pos_definite("mdivide_left_spd", "A", A);
stan::math::check_square("mdivide_left_spd", "A", A);
stan::math::check_multiplicable("mdivide_left_spd", 
                                                   "A", A,
                                                   "b", b);
```

@syclik pointed out we should be checking whether the two matrices are multiplicable before we run the check_pos_definite test. Check_pos_definite also already checks symmetry internally, so no need to call it twice.

**Comment by bob-carpenter** [comment]
The positive definiteness check should also check that the
matrix is square.

- Bob

**Comment by rtrangucci** [comment]
@bob-carpenter I should have added that check_symmetric calls check_square, so there only need to be two checks in mdivide_left_spd(A,b):

```
check_multiplicable(A,b)
check_pos_defininte(A)
```

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#88
