### ISSUE TITLE
next manual (2.6.3++)

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1420]
This is the issue for the next manual release.  Please submit all bugs and feature requests for the manual here.

**Comment by bob-carpenter** [comment]
Everyone keeps asking about whether Stan can just "keep going" and do more sampling.  

You absolutely cannot just keep going.  Nor do you want to. The problem is that if you haven't reached convergence, then you want to do more warmup, and then more sampling.  So you'd have to toss out the sampling part of the run anyway.

If you run 1000 warmup iterations and 1000 sampling iterations and haven't converged, then you want to go back and run 2000 warmup iterations and 2000 sampling iterations.  If you were to restart, after the original warmup iterations, you'd save around 15% of your work.  Here's an example with the default number of iterations (which is probably way too high):

#### Rerun from beginning, doubling sizes

```
   1000 + 1000
   2000 + 2000
   -----------
   3000 + 3000
```

#### Restart warmup (warmup hasn't converged):

```
   1000     + 1000
   0 + 1000 + 2000
   -----------
   2000 + 3000
```

The exception to this is when you have converged during warmup, but
just haven't drawn enough iterations for the n_eff you need.  In that
case, you'd get this:

 #### Resample
  
```
   1000 + 1000
      0 + 1000
   -----------
   3000
```

#### Restart sampling (warmup converged)

```
   1000 + 1000
   1000 + 2000
   -----------
   5000
```

So you'd save about 40% of your total effort if you could just run more samples.

**Comment by randommm** [comment]
Notice: I just created the branch for this issue with some typos fixed.

**Comment by syclik** [comment]
From Andrew:
- [ ] We should always lead with the fast code and then explain how it’s equivalent to the non-vectorized version.  For example on pp. 61-62 of manual we have multivariate regression with hier model and we start with non-vectorized.  This is confusing because if I want to imitate this model myself I have to grab different code snippets.

**Comment by bob-carpenter** [comment]
Sunil Nandihalli reported on stan-users:

on page 50 of stan-reference-2.6.2.pdf in section 5.7 it is said that C belongs R^(D-1)
should be read as C belongs to R^(K-1)

* [ ] fix it
* [ ] thank Sunil

**Comment by bob-carpenter** [comment]
Andy Choi brought this up on stan-users:

Under the Gaussian Process chapter of the STAN reference manual (Ch 14, version: 2.6.2, pg. 140, 142, 143), the footnote mentioned/suggested the code referenced in the text can be found at: http://mc-stan.org/examples.html

* [ ] point users to https://github.com/stan-dev/example-models/tree/master/misc/gaussian-process
* [ ] thank Andy

**Comment by bob-carpenter** [comment]
* [ ] add Alp Kucukelbir as a core developer (variational inference!)

**Comment by bob-carpenter** [comment]
From Sebastian Weber:

* [ ] add a reference to

https://software.intel.com/en-us/articles/consistency-of-floating-point-results-using-the-intel-compiler

in your manual concerning the Intel compiler. Most users won’t bother, but I certainly do.

**Comment by bob-carpenter** [comment]
From Heraa Hu in issue #1450 

In the manual p. 273 it says: "Stan allows function overloading, where two functions have the same name. For example, an overloaded unit-normal log density function might be declared with an overload of the function unit_normal_log, giving it three signatures with one argument each."

* [ ] remove this and explicitly mention that overloading doesn't work

**Comment by jgabry** [comment]
On p. 59 (second paragraph of section 5.12) it says 

"... and the outcome income, with predictors such as income and age...". 

Income is listed both as the outcome and a predictor here. Maybe use education level (or something else) as an example predictor instead of income?

**Comment by bob-carpenter** [comment]
* [ ] add a disclaimer about local optima in mixture models (degenerate solutions where one component collapses into another)

**Comment by syclik** [comment]
- [ ] thank @dvukcevic for fixing a typo and creating a pull request: #1491.
