### ISSUE TITLE
stable var(), sd(), covar() and corr() calculations with analytic derivatives

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1423]
We should write versions of all these functions that are numerically stable and have analytic derivatives:

* `var(reals) : real`
* `sd(reals) : real`
* `covar(reals,reals) : real`
* `corr(reals,reals) : real`

The signatures for `reals` would allow any of the 1D containe types (`real[]`, `vector`, or `row_vector`).  
Then we want versions to calculate whole matrices of covariances and correlations, as in:

* `covar(matrix): matrix`
* `covar(vector[]): matrix`
* `covar(row_vector[]) : matrix`
* `corr(matrix): matrix`
* `corr(vector[]): matrix`
* `corr(row_vector[]): matrix`

The signatures taking matrices should go row-wise, taking an `N x K` matrix to an `K x K` matrix of results.  These should be careful to only compute values for the below (or above) diagonal elements and reuse them in the final result and to only calculate the variance of each variable once.  

It might make sense to have versions that return a triangular matrix of results, but it's not urgent as the copies will be relatively cheap.

The Wikipedia has a nice summary of the problems the naive approaches have with catastrophic cancellation:

* Wikipedia: [Algorithms for Calculating (Co)Variance](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance)

The upshot is that we should be using Welford's algorithm for the calculations.  There's an implementation built into Boost's accumulators:

* Boost: [Accumulators reference](http://www.boost.org/doc/libs/1_55_0/doc/html/accumulators/reference.html)

We just have to be careful to do the (unbiased) sample versions of (co)variance that divide by `N-1` and not by `N`.  And then use those for `sd` and `corr`.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#89
