### ISSUE TITLE
global user-defined functions

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#1428]
The `sourceCpp()` function in the Rcpp package has some additional restrictions

"Functions exported using sourceCpp must meet several conditions, including being defined in the global namespace and having return types that are compatible with Rcpp::wrap and parameter types that are compatible with Rcpp::as. See the Rcpp::export documentation for more details."

Furthermore the Rcpp::export documentation says
"Functions marked with the Rcpp::export attribute must meet several conditions to be correctly handled:
Be defined in the global namespace (i.e. not within a C++ namespace declaration).
Have a return type that is either void or compatible with Rcpp::wrap and parameter types that are compatible with Rcpp::as (see sections 3.1 and 3.2 of the Rcpp-introduction vignette for more details).
Use fully qualified type names for the return value and all parameters. However, Rcpp types may appear without the namespace qualifier (i.e. DataFrame is okay as a type name but std::string must be specified fully).

If default argument values are provided in the C++ function definition then these defaults are also used for the exported R function."

I think the object types are not a limitation because there are wrap and as methods for std::vector and Eigen::everything. But the scalar types need to be double or int and not templated.

Essentially, I think it would work to put almost-copies of not inlined, not templated user-defined functions into the global namespace that just call the templated user-defined functions inside the model namespace. There are some quirks in terms of stream handling and instantiating the PRNG but we can figure out how best to handle those.

**Comment by bob-carpenter** [comment]
That's really too bad about global namespaces.  
I'm less keen to do that directly in our programs due to potential
conflicts --- users can define functions named anything and cause
all sorts of issues that way.

We can't include Rcpp dependencies in the code without downgrading
our license to GPLv3, which I'm not willing to do for this.  So
maybe we do just generate different code targets, which means
writing up an alternative generate function inside the generator.
We can generate with Rcpp annotations as long as we don't have to link
anywhere.

The std::vector and Eigen::Matrix types have template params inside
them to allow taking autodiff variables. But it's easy to write
a version that does all doubles.

- Bob

**Comment by bob-carpenter** [comment]
Can you just give me an example of what

  real foo(int x, real y) {
    return x + y;
  }

should look like when compiled for Rcpp?

- Bob

**Comment by bgoodri** [comment]
On Fri, Apr 17, 2015 at 1:50 AM, Bob Carpenter <notifications@github.com>
wrote:

> Can you just give me an example of what
>
> real foo(int x, real y) {
> return x + y;
> }
>
> should look like when compiled for Rcpp?


The essence of it would be

```
double
foo(const int& x,
     const double& y) {

  return model_namespace::foo(x,y);
}
```
although we have to add headers and stuff to make it work. I think that is
fine to do with rstan because it is interface specific. I would speculate
something similar is possible with Cython, Julia, and MATLAB. In other
words, adding interface specific stuff from the interface is not so bad,
but changing or deleting parts of Stan functions is pretty brittle.

**Comment by bgoodri** [comment]
On Fri, Apr 17, 2015 at 1:49 AM, Bob Carpenter <notifications@github.com>
wrote:

> That's really too bad about global namespaces.
> I'm less keen to do that directly in our programs due to potential
> conflicts --- users can define functions named anything and cause
> all sorts of issues that way.
>

It is true that they could mask stuff in the global namespace, but is there
anything in Stan that is using the global namespace? In other words, if the
user-defined functions are just calling things in the model namespace and
the things in the model namespace are not using anything in the global
namespace, then where would the trouble come from?


> We can't include Rcpp dependencies in the code without downgrading
> our license to GPLv3, which I'm not willing to do for this.


The licensing issue does not apply because we are not distributing the code
in question. The code in question is generated on the user's machine and
the user can distribute it under the GPL or not distribute it.


> So maybe we do just generate different code targets, which means
> writing up an alternative generate function inside the generator.
> We can generate with Rcpp annotations as long as we don't have to link
> anywhere.
>

I think it is fine to add interface-specific stuff from the interface. I
don't think we want to have separate flags to generate code that Rcpp can
export, Cython can export, Julia can export.

**Comment by bob-carpenter** [comment]
> On Apr 19, 2015, at 3:20 AM, bgoodri <notifications@github.com> wrote:
> 
> On Fri, Apr 17, 2015 at 1:49 AM, Bob Carpenter <notifications@github.com>
> wrote:
> 
> > That's really too bad about global namespaces.
> > I'm less keen to do that directly in our programs due to potential
> > conflicts --- users can define functions named anything and cause
> > all sorts of issues that way.
> >
> 
> It is true that they could mask stuff in the global namespace, but is there
> anything in Stan that is using the global namespace?

Of course not.  It just feels like not wearing seatbelts.

> In other words, if the
> user-defined functions are just calling things in the model namespace and
> the things in the model namespace are not using anything in the global
> namespace, then where would the trouble come from?

Other R or Rcpp packages.  The whole point is to uniquely determine
your package's functions.  

> > We can't include Rcpp dependencies in the code without downgrading
> > our license to GPLv3, which I'm not willing to do for this.
> 
> 
> The licensing issue does not apply because we are not distributing the code
> in question. The code in question is generated on the user's machine and
> the user can distribute it under the GPL or not distribute it.

Good point.  But it looks like we don't need any of that
from your last message anyway.

> > So maybe we do just generate different code targets, which means
> > writing up an alternative generate function inside the generator.
> > We can generate with Rcpp annotations as long as we don't have to link
> > anywhere.
> >
> 
> I think it is fine to add interface-specific stuff from the interface. I
> don't think we want to have separate flags to generate code that Rcpp can
> export, Cython can export, Julia can export.

Agreed --- that's just one more level of complexity and testing I'd
rather avoid.

- Bob

**Comment by bgoodri** [comment]
This is duplicative with #1703
