### ISSUE TITLE
poisson_log cdfs

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1432]
Requested by Henrik Mannerström on stan-users:

Add:

* [ ] poisson_log_cdf
* [ ] poisson_log_cdf_log
* [ ] poisson_log_ccdf_log

And then we can do truncations.

**Comment by betanalpha** [comment]
There’s no computational benefit to having inputs
on the log scale for the CDFs as they’re typically
given by transcendental functions and not amenable
to the analytic simplifications the PDFs are.

**Comment by bob-carpenter** [comment]
Even if there's no computational benefit, it's conceptually
cleaner to have them match, and it also allows people to
write truncated models, as in:

  y ~ poisson_log(alpha) T[3,];

So even a simple implementation in terms of just exp()
transforming the alpha argument would be worth adding for
convenience.

- Bob

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#90
