### ISSUE TITLE
Stan does not handle zero-length vectors properly

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/stan#1435]
The following code results in the error "Rejecting initialization at zero because of gradient failure. vector::_M_range_check."

    model <- '
    data {
      int<lower=0> N;
    }
    parameters {
      real x;
      vector[N] y;
    }
    model {
      x ~ normal(2, 1);
      if (N > 0)
        y ~ normal(3, 1);
    }
    '
    
    sm <- rstan::stan_model(model_code=model)
    opt.res <- rstan::optimizing(sm, data=list(N=0), init=0, as_vector=FALSE)

The error occurs whether or not "if (N > 0)" is included in the model.

This may seem like an unimportant use case, but this case of zero-length vectors is actually important if you want to write a model that has some optional parts.

**Comment by ksvanhorn** [comment]
I have a much more complicated model that exhibits a similar error. In this case, however, the optimization appears to succeed -- I see the message "Optimization terminated normally" after 552 iterations -- but then I get the error "Error in res[i - 1, ] : subscript out of bounds". Here is the traceback:

    9 seq_array_ind(d, col_major) 
    8 (function (n, d, col_major = FALSE) 
      {
        if (0 == length(d)) 
            return(n) ... 
    7 mapply(flat_one_par, names, dims, MoreArgs = list(col_major = col_major), 
        SIMPLIFY = FALSE, USE.NAMES = FALSE) 
    6 flatnames(m_pars, p_dims, col_major = TRUE) 
    5 .local(object, ...) 
    4 rstan::optimizing(sm, data = stan.data, init = 0, as_vector = TRUE) 
    3 rstan::optimizing(sm, data = stan.data, init = 0, as_vector = TRUE) at flexible-effects-model.R#151

**Comment by maverickg** [comment]
A rstan bug?  What's the model?

Jiqiang

**Comment by bob-carpenter** [comment]
I just verified this is indeed a bug in latest develop cmdstan. 
We'll need to fix it on the C++ side.  I don't think it's an
RStan bug. 

- Bob
