### ISSUE TITLE
Stan creates code that does not compile when max() used in parameter dimension

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/stan#1436]
When I run rstan::stan_model on a file containing the following model code, the generated C++ code fails to compile. If I replace max(1, K0_psevere) and max(1, Kb_psevere) with K0_psevere + 1 and Kb_psevere + 1, the problem goes away.

    data {
      int<lower=0, upper=1> use_psevere;

      int<lower=1> K;
      int<lower=2> B;
      int<lower=1, upper=K> K0_lambda;
      int<lower=1*use_psevere, upper=K*use_psevere> K0_psevere;
      int<lower=0, upper=K> Kb_lambda;
      int<lower=0, upper=K*use_psevere> Kb_psevere;
    }
    transformed data {
    }
    parameters {
      vector[K0_lambda] beta0_lambda;
      vector[max(1,K0_psevere)] beta0_psevere;

      matrix[Kb_lambda, B] pre_betab_lambda;
      matrix[max(1,Kb_psevere), B] pre_betab_psevere;
    }
    transformed parameters {
    }
    model {
      beta0_lambda ~ normal(0,1);
      if (use_psevere)
        beta0_psevere ~ normal(0,1);

      to_vector(pre_betab_lambda) ~ normal(0, 1);
      if (use_psevere)
        to_vector(pre_betab_psevere) ~ normal(0, 1);
    }

**Comment by bob-carpenter** [comment]
Confirmed.  In clang, here's the error message:

```
In file included from <built-in>:326:
In file included from <command line>:5:
In file included from /Users/carp/temp2/comp.hpp:3:
In file included from stan/src/stan/model/model_header.hpp:5:
In file included from stan/src/stan/math/prim/mat/meta.hpp:4:
In file included from stan/src/stan/math/prim/mat/meta/get.hpp:4:
In file included from stan/src/stan/math/prim/mat/fun/Eigen.hpp:4:
In file included from stan/lib/eigen_3.2.4/Eigen/Dense:1:
In file included from stan/lib/eigen_3.2.4/Eigen/Core:293:
stan/lib/eigen_3.2.4/Eigen/src/Core/PlainObjectBase.h:629:27: error: no member named
      'FLOATING_POINT_ARGUMENT_PASSED__INTEGER_WAS_EXPECTED' in
      'Eigen::internal::static_assertion<false>'
                          FLOATING_POINT_ARGUMENT_PASSED__INTEGER_WAS_EXPECTED)
                          ^
stan/lib/eigen_3.2.4/Eigen/src/Core/util/StaticAssert.h:114:65: note: expanded from macro
      'EIGEN_STATIC_ASSERT'
        if (Eigen::internal::static_assertion<bool(CONDITION)>::MSG) {}
                                                                ^
stan/lib/eigen_3.2.4/Eigen/src/Core/Matrix.h:235:22: note: in instantiation of function
      template specialization 'Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1>
      >::_init2<double, int>' requested here
      Base::template _init2<T0,T1>(x, y);
                     ^
/Users/carp/temp2/comp.hpp:180:18: note: in instantiation of function template specialization
      'Eigen::Matrix<double, -1, -1, 0, -1, -1>::Matrix<double, int>' requested here
        matrix_d pre_betab_psevere(max(1,Kb_psevere),B);
                 ^
1 error generated.
make: *** [/Users/carp/temp2/comp] Error 1
```

**Comment by bob-carpenter** [comment]
So it looks like `max()` is picking up a floating-point version where it should be picking up an integer version.
