### ISSUE TITLE
Optimization over-eager warning messages

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1437]
This is from Kevin van Horn on RStan issue: https://github.com/stan-dev/rstan/issues/160:

If you call rstan::optimizing and the data includes zero-length vectors, then you get warning messages saying "Warning in max(abs(x)) : no non-missing arguments to max; returning -Inf". This appears to be happening when rstan::optimizing calls rstan:::data_preprocess, in a test near the end of the function.

I know this is a minor issue, but spurious warning messages either (1) cause you to waste a lot of time tracking down their source, or (2) end up making you ignore all warning messages, even the important ones.

As mentioned in Stan issue #1435, the zero-length vector use case arises when you've created a model that has some optional parts.

**Comment by bob-carpenter** [comment]
I think this is on the Stan side.  No idea why max(abs(x)) is causing hte issue, though.  We need a reproducible example for this.

**Comment by sakrejda** [comment]
I've seen this one, it's from rstan::stan_rdump:

     if (!is.integer(vv) && max(abs(vv)) < .Machine$integer.max &&
            real_is_integer(vv))
            storage.mode(vv) <- "integer"





Krzysztof Sakrejda

Department of Biostatistics and Epidemiology
University of Massachusetts, Amherst
319 Morrill Science Center South
611 N. Pleasant Street
Amherst, MA 01003

work #: 413-325-6555
email: sakrejda@umass.edu

**Comment by maverickg** [comment]
The problem in Rstan is fixed today.

**Comment by bob-carpenter** [comment]
OK --- looks like this was an RStan issue.
