### ISSUE TITLE
Merge math namespaces

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1441]
Merge:

* `stan::math`
* `stan::agrad`
* `stan::prob`

into one namespace:

* `stan::math`

**Comment by bob-carpenter** [comment]
I think this is a great idea.  It will reduce the number of using statements in functions and provide simpler argument-dependent lookup, as well as being simpler overall for clients who won't have to remember which function came from which namespace. 

The goal is to move all of stan::math into its own standalone library that's used by the rest of Stan but also easily used by other projects.
