### ISSUE TITLE
implement vector view map

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/stan#1449]
interface should look like a generalized version of vector view, as suggested by @bob-carpenter :

template <typename Container, typename View>
class vector_view_map {
};

where user specifies the container type and the view type, and passes in a pointer of type View*. The class implements operator[](int i) and stores a pointer to an array of type View.

**Comment by rtrangucci** [comment]
@bob-carpenter @syclik what do you guys think about the name "array_view" for these objects? maybe "structured_array_view"? I don't like the "vector_view_map" but I'm not sure what a better name would be.

**Comment by betanalpha** [comment]
container_view?

**Comment by rtrangucci** [comment]
that's not so bad! better than vector_view_map.

**Comment by rtrangucci** [comment]
it's growing on me. think it may be the winner. @syclik @bob-carpenter thoughts? Any way to incorporate embiggen or cromulent into the name?

**Comment by betanalpha** [comment]
container.embiggen(5);

container.is_cromulent()

I will not approve any code review without these methods somewhere.

**Comment by rtrangucci** [comment]
haha! Thank you. Your input on this issue has been invaluable.

**Comment by bob-carpenter** [comment]
sequence_view or seq_view might be better given
that you're explicitly providing a view that
behaves like a sequence.

But if you're envisioning something more general,
container_view would work. 

As a general rule, try to stay away from vague
qualifiers like "structured" or redundant ones
like "object".

- Bob

**Comment by rtrangucci** [comment]
Yeah, agreed, structured is a bad modifier. I'm going to go with container_view, think it's concise and descriptive.

**Comment by bob-carpenter** [comment]
Are you imagining more general containers than sequences?

- Bob

**Comment by rtrangucci** [comment]
Hmm, probably not. You'd prefer sequence_view? I could see generalizing to an implementation with operator()(int i, int j) that could return a vector or a matrix, though perhaps that would be better as a separate class.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#103
