### ISSUE TITLE
to_matrix(vector, M, N) and to_matrix(matrix, M, N) functions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1452]
Add a new function to convert a vector to a matrix of a given size.  The current `to_matrix()` take a vector or row-vector to a matrix of the same shape, so can be thought of as implicitly speficying (M,1) or (1,N).    This might also be called `reshape` or something to that effect.  

We want all three signatures for convenience:
- [x] `to_matrix(vector, int, int)`
- [x] `to_matrix(row_vector, int, int)`
- [x] `to_matrix(array, int, int)`

It should work **column-major** to match Stan's other matrix manipulations.

It might be nice to add a flag for column-major vs. row-major and think of the above as defaulting to column-maor.
- [x] version with fourth `int column_major` argument
  - [x] `to_matrix(vector, int, int, int)`
  - [x] `to_matrix(row_vector, int, int, int)`
  - [x] `to_matrix(array, int, int, int)`

**Comment by flaxter** [comment]
Related to this earlier request: https://github.com/stan-dev/stan/issues/1193

**Comment by bob-carpenter** [comment]
Indeed, this one and #1193 should be done together or rolled into a single issue.

**Comment by jgabry** [comment]
Adding #1193 to this issue as suggested by Bob so we can close #1193. I also changed the title of this issue to reflect this.

* [ ] Generalize to_matrix to accept matrix arguments, e.g.

```
to_matrix(matrix,m,n) 

  =def= to_matrix(to_vector(matrix),m,n)
```
which would be useful for reshaping matrices.

**Comment by jmh530** [comment]
Given that some other to_matrix requests have been moved here, I thought I would also mention to_matrix is not defined on an array of vectors.

Since multi_normal requires the use of an array of vectors, you have to do some adjustments if you then want to do any matrix math on whatever is sampled from it.

**Comment by randommm** [comment]
How do I proceed to open a pull request for this on https://github.com/stan-dev/math? Should I open an issue there about the same thing, or just refer directly to this issue on the pull request?

**Comment by bob-carpenter** [comment]
@randomm  Welcome back!  Please  open an issue on stan-dev/math that refers to this issue.

**Comment by bob-carpenter** [comment]
Finished with PR #2264
