### ISSUE TITLE
Integrating positive ODE systems

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#1455]
A common component of many ODE systems is that the states are positive, which can cause numerical problems if the states are small.  One potential solution to small state values is to automatically convert the ODE system into one for the log states and then solve that.  In particular, if

dC/dt = f(t, C, theta)

then

d logC / dt = exp( logC ) f(t, logC, theta).

It's not clear if the exp( logC ) term would make the unconstrained ODE system any more stiff, but it would be easy to implement this with an `integrate_positive_ode` function just to experiment.  

Formally this can be generalized to other constrained states but I don't think any others would be particularly useful and be worth the generalization.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#94
