### ISSUE TITLE
Analytic evolve functions

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#1456]
In ODE models some components can be solved analytically such that some state components are given in closed form and some need to be solved numerically.  To maintain code consistency in these models it would be nice to have a function that parallels `integrate_ode` but instead of calling an ODE solver to evolve the state just applies a user-defined function,
```
real[] evolve_state(function, y0, t0, ts, theta, x_r, x_i) {
  real y[size(y0), size(ts)];
  y[,0] = y0;
  for (n in 1:size(ts))
    y[,n] = function(y[,n - 1], ts[n], theta, x_r, x_i)
  return y;
}
```

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#95
