### ISSUE TITLE
missing poisson_log_rng()

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1458]
As Bee pointed out on stan-users, the poisson_log_rng() function is not defined.

* [ ] add `poisson_log_rng()` --- implement as `poisson_rng(exp(...))`.
* [ ] add tests --- derive from `poisson_rng` tests

**Comment by randommm** [comment]
The function poisson_log_rng() and its tests exist, I think it's just a matter of adding to function_signatures.h

If so, this could be included in 2.7.0

**Comment by bob-carpenter** [comment]
No, it's there, it's just that what happens is that functions
call it with extreme parameters, then exceptions get raised in
calls it makes internally to gamma rng, so it reports errors
back to the user that there were errors in the gamma rng, not
that there was an error in the call to poisson_log_rng.

So we want to either trap the errors before the calls to the internal
RNG if we can or if not, just wrap everythnig in a try/catch where
the catch returns a more meaningful error that includes the info that
the error arose in poisson_log_rng.

**Comment by randommm** [comment]
I think you are making a confusion with the other issue (about neg_binomial_2_log_rng error messages) which doesn't have anything to do with this one. poisson_log_rng() does not call gamma_rng.

**Comment by bob-carpenter** [comment]
You're right --- sorry about that.

- Bob
