### ISSUE TITLE
Prep Stan Math library for separate release

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1465]
Todo (I'm working on branch `feature/issue-1465-math-lib `):
- [x] `2503163a`: Move all headers that are required for the Stan Math Library into `src/stan/math`. This includes all the memory headers.

    To find the dependencies: 
    `clang++ -I src -isystem lib/eigen_3.2.4 -isystem lib/boost_1.58.0 -Wall -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -pipe -Wno-unused-function -Wno-tautological-compare -Wno-c++11-long-long -Wsign-compare -ftemplate-depth=256 -O3  -MM src/stan/math.hpp`

- [x] `a22c5f55`: Remove all the folder level includes across all of Stan
    - [x] src/stan.hpp
    - [x] src/stan/command.hpp
    - [x] src/stan/interface.hpp
    - [x] src/stan/interface/callback.hpp
    - [x] src/stan/interface/recorder.hpp
    - [x] src/stan/interface/var_context_factory.hpp
    - [x] src/stan/io.hpp
    - [x] src/stan/io/json.hpp
    - [x] src/stan/lang.hpp
    - [x] src/stan/lang/grammars.hpp
    - [x] src/stan/mcmc.hpp
    - [x] src/stan/mcmc/hmc.hpp
    - [x] src/stan/mcmc/hmc/hamiltonians.hpp
    - [x] src/stan/mcmc/hmc/integrators.hpp
    - [x] src/stan/mcmc/hmc/nuts.hpp
    - [x] src/stan/mcmc/hmc/static.hpp
    - [x] src/stan/model.hpp
    - [x] src/stan/optimization.hpp
    - [x] src/stan/services.hpp
    - [x] src/stan/services/arguments.hpp
    - [x] src/stan/services/init.hpp
    - [x] src/stan/services/io.hpp
    - [x] src/stan/services/mcmc.hpp
    - [x] src/stan/services/optimization.hpp
- [x] `d0e5b34`: Remove all the folder level includes within Stan math
    - [x] src/stan/math/fwd.hpp
    - [x] src/stan/math/fwd/arr.hpp
    - [x] src/stan/math/fwd/arr/fun.hpp
    - [x] src/stan/math/fwd/mat.hpp
    - [x] src/stan/math/fwd/mat/fun.hpp
    - [x] src/stan/math/fwd/mat/functor.hpp
    - [x] src/stan/math/fwd/scal.hpp
    - [x] src/stan/math/fwd/scal/fun.hpp
    - [x] src/stan/math/fwd/scal/meta.hpp
    - [x] src/stan/math/mix.hpp
    - [x] src/stan/math/mix/arr.hpp
    - [x] src/stan/math/mix/core.hpp
    - [x] src/stan/math/mix/mat.hpp
    - [x] src/stan/math/mix/mat/fun.hpp
    - [x] src/stan/math/mix/mat/functor.hpp
    - [x] src/stan/math/mix/scal.hpp
    - [x] src/stan/math/prim.hpp
    - [x] src/stan/math/prim/arr.hpp
    - [x] src/stan/math/prim/arr/fun.hpp
    - [x] src/stan/math/prim/arr/functor.hpp
    - [x] src/stan/math/prim/arr/meta.hpp
    - [x] src/stan/math/prim/mat.hpp
    - [x] src/stan/math/prim/mat/err.hpp
    - [x] src/stan/math/prim/mat/fun.hpp
    - [x] src/stan/math/prim/mat/meta.hpp
    - [x] src/stan/math/prim/mat/prob.hpp
    - [x] src/stan/math/prim/scal.hpp
    - [x] src/stan/math/prim/scal/err.hpp
    - [x] src/stan/math/prim/scal/fun.hpp
    - [x] src/stan/math/prim/scal/meta.hpp
    - [x] src/stan/math/prim/scal/prob.hpp
    - [x] src/stan/math/rev.hpp
    - [x] src/stan/math/rev/arr.hpp
    - [x] src/stan/math/rev/arr/fun.hpp
    - [x] src/stan/math/rev/arr/functor.hpp
    - [x] src/stan/math/rev/mat.hpp
    - [x] src/stan/math/rev/mat/fun.hpp
    - [x] src/stan/math/rev/mat/functor.hpp
    - [x] src/stan/math/rev/scal.hpp
    - [x] src/stan/math/rev/scal/fun.hpp
    - [x] src/stan/math/rev/scal/meta.hpp
- [ ] Decide what to do with the `core.hpp` files:
    - src/stan/math/fwd/core.hpp
    - src/stan/math/rev/core.hpp
- [x] `456e79a246` Packaging it into its own lib including test location, etc. 
- [ ] Bringing it back into Stan sensibly using a submodule or similar
- [ ] Fiddling with Jenkins.

**Comment by syclik** [comment]
What version number should we start with?

**Comment by bob-carpenter** [comment]
Either 1.0 or 2.7 to match the Stan release from which
it was extracted.  I'm inclined to go with 1.0, but perhaps
2.7 would be seen as more trustworthy (or perhaps exactly
the opposite)?

- Bob

**Comment by syclik** [comment]
We decided to call this 2.7.0. In the code, I'm matching the current Stan version: 2.6.3. We will up the version when Stan gets updated.

**Comment by syclik** [comment]
I take that back -- I've set it up as 2.7.0.
