### ISSUE TITLE
neg_binomial_2_log_rng error messages

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1471]
As of 2.6.3, `neg_binomial_2_log_rng` doesn't do enough of its own error checking and allows invalid values to be passed internally so that errors are raised in calls it makes internally to other rngs.

* [ ] check bounds at the input level for `neg_binomial_2_log_rng` rather than letting the underlying messages fail and get through;  if necessary, catch exceptions raised from internal calls to `gamma_rng` and `poisson_rng`

There are probably other cases of this for other functions, which don't need to be fixed as part of this issue, but can be logged into another issue if found.

**Comment by randommm** [comment]
@bob-carpenter do you mind taking a look at https://github.com/stan-dev/stan/compare/feature/issue-1471-neg_binomial_2_log_rng-error-messages to check if that's what you think it should be?

**Comment by bob-carpenter** [comment]
I left a sentence dangling that wasn't going anywhere (so I ended
it), but otherwise it looks right.  If you don't want to do it,
just unassign yourself.  

There are lots more functions we'd like to implement.  And many many
more open issues for 2.7.0++ we'd like to track down.  I think we're
going to roll out 2.7.0 ASAP to fix the issues with R builds and BH. 

- Bob
