### ISSUE TITLE
lkj_corr_cholesky fvar instantiation fails

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/stan#1476]
`lkj_corr_cholesky` doesn't compile when instantiated with `Eigen::Matrix<fvar<double>, Dynamic, Dynamic>`. I think it's because of this line:

```
values += (2.0 * eta - 2.0) * log_diagonals;
```

Given that `eta` is a double and `log_diagonals` is a `Matrix<fvar<double>, Dynamic, 1>`.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#98
