### ISSUE TITLE
integer variables within transformed data is filled with DUMMY_VAR__

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1477]
## Bug Report

__Version__

2.6.3

__Description__

Integer variables declared within transformed data are being filled with `DUMMY_VAR__`. It is originally initialized with `int(0)`, which is ok.

__Steps__

Minimal example:
```
transformed data {
  int a;
  real b;
}
model {
}
```
Generate the C++ header file from this Stan program.

__Output__

This includes a block in the generated C++ that looks like:
```
        // validate data
        a = int(0);
        b = double(0);

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning


        // initialize transformed variables to avoid seg fault on val access
        stan::math::fill(a,DUMMY_VAR__);
        stan::math::fill(b,DUMMY_VAR__);
```

__Expected Output__

I think this should look like:
```
        // validate data
        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize transformed variables to avoid seg fault on val access
        a = int(0);
        b = double(DUMMY_VAR__);
```
This should solve the problem.

__Additional Information__

This is causing problems with g++ 4.9. I don't see how this didn't cause problems with the other compilers.

**Comment by betanalpha** [comment]
How will this generalize to arrays?  Isn�t that what stan::math::fill aims to do?
In other words, what�s wrong with 

const int INT_DUMMY_VAR__(0);
(void) INT_DUMMY_VAR__;  // suppress unused var warning

const double DBL_DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
(void) DBL_DUMMY_VAR__;  // suppress unused var warning

stan::math::fill(a, INT_DUMMY_VAR__);
stan::math::fill(b, DBL_DUMMY_VAR__);

**Comment by syclik** [comment]
It'll generalize fine. The way the code is generated is:
  xs = std::vector<std::vector<int>
>(Ndogs,std::vector<int>(Ntrials,int(0)));

**Comment by betanalpha** [comment]
So stan::math::fill is currently used only for scalars?  Odd.

In any case, it does seem more consistent to either have
dummy variables for both ints and doubles or neither
(i.e. just insert quiet_NaN() into the constructors directly
as in done with 0 for ints).

**Comment by syclik** [comment]
No, it's used for both scalers and arrays. I was just trying to show how it
fills.

I didn't realize that it was calling stan::math::fill. I had read that as
being in the std namespace. I think an appropriate fix could be to fix the
fill function. We should be able to create a unit test that fails for gcc
4.9.

**Comment by bgoodri** [comment]
This was fixed in develop to initialize ints to the most negative integer. Initializing ints to NaN was undefined behavior.
