### ISSUE TITLE
autodiff recover_memory segfault

### ISSUE THREAD

**Issue by fredRos** [stan-dev/stan#1478]
## Bug Report

__Version__
stan: 822ab42, system: debian jessie, clang version 3.5.0-10
__Description__
segfault with autodiff library in 2nd call to `recover_memory`, follow up to #1475
__Steps__
Minimal example compiled with
    clang++ -std=c++14 -Wall -pedantic -isystem ${STANHOME}/src -isystem ${STANHOME}/lib/eigen_3.2.4 segfault.cpp 
```cpp
#include <stan/math/prim/arr/meta.hpp>
#include <stan/math/prim/mat/meta.hpp>
#include <stan/math/prim/scal/meta.hpp>
#include <stan/math/rev/scal/meta.hpp>
#include <stan/math/prim.hpp>
#include <stan/math/rev.hpp>

int main() {
    stan::math::var x = 1.0, mu = 0.0, sigma = 1.0;

    stan::math::var z = normal_log(x, mu, sigma);
    z.grad();
    // no segfault if first recover_memory commented out
    stan::math::recover_memory();

    z = normal_log(x, mu, sigma);
    z.grad();
    // the culprit
    stan::math::recover_memory();

    return 0;
}

```
__Output__
Segmentation fault

**Comment by syclik** [comment]
That set fault falls into using an uninitialized var.  After the first call
to recover_memory, all the vars are uninitialized. They've all been
recovered.

To verify, print x directly after the call to recover memory.

If you want to do what you are intending, you need to recreate x, mu, and
sigma again after calling recover memory.

**Comment by syclik** [comment]
@fredRos, I see that it seg faults. That's known behavior.

I tried printing it, but it wasn't clear that it was uninitialized. I don't think there's a way to have that be a safe behavior without a lot of checking within the internals of the Stan Math library, so I think it'll stay this way. Do you have suggestions on how to fix the documentation? 

I will go through another pass once we solidify our library so it may be taken care of without any input. But, if you have a good way to explain why this is happening, then that's great.

To address what you're trying to do, put the initialization in a function.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#99
