### ISSUE TITLE
HTML conversion of manual

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1481]
Best idea yet is from Ben:  use pdf2htmlEx to convert our manual to HTML.

https://github.com/coolwanglu/pdf2htmlEX

Allen suggests these are good for search:  Python documentation or Rust documentation for the way that it provides search.

https://docs.python.org/3/

And this one has optimistic search results (no return) as you type:

http://doc.rust-lang.org/std/

**Comment by mitzimorris** [comment]
done - all docs are now in bookdown  and can be generated in both pdf and html.
