### ISSUE TITLE
add skew Student-t distribution

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1485]
Request from Slawek Smyl via stan-users group:

"... please add the Skew Student distribution - it would be very general and useful."

The background is this:

<blockquote>
I am creating time-series models on some volatile (and some not) curves and found Student distribution really useful, as it can accommodate to the curve volatility.  I would like to experiment with simpler models, where trend or drift is expressed just with skewedness.
</blockquote>

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#100
