### ISSUE TITLE
RFC: compiled C++ code for model should be invariant to whitespace in  Stan model

### ISSUE THREAD

**Issue by ariddell** [stan-dev/stan#1487]
In some distant future where one is able to pass around binaries of compiled stan models or cache commonly compiled models for pedagogical purposes (e.g., cloud.mc-stan.org), it would be great to be able to trivially test for equality given two compiled models by comparing the hash of the generated C++ code.

Right now models that differ only in whitespace generate different C++ code. For example, I added a few extra line breaks in `bernoulli.stan` and looked at the diff between the generated C++ code. This is it:

```diff
        // model body
         try {
-            current_statement_begin__ = 9;
+            current_statement_begin__ = 16;
             lp_accum__.add(beta_log<propto__>(theta, 1, 1));
-            current_statement_begin__ = 10;
+            current_statement_begin__ = 18;
             for (int n = 1; n <= N; ++n) {
-                current_statement_begin__ = 11;
+                current_statement_begin__ = 19;
                 lp_accum__.add(bernoulli_log<propto__>(get_base1(y,n,"y",1), theta));
             }
         } catch (const std::exception& e) {
```

Here are the model files:

model 1:
```stan
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta;
} 
model {
  theta ~ beta(1,1);
  for (n in 1:N) 
    y[n] ~ bernoulli(theta);
}
```

model 2:
```stan
data { 

  int<lower=0> N; 

  int<lower=0,upper=1> y[N];

} 
parameters {

  real<lower=0,upper=1>  theta;

} 

model {

  theta ~ beta(1,1);

  for (n in 1:N) 
    y[n] ~ bernoulli(theta);

}
```

I'm willing to acquaint myself with the relevant C++ code if there's not an easy fix.

**Comment by betanalpha** [comment]
This is a feature, not a bug.  The whitespace-dependent numbers are
used to locate what code caused Stan to fail internally, which is hugely
useful.  

I think your best bet would be to have a second parser that either removes
whitespace in a file or ignores these statements, and then use a hash of
that file for comparisons.

**Comment by ariddell** [comment]
Good point.

Is there an underlying representation that is invariant which one could
cast into a hashable buffer? Having Stan C++ do the hashing (and
having interfaces retrieve it) sounds like a fine strategy to me.

Boost has a hash function, but it sounds like it's suited to some
special case, http://www.boost.org/doc/libs/1_58_0/doc/html/hash.html.
Looks like Google's CityHash is tiny and MIT licensed. The reference
implementation is in C++ as well.

**Comment by bob-carpenter** [comment]
I wouldn't worry too much about whitespace.  If they change
the whitespace, the model gets recompiled.

It'd also be easy to cache without the whitespace by replacing
whitespace+ with a single space (' ').  

- Bob

**Comment by ariddell** [comment]
Dug into this today. Turns out that boost::hash is really nice. To use it, however, I'd have to teach boost how to hash every piece of `stan::gm::ast::program` individually.

Some standard is better than none, what about the following informal convention: take the SHA1 hash of the concatenation of the Stan library version number (as utf8 string) and the model_code (utf8) with all whitespace removed?

It appears to work for the present case:

```python
In [33]: import hashlib
In [34]: model1_sans_whitespace = re.sub('\s', '', model1)
In [35]: model2_sans_whitespace = re.sub('\s', '', model2)
In [36]: hashlib.sha1('2.6.3'.encode('utf8') + model1_stripped.encode('utf8')).hexdigest()
Out[36]: '917de985808483fc6a04bba2cdc838c1b1a72f37'
In [37]: hashlib.sha1('2.6.3'.encode('utf8') + model2_stripped.encode('utf8')).hexdigest()
Out[37]: '917de985808483fc6a04bba2cdc838c1b1a72f37'
```

**Comment by bob-carpenter** [comment]
I don't think it's a big deal to recompile if the user
changed the spacing in a file --- they edited it and
probably won't even be surprised.  So I'd be inclined
to keep it simple.  

Google tells me the space-free model name should
be model1_sine_albus_spatium

We don't properly handle UTF-8 spaces in the parser.
Or validate that strings are legal UTF-8.  Or deal with
UTF-8 keys in any of the interfaces.  So all I've ever
told people is that comments with UTF-8 should be OK.

- Bob

**Comment by ariddell** [comment]
Having thought about this some more I think one should just sha1 hash the Stan version (as a string) + the stan_code string. Premature optimization and all that...
