### ISSUE TITLE
row vector and matrix expressions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1489]
We need matrix expressions and vector expressions.  Probably something like:

#### row vector

```
[a b c]
```

#### vector

This can just be the transpose of a row vector.

```
[a b c]'
```

#### matrix

```
[[1 0], [0 1]]
```

Similar to array expressions as outlined in #1635

**Comment by mitzimorris** [comment]
Planning to implement this feature with commas, similar to array expressions:

row vector:
```
[a, b, d]
```
vector:
```
[a, b, c]'
```
for matrix expressions - commas between rows?

```
[ [1, 0], [0, 1]]
```

**Comment by bob-carpenter** [comment]
Yes to commas.  I updated the issue.
