### ISSUE TITLE
Manual: Inconsistent description of Phi() function

### ISSUE THREAD

**Issue by jonathan-g** [stan-dev/stan#1507]
The 2.6.2 manual (Saturday 14th March, 2015) describes Phi on page 46 as $\int_{-\infty}^x \text{Normal}(y|0,1) dy$, but on page 312 as $\frac{1}{\sqrt{2\pi}} \int_0^x e^{-t^2/2} dt$.  These are inconsistent in the lower limit of integration. I think the definition on page 312 should have $-\infty$ as the lower limit.

**Comment by bob-carpenter** [comment]
Thanks!  I moved this over to the next manual issue: #1508
