### ISSUE TITLE
access to unconstrained parameter vector

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1512]
Provide access to the unconstrained parameter vector in Stan models so that it may be used directly for priors.

This one is *not* intended to go in the manual<sup>1</sup> --- it's just for Andrew to use for EP under the hood.

<hr />
&nbsp;<sup>1</sup>  Remember, the first rule of unconstrained parameter club is that you don't mention unconstrained parameter club.

**Comment by betanalpha** [comment]
In all seriousness, this needs a big nasty “do not use unless you’ve
written a seminal book on Bayesian data analysis” parser warning.
People will find it so we need to make it as annoying as possible.

**Comment by bob-carpenter** [comment]
I went with:

```
WARNING:  Access to params_r__ unsupported.  Variable may be removed without notice.
```

But it's easy to change.

**Comment by betanalpha** [comment]
Serious again: I think it needs to be more explicit.  Perhaps

"WARNING: Direct access to params_r__ yields an inconsistent statistical
model in isolation and no guarantee is made that this model will yield valid
inferences.  Moreover, access to params_r__ is unsupported and the variable 
may be removed without notice."

**Comment by andrewgelman** [comment]
That’s a good warning because then Aki will be able to use it too.  Also the ghost of Laplace if he ever comes around.

**Comment by bob-carpenter** [comment]
OK.  That'll be the message.

You'll be happy to know Andrew that it's all done other than
the testing.  Writing these e-mails took longer than adding
the functionality :-)

- Bob
