### ISSUE TITLE
Failing unit tests with Intel 14 & g++ 4.4.7

### ISSUE THREAD

**Issue by wds15** [stan-dev/stan#1514]
I am experiencing 

* [x] failing unit tests with Intel 14 & g++ 4.4.7 (Redhat Linux 6.5):

./runTests.py src/test/unit/optimization

aborts with:

icpc -I src -isystem lib/eigen_3.2.4 -isystem lib/boost_1.58.0 -isystem lib/stan_math_2.6.3 -Wall -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -pipe -DEIGEN_USE_MKL_ALL -DNDEBUG    -c -O3 -DGTEST_USE_OWN_TR1_TUPLE -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 src/test/unit/optimization/lbfgs_update_test.cpp -o test/unit/optimization/lbfgs_update.o
src/test/unit/optimization/lbfgs_update_test.cpp(58): error: argument list for class template "stan::optimization::LBFGSUpdate" is missing
        mock_lbfgs_update(size_t L) : LBFGSUpdate(L) {};
                                      ^

compilation aborted for src/test/unit/optimization/lbfgs_update_test.cpp (code 2)
make: *** [test/unit/optimization/lbfgs_update.o] Error 2
make test/unit/optimization/bfgs_linesearch test/unit/optimization/bfgs_minimizer test/unit/optimization/bfgs test/unit/optimization/bfgs_update test/unit/optimization/lbfgs_update failed
exit now (06/24/15 13:15:43 CEST)

And the g++ does:

g++ -I src -isystem lib/eigen_3.2.4 -isystem lib/boost_1.58.0 -isystem lib/stan_math_2.6.3 -Wall -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -pipe   -c -O3 -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 src/test/unit/optimization/lbfgs_update_test.cpp -o test/unit/optimization/lbfgs_update.o
src/test/unit/optimization/lbfgs_update_test.cpp: In constructor \u2018stan::optimization::mock_lbfgs_update::mock_lbfgs_update(size_t)\u2019:
src/test/unit/optimization/lbfgs_update_test.cpp:58: error: class \u2018stan::optimization::mock_lbfgs_update\u2019 does not have any field named \u2018LBFGSUpdate\u2019
make: *** [test/unit/optimization/lbfgs_update.o] Error 1
rm test/unit/optimization/bfgs_minimizer.o test/unit/optimization/bfgs_update.o test/unit/optimization/bfgs.o test/unit/optimization/bfgs_linesearch.o
make test/unit/optimization/bfgs_linesearch test/unit/optimization/bfgs_minimizer test/unit/optimization/bfgs test/unit/optimization/bfgs_update test/unit/optimization/lbfgs_update failed
exit now (06/24/15 13:33:00 CEST)

Daniel already commented that this is a compiler bug.

* [ ] And here is another failing test which compiles, but does not execute successfully (this time only for the Intel 14 compiler):
./runTests.py -j2 src/test/unit/io

unknown file: Failure
C++ exception with description "data b value 2.22507e-308 beyond numeric range" thrown in the test body.

The Intel 14 was executed on the latest branch of the intel-14-fix & the g++ on the current develop.

**Comment by bob-carpenter** [comment]
Thanks for filing this as an issue.  I edited the wrapper a bit and added checkboxes for the two issues.  I think we have a handle on both these issues, so it shouldn't be an issue getting them fixed for 2.7.

**Comment by bgoodri** [comment]
Let me add to the thanks and also encourage you to run the tests as often as practical with the Intel 14 compiler because I only have Intel 15 to test with.

**Comment by syclik** [comment]
@wds15, can you compile and run these two programs? They should be self-contained. The first version crashes using g++ 4.4 (MacPorts version). The second one works.
```
#include <iostream>
#include <stdexcept>
#include <string>

class foo {
public:
  foo() {
    std::string msg("blah");
    throw std::runtime_error(msg);
  }
};

int main() {
  try {
    foo x;
  } catch (const std::exception& e) {
  }
  return 0;
}
```

This version works:
```
#include <stdexcept>
#include <string>

class foo {
public:
  std::string blah() {
    return "blah";
  }
  foo() {
    throw std::runtime_error(blah());
  }
};

int main() {
  try {
    foo x;
  } catch (const std::exception& e) {
  }
  return 0;
}
```

Can you verify on Linux under g++ 4.4 and icpc 14?

**Comment by syclik** [comment]
By the way, both of those should work. I think it's a bug that the first one creates an "abort trap."

**Comment by bob-carpenter** [comment]
As Daniel showed me, they do both work in later versions of gcc.

**Comment by wds15** [comment]
I tried both with g++ 4.4.7 and icpc 14.0.1 and both versions work with both compilers. I never see any message and the exit code is always 0.

I even tried to turn on optimization & the debugging mode (separately and in combination) and everything does work - I never see the messages nor do I observed a thrown exception.

BTW, the g++ 4.4.7 which we have is on Redhat Linux 6.5 - they patch g++ quite a bit over time. Hence, this is an improved g++ (at least according to Redhat).

**Comment by syclik** [comment]
Ok. That must be a Mac specific problem with g++ 4.4.7.

What fails on this branch: bugfix/issue-1514-gcc44?

Given that g++ 4.4.7 on Mac behaves differently than g++ 4.4.7 on Redhat
and icpc 14.0.1, I'm not sure we're going to be able to debug this one
easily. Any suggestions?

**Comment by bgoodri** [comment]
Yeti

**Comment by wds15** [comment]
Well, you fixed it with the branch origin/bugfix/issue-1514-gcc44 . I tried with Intel 14.

I just tried that one and it compiles successfully the optimizer tests (and they execute successfully as well). The only thing what stops me now from successfull tests is this one:

[ RUN      ] io_dump.reader_big_doubles
unknown file: Failure
C++ exception with description "data b value 2.22507e-308 beyond numeric range" thrown in the test body.
[  FAILED  ] io_dump.reader_big_doubles (0 ms)

which I think you discovered & discussed already in that other thread.

**Comment by wds15** [comment]
and g++ 4.4.7 on Redhat also gets everything right with the  origin/bugfix/issue-1514-gcc44 branch. Problem solved. Great.

**Comment by bob-carpenter** [comment]
Ben figured out how to fix that.  We just need to get the
pull request in, which should happen tomorrow at the latest.  

We're very close to 2.7 now, I think.  Thanks for your
patience while we sort out all these Intel compiler issues!

- Bob
