### ISSUE TITLE
unnormalized min/max tests failing for I/O on Intel compilers

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1515]
There's  noramlization issue with the icpc compiler, which Ben Goodrich tracked down:

Message 0:

I now have an icpc version 15. I am getting a test failure on this branch at

```
[ RUN      ] io_dump.reader_big_doubles
unknown file: Failure
C++ exception with description "data b value 2.22507e-308 beyond numeric range" thrown in the test body.
```

Message 1:

Yes, changing dmin to lowest() passes in C++11 mode, as does changing dmin
to -dmax without C++11.

Message 2:

Right now, it is
```
double dmax = std::numeric_limits<double>::max();
double dmin = std::numeric_limits<double>::min();
```
which fails, but changing dmin to either
```
double dmin = std::numeric_limits<double>::lower();
```
or
```
double dmin = -dmax;
```
passes. So, I think it does have something to do with the normalization.

Message 3:

OK. This passes:
```
double dmin = 2.225075e-308;
```
whereas
```
double dmin = std::numeric_limits<double>::min(); // about 2.22507_4_e-308
```
fails. So, it looks as if icpc can't handle that edge case.

**Comment by syclik** [comment]
I haven't look at the intent of the test. Is changing the test an option?

**Comment by bob-carpenter** [comment]
I just submitted a pull request with a changed test.  I
think it's the right thing to do --- that was just testing
a boundary condition and normalization is obviously an issue.
It doesn't change behavior.

- Bob

**Comment by syclik** [comment]
Thanks!
