### ISSUE TITLE
remove a new std::cout

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#1524]
@maverickg found that a std::cout came in with the ADVI stuff

https://github.com/stan-dev/stan/blob/develop/src/stan/variational/advi.hpp#L326

CRAN won't tolerate that for the rstan package.

**Comment by syclik** [comment]
My bad. I missed that. We'll get that in before we tag.

**Comment by akucukelbir** [comment]
good catch! sorry about that. 

i fixed it with https://github.com/stan-dev/stan/commit/6ae949d55504b5185c89d18af042a2556b14de6a
