### ISSUE TITLE
Next Manual, 2.7.1

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1526]
Here's where issues for the 2.7.1 manual go.

**Comment by bob-carpenter** [comment]
Missed this for 2.7.0, from @jonathan-g:

* [ ] page 451, section "Warmup Times and Estimating the Mass Matrix": minor LaTeX problem due to using non-ASCII character instead of ASCII single-quote for apostrophe in source: "... standardizing the data doesnâ ̆ Z ́ t always help. Therefore, Stan ..."

**Comment by bob-carpenter** [comment]
* [ ] Add Dustin Tran as developer

**Comment by syclik** [comment]
- [ ] thank @dvukcevic for stan-dev/stan#1548

**Comment by bob-carpenter** [comment]
From Andrew:

A funny thing:  exponential distribution is parameterized in terms of inverse-scale, but double_exponential is parameterized in terms of its scale.  For historical reasons I understand this but maybe 

* [ ] we should flag it in the manual.

**Comment by jgabry** [comment]
From Mike Lawrence on [stan-users](https://groups.google.com/forum/#!topic/stan-users/MZI0H_spXF8):

> In the pre-optimized code for the multivariate regression example, spanning pgs 66-67 in version 2.7.0 of the manual, there are two sampling statements for y; is this an error? If not, can someone explain what the two different statements are achieving?

There's a vectorized and non-vectorized version both in the same model block. 

- [ ] we should remove one of the sampling statements

**Comment by bob-carpenter** [comment]
* [ ] fix sign error in simple harmonic oscillator --- diff eq notation doesn't match code

**Comment by bob-carpenter** [comment]
* [ ] change "strangely" to "seemingly" in the unrelated regressions description

**Comment by bob-carpenter** [comment]
https://github.com/JuliaPalacios said in https://github.com/stan-dev/stan/issues/1577 

<blockquote>
section{Variational Inference} (the first Variational Inference section 1.6), first paragraph, there is this sentence:

"Variational inference can be much for estimating posterior means and marginal variances than MCMC. See Chapter 59 for more information."
</blockquote>

* [ ] fill in the much what?

**Comment by bgoodri** [comment]
In the section on the multinomial distribution, `multinomial_rng` returns an `int[]` rather than a `vector`.

**Comment by bob-carpenter** [comment]
* [ ] Thank Daniel Chen in the acknowledgements for supplying Python install instructions (that's code and doc!)

**Comment by bob-carpenter** [comment]
From Guido Biele on stan-users:

I think there is a small error in the example for ragged arrays on page 135 of the stan-reference.

the relevant section in the model block of the example reads:

```
  int pos;
  pos <- 1;
  for (k in 1:K)
    segment(y, pos, s[k]) ~ normal(mu[k], sigma);
```

which means that the stating index of the slicing operation is always 1. 

instead it should probably be something like 

```
 int pos;
  pos <- 1;
  for (k in 1:K){
    segment(y, pos, s[k]) ~ normal(mu[k], sigma);
    pos <- pos + s[k];
  }
```

(in figure 2 it should also be `z = [†1:3 2:4 0:9 ...`  and not `y = [†1:3 2:4 0:9 ..." , or better change the figure caption because `y` is also used in the example model ...)

* [ ] fix the example
* [ ] fix the figure
* [ ] thank Guido in the acknowledgements

**Comment by bob-carpenter** [comment]
* [ ] Thank Takahiro Kubo for install instructions for PyStan (I guess that's doc)

**Comment by bob-carpenter** [comment]
* [ ] replace `post_mulitply` with `pre_multiply` in the Cholesky example

**Comment by bob-carpenter** [comment]
* [ ] compare the mixture at model level vs. mixture at observation level

This is confusing a lot of users who try to vectorize and wind up mixing at the model level rather than observation level.

**Comment by bob-carpenter** [comment]
* [ ] remove any mention of `mc-stan.org` emails

**Comment by jgabry** [comment]
From [Andy on stan-users](https://groups.google.com/d/msg/stan-users/U6WHNwn13mo/pxiMsw1DDgAJ):

>[...] under "Time-Series Models"->"Autoregressive Models" of the manual (Ch 6.1) <lower=0> is not used for specifying sigma (e.g. pg 77)

* [ ] add lower=0 constraint for sigma in time series section

**Comment by bob-carpenter** [comment]
* [x] update grant funding and add corporate funding and foundation funding

**Comment by maciekjswat** [comment]
There is a typo in the section '48.6. Multivariate Student-t Distribution' in the PDF formula
It is: \Gamma \chi ((...
it should be: \Gamma ((...
