### ISSUE TITLE
Automatically adjust the hyperparameter for AdaGrad in ADVI

### ISSUE THREAD

**Issue by dustinvtran** [stan-dev/stan#1550]
We can do the standard thing in the optimization community, which is do a very coarse grid search, e.g., `eta in {0.001, 0.01, 0.1, 1, 10}`, and run a pass over a subset of the data. Then we set it according to which converged fastest.

**Comment by akucukelbir** [comment]
Implemented in https://github.com/stan-dev/stan/pull/1699.
