### ISSUE TITLE
check transformed data for `NaN`

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1557]
## Feature Request

**Version**

2.7.0

**Description**

Is there any reason transformed data isn't checked for `NaN` after the block?

**Example**

```
transformed data {
  real x;
}
parameters {
  real mu;
}
model {
  x ~ normal(mu, 1);
}
```

This currently tries to run and errors due to `NaN`.

I suggest this stops immediately, or is that a bad idea?

**Comment by bob-carpenter** [comment]
That was intentional as there's no constraint on `x`.  Maybe it was the wrong decision.  Do we want to completely disallow NaN values in transformed data?

**Comment by bgoodri** [comment]
This is related to #1477 . We need to do something, but we disallow NaN in transformed data now, then it would be very difficult to ever use NaN to represent missing values in the future. That would basically limit us to the last few numerically representable values or negative zero to represent missing values with.

**Comment by bob-carpenter** [comment]
I agree that we shouldn't disallow NaN in the transformed data block, so I'm closing this.
