### ISSUE TITLE
nan exception with variational inference

### ISSUE THREAD

**Issue by d10genes** [stan-dev/stan#1559]
For the following model

    data {
        int N;
        vector[N] p;
        int Ngrps;
        int<lower=1, upper=Ngrps> grp_index[N];
    }
    parameters {
        vector<lower=0.0001, upper=100>[Ngrps] sigmaGrp;
        vector<lower=-100, upper=1000>[Ngrps] muGrp;
    }

    model {
        int grpi;
        for (i in 1:N){
            grpi <- grp_index[i];
            p[i] ~ logistic(muGrp[grpi], sigmaGrp[grpi]);
        };
    }

I'm trying to estimate group level parameters from the following data (I generated with python and saved data file test.R with pystan):

    p = 63.1, 108.3, 1.0, 46.0, 22.9, 14.8, 28.8, 52.5, 60.1, 81.3
    grp_index = [1, 1, 1, 1, 1, 1, 2, 3, 4, 5]

    test_dat = dict(
        N=len(p),
        p=p,
        grp_index=grp_index,
        Ngrps=len(set(grp_index)),
    )    

When I compile and sample with advi using     

    $ modeldir/model/test variational data file=modeldir/dat/test.R random seed=3021828106

I get the exception:

    Exception: stan::variational::normal_meanfield::set_mu: Input vector[7] is nan, but must not be nan!
    Diagnostic information: 
    Dynamic exception type: std::domain_error
    std::exception::what: stan::variational::normal_meanfield::set_mu: Input vector[7] is nan, but must not be nan!

This is a small dataset, and the error can be avoided if I run with most other random seeds, but I originally ran into this every time with a larger data set, that presumably has some groups only represented once in the `grp_index` array. I could get rid of those groups in the dataset, but wondered if this is a bug with the variational algorithm.

**Comment by bob-carpenter** [comment]
Thanks for filing the issue.  This is a known bug with the way
errors are currently being trapped, which is why it hasn't
been ported to RStan yet --- this would've crashed RStan if
we'd included it.

We should have this fixed (and a version in RStan) by the 
next release.

- Bob

**Comment by bgoodri** [comment]
Specifically it is #1544 and there is a pull request (that needs some work) for it. So, I think we can close this issue.

**Comment by dustinvtran** [comment]
Yup, hopefully when I have time later this week, I can repush some changes to the current pull request as it isn't working at the moment.
