### ISSUE TITLE
change csv output

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1560]
@betanalpha has a fix on the feature/issue-1361-writer_callback branch.

**Comment by syclik** [comment]
Closing because the fix is not actually more robust. This will be fixed on the branch.

**Comment by syclik** [comment]
I'm changing this issue to making the updates to the output as @betanalpha has implemented on the branch.

**Comment by bgoodri** [comment]
Will this address #1321 ?

**Comment by syclik** [comment]
I think we should.

**Comment by betanalpha** [comment]
No.  The CmdStan output streams which means the adaptation
info is printed only when it’s available after warmup.  This
doesn’t change any of that.

**Comment by bob-carpenter** [comment]
@syclik and @betanalpha  Is this still relevant?

**Comment by bob-carpenter** [comment]
I ask again, @syclik and @betanalpha Is this still relevant?  If I don't hear back, I'll just close it.

**Comment by syclik** [comment]
I'm closing it. It isn't specified well enough to fix. It's much easier to address, but we'll need some sort of better design / plan.
