### ISSUE TITLE
numerical instability in incomplete beta

### ISSUE THREAD

**Issue by 5harad** [stan-dev/stan#1561]
beta_cdf is numerically unstable for large parameter values.

**Comment by bob-carpenter** [comment]
Thanks for the report.

Do you have a specific test that fails?  Which version of Stan/RStan
are you using?  This may have been fixed in Michael's recent patch
of ibeta.

- Bob

**Comment by 5harad** [comment]
I'm using cmdstan 2.7. No specific test case, but the instability is possibly causing the problem I encountered here: https://groups.google.com/forum/#!topic/stan-users/4tRIqqZ5cSI

**Comment by betanalpha** [comment]
The new ibeta derivatives weren’t propagated to the beta CDF,
just the negative binomials.

**Comment by betanalpha** [comment]
The incomplete beta is fine -- the problem  is that the beta CDF isn't using the update derivative implementation.  In any case, this is a math library issue -- see https://github.com/stan-dev/math/issues/124.
