### ISSUE TITLE
Add sparse matrix by dense vector multiplication

### ISSUE THREAD

**Issue by sakrejda** [stan-dev/stan#1565]
I let this go stale, I'm going to fix it up so I can get it in now, the background is in pull request [1405](https://github.com/stan-dev/stan/pull/1405).  It needs to be two separate pull requests now, one for [stan-dev/stan](https://github.com/stan-dev/math/issues/127) and one for stan-dev/math.  For stan-dev only the function signature needs to be exposed.

__Fixes__
* [x] Expose one multiplication function---named "csr_matrix_times_vector"
* [x] Expose constructor for a dense matrix using the sparse format---named "csr_to_dense_matrix"
* [x] Expose extractors for turning dense matrix to sparse matrix components named:
  * [x] "csr_extract_w"
  * [x] "csr_extract_v"
  * [x] "csr_extract_u"
  * [x] "csr_extract_z"

* [ ] add documentation
* [x] expose it to the language
* [x] add test models testing each instantiation of the function

**Comment by bgoodri** [comment]
Is this still considered close to ready? @jgabry and I would like to release an R package with precompiled .stan programs early in the Fall semester and could really use a sparse design matrix in a few places.

**Comment by sakrejda** [comment]
Yes, I expect to push something that should be ready for a real pull
request early next week.  Most of the work is on the math library side so
the issue with progress tracking is in the math library:
https://github.com/stan-dev/math/issues/127

Krzysztof


2015-08-06 15:33 GMT-04:00 bgoodri <notifications@github.com>:

**Comment by sakrejda** [comment]
@bgoodri, @jgabry, I just pushed to the sparse_multiply feature branch for the math library.  It passes tests but probably not linting yet.  If that goes through the changes required for the stan library are really minor and I can help plumb stuff through for rstan if there's interest.

**Comment by syclik** [comment]
@sakrejda, I just updated the list with two items; we're at the Stan meeting and want to make sure we wrote down what had to be done.

**Comment by syclik** [comment]
(we all know you're working on it)

**Comment by bob-carpenter** [comment]
I added a third item --- tests.  I volunteered to do all of this if you need help.  We're trying to release in the next week and need to get this in.

**Comment by sakrejda** [comment]
@bob-carpenter Can you write the doc?  I added the signatures and I'm in the middle of adding the test models.  If I get stuck I'll ask for help with that too so I'm not holding you up.

**Comment by bob-carpenter** [comment]
Sure --- I'll write the doc this afternoon.

**Comment by sakrejda** [comment]
I think I took care of exposing it and adding tests on the [branch](https://github.com/stan-dev/stan/tree/feature/issue-1565-sparse-multiply), the good models tests that I added all run fine locally.  Feel free to do the pull request when you add the doc, let me know if anything else needs to happen for this.
