### ISSUE TITLE
stan reference -introduction

### ISSUE THREAD

**Issue by JuliaPalacios** [stan-dev/stan#1577]
Hi, 

I am reading the stan-reference-2.7.0.pdf file and in introduction, section{Variational Inference} (the first Variational Inference section 1.6), first paragraph, there is this sentence:

"Variational inference can be much for estimating posterior means and marginal variances than MCMC. See Chapter 59 for more information."

can be much ?

Thanks,
Julia

**Comment by bob-carpenter** [comment]
Thanks.  We'll fix it in the next release.  It should've said "faster" and perhaps also "more scalable".   I moved your comment to the next manual issue and am closing this issue;  see

https://github.com/stan-dev/stan/issues/1526#issuecomment-126944324
