### ISSUE TITLE
Specifying maximum number of iterations to be less than eval_elbo

### ISSUE THREAD

**Issue by dustinvtran** [stan-dev/stan#1591]
If users currently try to run `./model variational iter=1 data file=model.data`, then the algorithm runs on infinitely often or until convergence, rather than stopping after the first iteration. This is because we only check if the current iteration is equal to the maximum number of iterations during ELBO evaluations.

trivial fix will be available in this [pull request](https://github.com/stan-dev/stan/pull/1590)

**Comment by akucukelbir** [comment]
yes! i was thinking about this earlier today. great catch.

**Comment by dustinvtran** [comment]
Oops, sorry, this is a bug only in that pull request. It has nothing to do with eval_elbo and only comes up when max_iters is less than warmup_iterations.
