### ISSUE TITLE
redraw when an exception is thrown during the sampling phase of ADVI

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#1593]
If the optimum found by ADVI is close to the boundary, it is possible the the transformed draws from the multivariate normal distribution will also throw exceptions. This apparently stops sampling from continuing. I think the easiest thing to do would be to draw from a multivariate normal again.

**Comment by akucukelbir** [comment]
hi ben. could you give an example? what do you mean by "draws from the multivariate normal distribution will also throw exceptions"? we draw from a diagonal normal, transform the mean and (co)variances using an affine transform (cholesky in the case of full rank), and then plug it into `write_iteration` which applies the transformations that come from the model. where in that process do the exceptions occur?

**Comment by bgoodri** [comment]
I'm not sure exactly since it was a student's code. But after the
optimization, they got this fatal error message

*Exception: Exception thrown at line 422:*

*cholesky_decompose: Cholesky decomposition of m failed*

*Diagnostic information: *

*Dynamic exception type: std::domain_error*

*std::exception::what: Exception thrown at line 422:*

*cholesky_decompose: Cholesky decomposition of m failed*

which I guess could be due to one of the variances underflowing to zero in
the covariance matrix.

**Comment by dustinvtran** [comment]
I saw this happen once when I was playing with a bunch of models. I'll submit a pull request which does the dropping for this too.

**Comment by bgoodri** [comment]
Would be good if we can get this in for the next release too, but if not, it could be pushed to the next release.

**Comment by akucukelbir** [comment]
Fixed with https://github.com/stan-dev/stan/pull/1699.
