### ISSUE TITLE
sign comparison warnings from .stan programs

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#1594]
You can get unnecessarily confusing compiler warnings from a .stan program like
```
functions {
  vector normal_vec_rng(int N) {
    vector[N] ret;
    for (n in 1:rows(ret)) ret[n] <- normal_rng(0,1);
    return ret;
  }
}
model {}
file79a1192eb904.cpp: In function ‘stan::math::vector_d normal_vec_rng(const int&, const int&)’:
file79a1192eb904.cpp:52:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int n = 1; n <= rows(ret); ++n) {
                               ^
```
Can we do something about that in the parser? Or do we need to change `rows`, `cols`, etc. to return a plain int?

**Comment by bob-carpenter** [comment]
> On Aug 20, 2015, at 4:45 PM, bgoodri <notifications@github.com> wrote:
> 
> You can get unnecessarily confusing compiler warnings from a .stan program like
> 
> functions {
>   vector normal_vec_rng(int N) {
>     vector[N] ret;
>     for (n in 1:rows(ret)) ret[n] <- normal_rng(0,1);
>     return ret;
>   }
> }
> model {}
> file79a1192eb904.cpp: In function ‘stan::math::vector_d normal_vec_rng(const int&, const int&)’:
> file79a1192eb904.cpp:52:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>              for (int n = 1; n <= rows(ret); ++n) {
>                                ^
> 
> Can we do something about that in the parser? Or do we need to change rows, cols, etc. to return a plain int?

No, we only have signed ints.  So rows, cols, etc. should be returning a plain int.
I can fix.

- Bob

**Comment by bob-carpenter** [comment]
I think this may also be a stan/math issue.

**Comment by bgoodri** [comment]
If the problem is the return type of rows, cols, etc. rather than the
parser, then yeah it could move to math/issues.

**Comment by bob-carpenter** [comment]
Moved to https://github.com/stan-dev/math/issues/151 in stan-dev/math
