### ISSUE TITLE
Improve doc for adding functions to Stan

### ISSUE THREAD

**Issue by sakrejda** [stan-dev/stan#1595]
The [documentation](https://github.com/stan-dev/stan/wiki/Contributing-New-Functions-to-Stan) for adding functions to Stan has not been updated to reflect the fact that the math repository is split out into its own repository.  

**Fix**
- [ ] There should be one section for the stan-dev/math repository,  and one for the stan-dev/stan repository.
- [ ] Math repository section:
  - [ ] Describe how functions are organized.
  - [ ] Describe how includes function.
  - [ ] Describe what basic unit tests are needed.
- [ ] Stan repository section:
  - [ ] Point to function_signatures file.
  - [ ] Describe how signatures are structured a little (especially useful for permutations of types).
  - [ ] Describe what basic unit tests are needed.

**Comment by syclik** [comment]
Thanks for writing this out.

**Comment by sakrejda** [comment]
This is ancient and not relevant, closing.
