### ISSUE TITLE
"row_vector * matrix" is slower than equivalent explicit sum over "real * vector" (on Mac OS X)

### ISSUE THREAD

**Issue by mkuhn** [stan-dev/stan#1596]
I've created two models that are equivalent, but where I use an explicit sum (vector = real * vector + real * vector + ...) in one model, and a matrix multiplication (row_vector = row_vector * matrix) in the second model. Inexplicably, the second model is 30% slower, even though it is more "vectorized". Why is this the case? 

Minimal code and run times: http://rpubs.com/biocs/stan_matrix_sum

**Comment by syclik** [comment]
What OS and compiler are you using? I'll check later today.

**Comment by mkuhn** [comment]
Mac OS X 10.10.5; running RStan with RStudio.

**Comment by mkuhn** [comment]
I installed RStan on an Ubuntu system, and the numbers are reversed: the explicit sum takes 23 seconds, and the matrix multiplication takes 15 seconds.

**Comment by syclik** [comment]
@mkuhn, compiler? optimization level? These things matter at this level.

Also, you should be fixing seeds. Have you run it enough times to know it's
not seed dependent?

If you think this is a non-issue, please close the issue.

**Comment by mkuhn** [comment]
> @mkuhn, compiler? optimization level? These things matter at this level.

I slightly disagree, since this is the "out of the box" behaviour of RStan. 

Here's the Makevars file for Mac OS X (matrix slow):

```
CXXFLAGS = -Wall -mtune=core2 -O3 $(LTO)  #set_by_rstan
R_XTRA_CPPFLAGS =  -I$(R_INCLUDE_DIR)   #set_by_rstan
CC=clang
CXX=clang++ -arch x86_64 -ftemplate-depth-256
```

and here the Ubuntu one (matrix faster):

```
CXXFLAGS = -O3 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 $(LTO)  #set_by_rstan
R_XTRA_CPPFLAGS =  -I$(R_INCLUDE_DIR)   #set_by_rstan
```

> Also, you should be fixing seeds. Have you run it enough times to know it's
not seed dependent?

I am fixing seeds in the linked example (`stan(model_code = explicit_sum, seed = 42)`), unless this is the wrong way to do it. I observed it several times in my actual model (with random seed), and then again in the minimal model.

**Comment by bob-carpenter** [comment]
Can you send us a copy of the model and data so we can try to
recreate this behavior?  

- Bob

**Comment by syclik** [comment]
So, the adaptation is different across the two programs. I'm checking to see if it's numeric instability or if we've got a bug in one or both of the implementations.

**Comment by syclik** [comment]
We start drifting in warmup between iteration 100 and 200. You can see it in the last decimal place printed in CmdStan's output (I added print statements to see what's going on).

Once it starts to drift, it drifts fast. (no surprise.)

Regarding computation time, if you limit the number of iterations to pre-drift, matrix multiplication is faster. After they drift, all bets are off due to the variable number computations.

The inferences (I spot checked) are similar, so I don't think there's an error.

@bob-carpenter, do you think we should characterize where this differs? I'm happy to close the issue and move on.

@mkuhn, thanks for creating an example that could be run. That helps immensely.

**Comment by bob-carpenter** [comment]
@mkuhn:  Thanks again for reporting.  I really wish "out of the box" meant the same thing on every box.  There is the issue of which compiler is installed in your OS and how your pathis resolved, plus whatever spec's in the R makefiles and also how R is wrapped (terminal, GUI, Rstudio --- they all buffer I/O differently from what I can tell from inspecting the output) and then on what options are set when the model is compiled (there's a fast and debug option configurable through RStan).

@syclik: I absolutely think it's worth blogging as a case study in exact vs. statistical replication. Maybe we can do that over coffee the next time we're sitting down together with some free time.

I also found that the default Eigen was faster than our matrix multiplication, but ours takes much less memory. I chalk it up to memory locality in the autodiff paper --- you can see the differing behavior of systems based on whether they declared Eigen traits properly or not.

I'm OK closing this issue---it's the tip of the iceberg in optimizing matrix ops.

**Comment by mkuhn** [comment]
Thanks a lot for checking the issue! In the end, vectorisation is very useful and it would help if more of it was implemented (e.g. allowing a[v] if v is a vector) -- I think there's an issue open for this somewhere. I'm closing this bug.
