### ISSUE TITLE
stanc and stanc_helper fails on read-only input files

### ISSUE THREAD

**Issue by enbrown** [stan-dev/stan#1615]
Stanc through `stan/src/stan/command/stanc_helper.hpp` appears to open the input stan file in input/output mode (as an `fstream`) which fails if the file is read-only. Perhaps there are other problems if this variable is an `ifstream` but so far that seems to fix this issue:

Changing line 94:

>    std::fstream in(in_file_name.c_str());

to:

>    std::ifstream in(in_file_name.c_str());

seems to be enough (without much testing on my part) to let `stanc` process read-only stan input files.

**Comment by bob-carpenter** [comment]
Thanks --- I assigned it to myself and will get it fixed in the next release.  We (probably I) was just being sloppy there.  This will probably all move to an interface somewhere in the Stan 3 refactor, so that only the parser/code generator with generic istream and ostream are left in Stan itself.

**Comment by syclik** [comment]
Thanks, Bob.
