### ISSUE TITLE
move src/stan/services

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1616]
On Michael's branch, there are a bunch of moved services. These all seem reasonable and moving them in a separate issue will decouple the move from changes to the implementation.

- [x] 2d413f25 `src/stan/io/mcmc_writer.hpp` -> `src/stan/services/sample/mcmc_writer.hpp`
- [x] 8dac3f0 `src/stan/services/optimization/do_bfgs_optimize.hpp` -> `src/stan/services/optimize/do_bfgs_optimize.hpp`
- [x]  c106097 `src/stan/services/mcmc/run_markov_chain.hpp` -> `src/stan/services/sample/generate_transitions.hpp`
- [x] 40bc976c 
    `src/stan/services/init/init_adapt.hpp` -> `src/stan/services/sample/init_adapt.hpp`
    `src/stan/services/init/init_nuts.hpp` -> `src/stan/services/sample/init_nuts.hpp`
    `src/stan/services/init/init_static_hmc.hpp` -> `src/stan/services/sample/init_static_hmc.hpp`
    `src/stan/services/init/init_windowed_adapt.hpp` -> `src/stan/services/sample/init_windowed_adapt.hpp`
- [x] 83290a8 `src/stan/services/mcmc/print_progress.hpp` -> `src/stan/services/sample/progress.hpp`

This will cut down on a lot of the number of files that we have to sift through for the pull request. I think most of these moves are reasonable and shouldn't affect rstan / pystan so much if we're careful about moving and not changing for this issue.

**Comment by syclik** [comment]
@betanalpha, does that list look right? (see the issue -- I updated the first comment so we have a checklist there)

**Comment by betanalpha** [comment]
src/stan/services/mcmc/sample.hpp is converted into src/stan/services/sample/run_adaptive_sampler.hpp _and_ src/stan/services/sample/run_sampler.hpp. src/stan/services/diagnose/diagnose.hpp,  src/stan/services/optimize/optimize.hpp, and src/stan/services/optimize/sample.hpp pull out code from cmdstan::src/command.hpp into API-accessible functions.

**Comment by syclik** [comment]
These need to go into another issue:
- `src/stan/services/mcmc/warmup.hpp` / `src/stan/services/mcmc/sample.hpp` -> `src/stan/services/sample/run_adaptive_sampler.hpp` / `src/stan/services/sample/run_adaptive_sampler.hpp`
- from CmdStan -> `src/stan/services/diagnose/diagnose.hpp`
- from CmdStan -> `src/stan/services/optimize/optimize.hpp`
- remove: `src/stan/services/io/write_interation_csv.hpp`

They're not just moving files and renaming. I'll add them to a subsequent issue.
