### ISSUE TITLE
Stan Modeling Language Manual bug

### ISSUE THREAD

**Issue by jireva** [stan-dev/stan#1629]
Section 1.6 (p25) and 1.8 (p26) are both titled Variational Inference.

They should be merged.
Or 1.6 should be removed (1.8 is more detailed).

**Comment by bob-carpenter** [comment]
Thanks for pointing that out.  I'll fix it for the next release.  I consolidated the issue into our next manual issue here

https://github.com/stan-dev/stan/issues/1617#issuecomment-146678770
