### ISSUE TITLE
L for HMC should be integer

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1637]
Ashley Ford reported this issue on stan-users.

<blockquote>
I have been leaving int_time__ at it's default value of 2 pi and and other parameters at their defaults. Calculating L  from the output of get_sampler_params(sg100Hresb,inc_warmup=TRUE) does give fractional values,  the heads of an example set of chains 
</blockquote>

With example:

```
  accept_stat__ stepsize__ int_time__        L
1  1.000000e+00  0.1250000   6.283185 50.26548
2  4.587079e-01  0.3599190   6.283185 17.45722
3  1.000000e+00  0.1777388   6.283185 35.35067
4  2.445632e-79  0.4722619   6.283185 13.30445
5  1.000000e+00  0.1439539   6.283185 43.64719
6  6.089640e-05  0.3901480   6.283185 16.10462
```

* [ ] these should print as the integer number of steps actually used (assuming it doesn't take a final partial step, in which case this issue should be moved to doc to explain the output)

* [ ] thank Ashley Ford in acknowledgements

**Comment by betanalpha** [comment]
From where is L getting printed?  The C++ prints only step size and integration time,
not L.  Is this an RStan issue?

**Comment by bob-carpenter** [comment]
I'd think CmdStan should print L as an integer.  So this must be 
an R thing.

But it needs to be available from the new interfaces, I'd think.

What is the actual number of steps --- round off or round up?

**Comment by betanalpha** [comment]
CmdStan shouldn't print L at all, which is what I was trying to say.
Behind the scenes it’s a static_cast, so follows the C++ rounding
rules.

**Comment by bob-carpenter** [comment]
If CmdStan shouldn't print it, then neither should RStan!

I realize it's derivable from two other things, but that doesn't
necessarily mean we don't want to print it.  Printing it means people
can inspect it easily in the output.

But I'm happy either way on this one.  It's no big deal because
it's just basic (non-NUTS) HMC anyway.

**Comment by apford** [comment]
I  hope my last post didn't confuse,  
I was calculating L myself from stepsize__ and int_time__   
My understanding now is that the actual integration time is
 stepsize__  *  round(int_time__ / stepsize__)
usually slightly less than  int_time__  
I don't think code needs any changes, just an extra sentence in documentation.

**Comment by bob-carpenter** [comment]
Moved to an issue comment in doc:  https://github.com/stan-dev/stan/issues/1617#issuecomment-150450203
