### ISSUE TITLE
Option to not calculate generated quantities during warmup when warmup samples are not saved

### ISSUE THREAD

**Issue by gbiele** [stan-dev/stan#1641]
## Feature Request

**Category**
New option/function

**Description**
Currently generated quantities are always calculated during warmup and sampling.
The motivation for always calculating generated quantities is that they can be
saved and examined during post-processing, which would crash if only parameters 
but not generated quantities would be saved during warmup.
(see Bobs comments here:
https://groups.google.com/d/msg/stan-users/Q-4MCXNGf54/2DEAWby8AwAJ)

However, calculating generated quantities can be computationally costly.

A "compromise" that insures no crashing when warmup samples are saved would be 
to selectively allow to not calculate generated quantities only when warmup samples
are not saved.

**Possible solutions**

<ol start="1">
<li> Add an option to interface(s) that allows to specify if generated quantities are calculated during warmup or not.</li>
<li>Expose a variable that tells the user if stan is currently in warmup or sampling "state".  This would allow the user to write a program that only really calculates generated quantities during sampling.</li>
</ol>

for example assuming there would be a variable "sampling" that has the value 0 
during warmup and 1 during sampling:

```
generated quantities {
  real posterior_prediction[N];
  if (sampling == 0) {
      // do not realy calculate anything, but instead put in a placeholder number
      posterior_prediction <- rep_array(1, N);
    } else {
      for (k in 1:N) posterior_prediction[n] <- normal_rng(alpha + beta * x, sigma);
    }  
}
```

**Further information**
Related to this stan-users mailing list topic:
https://groups.google.com/forum/#!topic/stan-users/Q-4MCXNGf54

**Comment by bob-carpenter** [comment]
* [ ] Generalize this to not evaluate/store generated quantities for intermediate iterations in 
    - [ ] ADVI
    - [ ] optimization

**Comment by syclik** [comment]
If someone wants to tackle this, start from branch: `feature/issue-1751-service-methods`. That's the refactor and this will be much easier to fix from that branch.

**Comment by martinmodrak** [comment]
Probably superseded by #2459

**Comment by rok-cesnovar** [comment]
Superseeded by #2459
