### ISSUE TITLE
whitelist segment() from Jacobian warnings

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#1642]
The .stan files in rstanarm currently produce this warning when build
```
DIAGNOSTIC(S) FROM PARSER:
Warning (non-fatal):
Left-hand side of sampling statement (~) may contain a non-linear transform of a parameter or local variable.
If so, you need to call increment_log_prob() with the log absolute determinant of the Jacobian of the transform.
Left-hand-side of sampling statement:
    segment(rho,pos_rho,(p[i] - 1)) ~ beta(...)
```
I don't think this will be a big deal as far as getting rstanarm onto CRAN goes, but it should be suppressed in the next Stan release because segment() is linear.

**Comment by bob-carpenter** [comment]
I think there may be a few other ones I missed.  I'll take a pass over the doc.

* [ ] segment

**Comment by bgoodri** [comment]
On #1583 now
