### ISSUE TITLE
Add tests for five regression models

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1643]
## Feature Request

**Version**

2.8.0

**Category**

testing

**Description**

@bgoodri has provided me with 5 examples, all from ARM:
1. Earnings from Chapter 4
2. Mesquite Weight from Chapter 4
3. Arsenic from Chapter 5
4. Roaches from Chapter 8
5. Elections from Chapter 14

**Additional Information**

From Ben:
         We will consider it to be working correctly if the point estimates from Stan for all parameters are within the 99% confidence intervals of the frequentist estimator.

**Comment by bob-carpenter** [comment]
What are the point estimates from Stan?  Is that the posterior means for MCMC or ADVI or the mode for maximization?

**Comment by syclik** [comment]
The intention was MCMC estimates from Stan.

**Comment by bob-carpenter** [comment]
This is a much bigger issue that we need to address in terms of a more general testing framework that takes Monte Carlo error and sample variation into account.
