### ISSUE TITLE
allow PRNGs to be called in transformed data

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1644]
The title says it all and it's backward compatible.

* [x] change to variable checking code in function semantic actions
* [x] updated model tests for parsability of RNG location
* [ ] update Stan manual

I'll try to knock this out when I want a small project.  If there are examples I should put in the manual, please comment or add sub-bullets to the above list.

**Comment by bgoodri** [comment]
Also, expose a `print_csv` function that takes a single arbitrary argument and prints to the output stream the object in CSV format so that the user can more easily capture the objects in the transformed data block that are PRNG.

**Comment by betanalpha** [comment]
I strongly oppose adding arbitrary messages to the output files.
The screen is one thing, but the csv_reader is enough of a mess
as it is.

**Comment by bgoodri** [comment]
I meant to say to the screen, not to samples.csv.

**Comment by bob-carpenter** [comment]
This is a separate issue and shouldn't be piled onto
the PRNG issue.  Also, I'm not clear what "CSV format" is.
You just mean the numbers we'd write out for it in the CSV
writer?  So no headers and presumably commas between numbers.
Newlines at end, or should user be able to stack?

- Bob
