### ISSUE TITLE
Adding basic operations for symmetric matrices

### ISSUE THREAD

**Issue by rayleigh** [stan-dev/stan#1647]
## Feature Request

__Version__
2.8.0++

__Description__
Add functions to do addition, subtraction, element multiplication, and element division for symmetric matrix. Because these functions need to check if the matrices are symmetric, the check for whether a matrix is symmetric will be updated to be more efficient.

__Example__
```
//user has specified some symmetric matrix A and B
C <- sym_add(A, B);
```

__Additional Information__
What should these functions be called? I'm thinking sym_add and sym_substract for addition and subtraction and sym_elem_multiply and sym_elem_divide for multiplication and division respectively.

Also, what should the function calls be? The following seem to make sense:

For symmetric matrix A and B,
```
//Adds a symmetric matrix to itself
sym_add(A) 

//Adds a symmetric matrix to another symmetric matrix
sym_add(A, B)
```

**Comment by bob-carpenter** [comment]
What are the slashes for in the text?  And you should quote the code.

Also, what is the plan to make the test for symmetry more efficient?  

Finally, I'm not sure we even need to do the test for symmetry.  It could be defined to take the lower-triangular portion, reflect to top and do the addition --- that's how Eigen works.  Check out their expression templates to see how they do it.

**Comment by bob-carpenter** [comment]
Also, there can be proper symmetric matrix multiplies --- they'd also work by doubling the lower-triangular view.  Eigen has built-ins that can make this more efficient.

**Comment by betanalpha** [comment]
I believe Eigen can also leverage the symmetry expression templates
when doing Cholesky decompositions.

**Comment by bgoodri** [comment]
Why was this issue reopened? It is in stan-dev/math .

**Comment by bob-carpenter** [comment]
must've fat-fingered it. closing now.
