### ISSUE TITLE
Update hamiltonians to hold its point type

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1653]
## Feature Request

__Description__

(This is part of @betanalpha's #1361 implementation.)

- [x] 378b6f5 Update `stan/mcmc/hmc/hamiltonians/base_hamiltonian.hpp`:
  1. Rename template arguments from `M` to `Model` and `P` to `Point`.
  2. Add typedef of `Point` to `PointType`.
- [x] ec731eba Update uses of hamiltonians: remove template parameter `P`, rename `H` to `Hamiltonian`, use `Hamiltonian::PointType` in place of `P`.
  - `stan/mcmc/hmc/integrators/base_leapfrog.hpp`
  - `stan/mcmc/hmc/integrators/expl_leapfrog.hpp`
  - `stan/mcmc/hmc/nuts/base_nuts.hpp`
  - `stan/mcmc/hmc/static/base_static_hmc.hpp`
  - `stan/mcmc/hmc/static/dense_e_static_hmc.hpp`
  - `stan/mcmc/hmc/static/diag_e_static_hmc.hpp`
  - `stan/mcmc/hmc/static/unit_e_static_hmc.hpp`
  - `stan/mcmc/hmc/base_hmc.hpp`

There might be a few more uses.

__Additional Information__

1. This was completely unrelated to #1361, so should be split out. I like the changes and won't affect the interfaces.
2. This will cut down the diff of @betanalpha's branch for #1361, so it'll be easier to tell what's going on there.

**Comment by betanalpha** [comment]
What’s the utility of using a typedef instead of templating everything out?

**Comment by syclik** [comment]
Great question. This was snuck into the 1361 branch. @betanalpha, want to answer that for us? 

I think it simplifies things so I'm in favor of it.

**Comment by betanalpha** [comment]
> Great question. This was snuck into the 1361 branch. @betanalpha, want to answer that for us?
> 
Dammit it’s confusing when you split these PR up like this.
Putting a typedef in the Hamltonian removes a bunch of
duplicated info in the template arguments which should
speed up compilation (somewhat) and avoid conflicting
template decorations (more important).  

Also

stan/mcmc/hmc/nuts/dense_e_nuts.hpp
stan/mcmc/hmc/nuts/diag_e_nuts.hpp
stan/mcmc/hmc/nuts/unit_e_nuts.hpp

will have to be updated.
