### ISSUE TITLE
Simplify mcmc_writer

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1666]
After staring at the implementation of mcmc_writer, I think it should be done a little simpler. I'll create a pull request and we can discuss whether it's the right thing to do.

**Comment by syclik** [comment]
@betanalpha, in the new implementation under the branch for 1361, why does mcmc_writer need to hold onto a model instance? I feel like I'm missing something.

**Comment by syclik** [comment]
I'm a little confused about the role of mcmc_writer at this point. It looks like it's more for convenience, is that right?

**Comment by syclik** [comment]
(btw, I think I might be responsible for the core of the functionality, but I don't want to have it look this way going forward and if you don't have any reason to keep it this way, I'll take a pass at fixing it.)

**Comment by betanalpha** [comment]
To print out the parameter names (both constrained and unconstrained)
and transformed an unconstrained sampler state to the constrained space.

**Comment by bob-carpenter** [comment]
@syclik Is this still an issue?

**Comment by syclik** [comment]
This is addressed with #1751. We can hold off on closing this until that is finished.

**Comment by bob-carpenter** [comment]
#1751 is closed, so I'm closing this.
