### ISSUE TITLE
Writer: use writer for hamiltonians (stan/mcmc/hmc/hamiltonians/)

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1678]

**Comment by bob-carpenter** [comment]
These little refactors would be good to knock off.  This one isn't specific enough for me to tackle.

**Comment by bob-carpenter** [comment]
Just to be clear, I didn't mean we should do this before 2.13, but we should eithet fix these little issues or remove them from the tracker.  I worked through all the ones I could on stan-dev/math and now I'm going to do the same for this repo.

**Comment by syclik** [comment]
I just checked. This was finished.
