### ISSUE TITLE
generate C++ top-level namespace for double versions of user-defined functions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1703]
To expose user-defined functions as R functions, RStan needs versions of the user-defined functions that are (a) defined in the top-level namespace, and (b) instantiated with double types.

Question 1:  What if the function throws an exception?  Can R handle that, or should we catch all those and return NaN or something if there's a return?   These come in either through functions or reject statements. 

Question 2:  What if the function prints?  Is it OK to have an output stream as one of the arguments?

**Comment by sakrejda** [comment]
It's relatively straightforward to catch exceptions via Rcpp.  Relevant
part near bottom of:

http://gallery.rcpp.org/articles/intro-to-exceptions/

Krzysztof

**Comment by bgoodri** [comment]
This would be nice to have but I'm not sure whether Rcpp::sourceCpp() will be able to compile an entire Stan C++ program. It only knows how to link against a few Rcpp related packages and it would be somewhat of a challenge to get all the rstan headers included in the right way. At the moment, when I strip out everything except the user-defined functions, I basically only need math.hpp.

**Comment by bob-carpenter** [comment]
I can generate complete double-only versions of the functions
that only depend on math.hpp.  It's exactly the same body-of-function
code generation as in the other case, just different arguments.

You wouldn't need to compile everything else.  

- Bob

**Comment by bgoodri** [comment]
OK, not a huge priority since the current `expose_stan_functions` works 98% of the time and does not call any internal functions, so it is easy to source a version from GitHub that works 98.5% of the time after I have fixed another corner case. Also, it wouldn't need to be double-only since ints are also allowed. It just can't have var, fvar<T>, etc.

**Comment by bob-carpenter** [comment]
I don't like things that only work 98% of the time, so it's
a high priority for me!  It shouldn't take me more than a day or
two to do, so I'll try to get it done before the end of the year.

- Bob

**Comment by bob-carpenter** [comment]
I think there's another issue floating around on roughly the same topic but can't find it now.  In any case, this is being pushed off to the future.

**Comment by sakrejda** [comment]
Hey, we did this already.
