### ISSUE TITLE
Allow specification of initial mass matrix for NUTS sampler

### ISSUE THREAD

**Issue by 137alpha** [stan-dev/stan#1706]
## Feature Request

Modified by @bob-carpenter

**Description**

Allow Stan to accept as input a matrix which should be used to initialise the mass matrix for the NUTS and static HMC samplers with diagonal (vector) and dense (matrix) [so that's a total of four commands].

The input should be handled by passing in an argument to match the way arguments get passed in for parameter initializations (that is going to bottom out in a `var_context` at some level).

The rationale for this is that poor variable scaling can lead to very long warmup times, particularly if the model is complex.  For many problems, an initial call to "optimizing" can be used to obtain a Hessian matrix which can be used as an initial guess at the mass matrix.  Even if this is only approximate, it may be much faster than waiting for Stan to discover the correct mass matrix.

The importance of this is greater when debugging a model, requiring many warmup cycles.

Where the mass matrix is diagonal, then the diagonal terms of an input matrix can be used (or alternatively, Stan could simply accept a vector which is the initalising diagonal).

This would be extremely useful for many users due to the substantial time savings, and much appreciated!

**Comment by bob-carpenter** [comment]
Thanks --- this is on our longer-term to do list for Stan 3, for exactly the reasons you outline.

**Comment by betanalpha** [comment]
Well, except for using a point Hessian estimate, which is just asking for trouble.
But, yes, this is one motivation for aspects of the current refactor.

**Comment by mitzimorris** [comment]
method "write_metric" in class stan::mcmc::base_hmc outputs stepsize as well as mass matrix.
for resuming sampling, does stepsize matter?

**Comment by bob-carpenter** [comment]
Yes.  But we can already supply a stepsize to all these functions, so that's not your problem for this issue.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/stan/pull/2260

**Comment by 137alpha** [comment]
Awesome! Thanks so much Stan dev team! <3

**Comment by 137alpha** [comment]
FWIW I am JulianK on the forums.

**Comment by bob-carpenter** [comment]
@137alpha --- we still still need to get it into the interfaces.
