### ISSUE TITLE
remove namespace pollution introduced by log_mix

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1707]
The file `stan/math/fwd/scal/fun/log_mix.hpp` currently has using statements at the namespace level.  We do not want to allow that anywhere.

* [x] remove top-level using
* [x] reintroducing using at function-scope level

**Comment by sakrejda** [comment]
@bob-carpenter I did this on a [branch](https://github.com/stan-dev/math/compare/cleanup/issue-1707-remove-namespace-level-using-in-log_mix?expand=1) (trying to remind myself what the process is around here...).

**Comment by bob-carpenter** [comment]
Great --- can you turn it into a pull request?  

I'd like to do a Stan-wide code review, since this seems
to be a pervasive problem (this isn't the first time someone's
committed one of these erroneously).

I'm not sure how to do that other than generating a big report
with context around the matches to " using ".

- Bob

**Comment by sakrejda** [comment]
Is this sort of thing a problem too?  There's a lot of "using Eigen::Dynamic;" in stan::math

~~~
./stan/math/prim/mat/err/check_corr_matrix.hpp-namespace stan {
./stan/math/prim/mat/err/check_corr_matrix.hpp-
./stan/math/prim/mat/err/check_corr_matrix.hpp-  namespace math {
./stan/math/prim/mat/err/check_corr_matrix.hpp:    using Eigen::Dynamic;
./stan/math/prim/mat/err/check_corr_matrix.hpp-    /**
./stan/math/prim/mat/err/check_corr_matrix.hpp-     * Return <code>true</code> if the specified matrix is a valid
./stan/math/prim/mat/err/check_corr_matrix.hpp-     * correlation matrix.
./stan/math/prim/mat/err/check_corr_matrix.hpp-     *
~~~

**Comment by syclik** [comment]
Yes, we're trying to avoid namespace-level using statements. It has some weird side-effects.

**Comment by sakrejda** [comment]
Ok, thanks for confirming.

**Comment by sakrejda** [comment]
I addressed this more generally in another [issue](https://github.com/stan-dev/math/issues/207) and a branch on [stan-dev/math](https://github.com/stan-dev/math/tree/cleanup/issue-207-scrape-replace-namespace-level-using), I ran tests locally so I'll wait to make sure it passes and make it a pull request tomorrow. Seems like this issue should be in stan-dev/math anyway so I'm closing it here.  Feel free to reopen if I'm wrong.  Maybe the same thing needs to happen more generally with stan-dev/stan as well.
