### ISSUE TITLE
next manual 2.9.0++

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1709]
This is where comments for the manual for the version after 2.9.0.

**Comment by bob-carpenter** [comment]
* [ ] update description of how Wiener distribution is defined according to following.

From Joachim Vandekerckhove on stan-users:

Sorry I'm a little late to this party, I had a long summer of travel.  The reason we originally implemented the lower-bound hits as negative reaction times was to have a cheap way of encoding what is essentially a bivariate distribution (strictly positive RT and binary response).  Because both the RT and the outcome are random variables, the current implementation (with only one bound) isn't entirely satisfactory if at any point we want to generate random numbers from the distribution.

I always liked the negative-RT solution even though it's a little counter-intuitive.  I'd probably prefer it in Stan since it's how it works in JAGS... but the more conventional solution would be to make it actually bivariate, and let it operate on a [RT response] pair, where the first is a strictly positive real and the second is a boolean.

**Comment by bob-carpenter** [comment]
add discussion of conditions on the function passed to `ode_integrate`, including:

* [ ] can it be discontinous?

Any other conditions we should warn users about?

**Comment by bob-carpenter** [comment]
From @brendan-r: 

Very minor:

The parameter for `segment` on a `row_vector` is `v` [in the specification](https://github.com/stan-dev/stan/blob/develop/src/docs/stan-reference/functions.tex#L2531), and `rv` in the description.

* [ ] fix it so that it says `rv` in both places

**Comment by bob-carpenter** [comment]
From @betanalpha on https://github.com/stan-dev/stan/issues/1734

The denominator in the ESS estimator in section "Estimation of Effective Sample Size" is missing a factor of 2.

* [ ] fix

**Comment by bob-carpenter** [comment]
* [ ] add Aki to list of developers

**Comment by bob-carpenter** [comment]
From @mike-lawrence originally in issue: https://github.com/stan-dev/stan/issues/1733

The very first paragraph ends with an incomplete sentence ("This allows hierarchical 1"), seemingly as if the rest was mistakenly cut.

* [ ] finish sentence
* [ ] thank Mike Lawrence

**Comment by bob-carpenter** [comment]
* [ ] add discussion of unknown time in discussion of ODE solver

There's a discussion here:  https://groups.google.com/d/msg/stan-users/Oo1SYf3Lo_8/OKfdJZVxBQAJ

* [ ] thank Dieter Menne for pointing that out

**Comment by bob-carpenter** [comment]
From James Savage (pc):

<blockquote>
I think there's a small error on the manual on P 58-59 (multi logit in the `K-1` vector identification bit). It should be `append_row()` rather than `append_col()`. 
</blockquote>

* [ ] fix it

**Comment by avehtari** [comment]
The code at bottom of p. 112 is missing log_sum_exp

* [ ] fix it

**Comment by bob-carpenter** [comment]
Stefano (on stan-users) said:

I wasn't aware of the "index-swapping problem". I think it would be helpful to reference it in the paragraph where the simple mixture deconvolution model is presented, as it is something not intuitive to pick for first Bayes modellers like me.

* [ ] add a note to that effect and cross-reference the identifiability discussion
    * [ ] normal mixture
    * [ ] clustering models

**Comment by bob-carpenter** [comment]
* [ ] thank Chris Black for a documentation patch

**Comment by bob-carpenter** [comment]
From Guido Biele on stan-users:

I had troubles implementing this because, i believe, the example  for the hurdle model on page 115 has a small but consequential error:

When implementing the truncation, I think the code increments the log posterior by

```
-log(poissonCDF(0,lambda))
```
instead of the correct

```
 -log(1-poissonCDF(0,lambda)).
```
Alternatively, `log(1-exp(-lambda))` is already the CCDF, and not the CDF as 
it says on page 115.

* [ ] check and correct

**Comment by bob-carpenter** [comment]
* [ ] add note that normalization for change point model is `lp - log_sum_exp(lp)` on the log scale and point users from p. 126 to the normalization on p. 127 --- the `q` notation isn't enough

* [ ] ideally roll the normalizing computation into the Stan program's generated quantities block;  if not, push this issue into longer-term issues for example models

**Comment by maciekjswat** [comment]
Typo in 'Ordered Logistic Distribution': redundant '-0' in the last condition "if k=K" or missing term?

**Comment by bob-carpenter** [comment]
@bgoodri on stan-users mailing list suggested this:

I would declare a parameter vector and transform it into a matrix using the new slicing assignment syntax:

```
transformed data { // you could also pass these in as data
  int<lower=1,upper=3> row_mark[7];
  int<lower=1,upper=3> col_mark[7];
  row_mark[1] <- 1; col_mark[1] <- 1;
  row_mark[2] <- 2; col_mark[2] <- 1;
  row_mark[3] <- 3; col_mark[3] <- 1;
  row_mark[4] <- 2; col_mark[4] <- 2;
  row_mark[5] <- 3; col_mark[5] <- 2;
  row_mark[6] <- 2; col_mark[6] <- 3;
  row_mark[7] <- 3; col_mark[7] <- 3;
}
parameters {
  vector[7] Bvec;
}
model {
  matrix[3,3] B;
  B[row_mark,col_mark] <- Bvec;
  B[1,2] <- 0;
  B[1,3] <- 0;
}
```

**Comment by bob-carpenter** [comment]
Mixture modeling chapter:

* [ ] discuss why the responsibilities mean each component gets proportionally less data (proportional to weighting)

* [ ] explain how this affects the prior

* [ ] explain difference between model averaging (whole data set at a time) vs. mixture modeling (item by item)

**Comment by bob-carpenter** [comment]
Andy Choi points out on stan-users:

* Under ch 10.3, mixing portion seems to be declared as theta. 
* Under ch 10.4, mixing portion seems to be declared as lambda.

* [ ] make them both `lambda` and standardize on that for mixing proportions

**Comment by bob-carpenter** [comment]
* [ ] thank Matthew Zeigenfuse for a bug report

**Comment by bob-carpenter** [comment]
* [ ] add discussion of why integers overflow in generated quantities
* [ ] explain how to use a conditional to prevent the problem

**Comment by bob-carpenter** [comment]
* [ ] Explain how to have a vector of lower bounds with

```
data {
  int N;
  vector[N] L;  // lower bounds

parameters {
  vector[N] my_vec_raw;


transformed parameters {
  vector[N] my_vec;
  my_vec <- L + exp(my_vec_raw);

model {
  increment_log_prob(sum(my_vec_raw));  // Jacobian
```

* [ ] note that it also works if L is  a parameter that doesn't depend on my_vec_raw, because of the lower-triangular structure of  (L, my_vec_raw) -> (L, my_vec) and the fact that the upper L x L block is just the unit matrix.

**Comment by bob-carpenter** [comment]
* [ ] multiple change point example missing argument in `rep_matrix`.

**Comment by jonathan-g** [comment]
Tiny typo: p. 70 "As an example, the individuals might people...", should probably be "As an example, the individuals might be people..."

**Comment by bob-carpenter** [comment]
Thanks for reporting this in the right place!  I'll fix
it for the next release.

**Comment by bob-carpenter** [comment]
From Jonathan Gilligan on stan-users:

u is declared on p. 72 as

```
row_vector[L] u[J];
```

and I was thinking that in the optimized version on pp. 74-75, this should be 

```
matrix[J,L] u;
```

so that it can be used for matrix multiplication in

```
u * gamma + (diag_pre_multiply(tau, L_Omega) * z)';
```

**Comment by bob-carpenter** [comment]
Yannick Spill on stan-users suggested:

* [ ] add the size of u,v,w in the docs for sparse matrices

Also

* [ ] thank Yannick

**Comment by bob-carpenter** [comment]
* [ ] explain in sparse matrix doc that it will be slower than dense matrix multiplication until there is substantial (90%?) sparseness.

**Comment by bgoodri** [comment]
We don't actually know how sparse a sparse matrix needs to be in order to
be faster than dense multiplication with all the zeros

https://github.com/stan-dev/math/issues/231

**Comment by sakrejda** [comment]
I was just about to point Nikolay Evdokimov from the users list to the reference manual to look up divergent transitions but when I search the manual for "divergent" nothing comes up.  There is a section on the HMC algorithm that maybe should have a search-friendly mention of the few numerical problems that can be tickled by model specification.

**Comment by jgabry** [comment]
From @ericnovik in #1826:

At the bottom of page 380 (in 2.9.0 manual) in the `generated quantities` block  `x[n]` should be `x_tilde[n]` in:

```stan
for (n in 1:N_tilde)
  y_tilde[n] <- normal_rng(alpha + beta * x[n], sigma);
```

* [ ] change `x[n]` to `x_tilde[n]`.

**Comment by bob-carpenter** [comment]
From Cody James Horst on stan-users:

a typo on page 41 under the header "5. Multiple and Range Indexing" :

Stan allows multiple indexes to be provided for containers (i.e., arrays, vectors,
and matrices) in a single position, using either an array of integer indexes or range bounds. 
This allows hierarchical 1

Then it just goes to a subheader. I thought this bit might be incomplete and wanted to pass this along so it doesn't go under the radar

* [ ] fix or trim
* [ ] thank Cody

**Comment by bob-carpenter** [comment]
* [ ] add doc on how to call the CVODE integrator
* [ ] add licensing info for CVODE

**Comment by bob-carpenter** [comment]
From @wds15 on stan-users:

All I wanted to say is that putting a note in the manual besides the normal_cdf (where you warn about the numerical issues due to over+underflow) would be helpful for users who wonder how they may get around these numerical challenges.

* [ ] add pointer to Phi_approx in normal_cdf function mentioning the improved stability

**Comment by bob-carpenter** [comment]
Guido Biele requested on stan-users:

* [ ] mention that with more data, the centered parameterization is better than non-centered (ideally this would go in a case study with simulations following Betancourt and Girolami's paper)

**Comment by bob-carpenter** [comment]
From Luke Wiklendt on stan-users:

* [ ] Update change-point model to use a specialized forward-backward algorithm:

```
  transformed parameters {
    vector[T] lp;
    {
      vector[T+1] lp_e;
      vector[T+1] lp_l;
      lp_e[1] <- 0;
      lp_l[1] <- 0;
      for (t in 1:T) {
        lp_e[t + 1] <- lp_e[t] + poisson_log(D[t], e);
        lp_l[t + 1] <- lp_l[t] + poisson_log(D[t], l);
      }
      lp <- rep_vector(log_unif + lp_l[T + 1], T) + head(lp_e, T) - head(lp_l, T);
    }
  }
```

* [ ] Thank Luke in the acknowledgements
