### ISSUE TITLE
Add option for more detailed output

### ISSUE THREAD

**Issue by davidmanheim** [stan-dev/stan#1714]
## Feature Request

__Version__
2.8

__Category__
User Interface

__Description__
Include an option for detailed output during model sampling process, especially to allow debugging for models that don't complete, and so the final output isn't available.

__Example__
Information might include, for each iteration; current stepsize, treedepth, and number of leapfrog steps

__Additional Information__
The model, while running, gives only the iteration number. It would be helpful / useful for it to provide more detail if asked to do so for each iteration, as well as information about what it is doing before sampling, so that if the model runs very slowly and cannot complete, it could be more easily determined why. (I'm unsure which steps are time-consuming before sampling, but presumably a message when generating initial values, if none are provided, and similar points could be output, since occasionally models cannot begin sampling and seem to be stuck, especially if misspecified - per the folk theorem.)

**Comment by davidmanheim** [comment]
I'm sure those that understand this better would be able to come up with what information would be most helpful to them in understanding the behavior of the model, but as a first approximation, (to be built on or corrected);

I would think that the best way to decide which things you might want to include would be based on profiling the code for complex models, and seeing which parts are slowest / most variable between different models and model types. If anyone is doing code profiling, this might be easy. If not, based on my very limited understanding, I would think that the interesting information would be about the initialization, then about the warmup adaptation stages (like the size of the slow adaptive windows.)

**Comment by jonathan-g** [comment]
A fair bit of this kind of information is available if you ask stan to create diagnostics files (if you're using `rstan`, use the `diagnostic_file = "foo_diag.txt"` or something like that as an argument to the `stan` or `sampling` function.

Then from a command-line, you can read the diagnostics file while stan is running (you don't want to open it in an editor, but `tail` and `grep` can be your friends). I have used this when I was having trouble with model performance, and I would grep for large treedepth or divergent steps to decide when to kill a sampling job that didn't look as though it was making progress.

**Comment by davidmanheim** [comment]
That's great under linux; some of us are stuck on Windows.

**Comment by bob-carpenter** [comment]
Cygwin is your friend on Windows.  It even lets you tail -f
just like on Linux and lets you grep through partially output
files.

- Bob

**Comment by syclik** [comment]
I'm closing this issue for now. We have plans to do better logging in the future, which would take care of this issue.
