### ISSUE TITLE
symmetry in Wishart RNG

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1746]
Andrew reported that the Wishart RNG was returning non-symmetric returns, so we need to either add it to its transpose and divide by 2.  You can see in the code that there's no guarantee that everything's going to be symmetric:

```
     MatrixXd B = MatrixXd::Zero(k, k);
     for (int j = 0; j < k; ++j) {
        for (int i = 0; i < j; ++i)
          B(i, j) = normal_rng(0, 1, rng);
        B(j, j) = std::sqrt(chi_square_rng(nu - j, rng));
      }

      return stan::math::crossprod(B * S.llt().matrixU());
```

* [ ] fix wishart_rng
* [ ] fix inv_wishart_rng
* [ ] check lkj_corr_rng and see if that also needs to be symmetrized

**Comment by andrewgelman** [comment]
Hi, I was also getting the occasional simulated matrix that was not positive definite.  I assume this is roundoff error as well.  I don’t know if this is important enough to worry about, I just wanted to let you know it’s happening on rare occasions.
A

**Comment by bgoodri** [comment]
I believe `lkj_corr_rng` uses `multiply_lower_tri_self_transpose` or whatever it is called, so it should be symmetric. Perhaps `wishart_rng` should too, although it would require its code to be transposed relative to what it is now.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#269
