### ISSUE TITLE
Stan doesn't respect starting values for multiple chains

### ISSUE THREAD

**Issue by RobertMyles** [stan-dev/stan#1757]
Hi stan folks,

First of all, thanks for stan, it's fantastic, and has saved me lots of time, as I was trying to run some ideal-point IRT models with JAGS and it was really slow. However, I'm having some trouble making stan use the initial values that I specify for my model (and initial values are important for these models). The model runs fine, it's a simple model, but never uses the initial values I provide. 

I have tried all the ways suggested in the R help for stan, and two ways are reproduced below in the toy example I provide. With one chain, there is no problem.  

Here's my example and thanks for any help:
(I know it's a short run so error messages pop up about the treesize etc., but it's the initial values problem that I'm interested in)

```library(rstan)
J <- 35
K <- 50
ThetaInit <- rnorm(J, 0, 1)
ThetaInit[1] <- 1.5
ThetaInit[2] <- -1.5
BetaInit <- rnorm(K, 0, 3)
AlphaInit <- rnorm(K, 0, 3)
y <- matrix(rbinom(J*K, size=1, prob=0.5), J, K)

#My real data has plenty of NA, so just to keep the example similar to the real thing:

y[20, 12] <- NA
y[5, 11] <- NA
y[6, 2] <- NA

N <- length(y)
j <- rep(1:J, times=K)
k <- rep(1:K, each=J)

#delete missing values

missing <- which(is.na(y))
N <- N - length(missing)
j <- j[-missing]
k <- k[-missing]
y <- y[-missing]

 #Model

stan.code <- "
data {
  int<lower=1> J;
  int<lower=1> K;
  int<lower=1> N;
  int<lower=1, upper=J> j[N];
  int<lower=1, upper=K> k[N];
  int<lower=0, upper=1> y[N];
}
parameters {
  real alpha[K];
  real beta[K];
  real theta[J];
}
model {
  alpha ~ normal(0,3); 
  beta ~ normal(0,3); 
  theta ~ normal(0,1); 
  theta[1] ~  normal(1, .001);
  theta[2] ~ normal(-1, .001); 
for (n in 1:N)
  y[n] ~ bernoulli(Phi(theta[j[n]] * beta[k[n]] - alpha[k[n]]));
}"

 # Inits
 # function form 2 with an argument named "chain_id"
 # This is copied from ?stan

initf2 <- function(chain_id = 1) {
  # cat("chain_id =", chain_id, "\n")
  list(beta=list(BetaInit), theta=list(ThetaInit), alpha=list(AlphaInit))
} 

 # generate a list of lists to specify initial values
 # Copied from ?stan

n_chains <- 4
init_ll <- lapply(1:n_chains, function(id) initf2(chain_id = id))

stan.data <- list(J=J, K=K, N=N, j=j, k=k, y=y)

stan.fit <- stan(model_code=stan.code, data=stan.data,
 iter=100, warmup=25, chains=4, thin=1,
 init=init_ll, verbose=TRUE, cores=4, seed=1234)

get_inits(stan.fit)
InitList <- get_inits(stan.fit)
Theta1 <- InitList[[1]][3]
Theta2 <- InitList[[2]][3]
Theta3 <- InitList[[3]][3]
Theta4 <- InitList[[4]][3]

Theta1[[1]][1] # all should be exactly 1.5
[1] -0.8131447
Theta2[[1]][1]
[1] 1.644208
Theta3[[1]][1]
[1] 1.42286
Theta4[[1]][1]
[1] 0.3714791
```

**Comment by betanalpha** [comment]
Stan doesn’t print the initial value — you're looking at the first sample
generated from the given initial value.  And if your problem is that
sensitive to the initial value then you should be suspect of the validity
of your inferences!

**Comment by jgabry** [comment]
If `rstan::get_inits` doesn't actually return initial values then I guess we should probably name the function something else or get rid of it.

**Comment by betanalpha** [comment]
Ooh, sorry, I didn’t recognize that it was the RStan specific
“get_inits” function.  Those values look like they’re initialized
and the init values are never being set.

**Comment by jgabry** [comment]
@RobertMyles I'm going to close this since this is an RStan issue rather than Stan proper. I just created a [new issue](https://github.com/stan-dev/rstan/issues/257) for this over on the RStan issue tracker so we'll follow up over there.

**Comment by RobertMyles** [comment]
@betanalpha Oh ok, I see that now. I thought "get_inits" was to see the inits that were fed to the call to stan. As for the sensitivity, it's just a problem with these IRT models as you need to 'pin down' the scale so to speak. 
@jgabry Thanks, I didn't realise there was a specific RStan issue tracker.

**Comment by bob-carpenter** [comment]
I'm not sure what you mean by pinning down the scale.
Do you want to pin down location to deal with multimodality
like a sign invariance?

- Bob

**Comment by RobertMyles** [comment]
Yes Bob, that's exactly what I meant. Taking ideal points of the US Congress as an example, initial values set at opposite ends of the scale (1 and -1 for example) is a simple way to lessen the chances of multimodality, since there's no a priori reason that Republicans would be 1 and Democrats -1 etc. It's not for identification or anything, but speeds up convergence and lessens the chances of seeing 'mirror-image' posterior distributions.

**Comment by bob-carpenter** [comment]
That is a kind of identification issue when there's a sign
invariance --- two different parameter vectors produce the
same data sampling distribution.  

I haven't tried the alternatives with ideal point
models --- setting one item's sign, for instance, and 
letting everything shake out around that.  

Most relevant posterior inferences won't care about the
sign invariance, but the convergence diagnostics and
effective sample size calculations on the non-identified
parameters will.

- Bob

**Comment by RobertMyles** [comment]
That's the problem alright, the Rhat etc are terrible. I usually use inequality constraints in these models, so in  1 dimensional for example, one legislator is constrained to be positive, another negative. All the others get N(0,1) priors and that identifies the model. If I set the initial values in accordance with these constraints (left-wing parties start off at -1 for example), then chains ending up on the 'wrong' side is rare. Or at least it was with JAGS. Another problem is that when I was using truncated distributions for the constrained legislators, (e.g. `theta[1]~N(0,1)T[,0]`), stan would sometimes select starting values outside the constraint, and so gave an error and wouldn't run...another reason I need it to use the starting values I set.

**Comment by jgabry** [comment]
Were you declaring theta[1] with the corresponding bounds in the parameters
block? If not, that should help.

**Comment by bob-carpenter** [comment]
But you can't define a constraint on just theta[1].

You can do this with the new slicing syntax:

  parameters {
    real<lower=0> theta_1;
    vector[N - 1] theta_2_N;

and then use them as:

    vector[N] theta;  // local variable or transformed parameter
    ...
    theta[1] <- theta_1;
    theta[2:N] <- theta_2_N;  // define theta before using it

or do it the old way, which is a bit clunky because we
only support appending vectors (not out of principle, but
because appending scalars hasn't been implemented yet):

  parameters {
    vector<lower=0>[1] theta_1_1;
    vector[N - 1] theta_2_N;

    vector[N] theta;
    theta <- append_col(theta_1_1, theta_2_N);

- Bob

**Comment by jgabry** [comment]
Yeah I guess you'd have to do one of those to deal with the constraints. My
point was just that it would help avoid invalid initial values. I hadn't
thought through it that far yet! The new indexing definitely helps though.
Super useful in general.

**Comment by bob-carpenter** [comment]
> On Jan 23, 2016, at 12:09 AM, Jonah Gabry <notifications@github.com> wrote:
> 
> Yeah I guess you'd have to do one of those to deal with the constraints. My
> point was just that it would help avoid invalid initial values. I hadn't
> thought through it that far yet! The new indexing definitely helps though.
> Super useful in general.

Just need to get it all compiling.  I'll have that fixed
by next week assuming I recover from the snow and Robbie Burns
party prep, party, and party cleanup.

- Bob

**Comment by RobertMyles** [comment]
That new syntax seems interesting. Before, I was using truncations on two of the theta, but it seemed much slower in comparison to just informative priors on the two.
