### ISSUE TITLE
Write CVODE doc

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1765]
Add documentation for `integrate_ode_cvode`.

Add note to look at each interface's documentation for instructions on how to install and use CVODE within the interface itself.

**Comment by bob-carpenter** [comment]
I'm closing this.  I'll add basic doc as part of the next manual issue.  

 The interface issues should be in a different repo.

Writing the algorithms doc for this is longer term;  we don't even have the basic ODE algorithms in the Stan manual, just in the arXiv paper.
