### ISSUE TITLE
remove lp__ from ADVI

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1785]
#### Summary:

ADVI has a vestigial `lp__` value that should be removed.  It's confusing users.

#### Description:

See summary.

#### Reproducible Steps:

This is just how ADVI is designed.

#### Current Output:

Has `lp__`

#### Expected Output:

Shouldn't have `lp__`.

#### Current Version:
v2.9.0

**Comment by dustinvtran** [comment]
The solution is an issue here: https://github.com/stan-dev/stan/issues/1538

**Comment by bob-carpenter** [comment]
If it's rolled into that issue, you can close this one!

- Bob

**Comment by dustinvtran** [comment]
Done :)
