### ISSUE TITLE
Compound and basic assignment operators

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1787]
Implement all the standard compound assignment operators as statements for all of the relevant types.  

For each assignment, we need:
- documentation in manual
- grammar for statements
- code generator
- tests for code generation (? haven't done this most places due to test brittleness)
- test grammars

We also need
- top-level documentation of the BNF
- documentation of the translations in the reference manual, which can follow the issue definition below
### Assign:  `a = b`

Should be a bit more general than what we currently have in order to support integer array promition to real arrays (standard lib vectors in the code).
## Compound Assignment

All types require the translations to be appropriate given assignment above.  The types assigned to the result of operators and all valid argument types are given in the index to the manual.
### Add-assign: `a += b`

Translation `a = a + b;` must be valid addition and assignment.
### Subtract-assign: `a -= b`

Translation `a = a - b;` must be valid subtraction and assignment.
### Multiply-assign: `a *= b`

Translation `a = a * b;` must be valid multiplication and assignment.
### Divide-assign: `a /= b`

Translation `a = a / b;` must be valid division and assignment.
## Beyond C++ Operators

Stan goes beyond C++ and could optionally support these compound operators, but they look a bit like a symbol mash to someone used to the C++ operators.
### Power: `a ^= b`

Translation `a = a ^ b;` must be valid left-division and assignment.
### Left-divide-assign: `a \= b`

Translation `a = a \ b;` must be valid left-division and assignment.
### Elementwise multiply-assign: `a .*= b`

Translation `a = a .* b` must be valid elementwise multiplication and assignment.
### Elementwise divide-assign: `a ./= b`

Translation `a = a ./ b` must be valid elementwise division and assignment.

**Comment by syclik** [comment]
4627ed62 took care of assignment `=`.

**Comment by mitzimorris** [comment]
closing as done - also see https://github.com/stan-dev/stan/pull/2185
