### ISSUE TITLE
Update HMC Diagnostics

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#1790]
#### Description:

Rename divergent iterations and add the value of the Hamiltonian to identify poorly chosen kinetic energies.

#### Current Version:
develop

**Comment by bob-carpenter** [comment]
What is being renamed to what?  Is this user facing?

**Comment by betanalpha** [comment]
Please look at the code — there are only a few file changes.
It’s user facing only if the interfaces change — of course that
has now been left to the interface designers so who the hell
knows?

**Comment by bob-carpenter** [comment]
What code am I supposed to be looking at?  Is there a branch or a pull request?

**Comment by betanalpha** [comment]
Huh?  You were commenting on it earlier. https://github.com/stan-dev/stan/pull/1791
