### ISSUE TITLE
break out language and algorithms/services into their own repos

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1805]
#### Summary:

Break the `stan-dev/stan` repo into two pieces:
- `stan-dev/language`
- `stan-dev/algorithms`
#### Description:

The goal is to separate out logically distinct pieces and make it so that someone can be in charge of each repo logically.

Basically, everything in `src/stan/lang` and `src/stan/model` should go in the first and everything else in algorithms, I believe.  

I think the manual in `language` should be reduced to the language reference manual and `algorithms` should get a manual that describes the algorithms and their arguments in a platform-neutral way.  Then, we can just ditch the rest of the manual for shorter documents.  For now, so as not to lose things before they're ported, I'll break the language user's guide out into its own document, separate from the language spec document.

**Comment by syclik** [comment]
I think the natural thing to do is to:
1. leave `src/stan/lang` and `src/stan/model` in this repo (stan-dev/stan). I think calling the language Stan is a good move. Alternatively, we could call it stan-dev/language
2. move the rest to another repo. stan-dev/algorithms?

**Comment by bob-carpenter** [comment]
We're going the other way toward a monorepo.
