### ISSUE TITLE
_lpdf, _lcdf, _lccdf, _norm suffixes, | separator for functions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1811]
#### Summary:

Probability function suffix cleanup with vertical bar separator.  

#### Description:

* [x] allow _lpdf or _lpmf, _lcdf, _lccdf suffixes for probability functions
    * [x] add to grammars with mangling
    * [x] grammar compile tests
    * [x] doc basic notation
    * [x] change existing doc for all affected functions
* [x] rewrite existing _log suffix functions
    * [x] symbol table
        * [x] `binomial_coefficient_log(M,N)` -> `lchoose(M, N)`
        * [x] `multiply_log(x,y)` -> `lmultiply(x, y)`
    * [x] name mangling in parser
    * [x] deprecation of old forms with suggestion of new forms
    * [x] doc new functions
    * [x] add deprecated functions to deprecation appendix
* [x] add vertical bar separator for lpdf, lpmf, lcdf, lccdf suffixed functions in grammars
    * [x] add to grammars
    * [x] general doc
* [x] deprecate _log, _cdf_log, _ccdf_log suffixes
    * [x] grammar deprecation warning
    * [x] test grammars for warning message
    * [x] doc note
* [x] generate appropriate cdf/ccdf function for truncated sampling statements
* [ ] allow suffixes (or args) in function definition syntax to use | notation (any change required?)
    * [ ] add to grammars
    * [ ] doc
* [ ] add _norm suffix for log densities to turn off propto in generated code
    * [ ] grammars
    * [ ] code generators
    * [ ] general doc
    * [ ] per-function doc

**Comment by sskates2** [comment]
There are multiple places in the Stan Manual 2.10 where dist_lpdf(y | theta1, ..., thetaN) is written as dist_lpdf(y, theta1, ..., thetaN) - i.e. without the vertical bar. The "comma" version results in a parser error.

**Comment by bob-carpenter** [comment]
Thanks.  This issue is closed, so I'm moving this comment to https://github.com/stan-dev/stan/issues/1868#issuecomment-233819787.
