### ISSUE TITLE
Do not imply <- is deprecated in R

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#1819]
#### Summary:
`stanc` implies `<-` is deprecated in R

#### Description:
When you parse a model in R using the develop branches, you see
`Warning (non-fatal): assignment operator <- deprecated; use = instead.`
which does not clarify that `<-` is deprecated in the Stan language rather than the R language.

#### Reproducible Steps:
In R, call
`stan_demo("funnel_reparam")`

#### Current Output:
`Warning (non-fatal): assignment operator <- deprecated; use = instead.`

#### Expected Output:
`Warning (non-fatal): assignment operator <- deprecated in the Stan language; use = instead.`

#### Additional Information:
No

#### Current Version:
develop

**Comment by bob-carpenter** [comment]
Thanks for noticing this.  I'll fix it ASAP.
