### ISSUE TITLE
stream exceptions to stderr

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#1836]
#### Summary:
The develop branch currently streams both progress and informational messages to stdout. The master branch streams progress to stdout and informational messages to stderr, which is preferable. 

#### Description:
The develop branch currently streams both progress and informational messages to stdout. The master branch streams progress to stdout and informational messages to stderr, which is preferable. 

#### Reproducible Steps:
In R (with development versions of StanHeaders and rstan),
```
library(rstan)
sink(file = "/tmp/stdout.txt", type = "output")
post <- stan_demo("inv_wishart", chains = 1) # parser warnings correctly go to stderr
sink(NULL)
q(save = "no")
```
In a shell,
```
grep -F "Informational" /tmp/stdout.txt
```

#### Current Output:
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:

#### Expected Output:
No output

#### Current Version:
v2.10.0

**Comment by syclik** [comment]
@bgoodri, can you take a look at the last push to the stan-dev/rstan repo on the feature/prepare_for_2.10.0 branch? I just installed it, but I don't know how we can test that the output is indeed ok.

**Comment by bgoodri** [comment]
That looks okay, but can we also make it so that print statements go to
stdout instead of stderr; see https://github.com/stan-dev/rstan/issues/288

**Comment by syclik** [comment]
Not at the moment. Those two things have never been separated. For 2.10.0,
let's go with the existing behavior. For the release after that, we'll have
a full blown log-level capable thing in place.

**Comment by syclik** [comment]
I take it back... that last statement wasn't correct, but this is getting
tricky. In order to separate these out, we'll need to get two streams
plumbed in, which will take a while longer. I'll get on it and do that. I
don't even know where the model print happens, but I'll figure it out.

**Comment by bgoodri** [comment]
To make things more complicated, reject statements should continue to go to
stderr.

**Comment by syclik** [comment]
It would help me immensely if you had some sort of test (even informal)
that demonstrated which things need to go where.

And... for the time being, please leave it to existing behavior from 2.9.0.
We'll fix things in general after this release.

Could you provide a sample Stan file and how to run it? I can knock it out
tomorrow if you do provide me with one.

**Comment by bob-carpenter** [comment]
print() statements in Stan programs are printed to the std::ostream*
that's passed in as an argument to any function in the C++ model
class that executes statements (log density evaluation, generated
quantities / write array / construction of transformed data).

- Bob

**Comment by bob-carpenter** [comment]
print statements -> handled through model as "stdout"

exception texts -> handled through "stderr"

The print statements are printed while executing a model class
method.  The exception texts are printed when exceptions are
caught outside of the model class execution.  

reject() statements throw exceptions, so those are exception texts.

There's no other text sources out of a Stan program execution.

There are other texts out of the parser, but that's a separate
issue.

- Bob

**Comment by syclik** [comment]
I've got it figured out. Pull request coming soon.

**Comment by syclik** [comment]
Ben, can you check the current branch (just pushed) for the right behavior?

**Comment by syclik** [comment]
I've updated cvodes and the separation of streams.
