### ISSUE TITLE
Multinomial sampling of NUTS trajectories.

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#1846]
#### Summary:
Change how NUTS samples from each dynamically generated trajectory.

#### Description:
Right now NUTS uses a slice sampler to select each point which is a bit ungainly.  Sampling points multinomially using their Metropolis probabilities will streamline the code and make it easier to experiment with algorithmic generalizations.

#### Current Version:
v2.9.0

**Comment by bob-carpenter** [comment]
Along the entire trajectory including the original point?  And I take it this is the one that's easy to Rao-Blackwellize rather than multinomial sample.  Any a priori theory on how this will compare to the slice sampling?  I don't imagine the normalization for the multinomial is going to be too compute intensive compared to everything else going on.

**Comment by betanalpha** [comment]
> Along the entire trajectory including the original point?
> 
Yes, including the original point is important for avoiding periodicity.
> And I take it this is the one that's easy to Rao-Blackwellize rather than multinomial sample.
> 
That is part of the motivation, although we are very far away from anything close to an implementation.
> Any a priori theory on how this will compare to the slice sampling?
> 
Marginally (over the slice level or multinomial sample) they are the same so they shouldn’t yield
appreciable difference.  Having all of the probabilities at hand is technically more information
but we’re not using that yet.
> I don't imagine the normalization for the multinomial is going to be too compute intensive compared to everything else going on.
> 

No, it’s negligible.

**Comment by bob-carpenter** [comment]
OK, I think you should be in charge of what we do for sampling.
So I'm OK with this change.  I still need to review the code, though.
