### ISSUE TITLE
expose HyperGeometric 2F1

### ISSUE THREAD

**Issue by wds15** [stan-dev/stan#1889]
#### Summary:

Expose the stan math function HyperGeometric 2F1
#### Description:

The 2F1 function is the analytic solution to some ODE systems which are relevant to PK/PD problems and would be very useful to have in Stan.
#### Reproducible Steps:

None.
#### Current Output:

NA
#### Expected Output:

NA
#### Additional Information:

NA
#### Current Version:

v2.9.0

**Comment by syclik** [comment]
@wds15, I don't think we have an implementation of hypergeometric 2F1 in the math library. We definitely have a function for the gradient, though:
- `stan/math/prim/scal/fun/grad_2F1.hpp`

Steps someone will need to take:
1. Create a hypergeometric 2F1 function in the Stan math library
2. Expose the function in the Stan language.

**Comment by wds15** [comment]
@syclik hmmm.... I thought @betanalpha has this function ready. I am not sure if I can provide an implementation as I have no experience with this 2F1 buisness, I was hoping @betanalpha has code ready and we only need to expose it.
