### ISSUE TITLE
neg_binomial errors refer to "phi" as "precision", creating confusion

### ISSUE THREAD

**Issue by jeffalstott** [stan-dev/stan#1890]
When using a `neg_binomial`, the `phi` parameter must be above 0. If, in the modeling process, this parameter goes to 0, we get this error:
`Exception thrown at line 118: stan::prob::neg_binomial_2_log_log: Precision parameter is 0, but must be > 0!`

This error message calls phi "precision". That's not helpful! Not knowing what the error was about, I had assumed that the "precision" parameter had something to do with numerical precision. The negative binomial literature doesn't typically use the name "precision" to refer to phi. I only pieced together the error message was referring to phi from this old issue: https://github.com/stan-dev/stan/issues/786

I suggest the error message be changed. If there is some mathematical connection between phi and the concept of precision, and thus one wants to still refer to phi as "precision", perhaps replace the current error with `Precision parameter phi is 0...`.

#### Current Version:
v2.9.0

**Comment by bob-carpenter** [comment]
The name "precision" is not applied to the variable phi in general;  it's the role played by the argument.  

The doc in the manual says:

```
real neg_binomial_2_log(ints y, reals mu, reals phi)
The negative binomial probability mass of n given location mu and precision phi.
```

It may also be helpful to add the identifier for the parameter (here, "phi").

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#297

**Comment by syclik** [comment]
This was moved to the math repo.
