### ISSUE TITLE
Non-compiling C++ interface for general models

### ISSUE THREAD

**Issue by jakebiesinger** [stan-dev/stan#1891]
#### Summary:
Feature Request: Provide a C++ interface that injests test models and produces an actual C++ class rather than a .cc and .h file with a C++ class in it.

#### Description:
Many environments don't have access to build tools in production, and therefore can't generate and compile new code on the fly.  Wrapping Stan in any kind of production server seems impossible at a first glance... I'd like to hit said server with a Stan text model description and some example data, and want the server to fit params to the data, do prediction, etc.

I haven't dug much into the code, but all the documentation refers to generated source code.  The generated source code itself doesn't seem all that fancy, so it seems like it could be generalized into a simple, more generic interface... a Stan model factory that generates objects instead of source.

Perhaps this already an undocumented thing?

#### Current Version:
v2.9.0

**Comment by sakrejda** [comment]
Any Stan model factory would still have to take a Stan program, generate C++, compile C++, and then call the resulting library.  In practice there is a path for this that's all-C++ using clang++'s API.  I haven't had the time to pursue it but it's on my long-term list (and will likely stay there till August...)

**Comment by jakebiesinger** [comment]
Bummer. What is it about the compilation step that makes it impossible to
generate a generic object? Send like the member variables in the generated
source files I've seen could be captured by lists or maps of vectors and
operations, though admittedly I've only done a few simple models.

**Comment by sakrejda** [comment]
The Stan program encodes a specific density (and gradient) calculation... I'm pretty sure there is no way to get around that but I'm not the one who's thought about it the most.  If you see a way of getting around that go ahead and flesh out the issue some more, we love help!

**Comment by betanalpha** [comment]
The Stan compiler generates a single .hpp file (not a header and source separately)
defining a model object which exposes the log probability and various utility functions.
This then gets compiled into an executable that uses that object in inference algorithms
depending on the interface.  As Krzysztof notes, there’s no way to avoid having to
compile this, and without an interface there’s no concept of an “object” that can be
passed around without compilation.

In the various interfaces there are ways to compile executables and reuse them,
which would allow you to deploy the executable itself into a production environment.
But that is a matter for the interfaces, not the Stan API.

**Comment by bob-carpenter** [comment]
It would technically be possible to write an interpreter
for Stan.  Right now, it's a compiled language.  There's
a big performance hit compared to compiling, especially given
how we're compiling, but it would be possible.  My very very
rough guess for time it'd take would be about a programmer-year
with high ongoing maintenance costs.  So unless someone with their
own funding wants to do this (we'd be glad to help), it's not
likely to get done.

- Bob

**Comment by syclik** [comment]
Closing this since there's no real way we can move forward on this issue.
