### ISSUE TITLE
filtering_stream.hpp generates 'deprecated' notes

### ISSUE THREAD

**Issue by tvanriper** [stan-dev/stan#1903]
#### Summary:

In Boost 1.61, if you #include <boost/iostreams//filtering_stream.hpp>, your compiles will receive three deprecation notices: one for boot_trait_def.hpp, and two for template_arity_spec.hpp.
#### Description:

In Boost 1.61, when you include boost/iostreams/filtering_stream.hpp, it includes detail/push.hpp, which includes detail/resolve.hpp, which includes detail/is_dereferenceable.hpp, which includes two header files that are apparently intended to be deprecated in some future version of the boost library.

These are:

bool_trait_def.hpp,
template_arity_spec.hpp
#### Reproducible Steps:

Create any sort of main.cpp, and at the top, #include <boost/iostreams/filtering_stream.hpp>.  Compile this (with the usual bits to tell the compiler where to find boost) and you should see the problem.
#### Current Output:

```
In file included from /build/sdks/b1_61/include/boost/iostreams/detail/is_dereferenceable.hpp:12:0,
                 from /build/sdks/b1_61/include/boost/iostreams/detail/resolve.hpp:26,
                 from /build/sdks/b1_61/include/boost/iostreams/detail/push.hpp:24,
                 from /build/sdks/b1_61/include/boost/iostreams/filtering_stream.hpp:19,
                 from service.hpp:41:
/build/sdks/b1_61/include/boost/type_traits/detail/bool_trait_def.hpp:18:79: note: #pragma message: NOTE: Use of this header (bool_trait_def.hpp) is deprecated
 # pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
                                                                               ^
In file included from /build/sdks/b1_61/include/boost/type_traits/detail/bool_trait_def.hpp:21:0,
                 from /build/sdks/b1_61/include/boost/iostreams/detail/is_dereferenceable.hpp:12,
                 from /build/sdks/b1_61/include/boost/iostreams/detail/resolve.hpp:26,
                 from /build/sdks/b1_61/include/boost/iostreams/detail/push.hpp:24,
                 from /build/sdks/b1_61/include/boost/iostreams/filtering_stream.hpp:19,
                 from service.hpp:42:
/build/sdks/b1_61/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
                                                                                    ^
In file included from /build/sdks/b1_61/include/boost/iostreams/detail/is_dereferenceable.hpp:13:0,
                 from /build/sdks/b1_61/include/boost/iostreams/detail/resolve.hpp:26,
                 from /build/sdks/b1_61/include/boost/iostreams/detail/push.hpp:24,
                 from /build/sdks/b1_61/include/boost/iostreams/filtering_stream.hpp:19,
                 from service.hpp:42:
/build/sdks/b1_61/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
```

```
                                                                                ^
```
#### Expected Output:

I should not see any of the above.
#### Additional Information:

I saw this in 1.60 as well, but expected someone was working on something towards 1.61 and accidentally pulled a tad more than expected for 1.60.  Now that boost has released 1.61, and I still see this, it seems appropriate to raise a flag.
#### Current Version:

v1.61

**Comment by syclik** [comment]
Thanks! This is immensely helpful. Do you know what we need to include to
avoid these?

We've spent some time trying to squash the warnings, but we haven't been
successful.

**Comment by bob-carpenter** [comment]
Boost's been having problem squashing the deprecations.
So these might not be fixable on our end --- related issues
were not fixable in Boost 1.60.

**Comment by tvanriper** [comment]
I've tried to find some kind of document to specify what one should do to address this, but I can't see anything.

Perhaps that's another ticket for someone to track in boost.type_traits?

**Comment by bob-carpenter** [comment]
Thanks for reporting, but this is a Boost issue we can't easily control.  They keep introducing these issues in releases and fixing ones in previous releases, but we don't want to change the Boost library (and in fact can't in R because we just depend on the BH package which isn't under our control).  So I'm closing this.
