### ISSUE TITLE
print() is broken when there is a rejection/exception in the model block

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1936]
#### Summary:

see title

#### Description:

see summary;  we can't debug models with print with this broken.

#### Reproducible Steps:

```
parameters {
  real y;
}
model {
  y ~ normal(0, 1);
  if (y < 0) {
    print("foo"); 
    reject("bar");
  }
}
```

#### Current Output:

When I run in CmdStan, I get:

```
...
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 8: bar
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,

but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 8: bar
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,

but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Iteration: 2000 / 2000 [100%]  (Sampling)

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 8: bar
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,

but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

 Elapsed Time: 0.095294 seconds (Warm-up)
               0.134391 seconds (Sampling)
               0.229685 seconds (Total)
```

#### Expected Output:

I expected to see "foo" being printed.  

#### Additional Information:

I believe this is a problem origininating in Stan itself as it shows up in all the interfaces.

#### Current Version:
v2.9.0

I think we need to fix this and can't wait for a refactoring to do it for us.

**Comment by betanalpha** [comment]
I’ve run across this a few times — does it have to do with
where print places print statements within the various
model member functions?

**Comment by bob-carpenter** [comment]
I'm not sure what the problem is.  The print statements
themselves just stream to the output streams.  Why they're
being buffered rather than printed is mysterious to me.

- Bob

**Comment by syclik** [comment]
I'll dig. This is definitely high priority and maybe we'll release a
v2.10.1 soon if we can find it.


Daniel

**Comment by bob-carpenter** [comment]
There's a bunch of stuff that got left behind at 2.10
that we could roll out relatively quickly if there
aren't more major algorithm and language changes (which I
can see are having repercussions upstream with things like
expose-stan-functions).

- Bob

**Comment by syclik** [comment]
I'm leaving a note behind for myself. It's in `initialize_state.hpp` inside the `initialize_state_values()` function.
