### ISSUE TITLE
rethrow_located issue with ios_base::failure

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1937]
Moved from:  https://github.com/stan-dev/rstan/issues/298

#### Summary:

clang++3.8 (at least) yields a linker error when compiling a model

#### Description:

You can an undefinied symbol from the mangled version of
`std::ios_base::failure::failure(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`

The solution is to remove the `ios_base::failure` case from `rethrow_located` and just let it be absorbed into the general default case.

#### Reproducible Steps:

Call `stan_model` on anything when clang++-3.8 is the compiler

#### Current Output:

```
Error in dyn.load(libLFile) : 
  unable to load shared object '/tmp/Rtmp3EYkrl/filebab4ea0765b.so':
  /tmp/Rtmp3EYkrl/filebab4ea0765b.so: undefined symbol: _ZNSt8ios_base7failureC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

#### Expected Output:
None

#### RStan Version:
2.9.0-3

#### R Version:
3.3.0

#### Operating System:
Debian

**Comment by bgoodri** [comment]
Can we slide the fix for this into the emergency release?

**Comment by syclik** [comment]
@bgoodri, can you create a pull request?

**Comment by bgoodri** [comment]
Yes, if the fix is merely to delete those two lines. Not sure if
@bob-carpenter was planning on doing something more elaborate.

**Comment by bob-carpenter** [comment]
Nope --- I just let the default case catch it instead,
so we'll lose the type but not the message.  I don't know
that one ever came up, I just wrote the class to cover
everything built into C++03.

- Bob
