### ISSUE TITLE
User defined function ending in _lpdf used with target+= parses but fails to compile

### ISSUE THREAD

**Issue by jrnold** [stan-dev/stan#1944]
#### Summary:

I was attempting to compile a model using `target += ` with a user function ending in `_lpdf`. The model parses without issue, but produces an error during compilation.

#### Reproducible Steps:

This was an attempt to try using my new state space functions to answer a question in [Stan Users](https://groups.google.com/d/msg/stan-users/-7zCbzPXH5w/5Eyj7xg0CQAJ). The code of the model and data I used is in [this github repo](https://github.com/jrnold/ssmodels-in-stan/tree/e85a663859f3c032816b4bf37f7738e4b98b994d/examples/linear_trends_ar2). The generated cpp code is in [linear_trend_ar2.cpp](https://github.com/jrnold/ssmodels-in-stan/blob/e85a663859f3c032816b4bf37f7738e4b98b994d/examples/linear_trends_ar2/linear_trend_ar2.cpp). This stan model [linear_trend_ar2.stan](https://github.com/jrnold/ssmodels-in-stan/blob/e85a663859f3c032816b4bf37f7738e4b98b994d/examples/linear_trends_ar2/linear_trend_ar2.stan) includes functions from [ssm.stan](https://github.com/jrnold/ssmodels-in-stan/blob/e85a663859f3c032816b4bf37f7738e4b98b994d/stan/includes/ssm.stan).

#### Current Output:

It fails to compile and gives this error message:
```
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! file149441cbeaa17.cpp:4427:32: error: use of undeclared identifier 'ssm_constant_log'
                lp_accum__.add(ssm_constant_log(y,c,Z,H,d,T,R,Q,a1,P1));
                               ^
/Library/Frameworks/R.framework/Versions/3.3/Resources/library/StanHeaders/include/src/stan/model/util.hpp:240:21: note: in instantiation of function template specialization 'model149447ff6b083_2b9a09a80692cb0c734884b5536d637a_namespace::model149447ff6b083_2b9a09a80692cb0c734884b5536d637a::log_prob<false, true, double>' requested here
          .template log_prob<propto,
                    ^
/Library/Frameworks/R.framework/Versions/3.3/Resources/library/StanHeaders/include/src/stan/model/util.hpp:296:7: note: in instantiation of function template specialization 'stan::model::finite_diff_grad<false, true, model149447ff6b083_2b9a09a80692cb0c734884b5536d637a_namespace::model149447ff6b083_2b9a09a80692cb0c734884b5536d637a>' requested here
In addition: Warning message:
running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB file149441cbeaa17.cpp 2> file149441cbeaa17.cpp.err.txt' had status 1 
```

#### Expected Output:

I expected it to compile.

#### Current Version:

Rstan v2.10.1

Here's the R session info
```
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] testthat_1.0.2       httr_1.2.0           rprojroot_1.0-2     
[4] lubridate_1.5.6      dplyr_0.5.0          rstan_2.10.1        
[7] StanHeaders_2.10.0-2 ggplot2_2.1.0       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5      formatR_1.4      git2r_0.15.0     plyr_1.8.4      
 [5] tools_3.3.0      digest_0.6.9     evaluate_0.9     memoise_1.0.0   
 [9] tibble_1.0       gtable_0.2.0     rstudioapi_0.6   shiny_0.13.2    
[13] DBI_0.4-1        yaml_2.1.13      curl_0.9.7       gridExtra_2.2.1 
[17] withr_1.0.2      stringr_1.0.0    knitr_1.13.1     devtools_1.12.0 
[21] stats4_3.3.0     grid_3.3.0       inline_0.3.14    R6_2.1.2        
[25] rmarkdown_0.9.6  bookdown_0.0.73  servr_0.4        magrittr_1.5    
[29] scales_0.4.0     htmltools_0.3.5  rsconnect_0.4.3  assertthat_0.1  
[33] xtable_1.8-2     mime_0.4         colorspace_1.2-6 httpuv_1.3.3    
[37] stringi_1.1.1    miniUI_0.1.1     munsell_0.4.3    crayon_1.3.2    
```

**Comment by bob-carpenter** [comment]
Thanks.  I'll fix for the next release.

**Comment by bob-carpenter** [comment]
You should be able to work around by using the old syntax.

**Comment by jrnold** [comment]
Thanks!

**Comment by bob-carpenter** [comment]
Not a general problem because this compiles just fine:

```
functions {
  real foo_lpdf(real x, real y) {
    return -x^2 / y^2;
  }
}
parameters {
  real y;
}
model {
  y ~ foo(7.0);
}
```

The example @jrnold provided is RStan specific with the `#include` syntax, but I'll try to simplify to an example that we can include.

**Comment by bob-carpenter** [comment]
This simple example fails, so it's usage of the `_lpdf` form as a function that's a problem:

```
functions {
  real foo_lpdf(real x, real y) {
    return -x^2 / y^2;
  }
}
parameters {
  real y;
}
model {
  target += foo_lpdf(y | 7.0);
}
```

**Comment by bob-carpenter** [comment]
I have a fix for this one in process.

**Comment by jrnold** [comment]
That was my experience as well: for a user defined function `foo_lpdf`, using `y ~ foo(...)` works, but `target += foo(y | ...)` fails and tries to look for `foo_log`.
