### ISSUE TITLE
User defined functions with same names as built in functions not caught 

### ISSUE THREAD

**Issue by jrnold** [stan-dev/stan#1947]
#### Summary:

A single user-defined function that shares a name with a built-in function compiles as long as that function does not have the one of the signatures of the built-in function.
 
#### Description:

I didn't think that user defined functions supposed to be allowed to share names with built-in functions. However, it seems that if the the user defines **one** function with the same name as a built-in function but a different signature, the model will parse, compile, and run. However, if the function either shares a signature with the built-in function, or a second function with the same name is declared in the functions block, the parser catches it. Is this the intended behavior? 

#### Reproducible Steps:

This model will compile and run
```stan
functions {
  void sum() {
    print("hello, world!");
  }
}
model {
  sum();
}
```

However, the next two models do not.
If  `sum` is defined twice in the user-defined function block the parser catches the error,
```stan
functions {
  void sum() {
    print("hello, world!");
  }
  real sum(real a) {
    return a;
  }
}
model {
  real foo;
  sum();
  foo = sum(0.0);
}
```
```stan
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

Parse Error.  Function already defined, name=sum
ERROR at line 8

  6:        return a;
  7:      }
  8:    }
        ^
  9:    model {
```
And if `sum` is defined with an existing signature it also produces an error,
```stan
functions {
  real sum(vector a) {
    return 1.0;
  }
}
model {
  real foo;
  foo = sum(rep_vector(0.0, 1));
}

```
```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
Parse Error.  Function system defined, name=sum
ERROR at line 5

  3:        return 1.0;
  4:      }
  5:    }
        ^
  6:    model {
```
#### Current Output:

See above.

#### Expected Output:

Even though it compiles, I find the existing behavior confusing and counterintuitive.

#### Current Version:
v2.10.0

**Comment by betanalpha** [comment]
The user-defined functions generate C++ functions with modified names
that distinguishes them from the built-in functions underneath the hood.
But that modified name is the same for any user-defined function regardless
of signature, so you can’t overload user-defined functions at all.

That explains what you’re seeing, and I could be convinced to have a lookup
against built-in functions (although there are subtleties, as the names in the
Stan language and the parsed C++ are not always the same).

**Comment by bob-carpenter** [comment]
What happened is that I intended to allow the usual
overloading everywhere.  So you can't have ambiguous
functions (two functions with the same signature).

But what happened is that user-defined functions generate
functors, and the functors wind up causing name clashes
at the class level I haven't sorted out yet.  So if you
name a function after a built-in, there's no clash, because
the built-ins don't have functors.

The functors are there to support ODE solving.  The goal's
to eventually allow everything to be overloaded, so I
don't think this is really an issue.

- Bob

**Comment by jrnold** [comment]
I didn't really think it's an issue. I came across this while trying to write a model that would produce a parser error to test something on syntax highlighting and was surprised that it didn't produce. So I thought I'd let you know in case it was an oversight.
