### ISSUE TITLE
Compound declaration / definition statements

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#1951]
#### Summary:
Allow compound declaration/definition statements such as:   
```
real x = 1.0;
```

#### Description:
For any variable that is assignable, allow assignment to be combined with the variable definition.
Assignable variable are local variables and variables declared in the transformed data, transformed parameters, and  generated quantities blocks.

#### Current Version:
v2.10.0

**Comment by mitzimorris** [comment]
Requires changes to both parsing and code generation.  The current Stan code generator component generates corresponding initialization statements for the variable declarations.
Instead, this will require that a default value is assigned to all variables at definition time.

**Comment by bob-carpenter** [comment]
Ideally, we'd issue a warning if a variable was used before it was defined.  But we can't require definitions to accompany declarations without breaking backward compatibility.

**Comment by bgoodri** [comment]
Once this is implemented, I still think we should at least have an annoying parser warning if a variable is declared without being defined on the same line.

**Comment by bgoodri** [comment]
Also, it would be good if we could relax the requirement that declarations have to come at the top of a block.

**Comment by bob-carpenter** [comment]
Yes, relacing the top-of-block requirement is probably also
a good idea.  Maybe we could make that a separate issue?  It's
a bit more confusing with the transformed data, transformed parameters,
and generated quantities, as then it might not be clear to users what's
getting printed out.  But we should be able to do it and maintain
backward compatibility for working programs.
