### ISSUE TITLE
new reference for tutorial paper

### ISSUE THREAD

**Issue by hohenstein** [stan-dev/stan#1965]
#### Summary:
A Stan tutorial was updated and the reference has to be modified.

#### Description:

A currently listed Stan tutorial was modified and accepted for publication. Hence, the reference for the tutorial paper should be modified to link to the newest version.

The tutorial references can be found at:
http://mc-stan.org/documentation/

The current reference:

Tanner Sorensen and Shravan Vasishth (2015) A tutorial on fitting
Bayesian linear mixed models using Stan. 2015. University of Postdam.
Earlier draft, arXiv: 1506.06201.

The new reference:

Tanner Sorensen, Sven Hohenstein, and Shravan Vasishth. Bayesian
linear mixed models using Stan: A tutorial for psychologists,
linguists, and cognitive scientists. Quantitative Methods for
Psychology, 2016. In Press. URL: bit.ly/HLMtutorial

#### Current Version:
v2.10.0

**Comment by bob-carpenter** [comment]
Thanks.  When the paper's actually available from the publisher, please submit an issue (or even better, a pull request), to our web site repo:

https://github.com/stan-dev/stan-dev.github.io

This is the general Stan repo, so I'm going to close this issue.
