### ISSUE TITLE
Expose chain_id to Stan programs

### ISSUE THREAD

**Issue by wds15** [stan-dev/stan#1968]
#### Summary:
expose chain id as variable to Stan programs

#### Description:
In some applications it would be useful to have the chain id available in a running Stan program. Essentially this allows to create a big, single data set and select in the Stan program a sub set of the input data to be processed in a given chain.

#### Reproducible Steps:
Currently one has to copy the data set for each started chain and include the chain number as data. This is a nasty workaround as it results in many copies of the data.

#### Current Output:
Its not there yet.

#### Expected Output:
Have a variable "chain_id" defined in the Stan program which is the chain id.

#### Current Version:
v2.10.0

**Comment by bob-carpenter** [comment]
1.  We are not going to expose new variables.  It would be a function `chain_id()`

2.  If we have the transformed data vary according to chain ID, then we'll still have to copy everything.  The data is stored as member variables in the model class, and if it needs to vary across chains, we'll have to copy everything anyway.

* allow in transformed data or not; including it in transformed data means no multi-threading because we can't share a single instantiated model among threads

**Comment by betanalpha** [comment]
I really don’t like exposing chain_id in the models as it breaks
the encapsulation of the model and the surrounding algorithms.

If data needs to be separated that really should be done
externally in the interfaces and then run in separate calls
to Stan.

**Comment by wds15** [comment]
@bob-carpenter : A function would be just fine. I intent to use S draws for each chain. For that I generate a matrix S x C (as data) when C is the maximum number of chains I run. In each given chain I just select the correct column. This way I get S draws which are different from chain to chain.

@betanalpha Not sure if I get this point... I would just like to avoid copying data around. How about enabling multiple input files for cmdstan instead? This would also solve the problem elegantly by allowing to specify a data-file which is the same across all chains and a chain specific one in addition. Is that better?

Maybe we discuss this next Stan meeting.

**Comment by syclik** [comment]
Multiple input files would be the easiest thing to do. In order to provide
the chain id as a function, we'll need to pass that info around somehow.
It's not a property of the Stan program. It can be done, but it'll take
some effort, I think.


Daniel

**Comment by bob-carpenter** [comment]
When we run multiple chains, we copy all the data anyway.  It'd
require a cross-platform multi-threading solution to avoid copying
data.  And that would slow down autodiff by about 20% based on our
early evaluations, but that was many compiler versions ago.  The
only way I know how to do this is to make the global autodiff
stack thread local.

I'm also sympathetic to Michael's point, which is that the
abstraction of the model class right now does not depend on
the chain ID.  Every time we add more bells and whistles like
this, we break simple invariants on the classes, which makes
everything harder to reason about and adds long-term maintenance
overhead to all of the internals and interfaces.  So I'd rather
avoid that if all possible

- Bob

**Comment by wds15** [comment]
As discussed during the meeting there appears not to be any use case by others. As I can work around this by some scripting, I am closing this issue.
