### ISSUE TITLE
multiple lower and upper bounds for constraints

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1971]
#### Summary:

Allow vectors and arrays for lower and upper bound constraints.
#### Description:

Support

```
data {
  ...
  real a[K];
  real<lower=a> b[K];  // a[k] <= b[k]

parameters {
  real<lower=a> x[K];
  real<upper=b> y[K];
  real<upper=a, upper=b> z[K];
```

Step 1.  Allow 1D containers to act as bounds for 1D containers.
Step 2.  Matrix containers with matrix bounds.
Step 3.  Deeper arrays with matching types

**Comment by bgoodri** [comment]
No. I think there is little chance of it happening before the refactoring to allow tuples to get it.

**Comment by bob-carpenter** [comment]
This has been medium to low priority for a long time because there's a fairly easy workaround given in the manual.  We would like to do it, though Ben's right it'll be after the new refactor, which I'm reviewing now.

**Comment by rok-cesnovar** [comment]
Done in https://github.com/stan-dev/stanc3/pull/552
