### ISSUE TITLE
integer division by zero isn't caught

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1974]
#### Summary:

Integer divide by zero throws an uncaught exception.

#### Description:

Running this crashes RStan:

```
library(rstan)

mc <- '
parameters {real theta;}
model {
  target += 1/0;
}
'
sm <- stan_model(model_code = mc)
post <- sampling(sm, show_messages = FALSE)
```

I'm reporting in Stan because in the command refactor, we'll be catching this in Stan itself.

#### Reproducible Steps:

See above.

#### Current Output:

Crashes with `Floating point exception: 8

#### Expected Output:

Informative error message.

#### Additional Information:

Originally reported by @davharris on RStan tracker in issue https://github.com/stan-dev/rstan/issues/316

#### Current Version:
v2.10.0

**Comment by syclik** [comment]
The problem is in math:
https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/fun/divide.hpp#L25

This line has undefined behavior:
```
return std::div(x, y).quot;
```

I didn't realize it threw an exception outside of the `stdexcept` types. Any suggestions on how to fix this call?

**Comment by bob-carpenter** [comment]
Overload for int and check for zero in denominator?

Do you know what it does throw?  If so, you could catch
and rethrow.

- Bob

**Comment by syclik** [comment]
The internet is saying check for 0, so that's the fix I'll apply.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#321
