### ISSUE TITLE
Model compilation error for log function with integer data

### ISSUE THREAD

**Issue by wrobell** [stan-dev/stan#1997]
This is for Stan ver. 2.11.0 run with gcc 6.1.1.

Please consider the following R code with the mines disaster model from the manual

```
library(rstan)

code = '
data {
    real<lower=0> r_e;
    real<lower=0> r_l;
    int<lower=1> T;
    int<lower=0> D[T];
}
transformed data {
    real log_unif;
    log_unif = -log(T);
}
parameters {
    real<lower=0> e;
    real<lower=0> l;
}
transformed parameters {
    vector[T] lp;
    {
        vector[T+1] lp_e;
        vector[T+1] lp_l;
        lp_e[1] <- 0;
        lp_l[1] <- 0;
        for (t in 1:T) {
            lp_e[t + 1] <- lp_e[t] + poisson_lpmf(D[t] | e);
            lp_l[t + 1] <- lp_l[t] + poisson_lpmf(D[t] | l);
        }
        lp <- rep_vector(log_unif + lp_l[T + 1], T) + head(lp_e, T) - head(lp_l, T);
    }
}
model {
    e ~ exponential(r_e);
    l ~ exponential(r_l);
    target += log_sum_exp(lp);
}
'

ch.model = stan_model(model_code=code)
```

The model compilation fails with error
```
filec1645817e3.cpp:92:49: error: call of overloaded ‘log(int&)’ is ambiguous
             stan::math::assign(log_unif, -(log(T)));
```

IMHO, each value passed to `log` should be converted to double, i.e.
```
stan::math::assign(log_unif, -(log((double) T)));
```

**Comment by syclik** [comment]
Hi @wrobell, this is a duplicate issue of stan-dev/math#327. We're having some difficulty compiling with gcc 6. The current workaround is to use a different compiler. Most of them work -- gcc 6 is the only (known) compiler for which this doesn't work.

We'll patch the math library so it works for gcc 6, but we're still working on it.

**Comment by wrobell** [comment]
Thanks for the info. Changing compiler is a bit nuclear option. ;)

Any suggestion which part of Stan code could be patched to make it work?

**Comment by syclik** [comment]
I'm not sure off the top of my head. The fastest way forward is to
reinstall 2.9.
