### ISSUE TITLE
typo in change point model in stan manual 

### ISSUE THREAD

**Issue by wrobell** [stan-dev/stan#1998]
In stan-reference-2.11.0.pdf at page 132
```
lp[s] = lp[s] + poisson_lpmf(D[t] | t < s ? e : l));
```

I believe it should be
```
lp[s] = lp[s] + poisson_lpmf(D[t] | (t < s ? e : l));
```
 (the "(" inserted before "t < s")

**Comment by syclik** [comment]
@wrobell, thanks! I added it as a comment on the running manual issue, #1868.
