### ISSUE TITLE
Wrong answers when fitting a multivariate normal

### ISSUE THREAD

**Issue by GGMeyers** [stan-dev/stan#2002]
Request Canceled

**Comment by GGMeyers** [comment]
I took a second look at the script and comment software messed up the expression for Sigma[1,2]
It should read Sigma[1,2]=rho*sqrt(sigsq1*sigsq2)

**Comment by GGMeyers** [comment]
It did it again  rho (times) the square root of (sigsq1 (times) sigsq2)

**Comment by bob-carpenter** [comment]
There's no longer an issue here.  Did you want to close this?  Are you using 2.11 rather than 2.10?

**Comment by GGMeyers** [comment]
Please close.  There was a bug on my account. 

I think it is great that you are on top of this so quickly. 

Glenn
