### ISSUE TITLE
indexing type error message is inaccurate

### ISSUE THREAD

**Issue by davharris** [stan-dev/stan#2003]
#### Description:

If I accidentally try to use a real for indexing (instead of an int), the parser fails with `PARSER EXPECTED: "]"`.  

A type error would be more informative/accurate, I think.

#### Reproducible Steps:

This model is slightly silly, but it produces the relevant error:

```
data {
  real y[2];
}
model {
  y[1.0] ~ normal(0, 1);
  y[2.0] ~ normal(0, 1);
}
```

#### Current Output:
```
PARSER EXPECTED: "]"
Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
  failed to parse Stan model 'problem' due to the above error.
```

#### Expected Output:
A type error

#### Current Version:
v2.11

**Comment by bob-carpenter** [comment]
The message is technically correct in that it's expecting the `]` after the `1` and before the `.`.  I'll have to change the strategy to accept a primitive and then throw a message if it's `real` rather than `int`.

**Comment by davharris** [comment]
Thanks Bob!

I don't think it's quite as simple as expecting the `]` before the `.`, since the same issue can happen when there aren't any explicit decimal points (see below).  It could still be what's going on under the hood, though, if `real i = 1` gets converted to `1.0` internally.

```
data {
  real y[2];
}
model {
  real i;
  i = 1;
  y[1 + i] ~ normal(0, 1);
}
```

**Comment by bob-carpenter** [comment]
OK, we're getting the "must be integer" message, but also
the expecting "]" later as the point cause of failure

That must be a backtracking case where it
goes back and tries to treat it as an empty
multi-index.  I need to do the Prolog equivalent of cut
after finding the first expression and fail if it's
not an integer and just say I was expecting an integer.

- Bob

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

index must be integer; found type=real

ERROR at line 7

  5:      real i;
  6:      i = 1;
  7:      y[1 + i] ~ normal(0, 1);
            ^
  8:    }

same for the 1.0 case:

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

index must be integer; found type=real

ERROR at line 7

  5:      real i;
  6:      i = 1;
  7:      y[1.2] ~ normal(0, 1);
            ^
  8:    }



I've been fixing these as I go to try to make the messages
more reasonable, so I think I can close this one unless you're
seeing something different in a release soemwhere.

**Comment by davharris** [comment]
>I've been fixing these as I go to try to make the messages more reasonable, so I think I can close this one unless you're seeing something different in a release soemwhere.

Okay, cool. Thanks for looking into it.

**Comment by bob-carpenter** [comment]
I'll try to fix with a rewrite so that it figures out the type of expression and if it's not a primitive integer, provides a better warning and removes the "expecting ]" bit.
