### ISSUE TITLE
Replacement of a deprecated function does not work

### ISSUE THREAD

**Issue by GGMeyers** [stan-dev/stan#2011]
#### Summary:
Please provide a short couple sentence summary.
Replacing the "normal_log" function with "normal_lpdf" does not work.

I copied the output from the 

#### Description:
Describe the issue as clearly as possible.
I just updated my rstan package this morning and got the news of the deprecated functions

#### Reproducible Steps:
R output after I fixed the "=" and "_lpdf" functions I got the console output below

After the error I reinstated the following R script and reran it.
++ replaced R script
for (i in 1:55) log_lik[i] = normal_log(logloss[i],mu[i],sig[d[i]]);
++ end of replaced R script
After the warning, It ran normally.

+++++R Console output
> source('~/Dropbox/Dependencies in SLR Models/ZDTest/CSR Bivariate Model 1Step.R')
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

ERROR at line 46

 44:    generated quantities{
 45:      vector[55] log_lik;
 46:    for (i in 1:55) log_lik[i] = normal_lpdf(logloss[i],mu[i],sig[d[i]]);
                                                ^
 47:    }

PARSER EXPECTED: <probability function arguments>
Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  failed to parse Stan model '177b6f674fa0af7d59af2b39ec775b82' due to the above error.
> source('~/Dropbox/Dependencies in SLR Models/ZDTest/CSR Bivariate Model 1Step.R')
DIAGNOSTIC(S) FROM PARSER:
Warning: Deprecated function 'normal_log'; please replace suffix '_log' with '_lpdf' for density functions or '_lpmf' for mass functions
Warning: Deprecated function 'normal_log'; please replace suffix '_log' with '_lpdf' for density functions or '_lpmf' for mass functions
+++++++End of R console output

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.11.0

**Comment by bob-carpenter** [comment]
Thanks for reporting, but could you please include the Stan model that produces the problem for you?  That dropbox link was to your own computer.

**Comment by bob-carpenter** [comment]
I went and tried to recreate an issue with `_lpdf` and realized you didn't update to the new density syntax.  What you want to use is this:

```
generated quantities {
  real y;
  y = normal_lpdf(0 | 1, 2);
}
```

with the vertical bar.  So I'm going to close the issue pending a reproducible error that follows our syntax.
