### ISSUE TITLE
NaN derivative in square(sqrt(x)) in model local variable

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#203]
Simon Barthelmé reported  via the stan-users list.  I simplified the reported model to this minimal instance:

```
parameters {
  real x;
}
model {
  real y;
  y <- sqrt(square(x-x));

  x ~ normal(0,1);
}
```

As Simon correctly diagnosed, this model causes a problem with autodiff, as can be seen when running from RStan 1.3:

```
TESTING GRADIENT FOR MODEL 'barthelme2' NOW (CHAIN 4).

TEST GRADIENT MODE

 Log probability=-0.0571533

 param idx           value           model     finite diff           error
         0       -0.338093             nan        0.338093             nan
```

First step is to move this into a unit test that displays the behavior.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#21
