### ISSUE TITLE
src/test/unit/lang/rethrow_located_test.cpp segfaults

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2030]
#### Summary:

src/test/unit/lang/rethrow_located_test.cpp segfaults when calling test_rethrow_located_2() on Ubuntu with g++-5.4

#### Description:

src/test/unit/lang/rethrow_located_test.cpp segfaults when calling test_rethrow_located_2() on Ubuntu with g++-5.4

#### Reproducible Steps:

`./runTests.py src/test/unit/lang/rethrow_located_test.cpp`

#### Current Output:

```
test/unit/lang/rethrow_located --gtest_output="xml:test/unit/lang/rethrow_located.xml"
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from langRethrowLocated
[ RUN      ] langRethrowLocated.allExpected
Segmentation fault (core dumped)
test/unit/lang/rethrow_located --gtest_output="xml:test/unit/lang/rethrow_located.xml" failed
```

#### Expected Output:

Not segfaulting

#### Additional Information:

Works with clang++-3.8

#### Current Version:
v2.11.0

**Comment by bob-carpenter** [comment]
Any idea which of the test within allExpected it fails on?  I'm installing g++5.4 from Macports, but it's going to take awhile.

**Comment by bob-carpenter** [comment]
Hmm.  Works with 5.4.0 on -O0, but not with -O3.  I'll try to track down what's going on.  I'm using:

```
g++-mp-5 (MacPorts gcc5 5.4.0_0) 5.4.0
```
