### ISSUE TITLE
vertical bar in _cdf functions to match _lcdf and _lccdf

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2034]
#### Summary:

Now the CDFs (non-log scale) use `,` instead of `|` but we should make them consistent with the log scale versions.
#### Current Version:

v2.11.0

**Comment by rok-cesnovar** [comment]
Closing this issue as we now have a stanc3 issue for it, which is the proper place for it: https://github.com/stan-dev/stanc3/issues/854
