### ISSUE TITLE
Feature: Matrix Exponential

### ISSUE THREAD

**Issue by charlesm93** [stan-dev/stan#2043]
#### Summary:

A function that takes in a matrix and returns the matrix exponential of the matrix. 
#### Description:

Use the matrix exponential function from Eigen/Unsupported and make it AD compatible by overloading a few functions with var and fvar. 
#### Additional Information:

Issue on stan-dev/math can be found here: https://github.com/stan-dev/math/issues/32#issuecomment-242997057
#### Current Version:

v2.11.0

**Comment by bob-carpenter** [comment]
Included with #2114
