### ISSUE TITLE
Fix Windows integration tests.

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#2058]
#### Summary:

Integration tests fail on Windows.
#### Description:

With the change to the integration tests trying to compile every model, we've now broken our Windows tests builds. It's trying to create executables that are too big for the linker using RTools's g++ 4.6.3.

I don't know if this problem no longer exists with a newer version of RTools.

The fix is to break apart the Stan programs into smaller chunks. There's a limit to the size of a Stan program and its different C++ instantiations under Windows. I don't think any user will realistically hit this limit unless they're generating code.
#### Reproducible Steps:

Run:

```
make src/test/test-models/good/function-signatures/distributions/univariate/continuous/exp_mod_normal/exp_mod_normal_ccdf_log_1.hpp-test
```

There are a few more that will fail. That's the first failure.
#### Current Output:

```
...
c:/rtools/gcc-4.6.3/bin/../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/bin/as.exe: nul: too many sections (35710)
{standard input}: Assembler messages:
{standard input}: Fatal error: can't write nul: File too big
```
#### Expected Output:

It should just pass.
#### Additional Information:

Maybe our tests on Windows should just skip this?
#### Current Version:

v2.12.0

**Comment by aadler** [comment]
Perhaps it's time to make rstan depend on R >= 3.3 and only use the 4.9.3 version of Rtools?

**Comment by syclik** [comment]
I'd prefer to have minimal requirements wherever possible. Here, we're just
pushing the ability of the 32-bit linker that comes with the compiler, I
think. If you look at what it's trying to do, it's not really realistic.
There's no need for us to force users to upgrade just to keep up with tests
that aren't even run by users.

**Comment by bob-carpenter** [comment]
@sycklik  Is this still a problem?  I added Sean as an asignee.

I'm also OK just skipping integration tests on Windows assuming we're doing it elsewhere if Windows can't handle it and this is going to be some hugely time-consuming process to fix.  Otherwise, I'm just bumping to 2.15++ now until a decision can be made.

**Comment by syclik** [comment]
Yes, this is still an outstanding issue. But I'm happy to give up on it for
now.

**Comment by seantalts** [comment]
Is it possible this will be fixed once we upgrade to the new R / Rcpp / RTools?

**Comment by syclik** [comment]
Yes. It's very possible. I'm not too hopeful, but if it does, then great.
