### ISSUE TITLE
error: "use of undeclared identifier" in transformed parameters

### ISSUE THREAD

**Issue by davharris** [stan-dev/stan#2061]
#### Summary:
- I can compile models that refer to `parameters` in the `transformed parameters` block, as expected. 
- If the model instead refers to the size of a parameter (e.g. via `num_elements`), the model is translated to C++ code that will not compile.
#### Reproducible Steps:

```
parameters {
  vector[1] alpha;
}
transformed parameters {
  vector[num_elements(alpha)] alpha2;
}
model {
}
```

On my machine, this code is parsed and produces c++ code (e.g. via the `stanc` function in rstan), but does not compile (see errors copied below).

Because the model doesn't compile, I have no dumpfile to attach.
#### Current Output:

```
...
./issue-2061.hpp:207:39: error: use of undeclared identifier 'alpha'; did you mean
      'std::ctype_base::alpha'?
        dims__.push_back(num_elements(alpha));
                                      ^~~~~
                                      std::ctype_base::alpha
...
```
#### Expected Output:

My understanding is that it should always be legal to refer to a parameter in the transformed parameters block; if so, then my expected output would be a compiled Stan model.

If I'm wrong, it would be nice for the parser to catch the problem and perhaps clarify what's going on. 
#### Current Version:

v2.12.0

**Comment by syclik** [comment]
@davharris:
- I confirmed this is indeed a bug
- I replaced the original model with something simpler
- hopefully you've found a workaround

@bob-carpenter: we're having trouble within the generated code for `get_dims()`. It looks like variables declared as data are made member variables of the generated C++'s class (rightly so), but the parameters are not. I'm not sure what the right fix is here.

**Comment by bob-carpenter** [comment]
Thanks for reporting. I'll look into it and either make it compile or make the parser throw an error with an explanation.
