### ISSUE TITLE
Add integer % operator to "Binary Infix Operators" documentation

### ISSUE THREAD

**Issue by davharris** [stan-dev/stan#2065]
#### Summary:
The mod operator `%` isn't listed under Section 32.1's subsection on "Binary Infix Operators" for integers, although it seems to be included in the language.  I was only able to find `fmod` (for reals) in the documentation.

#### Current Version:
v2.12.0

**Comment by syclik** [comment]
Thanks! I moved it to the running documentation issue, #2051.
