### ISSUE TITLE
Have parser permit user-defined functions that are declared but not defined

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2068]
#### Summary:

A parser error is thrown when a Stan program has a user-defined function that is declared but not defined. This is an antifeature since useful things could be accomplished if this check were simply dropped. There would be more compiler errors but they are pretty obvious things like "function foo not found".

#### Description:

The function definition could be in another C++ file or in a shared library, in which case it could compile just fine. But currently packages like rstanarm cannot utilize auxiliary C++ files because the parser prevents it. This implies we sometimes write a function in Stan and then have to write the same function in R, instead of writing it once in C++ and calling it from Stan and R. We can't write likelihood functions that accumulate gradients. We can't call functions in GPL'd libraries. 

#### Reproducible Steps:

Parse

```{Stan}
functions {
  real foo(real x);
}
model {}
```

#### Current Output:

> SYNTAX ERROR, MESSAGE(S) FROM PARSER:
>
> Function declared, but not defined. Function name=foo
>
> ERROR at line 3

#### Expected Output:

Nothing

#### Current Version:
v2.12.0

**Comment by bob-carpenter** [comment]
We want to work on a general inclusion mechanism. @syclik and I are so deeply buried in the weeds we can't even see out to new feature development that isn't just looking over what other people do and making them rewrite it.

I'm reluctant to do this from a user error checking perspective, but if everyone else thinks it's a good idea, it's simple to do and would be fast.  

Isn't the expected output a header file that doesn't contain any information about where to find foo()?  And that's stanc output, right?  What's the output from trying to call a substantive model with an undefined function when the linker fails?

**Comment by bgoodri** [comment]
Maybe `stanc` should emit a non-fatal message saying the user-defined function is not found in the Stan program so make sure you either #include the file defining it or link to a shared object where it is compiled. The linker error from clang++ is like
```
/tmp/SU/bad.hpp:25:1: warning: inline function 'bad_model_namespace::foo<stan::math::var>' is not defined [-Wundefined-inline]
foo(const T0__& x, std::ostream* pstream__);
^
/tmp/SU/bad.hpp:165:39: note: used here
            lp_accum__.add(normal_log(foo(theta, pstream__),0,1));
                                      ^
/tmp/SU/bad.hpp:25:1: warning: inline function 'bad_model_namespace::foo<double>' is not defined [-Wundefined-inline]
foo(const T0__& x, std::ostream* pstream__);
^
/tmp/SU/bad.hpp:165:39: note: used here
            lp_accum__.add(normal_log(foo(theta, pstream__),0,1));
                                      ^
2 warnings generated.
```
followed by a compiler salad. But who that has written a C++ program which is more complicated than "Hello world" wouldn't have encountered an error message like that before?

**Comment by bob-carpenter** [comment]
> ...But who that has written a C++ program which is more complicated than "Hello world" wouldn't have encountered an error message like that before?

It's not the C++ programmers I'm worried about, but our ordinary users getting messages like this when they forget to define or mistype a function.  But like I said, it's an easy change if everyone else thinks it's a good idea.  At least until we can figure out how to do extensions better from the C++ side.

**Comment by jgabry** [comment]
I think it's unfortunate any time a user has to see any output from Stan
that's not really from Stan. Especially since many -- maybe most -- of our
users apparently don't even know how to react to our own
informational, warning, and error messages (the extent to which the content
of our messages is to blame for that is a separate issue).

That said, I do agree that this could be useful for packages like rstanarm.
How far down the to-do list are easier extensions on the C++ side?

Jonah

**Comment by bgoodri** [comment]
Like I said, we could still have a parser message that says the same thing
it says now except isn't fatal. And / or we can have a switch that you have
to pass to stanc in order to get it to look the other way when the
user-defined function has no definition. But it is a bit different than
having a mechanism to #include Stan code. That is a good idea too but we
are already doing that with rstanarm.

**Comment by jgabry** [comment]
Ok I see. Thanks for clarifying.

**Comment by bob-carpenter** [comment]
We need to do both:

1. have a way for users to provide C++ extensions for
   functions and distributions

2. have a way for users to include code for Stan-defined functions

RStan and RStanArm are ahead of core Stan in functionality,
so any code in those is not portable across Stan interfaces.

No idea when we can get to any of this.   Daniel was going to
work on (1) and I was going to work on (2).  I'm guessing some
time after vectorization and some time before ragged, sparse,
triangular and other data types.

- Bob

**Comment by bgoodri** [comment]
I agree that we need to do both, but I don't see how progress on (2) is relevant to (1) or this GitHub issue. I am also not seeing how (1) could be done any easier than just having a mechanism to disable the check that user-defined Stan functions are defined and letting the compiler / linker figure it out.

**Comment by bob-carpenter** [comment]
(1) and (2) are both code inclusion mechanisms.  I agree that (2 -- including Stan functions) isn't relevant to this issue other than to clarify the scope of what we are and are not talking about.

To make (1 -- C++ functions) clean, users would add the signatures to the Stan parser through the C++ side, so you wouldn't need to declare functions in the Stan functions block.  That way you could write more general functions or have libraries, without having to write out all the function signatures longhand each time.

**Comment by bgoodri** [comment]
You vision of (1) seems to be different from this issue. In the case of R, stanc is already compiled in rstan with the signatures it knows about from StanHeaders. I don't see how it would be possible to add C++ code in rstanarm that could be called by the Stan code in rstanarm in such a way that stanc in rstan would know how to parse the Stan code in rstanarm.

If, however, stanc had a flag to make it not fail when it encountered a user-defined function in a Stan program that was declared but not defined, then it is easy for packages like rstanarm to link to their shared object that has the function definition in C++. 

This diff doesn't change any behavior and thus passes all the unit tests. We just need to hook it up with stanc so it is possible to specify `allow_undefined = true`.

```
diff --git a/src/stan/lang/grammars/functions_grammar_def.hpp b/src/stan/lang/grammars/functions_grammar_def.hpp
index e0de8cc..881459a 100644
--- a/src/stan/lang/grammars/functions_grammar_def.hpp
+++ b/src/stan/lang/grammars/functions_grammar_def.hpp
@@ -53,7 +53,7 @@ namespace stan {
         > eps[validate_declarations_f(_pass,
                                       boost::phoenix::ref(functions_declared_),
                                       boost::phoenix::ref(functions_defined_),
-                                      boost::phoenix::ref(error_msgs_))];
+                                      boost::phoenix::ref(error_msgs_), false)];
 
       // locals: _a = allow sampling, _b = origin (function, rng/lp)
       function_r.name("function declaration or definition");
diff --git a/src/stan/lang/grammars/semantic_actions.hpp b/src/stan/lang/grammars/semantic_actions.hpp
index 11aa36a..520ad53 100644
--- a/src/stan/lang/grammars/semantic_actions.hpp
+++ b/src/stan/lang/grammars/semantic_actions.hpp
@@ -250,13 +250,14 @@ namespace stan {
     set_allows_sampling_origin_f;
 
     // called from: functions_grammar
-    struct validate_declarations : public phoenix_functor_quaternary {
+    struct validate_declarations : public phoenix_functor_quinary {
       void operator()(bool& pass,
                       std::set<std::pair<std::string,
                                          function_signature_t> >& declared,
                       std::set<std::pair<std::string,
                                          function_signature_t> >& defined,
-                      std::ostream& error_msgs) const;
+                      std::ostream& error_msgs,
+                      const bool allow_undefined) const;
     };
     extern boost::phoenix::function<validate_declarations>
     validate_declarations_f;
diff --git a/src/stan/lang/grammars/semantic_actions_def.cpp b/src/stan/lang/grammars/semantic_actions_def.cpp
index 7627527..b9cc32d 100644
--- a/src/stan/lang/grammars/semantic_actions_def.cpp
+++ b/src/stan/lang/grammars/semantic_actions_def.cpp
@@ -315,18 +315,21 @@ namespace stan {
                                            function_signature_t> >& declared,
                                            std::set<std::pair<std::string,
                                            function_signature_t> >& defined,
-                                           std::ostream& error_msgs) const {
+                                           std::ostream& error_msgs,
+                                           const bool allow_undefined) const {
       using std::set;
       using std::string;
       using std::pair;
       typedef set<pair<string, function_signature_t> >::iterator iterator_t;
-      for (iterator_t it = declared.begin(); it != declared.end(); ++it) {
-        if (defined.find(*it) == defined.end()) {
-          error_msgs <<"Function declared, but not defined."
-                     << " Function name=" << (*it).first
-                     << std::endl;
-          pass = false;
-          return;
+      if (!allow_undefined) {
+        for (iterator_t it = declared.begin(); it != declared.end(); ++it) {
+          if (defined.find(*it) == defined.end()) {
+            error_msgs <<"Function declared, but not defined."
+                       << " Function name=" << (*it).first
+                       << std::endl;
+            pass = false;
+            return;
+          }
         }
       }
       pass = true;
```

**Comment by syclik** [comment]
@bgoodri, create a PR? If you've already got a reasonable fix, I don't know why we're talking about hypothetical issues.

I have been thinking about how to do the extension a little more generally instead of through the language. But this won't hurt / help that effort. The include mechanism in the makefiles might be the same, though, but that's a different issue.

The one issue with this approach is that the function signature will require an `ostream` argument, I believe. That may not be obvious to the C++ code writer, but if you think they're savvy enough, then it's fine.

**Comment by bob-carpenter** [comment]
Right---user defined functions might print, so any function
declared in the functions block is going to generate a signature
where the last argument is a std::ostream*, but it can be NULL
if it's not used.

- Bob

**Comment by syclik** [comment]
Ah yes. Forgot about that.

**Comment by bgoodri** [comment]
I have a PR almost ready. Where are the tests of the current behavior when
a function is not defined?

**Comment by bob-carpenter** [comment]
It's in:

  src/test/unit/lang/parser/user_defined_functions_test.cpp

Look for 

  test_throws("functions-bad2","Function declared, but not defined");

And then functions-bad2.stan is the file that shouldn't parse,
and that's in 

  src/test/test-models/bad/functions-bad2.stan

- Bob

**Comment by bgoodri** [comment]
OK. The parse() function now has an allow_undefined argument that gets
passed to it by compile() and stanc_helper(). How do I pass that in the
tests so that

src/test/test-models/bad/functions-bad2.stan

then parses?

**Comment by bob-carpenter** [comment]
The test code framework is included from test/unit/lang/utility.hpp

You'll probably need to add an optional argument to the test program
or write a new test program.

- Bob
