### ISSUE TITLE
Compiling in multiple translation units fails. Needs inline on functions.

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#2082]
#### Summary:

Compiling with multiple translation units fails.
#### Reproducible Steps:

See: https://github.com/stan-dev/stan/issues/1149#issuecomment-192535899
#### Current Output:

```
...
ld: 19 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
#### Expected Output:

Compiles.
#### Additional Information:

Adding inline should fix most of this. Add a new test. See stan-dev/math's multiple_translation_unit test.
#### Current Version:

v2.12.0

**Comment by syclik** [comment]
This branch fixes this issue: `feature/issue-2082-inline`. Unfortunately, this makes the build fail under Windows with the current RTools compiler. Once we move forward, hopefully we can merge this branch in.

**Comment by bob-carpenter** [comment]
@syclik --- has RTools caught up to `feature/issue-2082-inline` yet?

**Comment by syclik** [comment]
@bob-carpenter: nope. https://github.com/stan-dev/stan/pull/2087 http://d1m1s1b1.stat.columbia.edu:8080/job/Stan%20Pull%20Request/1400/

Still failing under Windows. Maybe we just skip that one test under Windows?

**Comment by bob-carpenter** [comment]
What test are you suggesting turning off?  Is it that the proposed fix will work for platforms other than Windows, there's a test to make sure it works on other platforms, but it can't be made to work on Windows, so we turn the test off without breaking other bits of the Windows build?  If so, I'm fine with that solution.

**Comment by syclik** [comment]
@bob-carpenter, yes. That's exactly what I'm suggesting. I'll think about
how to make that work and reopen the pull request when I've got a solution.

@seantalts, have any quick thoughts on how to get all but one test to run
on Windows?

**Comment by seantalts** [comment]
Maybe adding a flag to runTests.py for a test regex to exclude?

**Comment by bgoodri** [comment]
This still fails in 2.16 (on Linux)
```
library(rstan) 
funnel <- stan_demo("funnel", chains = 0) 
funnel_reparam <- stan_demo("funnel_reparam", chains = 0)
setwd(tempdir())
stopifnot(system("R CMD SHLIB --output=test *.o") == 0)
```
yielding
```
gcc-7 -shared -L/usr/lib/R/lib -Wl,-z,relro -o test file454b2fdbc541.o file454b3cac8481.o -L/usr/local/lib/R/site-library/StanHeaders/lib -lStanHeaders -L/usr/lib/R/lib -lR
file454b3cac8481.o: In function `stan::mcmc::write_metric(stan::callbacks::writer&)':
file454b3cac8481.cpp:(.text+0x2ff0): multiple definition of `stan::mcmc::write_metric(stan::callbacks::writer&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x2ea0): first defined here
file454b3cac8481.o: In function `stan::services::util::experimental_message(stan::callbacks::logger&)':
file454b3cac8481.cpp:(.text+0x3080): multiple definition of `stan::services::util::experimental_message(stan::callbacks::logger&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x2f30): first defined here
file454b3cac8481.o: In function `stan::services::util::read_diag_inv_metric(stan::io::var_context&, unsigned long, stan::callbacks::logger&)':
file454b3cac8481.cpp:(.text+0x3490): multiple definition of `stan::services::util::read_diag_inv_metric(stan::io::var_context&, unsigned long, stan::callbacks::logger&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x3340): first defined here
file454b3cac8481.o: In function `stan::variational::print_progress(int, int, int, int, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, stan::callbacks::logger&)':
file454b3cac8481.cpp:(.text+0x3b50): multiple definition of `stan::variational::print_progress(int, int, int, int, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, stan::callbacks::logger&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x3a00): first defined here
file454b3cac8481.o: In function `stan::services::util::read_dense_inv_metric(stan::io::var_context&, unsigned long, stan::callbacks::logger&)':
file454b3cac8481.cpp:(.text+0x4500): multiple definition of `stan::services::util::read_dense_inv_metric(stan::io::var_context&, unsigned long, stan::callbacks::logger&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x43c0): first defined here
file454b3cac8481.o: In function `stan::variational::operator/(stan::variational::normal_meanfield, stan::variational::normal_meanfield const&)':
file454b3cac8481.cpp:(.text+0x4d90): multiple definition of `stan::variational::operator/(stan::variational::normal_meanfield, stan::variational::normal_meanfield const&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x4c50): first defined here
file454b3cac8481.o: In function `stan::variational::operator*(double, stan::variational::normal_meanfield)':
file454b3cac8481.cpp:(.text+0x52f0): multiple definition of `stan::variational::operator*(double, stan::variational::normal_meanfield)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x55b0): first defined here
file454b3cac8481.o: In function `stan::variational::operator+(double, stan::variational::normal_meanfield)':
file454b3cac8481.cpp:(.text+0x56f0): multiple definition of `stan::variational::operator+(double, stan::variational::normal_meanfield)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x51b0): first defined here
file454b3cac8481.o: In function `stan::variational::operator/(stan::variational::normal_fullrank, stan::variational::normal_fullrank const&)':
file454b3cac8481.cpp:(.text+0x5af0): multiple definition of `stan::variational::operator/(stan::variational::normal_fullrank, stan::variational::normal_fullrank const&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x59b0): first defined here
file454b3cac8481.o: In function `stan::variational::operator*(double, stan::variational::normal_fullrank)':
file454b3cac8481.cpp:(.text+0x60e0): multiple definition of `stan::variational::operator*(double, stan::variational::normal_fullrank)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x5fa0): first defined here
file454b3cac8481.o: In function `stan::variational::operator+(double, stan::variational::normal_fullrank)':
file454b3cac8481.cpp:(.text+0x6550): multiple definition of `stan::variational::operator+(double, stan::variational::normal_fullrank)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x6410): first defined here
file454b3cac8481.o: In function `stan::services::util::validate_diag_inv_metric(Eigen::Matrix<double, -1, 1, 0, -1, 1> const&, stan::callbacks::logger&)':
file454b3cac8481.cpp:(.text+0x69c0): multiple definition of `stan::services::util::validate_diag_inv_metric(Eigen::Matrix<double, -1, 1, 0, -1, 1> const&, stan::callbacks::logger&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x6880): first defined here
file454b3cac8481.o: In function `stan::variational::operator+(stan::variational::normal_fullrank, stan::variational::normal_fullrank const&)':
file454b3cac8481.cpp:(.text+0x7ff0): multiple definition of `stan::variational::operator+(stan::variational::normal_fullrank, stan::variational::normal_fullrank const&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x7eb0): first defined here
file454b3cac8481.o: In function `stan::variational::operator+(stan::variational::normal_meanfield, stan::variational::normal_meanfield const&)':
file454b3cac8481.cpp:(.text+0x80e0): multiple definition of `stan::variational::operator+(stan::variational::normal_meanfield, stan::variational::normal_meanfield const&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x7fa0): first defined here
file454b3cac8481.o: In function `stan::services::util::create_unit_e_diag_inv_metric(unsigned long)':
file454b3cac8481.cpp:(.text+0xac80): multiple definition of `stan::services::util::create_unit_e_diag_inv_metric(unsigned long)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x9cf0): first defined here
file454b3cac8481.o: In function `stan::services::util::create_unit_e_dense_inv_metric(unsigned long)':
file454b3cac8481.cpp:(.text+0xad90): multiple definition of `stan::services::util::create_unit_e_dense_inv_metric(unsigned long)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0x9e00): first defined here
file454b3cac8481.o: In function `rstan::sample_writer_factory(std::ostream*, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> > const&)':
file454b3cac8481.cpp:(.text+0xb1d0): multiple definition of `rstan::sample_writer_factory(std::ostream*, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> > const&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0xa240): first defined here
file454b3cac8481.o: In function `stan::services::util::validate_dense_inv_metric(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, stan::callbacks::logger&)':
file454b3cac8481.cpp:(.text+0xbe50): multiple definition of `stan::services::util::validate_dense_inv_metric(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, stan::callbacks::logger&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0xb1d0): first defined here
file454b3cac8481.o: In function `stan::optimization::make_negative_definite_and_solve(Eigen::Matrix<double, -1, -1, 0, -1, -1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&)':
file454b3cac8481.cpp:(.text+0xbf50): multiple definition of `stan::optimization::make_negative_definite_and_solve(Eigen::Matrix<double, -1, -1, 0, -1, -1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&)'
file454b2fdbc541.o:file454b2fdbc541.cpp:(.text+0xb2d0): first defined here
collect2: error: ld returned 1 exit status
/usr/share/R/share/make/shlib.mk:6: recipe for target 'test' failed
make: *** [test] Error 1
Error: system("R CMD SHLIB --output=test *.o") == 0 is not TRUE
```

**Comment by bgoodri** [comment]
This seems to work if `LDFLAGS += -Wl,--allow-multiple-definition` is specified, but that is not a general solution.

**Comment by bob-carpenter** [comment]
@syclik  Do you know if Eigen just inlines every function and if that's a viable solution for Stan?  If so, I think that would be relatively easy to code.  @betanalpha suggested that we need tests for this, either by extending `cpplint` or by writing unit tests.

**Comment by syclik** [comment]
No idea. Updating the test would be good.

I'm not exactly sure how to reproduce. @bgoodri, can you export the C++ files you're using to cause the error? I can see the compiler options in the earlier post, so that's covered. Hopefully we can get a standalone, reproducible failure that doesn't depend on RStan.

**Comment by bgoodri** [comment]
You just need any two .o files. `R CMD SHLIB` calls
```
make -f '/usr/lib/R/etc/Makeconf' -f '/usr/share/R/share/make/shlib.mk' -f '/home/goodrich/.R/Makevars' \\
SHLIB='test' OBJECTS='file5d2d4950c6c.o file5d2d59e68efc.o'
```
so it is just a matter of calling `make` like Stan does with the `SHLIB` and `OBJECTS` variables set.

**Comment by bgoodri** [comment]
On my laptop this evaluates to
```
gcc-7 -shared -L/usr/lib/R/lib -Wl,-z,relro -o test file5d2d4950c6c.o file5d2d59e68efc.o  -L'/usr/local/lib/R/site-library/StanHeaders/lib' -lStanHeaders  -L/usr/lib/R/lib -lR; \
```
which fails unless I define `LDFLAGS += -Wl,--allow-multiple-definitions` in ~/.R/Makevars.

**Comment by bgoodri** [comment]
I have a branch --- https://github.com/stan-dev/stan/tree/bugfix/issue-2082-again --- that seems to work, but I didn't inline absolutely everything, only what appeared in error messages. We need a test that

1. Involves multiple Stan programs
2. Involves all possible function calls in src/stan/model
3. Creates (or fails to create) a shared object

**Comment by bob-carpenter** [comment]
Great news.  

@seantalts or @syclik seem like the best candidates to do this if they have the time.  I'm not sure how to tweak the builds to do this.

**Comment by bgoodri** [comment]
An additional issue is that the models compiled by the unit tests all have a `main` function, which means you automatically have a multiple definition problem even if you have inlined everything else. This aspect of the problem does not arise with RStan.

**Comment by bgoodri** [comment]
Does anyone mind if the test for this is "Does rstanarm build?" I don't see how to test it from the Stan unit tests.

**Comment by seantalts** [comment]
I think that's a reasonable test, since as far as I know that's the only existing use case for this feature right now and it should cover a lot of ground in case someone else were to start trying to use it.

**Comment by syclik** [comment]
Yup. It's fine as a stopgap. How do you test that rstanarm builds? We could set up a Jenkins job for that.

**Comment by bgoodri** [comment]
Yeah, I would just clone the rstanarm repo and execute `R CMD build
rstanarm/`. Except we have a chicken-and-egg problem that I can't refactor
rstanarm's makefiles until the PR is merged and we can't merge the PR until
it is tested.

**Comment by bgoodri** [comment]
This morning, @bob-carpenter said it was possible to generate C++ files without main functions. How is this done at the library level? I would recommend that we build them for the two .stan files under `src/test/test-models/good/mcmc/common` and then test if the resulting object files can be combined into a shared object.

**Comment by bob-carpenter** [comment]
I'm not sure where the main() you're talking about is coming from.  We used to generate that, and I thought we might have had a flag somewhere now, but I can't find anything that generates a main() in Stan.

**Comment by syclik** [comment]
Yes, there is no main. 

One problem I can see is that there's a typedef defined in the generated hpp. 

Ben, what would help me get up to speed quickly is if you were to generate two hpp files from rstanarm and showed the invocation to the compiler that fails. I'm not quick enough with r packages to understand how to generate those headers as you have them. I can try with Stan's headers, but I still don't have all the compiler options set correctly. Maybe there's a difference in the flags or some order dependent thing for g++.

Just need some help getting set up and I can dig into it.

**Comment by bgoodri** [comment]
The attached two files (when their extensions are changed to .cpp) can be compiled from R with

```
Rcpp::sourceCpp("file55a75d006572.cpp", cacheDir = getwd())
Rcpp::sourceCpp("file55a7c587378.cpp", cacheDir = getwd())
```
Then outside of R, but in the same working directory there will be a folder that starts with the string "sourceCpp". Inside that there will be two more folders named sourcecpp_2d574211641f  and sourcecpp_2d577ea1af8. Inside each of those two folders will be a compiled .o file named file55a75d006572.o and file55a7c587378.o respectively. Executing
```
R CMD SHLIB --output=test sourceCpp*/*/*.o
```
will try (but fail) to build a shared object named test with the StanHeaders from CRAN. On my system, that maps to
```
gcc-7 -shared -L/usr/lib/R/lib -Wl,-z,relro -o test sourceCpp-x86_64-pc-linux-gnu-0.12.12/sourcecpp_2d574211641f/file55a75d006572.o sourceCpp-x86_64-pc-linux-gnu-0.12.12/sourcecpp_2d577ea1af8/file55a7c587378.o -L/usr/lib/R/lib -lR
```
On your system, it will probably be slightly different but whatever the underlying command is will be echoed to the shell and can be seen in more detail by adding the `--dry-run`option to `R CMD SHLIB`.

With the issue-2082-again branch, the above commands work, although there does not seem to be any rhyme or reason to which functions need to be inlined and which do not.

[file55a7c587378.txt](https://github.com/stan-dev/stan/files/1216988/file55a7c587378.txt)
[file55a75d006572.txt](https://github.com/stan-dev/stan/files/1216989/file55a75d006572.txt)

**Comment by syclik** [comment]
@bgoodri, thanks. This helps a lot.

I followed it and ran:
```
R CMD SHLIB --output=test sourceCpp*/*/*.o
```

and it successfully compiled a `test` executable, but I can't run it. What should I be able to do with it? Should I be able to run it from the command line?

Is it possible that this is a problem with using `gcc-7`? Can you try using `g++-7` instead? Or try using the default g++ compiler? I'm trying to understand if this is a problem with g++ in general or just g++-7. I'm also trying to understand what this is supposed to do. There's a lot of additional included code in here that depends on Rcpp and RStan and I'm not sure if the problem stems from Stan or it starts with RStan. I guess that's why I was trying to find a minimal Stan example (without additional dependencies on RStan / Rcpp) to show the problem.

**Comment by bgoodri** [comment]
Sorry, I accidentally generated those files with the fixed versions of Stan. These two attachments, when compiled, actually fail to make a shared object when you do `R CMD SHLIB --output=test sourceCpp*/*/*.o`. It doesn't have anything to do with Rcpp. The errors (which are the same as those I reported on the June 24 post) all refer to the `stan::` namespace except for one that refers to the `rstan::` namespace that is already fixed on GitHub.

[file57d3028d1cc.txt](https://github.com/stan-dev/stan/files/1219890/file57d3028d1cc.txt)
[file57d3077f018.txt](https://github.com/stan-dev/stan/files/1219891/file57d3077f018.txt)

**Comment by syclik** [comment]
Ah. Ok. I'll try it early this week.
