### ISSUE TITLE
Provide a landing site for development

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#2089]
#### Summary:
Create a landing page that we can contributors to. Put the links in `.github/CONTRIBUTING.md`.

Point to a search for "next manual" issue for doc corrections (say they should indicate a name if they want to be acknowledged).

**Comment by syclik** [comment]
Add a link to the running manual issue.

**Comment by bob-carpenter** [comment]
Done.  Just pushed directly as it was a .md file that doesn't touch anything else.
