### ISSUE TITLE
Stan manual.  T[,]

### ISSUE THREAD

**Issue by skanskan** [stan-dev/stan#2093]
#### Summary:

T[,] is not explained in the manual.

#### Description:

Hello.

In the Stan manual, section 9.2, you can read:

> data {
> real<upper=U> y[N];
> }
> **y[n] ~ normal(mu, sigma) T[,U]**;

The model declares an upper bound U as data and constrains the data for y to respect the constraint.

But I can't find any explanation on the meaning of that T[].

If I just had 

> y[n] ~ normal(mu, sigma);

It would mean that the y is distributed normally, 
but what is that T ?

#### Current Version:
Any version of the stan manual, including the v2.12.0

**Comment by bob-carpenter** [comment]
There's section 9.1 Truncated Distributions in the programming guide and section 27.3 on sampling statements has a subsection Truncated Distributions that goes over the gory details.

We do need a better index, but that's a different issue than this one so I'm closing.

**Comment by skanskan** [comment]
OK, thanks.
Strange way to write the truncation.

**Comment by bob-carpenter** [comment]
It's a holdover from JAGS with square brackets to
indicate the bounds are inclusive:

https://sourceforge.net/p/mcmc-jags/discussion/610037/thread/4288692c/
