### ISSUE TITLE
Support discrete parameters

### ISSUE THREAD

**Issue by skanskan** [stan-dev/stan#2094]
Is stan ever going to support sampling discrete parameters?
Now we have to try to marginalize the parameter and rewrite the code. it's complex and prone to errors.

**Comment by bob-carpenter** [comment]
Probably not any time soon.

On the plus side, marginalizing leads to much faster code
(orders of magnitude) in terms of n_eff per second and computes
more accurate statistics for tails which you can never get
into with discrete sampling (see the manual chapter on
latent discrete parameters for an example using the choice
point model).  Marginalizing discrete parameters should be
done in JAGS and BUGS where possible, too!

- Bob

**Comment by jgabry** [comment]
It's true that it can complicated and prone to errors but it's less
complicated and prone to errors than adding discrete parameters to Stan
without a stable and efficient way of doing it ;)

In theory having discrete parameters in Stan would be great, and I don't
think we've ruled it out, but as far as I know there hasn't yet been a
proposal that would provide a robust implementation. There are plenty of
toy examples in which HMC can be combined with some other procedure to
handle discrete parameters, but I believe it still remains in the toy
example stage.

**Comment by bob-carpenter** [comment]
We could always use Metropolis or Gibbs.  But we can't do those
efficiently because we don't have a way to pull the Markov blanket
out of a Stan program.  It's not restricted to graphical models.
So we've thought about supporting discrete parameters for a restricted
set of models.  Otherwise, we have no idea how to do it efficiently enough
that people wouldn't just say "Oh, now Stan can fit discrete parameters,
but it's so slow as to be useless."

What we don't know is how changes to discrete parameters will affect
static HMC or NUTS, and especially, whether they'll defeat all the
adaptation.  Essentially, changing the discrete parameters changes
the continuous distribution if they're not independent, and we don't
know what affect that will have on the continuous sampling.

But the real reason we haven't done discrete sampling is that
we don't know how to do it efficiently without forcing users to
write all the conditional pmfs so we can do Gibbs efficiently.

- Bob

**Comment by skanskan** [comment]
I'm just starting to learn Stan.
I would like to find more information (and examples) on how to work with discrete parameters (beyond what we can find in the manual). I would like to see an extended version of the part "marginalizing out the discrete parameters".

In the example you provide in that section... for me it's difficult to follow and understand why you modify the log_sum_exp(lp), and how to generalize it to other examples.

I guess I'm missing some step. 

Regards

**Comment by skanskan** [comment]
I don't know if this is the proper place to ask but... 
Can packages such as brms or stanarm help me to get the proper code  (marginalized) when working with discrete parametes?

**Comment by sakrejda** [comment]
@skanskan Try asking on the users list with the specific model in question, you are more likely to get help there, we try to keep discussion out of the issues. But no, I don't think those will help you understand marginalization.  It's really best to try and understand it on a simple example I suggest a toy model with a bernoulli parameter or a two-component normal mixture.  See if you can write down the continuous density for that.

**Comment by skanskan** [comment]
OK, I'll be back when I study a little bit more.
Thanks

**Comment by bob-carpenter** [comment]
I added discrete parameters to our long-term to-do list, which is where it belongs until we have a concrete plan we can turn into an issue:

https://github.com/stan-dev/stan/wiki/Longer-Term-To-Do-List

We only want issues that are concrete enough to be actionable and we don't know how to approach this one, so I'm closing.

**Comment by bob-carpenter** [comment]
A whole lot of the stats literature in the past is aimed
at doing these marginalizations because people fit maximum
likelihood estimates.  Exactly the same marginalizations work
for Stan.

log_sum_exp() lets you do linear addition on the log scale.

log_sum_exp(a, b) = log(exp(a) + exp(b))

So if a and b are log quantities, log_sum_exp(a, b) is the
log of adding a and b on the linear scale.

- Bob

**Comment by skanskan** [comment]
I don't speak well English but I can quote some words from the book Doing Bayesian Data Analysis: 
"The lack of discrete parameters in Stan means that we cannot do model comparison as a hierarchical model with an indexical parameter at the top level. There might be ways to work around this restriction by using clever programming contrivances, but presently there is nothing as straight forward as the model specification in JAGS.

**Comment by betanalpha** [comment]
Easy to specify does not mean that the resulting fit will
be fast or even right.  Gibbs samplers that are easily
implemented for models with discrete parameters can
be very slow and and in many cases do not even explore
sufficiently well, causing biased expectation estimation.
Kruschke�s comment here is statistically naive and when
taken seriously quite dangerous. 

When coupled with the technical difficultly of calculating 
the terms necessary for implementing Gibbs sampling or 
Random Walk Metropolis with models featuring both 
discrete and continuous parameters, we are not eager
to support discrete parameters.  Especially when with
a little work most of these models can be implemented
with marginalization in Stan.  

Of course we are actively researching and in contact
with the vanguard of the statistical community, and
if a robust sampler for discrete parameters is introduced
it will be considered for Stan as soon as possible.

**Comment by bob-carpenter** [comment]
The "clever programming contrivance" is a marginalization:

  https://en.wikipedia.org/wiki/Marginal_distribution

The mixture models chapter shows how to code it in Stan.

The marginalized model will be more efficient, especially
for values of the discrete parameters that have low marginal
probability in the posterior.

**Comment by skanskan** [comment]
OK, I understand the theory of the marginalization, expressing the probability as a summation...
What I don't understand is what **target +=**  does

**Comment by sakrejda** [comment]
@skanskan please ask on the mailing list: https://groups.google.com/forum/#!forum/stan-users

**Comment by jgabry** [comment]
On Wednesday, October 26, 2016, Michael Betancourt <notifications@github.com>
wrote:

> Easy to specify does not mean that the resulting fit will
> be fast or even right. Gibbs samplers that are easily
> implemented for models with discrete parameters can
> be very slow and and in many cases do not even explore
> sufficiently well, causing biased expectation estimation.
> Kruschke�s comment here is statistically naive and when
> taken seriously quite dangerous.
>
>
I completely agree. It's great that he updated the book to include Stan,
but this comment of his in the book (and a few others like it) were quite
frustrating when I read the book. Maybe we can encourage Kruschke to make
some changes in the next edition.

Regarding this specific comment about model comparison via a hierarchical
model with an index for the models being compared: it's fine if the idea is
that it would be great if this setup worked well, but it's far more
important that the models being compared are estimated well than it is to
be able to set up the comparison in this particular way.

**Comment by skanskan** [comment]
OK, I continue here
http://stackoverflow.com/questions/40289457/stan-using-target-syntax

**Comment by skanskan** [comment]
Back to marginalization...
In Stan 2.12 manual page 131 and 132 you marginalize out a discrete parameter s.  You do it summing out s.
That way you can "forget" s, solve the problem, and simulate the posterior for the other parameters.

But how can you get the posterior of that parameter s from the data you have generated?
I say it because s is not declared as a parameter.

**Comment by skanskan** [comment]
And here my doubt on how to work with a simple discrete example, the binomial.
http://stackoverflow.com/questions/40293595/marginalizing-out-discrete-parameters-with-stan

**Comment by jgabry** [comment]
stackoverflow is fine but a lot more stan devs and users will see the
question if it's on the Stan users list that Krzysztof linked to.

**Comment by bob-carpenter** [comment]
Please don't keep writing into this issue.

**Comment by bob-carpenter** [comment]
I just locked this issue.  Please use our mailing lists or stackoverflow or some other means of asking questions other than our issues.  Thanks.
