### ISSUE TITLE
Vector addition gives a compiler error in Microsoft Visual C++

### ISSUE THREAD

**Issue by belteshassar** [stan-dev/stan#2110]
#### Summary:
Vector addition gives a compiler error in Microsoft Visual C++ 14.0. This does not reproduce when using g++ on Ubuntu on Windows.

#### Description:
I use pystan with Python 3.5. I have managed to compile and run a variety of models both on Windows using Visual C++ 14.0 and on the new Windows subsystem for Linux (WSL). When building a more complex model with vector parameters I managed to get a compiler error in Visual C++ 

```
error C2672: 'add': no matching overloaded function found
```

I narrowed the issue down to vector addition. I can reproduce the issue using a vector addition in either of the transformed data, transformed parameters, or model blocks.

I don't know if this can be reproduced on older versions of Python using older compilers. I use Visual C++ 14.0 since it's the recommended compiler for building Python extensions for Python 3.5 on Windows.

#### Reproducible Steps:
Here is a simplified model that can reproduce the issue:
```
data {
  int<lower=0> I;
  simplex[I] y;
}
transformed data {
  vector[I] ones;
  for (i in 1:I) {
    ones[i] = 1.0;
  }
}
parameters {
  vector[I] alpha;
}
model {
  y ~ dirichlet(alpha + ones);
}
```

#### Current Output:
```
error C2672: 'add': no matching overloaded function found
```

#### Additional Information:
OS: Windows 10 Pro 64-bit Build 14393.447
Visual C++ 14.0
Python 3.5.2
pystan 2.12.0.0

#### Current Version:
v2.12.0

**Comment by bob-carpenter** [comment]
We don't support MS Visual C++, but we're happy to take pull requests that fix problems.

At some point Stan was working for MSVC.  No idea what state it's in now.

This issue should be in stan-dev/math, so I'm closing this and reopening as:  https://github.com/stan-dev/math/issues/434

You should be able to get Stan working using g++ for Windows, for instance as distributed with Rtools.
