### ISSUE TITLE
cov_exp_quad() doesn't compile

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#2113]
#### Summary:
From stan-dev/pystan#271.

This generates C++ that does not compile:
```stan
data {
  real x[5];
}
model {
  matrix[5,5] a;
  a = cov_exp_quad(x, 1.0, 1.0);
}
```

#### Description:
This should compile.

#### Reproducible Steps:
Translate to C++. Compile the C++.

#### Current Output:
```
clang++ -I src -I stan_2.12.0/src -isystem stan_2.12.0/lib/stan_math_2.12.0/ -isystem stan_2.12.0/lib/stan_math_2.12.0/lib/eigen_3.2.9 -isystem stan_2.12.0/lib/stan_math_2.12.0/lib/boost_1.60.0 -isystem stan_2.12.0/lib/stan_math_2.12.0/lib/cvodes_2.8.2/include -Wall -DEIGEN_NO_DEBUG  -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12 -DNO_FPRINTF_OUTPUT -pipe  -Wno-unused-function -ftemplate-depth-256    -O3 -o pystan src/cmdstan/main.cpp -include pystan.hpp stan_2.12.0/lib/stan_math_2.12.0/lib/cvodes_2.8.2/lib/libsundials_nvecserial.a stan_2.12.0/lib/stan_math_2.12.0/lib/cvodes_2.8.2/lib/libsundials_cvodes.a 
In file included from <built-in>:336:
In file included from <command line>:7:
./pystan.hpp:153:39: error: no matching function for call to 'cov_exp_quad'
                stan::math::assign(a, cov_exp_quad(rx1,rx1,1.0,1.0));
                                      ^~~~~~~~~~~~
stan_2.12.0/lib/stan_math_2.12.0/stan/math/prim/mat/fun/cov_exp_quad.hpp:85:5: note: candidate
      function [with T_x1 = double, T_x2 = double, T_sigma = double, T_l = double] not viable:
      expects an l-value for 3rd argument
    cov_exp_quad(const std::vector<T_x1>& x1,
    ^
stan_2.12.0/lib/stan_math_2.12.0/stan/math/prim/mat/fun/cov_exp_quad.hpp:35:5: note: candidate
      function template not viable: requires 3 arguments, but 4 were provided
    cov_exp_quad(const std::vector<T_x>& x,
    ^
1 error generated.
```

#### Expected Output:
No error.

#### Additional Information:
thanks @nesanders and @ariddell for finding this and creating a minimal working example

#### Current Version:
v2.12.0

**Comment by rtrangucci** [comment]
@syclik We do have tests for all combinations of inputs, but we don't have tests corresponding to passing doubles in directly.

This will compile:

```
data {
  real x[5];
}
transformed data {
  real sigma;
  real length;

  sigma = 1;
  length = 1;
}
model {
  matrix[5,5] a;
  a = cov_exp_quad(x, sigma, length);
}
```

I'll take a look at this.

**Comment by syclik** [comment]
Thanks. Maybe it's the reference not resolving with a literal.

**Comment by rtrangucci** [comment]
Looks like it's OK in math.

Have you been able to recreate on the current Stan develop branch, or just
in cmdstan-2.12.0?


Rob

**Comment by rtrangucci** [comment]
The example above compiles ok on my computer when I use the `develop` branch of `math`

**Comment by syclik** [comment]
I only checked with tagged 2.12. I didn't even think to try develop. If it's fixed now, that's great and we can close both issues.

**Comment by nesanders** [comment]
That sounds like good news :)  Thanks again to everyone for looking into the issue.

What's the easiest way for a pystan user to upgrade to the develop branch of math?

**Comment by ariddell** [comment]
That's a good question. Dealing with submodules isn't terribly easy.

You want to check out the source and then update the stan submodule to the current commit. Then you'll need to update the math sub (sub!) module to the indicated commit.

**Comment by syclik** [comment]
I just verified that this works with the current version of `develop`, so I'm closing it. @nesanders, I'll reply back to you on the pystan issue.
