### ISSUE TITLE
stack use after scope

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2117]
#### Summary:

Stan seems to have "stack-use-after-scope" in line 109 of rethrow_located.hpp 
https://github.com/stan-dev/stan/blob/master/src/stan/lang/rethrow_located.hpp#L109

#### Description:

No clue

#### Reproducible Steps:

Run R CMD check with g++-7 and -fsanitize=memory

#### Current Output:

https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc7-ASAN/rstanarm/tests/testthat.Rout.fail

#### Expected Output:

No errors

#### Additional Information:

I need to at least get this fixed in StanHeaders even if we can't do it for Stan 2.13.

#### Current Version:

v2.12.0

**Comment by bob-carpenter** [comment]
What is stack-use-after-scope?  I see lots of references online, but didn't see a definition of what it is.  Also lots of issues around making the test more robust in the sanitizer, so it could even be a false positive (?).

If you set

```
std::string msg(e.what());
o << ... << msg;
```

do you still get the problem?  You'll see that the use in our code is exactly like the example use given on cplusplus.com (my heroes):

http://www.cplusplus.com/reference/exception/exception/what/

This rethrow-located thing has been no end of trouble.  I don't know why it's so problematic.

**Comment by bob-carpenter** [comment]
I can't run `R CMD` anything in Stan because there's no R to build.  Do I have to use an RStan release to do that?  I can get Daniel to give me a hand with that next week if he's around.

**Comment by bob-carpenter** [comment]
And is it only a g++7 thing?  It doesn't look like there's even a supported version of g++ 7 yet:

https://gcc.gnu.org

https://gcc.gnu.org/gcc-7/changes.html

https://gcc.gnu.org/develop.html

**Comment by bgoodri** [comment]
You usually have to rebuild R with -fsanitize too. I'll see if I can get
that set up on the server.

**Comment by bgoodri** [comment]
It is true that it is not released yet, but it basically exists as the
develop branch of g++.

**Comment by bob-carpenter** [comment]
Does anybody know what stack-use-after-scope means?  My guess is that it thinks it's hanging onto the `const char*` for the `what()` call too long.  That's why I'd guess that assiging it to a local might get rid of the message.  But the usage it's complaining about is exactly like the textbook example of calling the `what()` method.

@bgoodri Could you try that?

**Comment by bob-carpenter** [comment]
I still don't know what this is or how to fix it.  @bgoodri?

**Comment by bgoodri** [comment]
I will guess a bug with g++-7
