### ISSUE TITLE
Line too long in stan-reference pdf

### ISSUE THREAD

**Issue by alvaro1101** [stan-dev/stan#2121]
#### Summary:

![screenshoot](https://cloud.githubusercontent.com/assets/23438323/20500222/e36e7ef8-b034-11e6-8e9e-10a003672245.jpg)
****

The file is the version 2.12.0 of the reference manual.

#### Disclaimer
I added this issue in the wrong place. I still don't know if this is the right place. If it's not, sorry again.

Álvaro.

**Comment by bob-carpenter** [comment]
Thanks for reporting.  I moved this to #2122.  We always have (or should have) a manual issue going for the next release.  The one for 2.13 just got merged, so we may not get these changes in until 2.14.
