### ISSUE TITLE
variables ending in _lpdf interpreted as user defined densities

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2123]
#### Summary:

From Ryan Giordano on the stan-users list:

This gives the compiler error `PARSER EXPECTED: <probability function argument>`:

```
data {
    real x;
}
parameters {
    real mu;
}
transformed parameters {
    real mu_lpdf;
    mu_lpdf = normal_lpdf(mu | 0, 1);
}

model {
    target += mu_lpdf;
}
```

#### Description:

The parser is almost certainly interpreting that as a user-defined probability function and looking for the arguments.  Should be easy to fix.

#### Reproducible Steps:

See above.

#### Current Version:
v2.12.0

**Comment by bob-carpenter** [comment]
As an aside, that program should just use `_lpd` or even `_lp` because the 'f' is for "function" and `mu` is not a function.

**Comment by betanalpha** [comment]
+1.  I wouldn’t at all be against not allowing variables ending with lpdf or lpmf.

**Comment by andrewgelman** [comment]
Wow--a triple negative!  That doesn't come along every day.
