### ISSUE TITLE
makefile rule "clean-all" references missing target "clean-libraries"

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2136]
#### Summary:
Please provide a short couple sentence summary.
makefile rule "clean-all" references target "clean-libraries" - https://github.com/stan-dev/stan/blob/develop/makefile#L192

#### Description:
Describe the issue as clearly as possible.
the stan makefile references a missing target, `make clean-all`  command exits with message:

> make: *** No rule to make target `clean-libraries', needed by `clean-all'.  Stop.
> make: *** Waiting for unfinished jobs....
>   removing dependency files

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue:

run command `make clean-all`

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

> ~/github/stan-dev/cmdstan/stan (develop)> make clean-all
> rm -f  
> rm -rf doc
> cd src/docs/stan-reference; rm -f *.brf *.aux *.bbl *.blg *.log *.toc *.pdf *.out *.idx *.ilg *.ind *.cb *.cb2 *.upa
> rm -f 
> rm -f 
> rm -f 
> rm -f 
> make: *** No rule to make target `clean-libraries', needed by `clean-all'.  Stop.
> make: *** Waiting for unfinished jobs....
>   removing dependency files
> 

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.13.0

**Comment by mitzimorris** [comment]
this is a problem for makefile in version 2.13.0:
https://github.com/stan-dev/stan/blob/v2.13.0/makefile

**Comment by mitzimorris** [comment]
if this was introduced during the release process, then we need to add additional checks to test makefile tasks - this would require running a make task that builds the math libraries, then running task `make clean-all`  to verify that it runs correctly.

**Comment by syclik** [comment]
Yikes. It was from when we restarted the script. I'll check your pull
request; I know how to fix it.
