### ISSUE TITLE
parser confused by rng in local block of generated quantities with declare & define

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2145]
#### Summary:

Parser throws an error when it should not

#### Description:

If you have a simultaneous declare and define where the right-hand side is a call to a `_rng` function in a local block of the generated quantities block, you get a parser error. Somehow, declaring in advance and defining later works.

#### Reproducible Steps:

This was a snippet from polr.stan in rstanarm
```
generated quantities {
  {
    int y_tilde = categorical_rng(theta);
  }
}
```

#### Current Output:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

ERROR: random number generators only allowed in transformed data block, generated quantities block or user-defined functions with names ending in _rng; found function=categorical_rng in block=local

ERROR at line 283

 281:          }
 282:          else {
 283:            int y_tilde = categorical_rng(theta);
                                                     ^
```

#### Expected Output:

None

#### Additional Information:

Don't hold up the release for this

#### Current Version:
v2.13.0

**Comment by syclik** [comment]
@bgoodri, for future reference, it does help if you give a complete example and better yet, if you provide a minimal example that shows the problem.

@bob-carpenter, this is a problem with local blocks.

This works:
```stan
model {
}
generated quantities {
  int y = categorical_rng(rep_vector(0.1, 10));
}
```

This does not work:
```stan
model {
}
generated quantities {
  {
    int y = categorical_rng(rep_vector(0.1, 10));
  }
}
```

and it provides this message:
```
> make issue-2145

--- Translating Stan model to C++ code ---
bin/stanc issue-2145.stan --o=issue-2145.hpp
Model name=issue_2145_model
Input file=issue-2145.stan
Output file=issue-2145.hpp

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

ERROR: random number generators only allowed in transformed data block, generated quantities block or user-defined functions with names ending in _rng; found function=categorical_rng in block=local

ERROR at line 5

  3:    generated quantities {
  4:      {
  5:        int y = categorical_rng(rep_vector(0.1, 10));
                                                        ^
  6:      }


make: *** [issue-2145.hpp] Error 253
```

Note, the "block = local" in the error message.

**Comment by bob-carpenter** [comment]
I reminded @mitzimorris and she'll work on this next rather than vector expressions.  Shouldn't be hard to fix.  It slipped both of our minds in the last release.

**Comment by mitzimorris** [comment]
fixed via PR https://github.com/stan-dev/stan/pull/2216
