### ISSUE TITLE
compound declare define not working for variables of type matrix

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2146]
#### Summary:
Compound declare define statements for matrix variables result in variable declaration only.

#### Description:
The Stan parser component for variable declarations is missing a specification for the definition component of a matrix variable declaration, so that the parser fails to record the variable definition.  The parsed variable declaration is treated as a variable which is declared but not defined.  Everything parses.  However, inspection of the generated code shows that the expected assignment of the definition to the variable is missing.

#### Reproducible Steps:
Write a Stan program which includes the following:

> transformed data {
>   matrix[2,3] m23;
>   matrix[2,3] yam23 = m23;
> }

#### Current Output:
The generated code for the model has the following:

>       // initialize undefined transformed variables to avoid seg fault on val access
>         stan::math::fill(m23,DUMMY_VAR__);
>         stan::math::fill(yam23,DUMMY_VAR__);
>         // assign variable definitions
> 

There should be an assignment to variable `yam23` - is it missing

#### Additional Information:
The fix is straightforward:  change the grammar so that the BOOST_FUSION_ADAPT_STRUCT for a matrix variable declaration includes the definition element.

#### Current Version:
v2.13.0

**Comment by bgoodri** [comment]
Is this the same problem? From polr.stan in the rstanarm package:
```
  vector pw_polr(int[] y, vector eta, vector cutpoints, 
                 int link, real alpha) {
    int N = rows(eta);
    int J = rows(cutpoints) + 1;
    vector[N] ll;
    if (rows(ll) == 0 && rows(eta) > 0) reject("this is a bug");
```
The last line is getting triggered somehow.

**Comment by bgoodri** [comment]
Also, I think this is the same issue
```
matrix[nc,nc] T_i = rep_matrix(0, nc, nc); // has NaNs in it
```

**Comment by mitzimorris** [comment]
this is a different problem.  the generator code needs to be reworked so that assigment follows directly after definition.

**Comment by bgoodri** [comment]
OK. I will make new issues for these.
