### ISSUE TITLE
pre and post ++ and -- operators

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2152]
#### Summary:

Allow `++x`, `x++`, `--x`, `x--` for (possibly indexed) variables `x` with usual C++ behavior for all relevant types in Stan.

#### Description:

See https://github.com/stan-dev/math/issues/462 for issue to implement underlying operations.

#### Current Version:
v2.13.0

**Comment by mitzimorris** [comment]
closing this; leaving #2322 open.
