### ISSUE TITLE
Suggestion Bayesian optimization of stan programs

### ISSUE THREAD

**Issue by evelynmitchell** [stan-dev/stan#2164]
#### Summary:
Following the NIPS 2016 [presentation](https://www.youtube.com/watch?v=gVzV-NxKa9U)  [paper](http://www.robots.ox.ac.uk/~twgr/assets/pdf/rainforth2016BOPP.pdf) and [code](https://github.com/probprog/bopp) on BOPP (bayesian optimization of probabilistic programming)
look at adding a similar functionality on top of stan.

That implementation is based on clojure on top of Anglican, but the principle applies to Stan.

#### Description:
Describe the issue as clearly as possible.
Bayesian Optimization is used to direct code rewriting to guide hyper parameter search most efficiently.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.13.1

**Comment by bob-carpenter** [comment]
Thanks for creating the issue.  We're trying to limit our issues to technical specs with concrete implementation plans.  For more open-ended functional specs, we tend to start on the dev group, then put something on our issue Wiki:  https://github.com/stan-dev/stan/wiki/Longer-Term-To-Do-List, and then try to hammer out technical specs on a dedicated Wiki page. Then it gets broken down into concrete issues and dumped back here on the issue tracker.  At least that's the plan.  Is there a paper or just a video?

If you'd like to get involved in Stan development, let us know and we can give you posting permission on the dev list, which is the place to start this discussion.
