### ISSUE TITLE
Printing a matrix seems wrong

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#2169]
#### Summary:
Matrix is printing incorrectly.

#### Description:
Matrix is printed as its transpose. I checked and arrays of everything else looks ok.

Perhaps we should print like how we expect the array expressions to be written out in the Stan language.

#### Reproducible Steps:
```stan
transformed data {
  int i[2, 3];
  real r[2, 3];
  vector[3] v[2];
  row_vector[2] rv[3];
  matrix[2, 3] m;

  i[1, 1] = 1;
  i[1, 2] = 2;
  i[1, 3] = 3;
  i[2, 1] = 4;
  i[2, 2] = 5;
  i[2, 3] = 6;

  r[1, 1] = 1;
  r[1, 2] = 2;
  r[1, 3] = 3;
  r[2, 1] = 4;
  r[2, 2] = 5;
  r[2, 3] = 6;

  v[1, 1] = 1;
  v[1, 2] = 2;
  v[1, 3] = 3;
  v[2, 1] = 4;
  v[2, 2] = 5;
  v[2, 3] = 6;

  rv[1, 1] = 1;
  rv[1, 2] = 4;
  rv[2, 1] = 2;
  rv[2, 2] = 5;
  rv[3, 1] = 3;
  rv[3, 2] = 6;

  m[1, 1] = 1;
  m[1, 2] = 2;
  m[1, 3] = 3;
  m[2, 1] = 4;
  m[2, 2] = 5;
  m[2, 3] = 6;


  print("i =  ", i);
  print("r =  ", r);
  print("v =  ", v);
  print("rv = ", rv);
  print("m =  ", m);
}
parameters {
  real<lower = 0, upper = 1> theta;
}
model { }
```

#### Current Output:
```
i =  [[1,2,3],[4,5,6]]
r =  [[1,2,3],[4,5,6]]
v =  [1
2
3,4
5
6]
rv = [1 4,2 5,3 6]
m =  [[1,2,3],[4,5,6]]
```

#### Expected Output:

For m:
```
m =  [[1,2],
[3,4],
[5,6]]
```
or
```
m =  [[1,
2,
3],[4,
5,
6]]
```
(I don't know if we should get rid of one set of square brackets.

#### Additional Information:
It looks like matrix is printing incorrectly.

I think it makes sense to follow the array expressions for printing, but that will be more work. Thoughts?

I don't know if the printing is done within the Stan math library. It seems reasonable that the printing is handled in the Stan library.

#### Current Version:
v2.13.1

**Comment by bob-carpenter** [comment]
Stan code generates the print.  We can do it however makes sense.  The syntax for the vector, row vector and matrix expressions hasn't been finalized, but I agree that's the form we want to use.  The goal is that someone could cut and paste what was printed out and use it as an input expression in Stan.

**Comment by bob-carpenter** [comment]
Matrix is not printing out as its transpose, by the way, and that's very close to what the matrix expressions will produce.  

```
matrix[2, 3] m;
m[1, 1] = 1;
m[1, 2] = 2;
m[1, 3] = 3;
m[2, 1] = 4;
m[2, 2] = 5;
m[2, 3] = 6;
print("m =  ", m);
```

**should** print 

```
m =  [[1, 2, 3], [4, 5, 6]]
```

It'd be initialized in Stan that way, because `[1, 2, 3]` is going to be a row vector.  In Eigen, the init is:

```
m << 1, 2, 3,
     4, 5, 6;
```

This all despite the fact that it uses column-major storage internally.

**Comment by syclik** [comment]
Yes, of course. I wasn't thinking right.

**Comment by syclik** [comment]
Sorry, I'm closing this issue. I definitely wasn't thinking right about the types. We can reopen once the array expressions are in.
