### ISSUE TITLE
code generate primitive versions of built-in functions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2196]
#### Summary:

RStan is currently exposing functions through regex matching and code generation.  This should be moved into the code generator for Stan itself. 

#### Description:

We need a separate file to be generated with these in the top-level namespace and some comments that RStan can interpret.

#### Current Version:
v2.14.0

**Comment by rok-cesnovar** [comment]
Done in stanc3 via the standalone-functions.
