### ISSUE TITLE
Update website after PyStan 2.14.0.0

### ISSUE THREAD

**Issue by ariddell** [stan-dev/stan#2199]
@syclik mentioned I should open an issue after PyStan 2.14.0.0 was released.

In the future, if there are instructions/checklists for PyStan to follow to do this, I will add them to the existing PyStan release checklist stan-dev/pystan#288

**Comment by syclik** [comment]
Looks like the only place that's absolutely necessary is in `citations/index.md`. There's a version number there. 

The other place is in the documentation: I had a link up for the old doc that matched pystan's version. I removed it.

By the way, this was the wrong repo for the issue -- it should have been on the website repo: https://github.com/stan-dev/stan-dev.github.io

Don't worry about it, though. I've got it fixed.
