### ISSUE TITLE
Mistake in code in section 12.5 Vectorizing Mixtures (Stan Reference 2.14.0)?

### ISSUE THREAD

**Issue by vasishth** [stan-dev/stan#2212]
#### Summary:
Please provide a short couple sentence summary.

There seems to be a mistake in the very first code chunk: 

```
   for (n in 1:N) {   
         target += log_sum_exp(log(lambda)
     + normal_lpdf(y[n] | mu[1], sigma[1]),
   log1m(lambda)
     + normal_lpdf(y[n] | mu[2], sigma[2]));
```

#### Description:
Describe the issue as clearly as possible.

I think the lambda terms should be lambda[1] and lambda[2] respectively. They can't be vectors (or k-simplex).

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

I implemented the code suggested above and it returned an error.

```
   log_sum_exp(vector, vector)
```

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.14.0

**Comment by betanalpha** [comment]
There are not multiple lambdas in that example — just a single mixture probability
that is the same for all times.  

In particular, the section is trying to demonstrate that you have to be careful when
vectorizing the densities (the last two arguments of log_mix) as there is a difference 
mixing each component separately or as a whole.  But it’s the same single mixture
probability in each case.

**Comment by bob-carpenter** [comment]
Thanks for reporting, but this isn't a bug.  It's not explained particularly well, so I'll add a clarification in the code along the lines of what Michael said above:

https://github.com/stan-dev/stan/issues/2122#issuecomment-275211339

We always have a running manual issue like the one above where you can add comments like this rather than starting a new issue.  I knock them all off before a release.
