### ISSUE TITLE
Stan parsers fails to catch forbidden data to var casting

### ISSUE THREAD

**Issue by wds15** [stan-dev/stan#2213]
#### Summary:
The stan parsers generates a program without error which cannot be compiled.

#### Description:
The ODE solver expects the x_r argument to be data only. When one nests the integrate_ode call sufficiently deep into functions and then manipulating the x_r argument within those functions does not result in a failure from the parser. Instead the C++ is created, but fails to compile as the manipulated x_r is casted to a var due to assignment to a variable which is local to a function.

#### Reproducible Steps:
Here is a Stan program which triggers the error (just try to compile this Stan program with cmdstan/rstan/whatever):

```
functions {
  real[] sho(real t,
             real[] y,
             real[] theta,
             real[] x_r,
             int[] x_i) {
    real dydt[2];
    dydt[1] = y[2];
    dydt[2] = -y[1] - theta[1] * y[2];
    return dydt;
  }

  // gets parsed, but fails to compile, probably due to propagation to
  // var in x_r argument
  real[,] do_integration_nested(real[] y0, real t0, real[] ts, real[] theta, matrix xmat_r, real[] x_r) {
    int x_i[0];
    // here the parser does not catch that x_r got propagated to var
    return(integrate_ode_rk45(sho, y0, t0, ts, theta, to_array_1d(xmat_r[1]), x_i));
  }

  real[,] do_integration(real[] y0, real t0, real[] ts, real[] theta, matrix xmat_r, real[] x_r) {
    int x_i[0];
    matrix[2,2] xmat_sub_r;
    xmat_sub_r <- block(xmat_r, 1, 1, 2, 2);
    // this is correctly refused by the parser
    //return(integrate_ode_rk45(sho, y0, t0, ts, theta, to_array_1d(xmat_sub_r[1]), x_i));
    return(do_integration_nested(y0, t0, ts, theta, xmat_sub_r, x_r));
  }
}
data {
  int<lower=1> T;
  real y[T,2];
  real t0;
  real ts[T];
}
transformed data {
  real x_r[1];
  matrix[2,2] xmat_r;
  xmat_r <- rep_matrix(0, 2, 2);
  x_r[1] <- 0;
}
parameters {
  real y0[2];
  vector<lower=0>[2] sigma;
  real theta[1];
}
transformed parameters {
  real y_hat[T,2];
  //y_hat = integrate_ode_rk45(sho, y0, t0, ts, theta, x_r, x_i);
  y_hat = do_integration(y0, t0, ts, theta, xmat_r, x_r);
}
model {
  sigma ~ cauchy(0, 2.5);
  theta ~ normal(0, 1);
  y0 ~ normal(0, 1);
  for (t in 1:T)
    y[t] ~ normal(y_hat[t], sigma);
}

```

#### Current Output:
Stan parses OK, but fails to compile

#### Expected Output:
A decent error message should be given by the parser. I know this is hard as things are very nested, but optimally the Stan parser should point out where the unintenional casting from data to var occurs. The least is to stop translating the Stan program and tell the user that the ODE integrator expects data as x_r.

#### Current Version:
v2.14.0

**Comment by bob-carpenter** [comment]
I assigned it to myself and I'll fix it. We don't want to allow this in general.  Luckily, @mitzimorris is just wrapping up a pull request that's going to make it possible to get the conditions right.  There wasn't previously enough scope information being passed down.

**Comment by bob-carpenter** [comment]
Stage this for after https://github.com/stan-dev/stan/pull/2216

**Comment by bob-carpenter** [comment]
That version labeled "correctly rejects" with `xmat_sub_r` declared in the function body will be a false positive if you pass only data variables to the function.  

To get this right, we need to trace instantiations of argument variables to functions.

So I take back what I said in https://github.com/stan-dev/stan/issues/2213#issuecomment-275756178 --- I don't see how to fix this.  At least not without figuring out how to trace instantiations of functions.  It's surely possible, but would be a huge amount of work.

The closure-based approach to functions I want to allow won't have this problem because the data won't be an argument.  It will have the problem that somewhere the parameters need to be declared (as @wds15 points out) in order to calculate the right Jacobians in the ODE solvers.

**Comment by bob-carpenter** [comment]
@syclik Here's your ping.  See:  https://github.com/stan-dev/stan/issues/2213#issuecomment-301935693

**Comment by mitzimorris** [comment]
in the example model:

* function `do_integration` calls function `do_integration_nested` and passes in a local variable `xmat_sub_r` as the 6th argument
* function `do_integration_nested` calls `integrate_ode_rk45` and the 6th argument to `integrate_ode_rk45` is derived from `xmat_sub_r` which causes a compile-time error.

adding the "data" qualifier to the 5th arg of `do_integration_nested` allows the parser to detect this problem and generate the appropriate error message:

```
  real[,] do_integration_nested(real[] y0, real t0, real[] ts, real[] theta, data matrix xmat_r, real[] x_r) {
    int x_i[0];
    return(integrate_ode_rk45(sho, y0, t0, ts, theta, to_array_1d(xmat_r[1]), x_i));
  }
```

```
Function argument error, function: do_integration_nested, argument: 5 must be data only, found expression containing a parameter varaible.
```

(per bugfix on branch https://github.com/stan-dev/stan/tree/bugfix/2369-type-qualifier-data-function-args, not yet ready for PR).
