### ISSUE TITLE
general include mechanism for Stan programs

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2224]
#### Summary:

Add a general file include mechanism in the Stan language to support system and user libraries of Stan functions.

#### Description:

Follow C/C++ convention with system libs in braces:

```
#include <gp>
```

and quoted strings for user libs

```
#include "foo/my_gp_funs.stan"
```

The `compiler` class in `stan::lang` and the `bin/stanc` executable will need to be given an ordered search path for system files and for user files.  

We might want to 

* use `@` instead of `#`, 

* relax the line-initial constraint, and 

* remove the need for quotes around paths.

This deals with half of #810 and generalizes #1294 (both of those issues are now closed).

#### Current Version:
v2.14.0

**Comment by martincerny** [comment]
I am actually itching to have a go at implementing this (at least try to :-) ). To be able to think about this clearly - what are the use cases that need to be addressed? I think mostly you want to reuse functions, but I noticed rstanarm also uses includes in the ```data``` section. Is this encouraged? Are there other legitimate/non-hacky use cases for an include mechanism?

In general, I am unsure it is wise to mimic the behavior of C++ preprocessor as it has history of enabling users to write very hard-to-maintain code (especially if the include mechanism gets later extended with compile-time flags similar to ```#define / #ifdef```). My ideal would be closer to "import" in Python/Java. In practice this could translate some of the following design choices:

- allow ```include``` only at specific places (beginning of file/between top-level blocks/at block beginning)
- don't allow a file to be included twice
- included files are somehow encapsulated (e.g. they contain top level blocks)
- included files are self-sufficient: during model development an included file can be checked for syntax correctness separately (e.g. "Check on save" in RStudio) as it will not be dependent on the contents of the top-level file

Still the actual implementation of the include mechanism would be just pasting the file contents at the right place (because that's easier to do), but IMHO it would feel closer to modern languages with only minor modifications to the parser (e.g. allow multiple ```functions``` blocks in a single program).

**Comment by bob-carpenter** [comment]
I've already finished the guts of the raw include mechanism
on this branch:

  https://github.com/stan-dev/stan/tree/feature/2224-stan-includes

There's a new class called io::program_reader whose constructor
reads a named input stream, expands the includes relative to an
ordered sequence of directories in which to search, and keeps a
record of line numbers.  Once constructed it provides functions to 
  
  * returns the whole program after includes, and

  * map a line number in the whole program back to where it
    came from as a stack of includes and line numbers.

It still needs to be plumbed through the compiler, including
the search path, and then up through the interfaces.

Right now, there are no safeguards, and it allows

  * #include to show up anywhere

  * files to be included more than once

There's no header guard strategy, either.  I should at least
make sure files don't get included twice recursively.  

There's also no way to independently test a file.  What would
be nice would be to have a way to compile a file of Stan
functions into C++ functions.  As is, the functions are all
static in the sense that they can't depend on the data provided
to a model (as they would be allowed to do if they were closures
or if they were class methods rather than static functions).  So
they should be independently compilable.  They do depend on
some of the inputs that are available in context (such as a function
ending in _rng having access to the core RNG to allow reproducibility).

Let me run the question by everyone in the Stan meeting.  I'd
be OK with just having includes in the function block, but I seem
to recall others thought they'd be useful elsewhere and I shouldn't
disallow it.  Either way, we should be able to figure out a way
to generate C++ code just for functions, which in and of itself
would be super useful.  If you want to get your feet wet, you might
try writing a function in stan/lang/compile_functions.hpp that
takes a program that only consists of functions and compiles it
with the necessary includes.  What we really need for the R interface
is something that then instantiates that with double values and
drops it in the top-level namespace. 

- Bob

P.S.  I also like the way Java approaches things.  Much much easier
to deal with than C++ on all fronts in my experience (though
I've only been at C++ for 5 years, whereas I spent nearly 10 years
working primarily in Java).

**Comment by wds15** [comment]
Let's discuss at the meeting, but I definitely use includes in all blocks.

For example, I include code snippets into the transformed data block which reformat an input data set into something Stan model friendly. The input data set is standard and can't be changed, but the way I handle this data in Stan is different. Hence, an include in transformed data is needed.

**Comment by sakrejda** [comment]
Couldn't that just be an included function called in the transformed data
block? I guess only if we had tuples.

**Comment by bob-carpenter** [comment]
Right -- we'd need tuples.  Or call-by-reference.  But I fear call-by-reference is way too confusing.  

If we start allowing includes everywhere, it's going to be hard to go back in the future without breaking a lot of user code. 

Because people had uses for includes everywhere and that's what RStan did, we decided to just do that with the Stan feature a few meetings ago when I brought this up.

**Comment by martincerny** [comment]
OK, I'll have a look at compiling the functions block separately.

As for the includes:
- OK I see that the code is already implemented and works. Since the chosen way to implement this is oblivious of the context of the ```#include``` statements, I guess I am out of luck :-) But I will still try a few arguments, just to feel better...
- I still think allowing includes everywhere has the potential to create a lot of mess and hair scratching when debugging code (I think there is a good reason why no other major language has anything similar to C preprocessor). I understand that doing exactly what RStan does has a lot of value (especially if people already depend on it). Also you are the core team and I am just someone arguing on the Internet :-). But once this gets introduced into stan proper, there really is no going back. As far as I understand the ```transformed data``` use-case, it could be handled by an ```#include``` at the top level, if multiple consecutive ```transformed data``` blocks were allowed. Or am I wrong?
- A specific practical concern I see with "includes anywhere" is that it will be harder to provide good editor support for the included files.
- I also think that some of the use cases for includes somewhere in the middle of a block (and bunch of others) could be adressed by conditional compilation. Once the include mechanism gets implemented C-style, implementing conditional compilation that does not allow ugly code will be hard/inconsistent (for example, Rust has conditional compilation, but it ensures that the branches contain either a single statement or a complete program block).

**Comment by bgoodri** [comment]
We wrote the #include mechanism in `rstan::stan_builder` to facilitate
building R packages (such as rstanarm) with multiple Stan programs. We use
includes in all the blocks to minimize code duplication. We know from
experience that it is hard to debug and you have to have a bunch of tabs
open to see what is going on in a Stan program that includes Stan snippets
from files in the inst/chunks directory. But only having #includes in the
functions block would be a much more severe problem.

**Comment by bob-carpenter** [comment]
> On Apr 5, 2017, at 3:27 PM, Martin Černý <notifications@github.com> wrote:
> 
> OK, I'll have a look at compiling the functions block separately.
> 
> As for the includes:
> 
> 	• OK I see that the code is already implemented and works.

It's already implemented in RStan, but it's not implemented anywhere
else, so now's the time to change the behavior.

It does sound like our devs want to be able to include everywhere in
their own models.

> Since the chosen way to implement this is oblivious of the context of the #include statements, I guess I am out of luck :-) But I will still try a few arguments, just to feel better...
> 	• I still think allowing includes everywhere has the potential to create a lot of mess and hair scratching when debugging code (I think there is a good reason why no other major language has anything similar to C preprocessor).

We all realize this.

> I understand that doing exactly what RStan does has a lot of value (especially if people already depend on it). Also you are the core team and I am just someone arguing on the Internet :-).

We try to pay attention no matter who's talking.

> But once this gets introduced into stan proper, there really is no going back.

Not without more pain.

> As far as I understand the transformed data use-case, it could be handled by an #include at the top level, if multiple consecutive transformed data blocks were allowed. Or am I wrong?

Not sure what you mean by top level here.  The order of blocks is functions, data,
then transformed data, so no way to put transformed data at the top.


> 	• A specific practical concern I see with "includes anywhere" is that it will be harder to provide good editor support for the included files.

Seems likely.

> 	• I also think that some of the use cases for includes somewhere in the middle of a block (and bunch of others) could be adressed by conditional compilation. Once the include mechanism gets implemented C-style, implementing conditional compilation that does not allow ugly code will be hard/inconsistent (for example, Rust has conditional compilation, but it ensures that the branches contain either a single statement or a complete program block).

Yikes.  That sounds like even more complication.  It'd be easy to allow in
some sense, because we can just compile down to C++.

Ben's implemented conditional evaluation of model blocks using data constants
and conditionals in RStanArm.  This still requires both branches of the conditional
to compile, it creates a larger object file (not a bottleneck), requires the appropriate
data constant to be passed in, and incurs a tiny bit of overhead in the conditional
(conditionals are very expensive, but not compared to what else is going on in those
programs).

- Bob

**Comment by bob-carpenter** [comment]
If Ben needs these for RStanArm, they're going to get in. :-)  We'll warn people, but that's a losing battle.

One thing we should be able to do is dump out the entire composed program to allow for easier debugging.  That's why I wanted to get the file locations plumbed through before releasing a general version.

**Comment by martincerny** [comment]
My main idea was to force/encourage/allow a pattern like this:

main.stan:
```
#include "custom_funcs.stanh"
functions {
     ...
}

data {
   ...
}
#include "custom_transformations.stanh"
transformed data {
  ...
}
....

````
custom_funcs.stanh:
```
functions {
   int f1() {}
}
```

custom_transformations.stanh:
```
transformed data {
   int newX = x + 5;
}
```

That's what I meant by includes at the top level.
This would require the parser to allow multiple sections of the same type (but only consecutive), and would give a reasonable encapsulation of the included code. The intended difference between ```.stan``` and ```.stanh``` files is that ```.stanh``` files are not required to contain any executable section (model or generated data) to be correct and can thus be better checked in the editor.

Further, if files are never included twice, the ```.stanh``` files are free to include any prerequisities they need and thus could be completely independently checked in editor.

Hope this makes sense.

**Comment by wds15** [comment]
I like this way of include, but I think this should be added to language as a feature in itself. It would be a generalization of the rather old idea to have multiple generated quantities blocks (which can be called independent of the others).

Other than that, I really think that if users start to include code-snippets like in rstanarm then it is safe to assume that these are quite advanced users. Giving such a crowd help in debugging is great, but much less babysitting is needed.

Personally I always let stanc_builder create from foo.stan a foo_run.stan which has all includes spelled out. Analyzing what went wrong is then no problem at all. Maybe you want to replace each include with

// comment on which file included this
file-content

such that the foo_run.stan file would allow easy tracing where things came from, but I see this completely optional as I could just start my own include files with a respective comment.

**Comment by sakrejda** [comment]
I can't forsee us supporting programs with non-top-level includes on the
mailing list.  If this is just to get rstanarm standardized via core Stan
that's fine but at least let's be clear in the manual that this is a
footgun feature and you're not likely to get support on the mailing list if
you have non-top-level includes.

I still can't think of a case where this nested include stuff can't be
replaced by functions (with tuple returns).

**Comment by bgoodri** [comment]
And we use includes in the data block.

**Comment by sakrejda** [comment]
Sounds like you should call an included function with no arguments that
returns a tuple you unpack (or we could support the python syntax):

#include special_config_function.stan.h

(a, b, c) = dump_config_vars();

**Comment by sakrejda** [comment]
Yeah, functions/tuples won't do that, but having multiple data blocks
wouldn't hurt interpretabillity of the program and that doesn't require
within-block includes.

**Comment by bob-carpenter** [comment]
We don't have tuples, yet anyway.

- Bob

**Comment by bob-carpenter** [comment]
I'd just as soon keep all the functions at the top as in the first example.

But we're thinking about adding closures with C++11 to cut down on all the packing into arrays and unpacking our functionals do now (integrate ode, and the new solvers in the pipeline).

This is another case where we really want to be able to include statistically functional units, like a hierarchical model, but that's spread over multiple blocks in Stan.

**Comment by sakrejda** [comment]
I get it, I'm just imagining the users' list nightmare.

**Comment by martincerny** [comment]
@bob-carpenter I think including a full submodel that spans multiple blocks is orthogonal to the question at hand - it requires more parser flexibility (interleaved blocks) and once the parser gets more flexible, it only requires an include at the top level.

**Comment by bob-carpenter** [comment]
> On Apr 6, 2017, at 11:30 AM, Martin Černý <notifications@github.com> wrote:
> 
> @bob-carpenter I think including a full submodel that spans multiple blocks is orthogonal to the question at hand

I don't even know how to specify it, much less implement it.  But if we did implement something like this, it'd probably subsume the simple include mechanism.

**Comment by beyondpie** [comment]
> My main idea was to force/encourage/allow a pattern like this:
> 
> main.stan:
> 
> ```
> #include "custom_funcs.stanh"
> functions {
>      ...
> }
> 
> data {
>    ...
> }
> #include "custom_transformations.stanh"
> transformed data {
>   ...
> }
> ....
> ```
> 
> custom_funcs.stanh:
> 
> ```
> functions {
>    int f1() {}
> }
> ```
> 
> custom_transformations.stanh:
> 
> ```
> transformed data {
>    int newX = x + 5;
> }
> ```
> 
> That's what I meant by includes at the top level.
> This would require the parser to allow multiple sections of the same type (but only consecutive), and would give a reasonable encapsulation of the included code. The intended difference between `.stan` and `.stanh` files is that `.stanh` files are not required to contain any executable section (model or generated data) to be correct and can thus be better checked in the editor.
> 
> Further, if files are never included twice, the `.stanh` files are free to include any prerequisities they need and thus could be completely independently checked in editor.
> 
> Hope this makes sense.

Hi @martinmodrak 
I'm also looking for this kind of include. My situation is I have a common data, but want to explore different models. So I hope to include the data block with some modifications (in data block for each separated model, for example, add one data element) in each model. 

From the reference manual, it seems no such support, right ?

**Comment by bob-carpenter** [comment]
See:  https://mc-stan.org/docs/2_23/reference-manual/includes-section.html

**Comment by beyondpie** [comment]
Thanks! I read this part. But when using cmdstan,  it seems that  make cannot find my local include file even I use the full-path.  I should add  the dir to some variables, like  CXXFLAGS, right ? I will test this later. 

Thanks again!

**Comment by mitzimorris** [comment]
from the CmdStan User's Guide:


> The makefile rules first invoke the stanc compiler to translate the Stan model to C++ , then compiles and links the C++ code to a binary executable. The makefile variable STANCFLAGS can be used to to override the default arguments to stanc, e.g.,

```
> make STANCFLAGS="--include_paths=~/foo" examples/bernoulli/bernoulli
```

**Comment by beyondpie** [comment]
@mitzimorris  Glad to know this detail !
