### ISSUE TITLE
sbpwdddc

### ISSUE THREAD

**Issue by AlexGKim** [stan-dev/stan#2225]
#### Summary:
Please provide a short couple sentence summary.

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.14.0

**Comment by bob-carpenter** [comment]
@AlexGKim Why did you create a junk issue and close it right away.

This is the second word salad issue that was instantly opened and closed on Stan and I wonder if it's some kind of spam or SEO hacking someone's doing.

**Comment by AlexGKim** [comment]
Sorry this was an accident.  I had the git issue page open, typed thinking I was in another window, and ended up opening the issue.  Would it be possible for an admin to delete it?  Perhaps the first word salad issue was the same thing.

Cheers
Alex

**Comment by bob-carpenter** [comment]
Thanks for getting back to us.  I don't want to rewrite our history, so we'll just leave it.  Especially now that we know the cause.
