### ISSUE TITLE
Transpiler should check input and output stream states

### ISSUE THREAD

**Issue by mystatistic** [stan-dev/stan#2227]
#### Summary:
Stan transpiler does not check whether the input and output files can be read and written respectively.

#### Description:
If the output directory/file cannot be written (e.g. due to Unix permissions), then the `stanc` command (and presumably all other interfaces that invoke the transpiler) does not report any errors but obviously the output stream is in an invalid state and doesn't get written to. When using cmdstan, this encourages `make` to try to link the C++ model, but `g++` then gives a fatal error saying `No such file or directory` for the model header `.hpp` file, which looks odd because there are no signs that the `stanc` step didn't work.

Similarly if the input file does not exist or is not readable, then `stanc` says there's a syntax error on line 1 instead of reporting failure to open the file, and in this case a slightly more descriptive error message might be helpful.

#### Reproducible Steps:
Described using cmdstan/`stanc` interface, but fix felt likely to be in main stan repository.

Missing/unreadable input file case:

```bin/stanc nonexistent-file.stan --o=nonexistent-file.hpp```

Non-writable output file case:

```
touch examples/bernoulli/bernoulli.hpp
chmod ugo-w examples/bernoulli/bernoulli.hpp
bin/stanc examples/bernoulli/bernoulli.stan --o=examples/bernoulli/bernoulli.hpp
```
(The non-writable output file case can be easily reached using the documented `make` command as well.)

#### Current Output:
Missing/unreadable input file case:
```
$ bin/stanc nonexistent-file.stan --o=nonexistent-file.hpp
Model name=nonexistent_file_model
Input file=nonexistent-file.stan
Output file=nonexistent-file.hpp

SYNTAX ERROR, MESSAGE(S) FROM PARSER:


ERROR at line 1

  1:
       ^

PARSER EXPECTED: <model declaration (or perhaps an earlier block)>

$ echo $?
253
```

Non-writable output file case:
```
$ touch examples/bernoulli/bernoulli.hpp

$ chmod ugo-w examples/bernoulli/bernoulli.hpp

$ bin/stanc examples/bernoulli/bernoulli.stan --o=examples/bernoulli/bernoulli.hpp
Model name=bernoulli_model                  
Input file=examples/bernoulli/bernoulli.stan
Output file=examples/bernoulli/bernoulli.hpp

$ echo $?
0

$ ls -l examples/bernoulli/
-r--r--r--+ 1 mystatistic mystatistic    0 Feb  8 16:43 bernoulli.hpp
```
(i.e. the file still has 0 bytes and `stanc` didn't in fact succeed in writing it despite no error messages on stdout/stderr and a return code of EXIT_SUCCESS)

#### Expected Output:
Missing/unreadable input file case:
```
$ bin/stanc nonexistent-file.stan --o=nonexistent-file.hpp
Model name=nonexistent_file_model
Input file=nonexistent-file.stan
Output file=nonexistent-file.hpp

FILE I/O ERROR: Unable to read the input file 'nonexistent-file.stan'

$ echo $?
253
```

Non-writable output file case:
```
$ touch examples/bernoulli/bernoulli.hpp

$ chmod ugo-w examples/bernoulli/bernoulli.hpp

$ bin/stanc examples/bernoulli/bernoulli.stan --o=examples/bernoulli/bernoulli.hpp
Model name=bernoulli_model                  
Input file=examples/bernoulli/bernoulli.stan
Output file=examples/bernoulli/bernoulli.hpp

FILE I/O ERROR: Unable to write to the output file 'examples/bernoulli/bernoulli.hpp'

$ echo $?
253
```

#### Additional Information:
I have being trying to run cmdstan on our local cluster, which suffers from permission problems, and a more helpful error message and return code might have assisted me in diagnosing the issue sooner.

#### Current Version:
v2.14.0

**Comment by syclik** [comment]
Thanks for a clear issue!

We should be able to fix this quickly.

**Comment by syclik** [comment]
@seantalts, I added you to the issue, but no need to tackle it if you don't have time. I'm not sure if it's code in stan-dev/stan or cmdstan off the top of my head.

**Comment by bob-carpenter** [comment]
I can do this if nobody else wants to.  I have include basically working (other than error reporting) and this change has to work with that.
