### ISSUE TITLE
Exact reproducibility bug

### ISSUE THREAD

**Issue by wds15** [stan-dev/stan#2232]
#### Summary:
Exact reproducibility is not given when warmup is enabled.

#### Description:
Output from the sampler is not exactly the same when starting it on the same platform with the exact same seed. This happens whenever warmup is performed. When warmup=0 then the Stan program is again exactly reproducible.

#### Reproducible Steps:
Attached is a zip file containing an example which used clang on Mac. The problem also happens when using gcc 6 with cmdstan.

[normal_exact_repo_bug.zip](https://github.com/stan-dev/stan/files/776911/normal_exact_repo_bug.zip)

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
It must be exactly reproducible regardless if warmup was performed or not.

#### Additional Information:
Provide any additional information here.

clang version:
```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
```
g++ version:
```
g++-mp-6 (MacPorts gcc6 6.3.0_0) 6.3.0
```

#### Current Version:
v2.14.0

**Comment by betanalpha** [comment]
I cannot recover this behavior on the dev branch CmdStan
with clang.  When the same seed is used multiple times 
each execution recovers exactly the same output save for
the timing.

```
> ./normal sample random seed=488338392
> mv output.csv output.1.csv

> ./normal sample random seed=488338392
> mv output.csv output.2.csv

> diff output.1.csv output.2.csv
1044,1046c1044,1046
< #  Elapsed Time: 0.006719 seconds (Warm-up)
< #                0.01308 seconds (Sampling)
< #                0.019799 seconds (Total)
---
> #  Elapsed Time: 0.006626 seconds (Warm-up)
> #                0.013641 seconds (Sampling)
> #                0.020267 seconds (Total)
```

**Comment by wds15** [comment]
Thanks much Michael! I was really hoping to be wrong. I checked with the cmdstan 2.14.0 and the dev version using clang. Both versions of cmdstan are exactly reproducible.

However, when reading in the cmdstan csv files using `read_stan_csv` the output is not exactly the same when warmup is enabled. That is, when I read the csv files with basic R facilities, then I also get an exact match between respective files. If you agree, then we can close this issue fortunately. I will verify the issue in rstan on another system and report the problem there. If gcc6 causes any problem remains to be tested, but my working assumption is that this is not the case, but rather the read_stan_csv command is the source of all trouble here.

Sorry for the noise, but these things make me really nervous.

[exact_repo_bug.zip](https://github.com/stan-dev/stan/files/779556/exact_repo_bug.zip)

**Comment by wds15** [comment]
Should anyone want to follow this up what happened:

https://github.com/stan-dev/rstan/issues/393

**Comment by bob-carpenter** [comment]
Thanks for following up on this, @betanalpha.
