### ISSUE TITLE
feature request: abbreviated bound labels

### ISSUE THREAD

**Issue by sdewaele** [stan-dev/stan#2238]
#### Summary:
Allow using abbreviated labels for variable bounds to declutter a Stan script.

#### Description:
Currently, parameter bounds can only be described by is full label, e.g.
```
real<lower=0, upper=1> a;
real<lower=0, upper=1> b;
real<lower=0, upper=1> c;
```

The request is to allow abbreviated labels for `lower` and `upper`. This helps to declutter your Stan script. E.g. the following would be valid code:
```
real<low=0, up=1> a;
real<low=0, up=1> b;
real<low=0, up=1> c;
```
as well as:
```
real<l=0, u=1> a;
real<l=0, u=1> b;
real<l=0, u=1> c;
```

#### Current Version:
v2.14.0

**Comment by bob-carpenter** [comment]
Thanks for submitting a pull request, but we don't want to either break backward compatibility or introduce multiple ways of expressing the same thing.  Unless anyone on the dev team disagrees vehemently, I'm going to close this issue.

**Comment by syclik** [comment]
Bob, I whole-heartedly agree with you.
