### ISSUE TITLE
Update GP chapter in manual

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/stan#2240]
#### Summary:

Update GP code in manual to reflect best-practices GP coding.

#### Description:

Current GP code does not reflect the most up-to-date Stan programming standards. We need to update these code snippets to incorporate the most efficient constructions of Gaussian process priors.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.14.0

**Comment by ariddell** [comment]
Is this mainly about cov_exp_quad?

**Comment by rtrangucci** [comment]
And `cholesky_decompose`, coupled with `multi_normal_cholesky` and multivariate version of the non-centered-parameterization

**Comment by betanalpha** [comment]
Plus priors!

**Comment by rtrangucci** [comment]
Of course!

**Comment by Emaasit** [comment]
@rtrangucci Please also add a subsection on constructing kernels e.g. a sum or product of kernels. For example: 
$$f(x_1, x_2) = f_1(x_1) + f_2(x_2)$$
`cov_all = cov_exp_quad(**x_1**, alpha, length_scale) + cov_exp_quad(**x_2**, alpha, length_scale);`

**Comment by bob-carpenter** [comment]
@rtrangucci  If you have time, now's the time to get this in for the next manual.  Otherwise, I pushed this to the future.

**Comment by rtrangucci** [comment]
I have time now, I can get a draft together by end of next week.


Rob

**Comment by bob-carpenter** [comment]
Great.  

- Bob

**Comment by bob-carpenter** [comment]
The alternative's to write up a case study.  I'm pretty sure we're going to be moving the manual to bookdown and trying to move these example models into general case studies.  Maybe you already have that from StanCon?

**Comment by rtrangucci** [comment]
I do already have this from StanCon. It has all the code I want to add to the manual: https://github.com/stan-dev/stancon_talks/blob/master/2017/Contributed-Talks/08_trangucci/hierarchical_GPs_in_stan.Rmd

**Comment by bob-carpenter** [comment]
Thanks.  I added a link to the StanCon talks on the docs page of mc-stan.org.

**Comment by rtrangucci** [comment]
Taken care of with #2301
