### ISSUE TITLE
more undefined behavior

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2248]
#### Summary:

src/stan/lang/ast/node/array_expr.hpp seems not to initialize its bool values

#### Description:

Including this file yields a `runtime error: load of value 3, which is not a valid value for type 'bool'`

See:
https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-UBSAN/rstan/build_vignettes.log
http://stackoverflow.com/questions/31420154/runtime-error-load-of-value-127-which-is-not-a-valid-value-for-type-bool

#### Reproducible Steps:

Build with `-fsanitize=undefined` in CFLAGS

#### Current Output:

Build error

#### Expected Output:

No build error

#### Current Version:
v2.14.0

**Comment by mitzimorris** [comment]
fixed and PR https://github.com/stan-dev/stan/pull/2251 needs review  - @bgoodri could you please run the check w/ CFLAGS `-fsanitize=undefined`   (mac's clang++ doesn't have this option in Xcode llvm)

**Comment by bob-carpenter** [comment]
fixed with #2256
