### ISSUE TITLE
clean up OperandsAndPartials

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2252]
#### Summary:

* The class `partials_vari`in `OperandsAndPartials.hpp` is redundant and should be replaced by including and using `precomputed_gradients.hpp`

* reuse `d_xN` in `d_x(N+1)` rather than recomputing

* replace `all_varis` allocation with direct calls to `array_alloc` rather than roundabout `vari::operator new` calls

#### Current Version:
v2.14.0

**Comment by seantalts** [comment]
Closing since I think this belongs in the math repo https://github.com/stan-dev/math/issues/546
