### ISSUE TITLE
parser rejects valid Stan code

### ISSUE THREAD

**Issue by wds15** [stan-dev/stan#2254]
#### Summary:
The current develop parser rejects code which is OK in 2.14.0

#### Description:
Things worked with the released 2.14.0 but stopped working in the current develop as of 210cc283e0e1da24bd6408f417729572a84c01f0

#### Reproducible Steps:
Here is a small Stan program:

```c++
functions {
  matrix slice_m(matrix data, int[] S, int s) {
     int l = sum(S[1:(s-1)]);
     int u = l + S[s];
     return(data[(l+1):u,:]);
   }

  // given as input a 2D matrix of size NxM and a slicing vector S, the
  // output is a 1D array with each slice flattened to a 1D column major
  // ordering.
  real[] to_array_1d_sliced(matrix data, int[] S) {
    int N = dims(data)[1];
    int M = dims(data)[2];
    real res[N*M];
    int rs = 1;

    for(s in 1:size(S)) {
      res[rs : (rs + M*S[s] - 1)] = to_array_1d(slice_m(data, S, s));
      rs = rs + M*S[s];
    }

    return(res);
  }
}
model {}
```

#### Current Output:
2.14.0 parses and runs this code. current develop stops in the stanc parsing step with

```
Model name=model_problem
Input file=../bugs/stan-parse-2/problem.stan
Output file=../bugs/stan-parse-2/problem.hpp

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

Illegal statement beginning with non-void expression parsed as
  res[rs:((rs + (M * S[s])) - 1)]
Not a legal assignment, sampling, or function statement.  Note that
  * Assignment statements only allow variables (with optional indexes) on the left;
    if you see an outer function logical_lt (<) with negated (-) second argument,
    it indicates an assignment statement A <- B with illegal left
    side A parsed as expression (A < (-B)).
  * Sampling statements allow arbitrary value-denoting expressions on the left.
  * Functions used as statements must be declared to have void returns


ERROR at line 18

 17:        for(s in 1:size(S)) {
 18:          res[rs : (rs + M*S[s] - 1)] = to_array_1d(slice_m(data, S, s));
              ^
 19:          rs = rs + M*S[s];

PARSER EXPECTED: "}"
```

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
develop

**Comment by bob-carpenter** [comment]
Thanks for the simple reproducible example.  I verified this is indeed a bug in the current version of develop.  @wds15 It's helpful if you just edit out the bits of the form you don't fill in.  Here's a simpler model that tickles the bug:

```
functions {
  void foo() {
    real a[10];
    a[1:2] = a[2:3];
  }
}
model { }
```

And there seem to be problems with `<-` as well if you replace `=` with `<-` --- it seems to be taking `<` as an operator and then overcommitting when it can't negate `a[2:3]`.
