### ISSUE TITLE
Standalone compilation of functions block

### ISSUE THREAD

**Issue by martincerny** [stan-dev/stan#2267]
#### Summary:
In order to call Stan functions directly from R, the c++ file must contain:

- double-instantiated only functions, (not templated for double/var)
- R comments in generated code that R needs

To do this, add function `stan/lang/compile_functions.hpp` that takes a program that only consists of functions and compiles to C++ it with the necessary includes.

This is needed to circumvent the current Rstan hack which uses regexes to munge the transpiled hpp code - we want to go _directly_ from Stan program to c++ code that is callable from R without further processing.

#### Description:
Originated in the discussion of #2224 - it would be useful to be able to parse and compile a file that contains only a functions block. The primary use case is to let thos functions then be invoked from R, but it could also help in allowing truly modular Stan programs.

#### Current Version:
v2.14.0

**Comment by martincerny** [comment]
I am trying this as my first task in the Stan codebase (but it seems I cannot assign myself nor add a "feature" label)

**Comment by bob-carpenter** [comment]
I think we have to somehow make you a member of the project.  Also, you want to coordinate with @mitzimorris.  I believe the recent pull request to remove the requirement of a `model { }` block will make this very easy to generate functions only.

The tricky part is going to be finding minimal headers.  I fear there will be dependencies on code that's only in stan-dev/stan rather than just in stan-dev/math, which would be ideal (much more minimal include).  

The other thing we really want out of this function is an ability to (a) control the namespace in which they get generated from the call (`vector<string>` for namespaces would work), and (b) have them instantiated with only `int` and `double` primitive types.  Having both of these will let us generate functions that can be used directly by Rcpp.

**Comment by martincerny** [comment]
Nice codebase you have! Getting into it was easier than I expected.

I have some working code with a rudimentary test which shows that the generated functions can be parsed and instantiated. The feature is not yet done, but I think it is the correct time to ask for some feedback (all tests currently pass).

The changes I made can be found at https://github.com/martincerny/stan/tree/feature/2267-standalone-functions and a comparison to stan/develop can be reviewed here:
https://github.com/stan-dev/stan/compare/develop...martincerny:feature/2267-standalone-functions?expand=1

What it does:
- There is now a function ```stan::lang::compile_functions()``` that runs the normal parser, but generates only the function block. The normal parser already worked with models that contain only the function block, only difference from ```stan::lang::compile()``` is in the way the output is generated: only the functions block is created, it is possible to specify the namespace for the functions block and no class declaration is created.
- ```stanc_helper()``` now invokes ```compile_functions()``` on files with the extension ```.stanfuncs``` and allows for a ```-namespace``` command line parameter to specify the target namespace
- Compiling ```.stanfuncs``` files with stanc as "functions only" has been added to ```make/tests``` so tests can depend on the compiled ```.hpp``` files.

Some specific points I'd like someone from the core team to give feedback on:
- The decision to choose mode of compilation (functions only / model) by file extension and the choice of the ```.stanfuncs``` extension are both important and should be discussed by the core team (there could be a need for more compilation modes in the future, especially with regards to #2224).
  - My reasoning behind this decision was: 
    - The mode of compilation should be deductible from the file to be compiled and should not require the user to check some external configuration/build/... file. This is good for both reading code and editor support.
     - Deciding what to do with a file based on its extension is a common practice, in particular it is what gcc does.
- I did some changes/refactoring to some very core files and to the test infrastructure to avoid duplicating code, but I felt very uncomfortable making the changes without supervision from someone who understands the project better.
- Test functions files now reside in ```test/test-models/good-standalone-functions``` - is this a reasonable place in the tree? (an obvious alternative would be ```test/test-standalone-functions/good```)
- I had trouble with the 80 char limit, I don't like some of the indents / line breaks it forced me to do, but I couldn't find a better way - could you please check that the code reads nice and is aligned with what others write? (e.g. the two-line ```for``` cycle in ```stanc_helper.hpp``` line 280).
- When compiling standalone functions, it is definitely necessary to check whether other blocks are contained in the input file. I see two possible ways of doing this - what would you prefer?
  1) keep the default parser and check whether the members of ```stan::lang::program``` are all empty except ```function_decl_defs_``` (requires maintanence when new types of program blocks are introduced or when the ```program``` struct changes)
  2) create a specific parser variant that only recognizes the functions block (would require maintanance when the parser structure changes and a specific parser for other compilation modes would have to be created as well)
- Should ```compile_functions()``` give a warning or error when other blocks are present?

**Comment by martincerny** [comment]
Additionally, I have reduced the required includes to ```stan/math.hpp```, ```stan/lang/rethrow_located.hpp``` and a few standard headers.

**Comment by sakrejda** [comment]
Sweet, is it set up to compile to a library too?

**Comment by martincerny** [comment]
Happy easter, everybody.

I have now also written code to generate concrete instantiations of the templated functions. For templated function ```func``` it generates ````func__double_only``` where all parameters are based on doubles + there is a concrete RNG for the ```_rng``` functions. I have two more points for feedback:

1) What is the ```bool propto``` template parameter for the ```_lpdf``` functions? If I get it right, ```propto == true``` means the function should ignore constant terms. Therefore, in the instantiated functions, it is always false.
2) In generate_function_instantiation_template_parameters.hpp the 80 chars limit forced me to split the initial ```#ifndef / #define``` directives on two lines... Shouldn't that be exempt from this rule?

**Comment by martincerny** [comment]
@sakrejda Not sure what you mean, but probably not :-) In particular, if you mean the ability to wrap the functions in a library that can be invoked from RStan, than I have not looked at that yet.

**Comment by sakrejda** [comment]
Just so it's compatible with being compiled as a shared library, nice if
there's support for instantiating with all doubles.

**Comment by bob-carpenter** [comment]
> I have now also written code to generate concrete instantiations of the templated functions.

Great!  That should be super-helpful in R.  I think there's a few things that need to go into a comment to make it usable in R. 
@bgoodri --- is there an example somewhere of what you need for this for RStan?

> For templated function func it generates ````func__double_onlywhere all parameters are based on doubles + there is a concrete RNG for the_rng``` functions.

That got lost in translation.

> I have two more points for feedback:
> 
> 	• What is the bool propto template parameter for the _lpdf functions? If I get it right, propto == true means the function should ignore constant terms. Therefore, in the instantiated functions, it is always false.

You got it right.

> 	• In generate_function_instantiation_template_parameters.hpp the 80 chars limit forced me to split the initial #ifndef / #define directives on two lines... Shouldn't that be exempt from this rule?

How about a shorter file name?  Maybe just dropping "template_parameters"?

**Comment by bob-carpenter** [comment]
OK, I see the issue now.  Why do you want to mangle the function name to `func_double_only`?

**Comment by bgoodri** [comment]
All the hacks are in the expose_stan_functions() function.

**Comment by wds15** [comment]
This looks really awesome!

Would it be possible to generate for ODE functors in addition to double only versions a flavor which has the argument for the states as var?

Currently, functions which involve integrate_ode_bdf cannot be exposed to R. The reason is that the bdf integrator needs the Jacobian of the ODE RHS wrt to the states which is done by default using autodiff. However, this maybe conceptually not possible as AD is not usable in the exported functions; I don't know - but if this could work that would be amazing.

**Comment by martincerny** [comment]
@wds15 I think it should be possible, but I've never really used the ODE solver. Could you provide an example you are interested in? - please describe the complete use case and share code for a specific Stan function you would like to have available.

@bob-carpenter The long name follows the naming conventions of the rest of the directory (and the shorter one you suggest is used by another file). I have mixed feelings about the "one function per file " approach, but that's how the rest of the code is written.
The '_double_only' suffix just felt right to distinguish the template from the instantiation, but I guess it's not necessary (though I have only shallow knowledge of the darker corners of C++ templates and R-C++ interop)

**Comment by martincerny** [comment]
@bob-carpenter One more thing: note that the function instantiation is something different than the template - in particular, it is NOT an explicit specialization of the template (as that would not guarantee it gets actually instantiated), but it is a normal function that calls the templated function - I am not completely sure what the compiler would do if I named them the same. That's why I named them differently. Another way to keep things clean would be to put either the templates or the instantiations into a different namespace (```xx::instances``` or ```xx::templates```)...

**Comment by wds15** [comment]
Ok, here it goes: This is the Stan file which should be exported to R

```C++
functions {

  vector integrand(vector x) {
    return exp(-square(x));
  }

  real[] integrand_ode(real r, real[] f, real[] theta, real[] x_r, int[] x_i) {
    real df_dx[1];
    real x = logit(r);
    df_dx[1] = exp(-square(x)) * 1/(r * (1-r));
    return(df_dx);
  }

  real ode_integrate() {
    int x_i[0];
    // ok:
    //return(integrate_ode_rk45(integrand_ode, rep_array(0.0, 1),
    //1E-5, rep_array(1.0-1E-5, 1), rep_array(0.0, 0), rep_array(0.0,
    //0), x_i)[1,1]);
    // not ok
    return(integrate_ode_bdf(integrand_ode, rep_array(0.0, 1), 1E-5, rep_array(1.0-1E-5, 1), rep_array(0.0, 0), rep_array(0.0, 0), x_i)[1,1]);
  }

}
data {
}
model {}
```

The generated functor for integrand_ode looks like this:

```c++ 
template <typename T0__, typename T1__, typename T2__, typename T3__>
std::vector<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type>
integrand_ode(const T0__& r,
                  const std::vector<T1__>& f,
                  const std::vector<T2__>& theta,
                  const std::vector<T3__>& x_r,
                  const std::vector<int>& x_i, std::ostream* pstream__) {
```

Things do not work, because we only get a double only version of that thing. However, we need the Jacobian wrt to states, so we need a version of the functor where T0, T2 and T3 are doubles (as before), but T1 must be stan::math::var.

Of course, you then also need to pull in the AD machinery...

**Comment by martincerny** [comment]
@wds15 Thanks for the code. It is however not clear to me, why would you want T1 to be stan::math::var and how do you intend to use the standalone function from R. Maybe there is a solution to your problem without resorting to stan::math::var (and choosing that only T1 has stan::math::var seems quite arbitrary). Could you please elaborate on what exactly is your ultimate goal? I'd like to avoid the [XY Problem](https://meta.stackexchange.com/a/66378/313955) :-).

**Comment by wds15** [comment]
well, then just dump the above stan model into a file, call it integrate.stan and then do in R

```R
library(rstan)
expose_stan_functions("integrate.stan")
```

You will see that the compilation fails, because the functor I refer to is not available. If you trace where things are coming from, the you see that the integrate_ode_bdf tries to get the derivative of the functor wrt to the states.

Does that clear things up?

**Comment by bob-carpenter** [comment]
```
#include <iostream>
#include <string>

template <typename T>
double foo(T x) { return 1; }

double foo(double x) { return 2; }

template <>
double foo(double x) { return 3; }

template <>
double foo<std::string>(std::string x) { return 4; }

int main() {
  std::cout << "foo(2.7) = " << foo(2.7) << std::endl;
  std::cout << "foo(1) = " << foo(1) << std::endl;
  std::cout << "foo(\"bar\") = " << foo("bar") << std::endl;
  std::cout << "foo(std::string(\"bar\")) = " << foo(std::string("bar")) << std::endl;
}
```

outputs

```
foo(2.7) = 2
foo(1) = 1
foo("bar") = 1
foo(std::string("bar")) = 4
```

So you see that first it figures out which template function to use, and only then figures out the specialization.  That's why `foo(2.7)` evaluates to `2`.  The overload is more specific than the template, despite the template having a double specialization.

**Comment by bob-carpenter** [comment]
> @bob-carpenter The long name follows the naming conventions of the rest of the directory (and the shorter one you suggest is used by another file). I have mixed feelings about the "one function per file " approach, but that's how the rest of the code is written.

So do we all.  We've found it easier to find things that way. May be because Daniel and I came from Java backgrounds which strictly enforced the one class per file issue.

**Comment by bob-carpenter** [comment]
In response to https://github.com/stan-dev/stan/issues/2267#issuecomment-295099249, that's totally OK.  The resolution mechanism first figures out which overload to use, then if the result is a template function, which instantiation to use.  Both steps need to be unambiguous, that's all.

**Comment by martincerny** [comment]
@wds15 I think I still miss the bigger picture - do you want/need to evaluate the derivatives with respect to the parameters in R? Or are you just interested in performing the numerical integration? Or you really only care about the evaluating the state function?

**Comment by sakrejda** [comment]
He wants the integration to run.

**Comment by martincerny** [comment]
@sakrejda @wds15 I have written a test that verifies that the example code with ODE can compile into a standalone functions file and that the ```ode_integrate()``` can be called. However, since there is no current complement to ```expose_stan_functions``` for the standalone functions, I cannot verify it works also in R.

Furhter I have filed a pull  request in hope of getting more feedback on my initial questions from April 15.

**Comment by mitzimorris** [comment]
I updated the title and description to add context as to how this feature will be used.

**Comment by martincerny** [comment]
The core has been implemented and merged, remaining problems are tracked elsewhere, closing.
