### ISSUE TITLE
bad_alloc in ODE model

### ISSUE THREAD

**Issue by virgile-baudrot** [stan-dev/stan#2272]
#### Summary:
In functions for ode integration, the following code do not compile but do not return error as it could be expected but a "std::bad_alloc".

```
int nb_eq;    
real dydt[nb_eq];
```
#### Reproducible Steps:

A reproducible example with a slight modification of Harmonic Oscillator model (provided with the Manual):
[bad_alloc_ODE.tar.gz](https://github.com/stan-dev/stan/files/916732/bad_alloc_ODE.tar.gz)

#### Expected Output:
An error message

#### Current Version:
v2.14.0

**Comment by bob-carpenter** [comment]
Can you run other Stan models?

**Comment by virgile-baudrot** [comment]
Yes. I can run Harmonic Oscillator example (And others also) without introducing what I named "nb_eq"

**Comment by wds15** [comment]
the Stan model is wrong... the nb_eq is never initialized inside the ODE RHS functor. The model should run ok with declaring

int nb_eq = 2;

inside the ODE RHS functor. Note that the variables in the data block are not globally available. You can use the x_i argument to pass integer data around.

That said, I haven't run the model, so the error message could possibly be improved.

**Comment by virgile-baudrot** [comment]
Yes. Actually, I did this mistake in the model, but had some difficulties to find the error because of the message.

**Comment by sakrejda** [comment]
Could we catch stuff when values are not initialized properly to give error messages?

**Comment by syclik** [comment]
I saw this in the wild not too long ago. Last I saw, it happened when some
of the returned dy_dt were NaN.

We certainly can stop this by adding more checks. We need to think through
how the error handling is propagated, but it can be handled. (I believe on
an earlier implementation there were checks in place. It's one of the
reasons I'm all for putting checks in place. It saves so much more headache
for users, devs, etc.)

Options:
1. we can probably checks to the functor that's generated
2. I think we can fix this in the integrate_* calls.

**Comment by bob-carpenter** [comment]
Is this the CVODES or Boost integrator?  Can we file an issue with them not to go bonkers when given NaN values?

We have lots of layers of wrappers where we could brute force the check.  Probably not a big performance overhead.

**Comment by wds15** [comment]
I don't think that checking every ODE RHS evaluation is a good thing as it gets called really often and should add some performance overhead which all users have to pay always.

A good compromise is to call the ODE RHS in the integrate_* function with the initial state. Then we check if the initial dy_dt at t=t0 has the correct size and is not NaN. This would catch the reported case and probably about any other realistic ones which are the most common ones.

However, the even better solution would be to not rely on the user create a dy_dt which has the correct size inside the ODE RHS. Instead it would be better to have a design where Stan manages the dy_dt and the user only populates its values. This would avoid much of the ongoing copying and always ensure that dy_dt is of the right size.

**Comment by syclik** [comment]
> A good compromise is to call the ODE RHS in the integrate_* function with the initial state. Then we check if the initial dy_dt at t=t0 has the correct size and is not NaN. This would catch the reported case and probably about any other realistic ones which are the most common ones.

That may catch the reported case, but there's also an issue if the array is the correct size, but elements are `NaN`. Given users are defining functions, we should be safe.

> However, the even better solution would be to not rely on the user create a dy_dt which has the correct size inside the ODE RHS. Instead it would be better to have a design where Stan manages the dy_dt and the user only populates its values. This would avoid much of the ongoing copying and always ensure that dy_dt is of the right size.

What you're suggesting can't work with the current function implementation. That said, nothing is impossible, so if you have a proposal that makes sense, I'm sure we're all willing to hear it out.

> I don't think that checking every ODE RHS evaluation is a good thing as it gets called really often and should add some performance overhead which all users have to pay always.

I completely disagree. It's caused confusion and I'm sure some people have given up on ODEs due to a simple programming error because we don't have error reporting.

What I would suggest is that we do some real timing experiments. You would be surprised how cheap checking for `NaN` is relative to anything else. In fact, if you send me an example that you're happy with that takes more than a couple seconds, I can implement it and we can see how much time it takes.

**Comment by wds15** [comment]
Well, I would be surprised if extra checks are for free (array bound checks are also disabled for a reason in std::vector or Eigen) - in a Stan run you get at the order of 10^6 integrations easily. Each integration sweep can easily again trigger 10^6 calls to the ODE RHS. That's a lot with about 10^12. Let me prepare an example to play with and we check the overhead.

Should we have a discussion in a meeting on a Stan default (with all checking) and a Stan "speed" mode (disabling all checks). The "speed" mode could only by activated with a switch called like "--give-me-all-speed-even-if-I-fool-myself"?

I know that the current design does not allow what I have suggested. I don't have a good solution at hand. The obvious approaches are by reference dy_dt arguments to the functor or a predefined dy_dt symbol which the user must populate inside the function. Neither approach is too elegant.

**Comment by bob-carpenter** [comment]
@wds15  Would you mind creating an issue or discourse thread for discussing your proposed unsafe mode?   It's off topic on this issue.  Thanks.

**Comment by bob-carpenter** [comment]
Back to the original point, we don't want to be throwing uncaught exceptions back to users at runtime or crashing their R sessions (at least until they've signed a waiver and we've given them keys to Ben and Sebastian's unsafe mode).

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#548

**Comment by syclik** [comment]
I just moved the issue to math: the fix will have to be applied there.
