### ISSUE TITLE
compiler needs to capture line number for variable declarations

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2280]
#### Summary:
Runtime errors arising from compound declare-define statements don't provide program line numbers because Stan compiler only records this information for statements, not variable declarations.

#### Description:
Stan parser captures program line number for statements and generator function `generate_statement` generates c++ statement `current_statement_begin__ = XX` where XX is statement field `begin_line_`.   Struct var_decl should also have field `begin_line_`.  Change `stan/lang/ast/node/var_decl` struct as well as parser and generator so that generated code provides line numbers for variable declarations.

#### Current Version:
v2.15.0

**Comment by mitzimorris** [comment]
related to issue #1990

**Comment by bob-carpenter** [comment]
I upped the priority on this after Daniel re-reported in https://github.com/stan-dev/stan/issues/2348

**Comment by syclik** [comment]
@bob-carpenter, thanks! I didn't realize there was already an issue for this.

**Comment by mitzimorris** [comment]
fixed and merged via PR https://github.com/stan-dev/stan/pull/2357
