### ISSUE TITLE
add for_each loops

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2296]
#### Summary:

Add for_each loops to Stan. These would look like this:

```
vector[7] ys;
for (y in ys)
  y ~ normal(mu, sigma);
```

#### Description:

Have to be careful to make sure that Eigen works has the appropriate `x.begin()` and `x.end()`, but now we can write `begin(Eigen::Matrix)`.

#### Current Version:
v2.15.0

**Comment by VMatthijs** [comment]
Solved by following PR: https://github.com/stan-dev/stan/pull/2438
