### ISSUE TITLE
Manual - Parenthesis and spelling  

### ISSUE THREAD

**Issue by stemangiola** [stan-dev/stan#2302]
#### Summary:
Please provide a short couple sentence summary.

This part 

target += -2 * log(y_inv) ); // adjustme;

Contains spare parenthesis 

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.15.0

**Comment by bob-carpenter** [comment]
There's always an issue open for fixes to the next manual, so I'm moving this comment there.  Here's the replacement for this issue:  https://github.com/stan-dev/stan/issues/2265#issuecomment-299551712
