### ISSUE TITLE
Manual - Sampling statement in the wrong block

### ISSUE THREAD

**Issue by stemangiola** [stan-dev/stan#2303]
#### Summary:
Please provide a short couple sentence summary.

target += is shown in the transformed parameters, while stan complains it should be in the model block, I believe.

transformed parameters {
real<lower=0> y;
y = 1 / y_inv; // change
target += -2 * log(y_inv) ); // adjustme;
}

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.15.0

**Comment by bob-carpenter** [comment]
Moved to comment on existing manual issue:  https://github.com/stan-dev/stan/issues/2265#issuecomment-299551712
