### ISSUE TITLE
Signature of [Modified] Bessel Functions [of the Second Kind]

### ISSUE THREAD

**Issue by ecbrown** [stan-dev/stan#231]
I am trying to implement a Matern Covariance function, which depends on K_v.  I believe that v may take on non-integer values, e.g v=1/2 is quite significant from a theoretical standpoint.

However, when I supply both arguments as real (nu is a real<lower=0.5> parameter):

```
Sigma[i,j] <- sigmasq * 1.0/(tgamma(nu)*pow(2.0,nu-1.0) *
pow(sqrt(2.0*nu)*D[i,j]/phi,nu) * modified_bessel_second_kind(nu,
sqrt(2.0*nu)*D[i,j]/phi);
```
I get a compilation error:

```
DIAGNOSTIC(S) FROM PARSER:
no matches for function name="modified_bessel_second_kind"
   arg 0 type=real
   arg 1 type=real
available function signatures for modified_bessel_second_kind:
0.  modified_bessel_second_kind(int, real) : real
```

which seems to make me think that K_v only takes integer v.

Is it possible to make it take two real arguments?

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#23
