### ISSUE TITLE
Print statements occurring before a "reject" do not get output

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2311]
_From @ksvanhorn on May 18, 2017 22:45_

#### Summary:
Print statements occurring *before* a reject() in the model block never get output.

#### Description:
If a reject() gets called from within the model block, then no output is seen from print statements occurring before the rejection in the model block, nor from print statements occurring in the transformed parameters block. The reject message also is not output.

#### Reproducible Steps:
    model_code <- '
    data {
    }
    transformed data {
    real lo;
    lo <- negative_infinity();
    print("Finished transforming data.");
    }
    parameters {
    real scale;
    }
    transformed parameters {
      print("In transformed parameters");
    }
    model {
    print("Starting model.");
    scale ~ normal(0, 1);
    print("A");
    reject("QUIT");
    }
    '
    
    sm <- stan_model(model_code = model_code)
    fit <- vb(sm, data=list())

#### Current Output:
The message "Finished transforming data." is output, but none of the other ones. There are a large number of error messages saying "Rejecting initial value: Error evaluating the log probability at the initial value." The reject message "QUIT" does not appear in the output.

Note: I also see the same kind of behavior in a more complex model that doesn't have an obvious reject() statement in it.

#### Expected Output:
The messages "In transformed parameters." and "Starting model." and "A" should also appear in the output. Furthermore, the reject message "QUIT" should appear somewhere in the output.

#### RStan Version:
2.15.1

#### R Version:
3.3.0

#### Operating System:
OS X 10.12.4

_Copied from original issue: stan-dev/rstan#416_

**Comment by bob-carpenter** [comment]
_From @bgoodri on May 18, 2017 23:18_

I am pretty sure it has always been like this. In any event, RStan doesn't
do anything with print() statements, so this would have to get fixed in
Stan.

On Thu, May 18, 2017 at 6:45 PM, Kevin S. Van Horn <notifications@github.com

**Comment by bob-carpenter** [comment]
_From @ksvanhorn on May 18, 2017 23:20_

Oops, yeah, should have filed this in Stan instead of RStan. Is there an easy way to move it?

**Comment by bob-carpenter** [comment]
_From @ksvanhorn on May 18, 2017 23:22_

If it's always been like this, that just means it's always been wrong. Print statements are failing to output in precisely the situation where they are most needed, for debugging.

**Comment by bob-carpenter** [comment]
_From @jgabry on May 18, 2017 23:43_

On Thu, May 18, 2017 at 7:22 PM Kevin S. Van Horn <notifications@github.com>
wrote:

> If it's always been like this, that just means it's always been wrong.
>

Yeah, I agree. I don't see why we'd want it that way and I'd be surprised
if that behavior is intentional. I haven't looked yet, but I bet there's
been discussion of this somewhere in the stan repo's issues. That is, if
this has indeed been the standard behavior.

**Comment by bob-carpenter** [comment]
_From @bgoodri on May 19, 2017 1:3_

I think it is somewhat intentional in that it is a side of effect of the
deliberate decision to throw / catch an exception as soon as something
exceptional happens, which means the instructions to flush the buffered
print messages don't get executed.

**Comment by bob-carpenter** [comment]
Thanks, @ksvanhorn.  I completely agree with your reasoning and that we should not be losing this print output---that was never my intention in adding `print()` in the first place.

I verified it's a problem in CmdStan, too, so I'll move this issue to Stan.

**Comment by mitzimorris** [comment]
tackling this now.

**Comment by bob-carpenter** [comment]
Fixed with #2314
