### ISSUE TITLE
real replacement by vector

### ISSUE THREAD

**Issue by stemangiola** [stan-dev/stan#2315]
#### Summary:
Please provide a short couple sentence summary.

In mixture models

real log_theta[K] = log(theta); // cache log calculation

should be replaced by 

vector[3] log_theta = log(theta); // cache log calculation

Otherwise gives error

```
variable definition base type mismatch, variable declared as base type: real variable definition has base: vectorvariable definition dimensions mismatch, definition specifies 1, declaration specifies 0
ERROR at line 15

 13:    }
 14:    model {
 15:    	real log_lambda[3] = log(lambda); // cache log calculation
                                           ^
 16:    	real lps[3];
```

#### Description:
Describe the issue as clearly as possible.

model {
real log_theta[K] = log(theta); // cache log calculation
sigma ~ lognormal(0, 2);
mu ~ normal(0, 10);
for (n in 1:N) {
real lps[K] = log_theta;
for (k in 1:K)
lps[k] = lps[k] + normal_lpdf(y[n] | mu[k], sigma[k]);
target += log_sum_exp(lps);
}
}

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.15.0

**Comment by bob-carpenter** [comment]
I don't see an issue here.  I'm not sure where the "should be replaced" is supposed to apply.  Is this in documentation somewhere or example models or something else?

**Comment by lukasvermeer** [comment]
I suspect @stemangiola is referring to the code in the "Estimating Parameters of a Mixture" section on page 193 of [Modeling Language User's Guide and Reference Manual, Version 2.16.0](https://github.com/stan-dev/stan/releases/download/v2.16.0/stan-reference-2.16.0.pdf).

The document currently reads:
```
data {
  int<lower=1> K; // number of mixture components
  int<lower=1> N; // number of data points
  real y[N]; // observations
}
parameters {
  simplex[K] theta; // mixing proportions
  ordered mu[K]; // locations of mixture components
  vector<lower=0>[K] sigma;  // scales of mixture components
}
model {
  real log_theta[K] = log(theta);  // cache log calculation
  sigma ~ lognormal(0, 2);
  mu ~ normal(0, 10);
  for (n in 1:N) {
    real lps[K] = log_theta;
    for (k in 1:K)
      lps[k] = lps[k] + normal_lpdf(y[n] | mu[k], sigma[k]);
    target += log_sum_exp(lps);
  }
}
```

But this results in various compilation errors.

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in '../../Desktop/model2.stan' at line 8, column 10
  -------------------------------------------------
     6: parameters {
     7:   simplex[K] theta; // mixing proportions
     8:   ordered mu[K]; // locations of mixture components
                 ^
     9:   vector<lower=0>[K] sigma;  // scales of mixture components
  -------------------------------------------------

PARSER EXPECTED: <size declaration: integer (data-only) in square brackets>
```

When that's fixed, there are more.

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

variable definition base type mismatch, variable declared as base type: real variable definition has base: vectorvariable definition dimensions mismatch, definition specifies 1, declaration specifies 0  error in '../../Desktop/model2.stan' at line 12, column 33
  -------------------------------------------------
    10: }
    11: model {
    12:   real log_theta[K] = log(theta);  // cache log calculation
                                        ^
    13:   sigma ~ lognormal(0, 2);
  -------------------------------------------------
```

And so on.

The following code (patched by yours truly with no real understanding of how Stan works and aided only by hints in error messages and Google) runs and gives Reasonable Looking™ results.

```
data {
  int<lower=1> K; // number of mixture components
  int<lower=1> N; // number of data points
  real y[N]; // observations
}
parameters {
  simplex[K] theta; // mixing proportions
  ordered[K] mu; // locations of mixture components
  vector<lower=0>[K] sigma; // scales of mixture components
}
model {
  vector[K] log_theta = log(theta); // cache log calculation
  sigma ~ lognormal(0, 2);
  mu ~ normal(0, 10);
  for (n in 1:N) {
    vector[K] lps = log_theta;
    for (k in 1:K) {
      lps[k] = lps[k] + normal_lpdf(y[n] | mu[k], sigma[k]);
    }
    target += log_sum_exp(lps);
  }
}
```

Not sure if this is the right place to report documentation errors, but I'm sure that if this is not the case someone can point me in the right direction.

**Comment by stemangiola** [comment]
Sorry Guys, I missed this one.

Page 191 Reference manual  2.15.0

**Comment by bob-carpenter** [comment]
Thanks.  Wasn't clear it was about the manual from the original issue.  We have a manual issue for minor patches like this and it's best to report there.  I fix them all before every release.  I created an issue for this there and am closing this issue:

https://github.com/stan-dev/stan/issues/2336#issuecomment-312171439
