### ISSUE TITLE
for(-each) loop

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2325]
#### Summary:

Stan should support a foreach loop syntax:

```
for (x in xs) {
  ...
}
```

For example,  

```
for (x in { 1, 2, 3 }) print("foo(", x, ")=", foo(x));
```
```
matrix y;
...
for (y_i in y) target += bar_lpdf(y_i | theta);
```

#### Description:

As with for loops, the loop declares a local variable `x`, whose type is given by

* if `xs` is a `vector` or `row_vector` or `matrix`, then `x` is `real`, and
* if `xs` is an array of type `T[]`, then `x` is of type `T`

The variable `x` here can be any identifier, but it must not be a reserved word or defined in the containing scope (i.e., no masking).

The underlying implementation should just rely on the C++11 foreach, with

```
foreach (x in xs) body(x)
```

translating to

```
for (const auto&& x : [[xs]])
  [[ body ]]
```

where `[[xs]]` and `[[body]]` are the translations of `xs` and `body`.  The `body` should not allow assignment to `x`.  

(I haven't tried it, but the translation is intended to pass `x` by constant reference.)

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.15.0

**Comment by VMatthijs** [comment]
Solved by PR https://github.com/stan-dev/stan/pull/2438
