### ISSUE TITLE
Skew-Normal documentation suggestion

### ISSUE THREAD

**Issue by stephensrmmartin** [stan-dev/stan#2326]
In the documentation, for consistency's sake, you use mu and sigma as the parameters as location and scale, respectively.
However, this can be misleading: There are two primary parameterizations of the SN distribution, one in terms of location, scale, and alpha-skewness: SN(xi, omega, alpha), and the other in terms of MEAN, SD, and gamma-skewness: SN(mu, sigma, gamma).

You all use the 'direct' parameterization, as you should, which normally is notated with xi, omega, and alpha. I believe this is misleading, because users may see mu and sigma and believe that stan is using the other parameterization in terms of means/sd.

It seems inconsequential, but e.g., in regression, you may want to predict the /means/ and not the /location parameter/, and in doing so your coefficients will be different. (Mean-Regression is nevertheless easily done in stan via reparameterization, but I digress). This is in particular true if you are modeling heterogenous variances in a linear model. Two groups may have different variances, but the same mean; if that's true, the /location/ parameters are very, very different between the two groups.

**Comment by bob-carpenter** [comment]
Thanks for the suggestion---I'll fix it.  I didn't even realize people used "location" and "scale" when they didn't determine the values for the mean and standard deviation on the density.  I'll make sure our notation matches your suggestion, which aligns with

https://en.wikipedia.org/wiki/Skew_normal_distribution

I've moved this issue to a comment on the next manual issue;  I'll take care of all of those before 2.16:

https://github.com/stan-dev/stan/issues/2265#issuecomment-308322174

**Comment by stephensrmmartin** [comment]
Awesome, thanks! (So quick to respond)

SN is a weird one. Xi will be the mean only when alpha is 0; likewise, scale = SD if alpha is 0. It's a bit like Xi and scale represent the mean and sd of a normal distribution prior to skewing it.

I'd also love to see the skew-t and multivariate skew-{normal, t} distributions if ever possible; I can manually add in a skew-t using a really inefficient method:
`  target += 2 + student_t_lpdf(y | nu, mu, scale) + student_t_lcdf((y - mu)/scale * alpha | nu,0, 1);`
but, the skew-t distribution is surprisingly useful for skewed data.
Separate issue though, should search to see whether this is already requested.

**Comment by bob-carpenter** [comment]
I don't think those are on our list.  Feel free to open an issue.  We'll try to keep knocking off densities that people use.  Unless there are a lot of shared computations in the log pdf and log cdf, there might not be much efficiency gained from a direct C++ implementation.  But it's always easier to have something built in, even if we just literally code what you have written above.  Feel free to open a new issue in `stan-dev/math`, which is where the densities go first---the Stan part is trivial once we have a C++ implementation.
