### ISSUE TITLE
Mistake in manual: normal_rng(real mu | real sigma)

### ISSUE THREAD

**Issue by stephensrmmartin** [stan-dev/stan#2327]
normal_rng(real mu | real sigma) should be normal_rng(real mu, real sigma)

**Comment by bob-carpenter** [comment]
If you wouldn't mind, please list these on the "next manual" issue.  When they're all listed as their own issue, I have to laboriously copy them over and cross reference.  This one's going here:

https://github.com/stan-dev/stan/issues/2265#issuecomment-308326251

**Comment by stephensrmmartin** [comment]
I apologize; I didn't actually realize I could I could comment there! I'll do that from now on.

**Comment by bob-carpenter** [comment]
No worries.  We're happy to get corrections any way we can!
