### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2338]
#### Summary:

`src/stan/lang/generator/generate_function_instantiation_template_parameters.hpp` is too long of a filename for the StanHeaders R package

#### Description:

Storing paths of more than 100 bytes is not portable and may fail on very old systems.

#### Reproducible Steps:

Build the StanHeaders package

#### Current Output:

```
* building ‘StanHeaders_2.16.0.tar.gz’
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  ‘StanHeaders/inst/include/src/stan/lang/generator/generate_function_instantiation_template_parameters.hpp’
```

#### Expected Output:

None

#### Additional Information:

None

#### Current Version:
v2.16.0

**Comment by bob-carpenter** [comment]
OK, I can fix that for the next release.

**Comment by mcol** [comment]
The function was renamed in 1c404cad99d1b86ff38462ba77e8f47b14facedd to `generate_fun_inst_templ_params.hpp`.
