### ISSUE TITLE
Stanc doc out of date

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#2354]
#### Description:

The doc in the `--help`` output of `stan-dev/stan:src/stan/command/stanc_helper.hpp` is not up to date with user-defined functions or file includes.  Without doc it's hard to figure out how to use either of these functionalities with the Stan compiler.

#### Current Version:
v2.16.0

**Comment by mcol** [comment]
With stanc3, I don't think there's an interest in this anymore.
