### ISSUE TITLE
allow space before # in includes

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2358]
#### Summary:

Title says it all.  They will still be first thing on the line.  

Should the extra whitespace on the line go into the output?

This will actually match the doc as written and the existing RStan behavior.

#### Current Version:

v2.16.0

**Comment by bgoodri** [comment]
I think keep the whitespace. Also, trailing whitespace and / or comments,
such as

  #include functions.stan  // defines foo and bar

should be legal.

**Comment by bob-carpenter** [comment]
Do we need to add quotes in case there are spaces in function names?  Otherwise, I'm not quite sure where to stop.  I think right now I was intending to go to the end of the line and then trim any excess initial and final whitespace.  But either requiring it to be contiguous or to have quotes is probably better.  Then I could include things after it.  We're talking about

```
    #include foo  // defines foo and bar
```
produce
```
    <foo file
contents>  // defines foo and bar
```
so that the space comes at the beginning and the rest at the end.  I think this may get very confusing for people.

**Comment by bgoodri** [comment]
File names with spaces in them are going to be a problem unless we require
quotes, at least in that case. Basically I think #include in Stan should
work in the same way(s) it works in C++.

**Comment by bob-carpenter** [comment]
That makes sense.  Should I allow angle brackets and quotes?

**Comment by betanalpha** [comment]
I suggest we use one but not the other (to avoid the
confusion about which use which paths and whatnot).
I think that quotes would be sufficient.

**Comment by bgoodri** [comment]
Sure. Why not, I guess.

**Comment by bob-carpenter** [comment]
I'm working on this one now.
