### ISSUE TITLE
missing final line in parser error report

### ISSUE THREAD

**Issue by maverickg** [stan-dev/stan#2359]
_From @bob-carpenter on July 20, 2017 19:35_

#### Summary:

With program

```
data {
  foo bar; } model { }
```

CmdStan outputs:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in '/Users/carp/temp2/foo.stan' at line 2, column 3
  -------------------------------------------------
     1: data {
     2:   foo bar; } model { }
          ^
  -------------------------------------------------

PARSER EXPECTED: <one of the following:
  a variable declaration, beginning with type,
      (int, real, vector, row_vector, matrix, unit_vector,
       simplex, ordered, positive_ordered,
       corr_matrix, cov_matrix,
       cholesky_corr, cholesky_cov
  or '}' to close variable declarations>
```

whereas RStan (on my Mac, RStudio and R GUI), I get:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in 'model10239103581_foo' at line 2, column 3
  -------------------------------------------------
     1: data {
          ^
  -------------------------------------------------

PARSER EXPECTED: <one of the following:
  a variable declaration, beginning with type,
      (int, real, vector, row_vector, matrix, unit_vector,
       simplex, ordered, positive_ordered,
       corr_matrix, cov_matrix,
       cholesky_corr, cholesky_cov
  or '}' to close variable declarations>
```

What's odd is that it's only partway through the output from the parser.

#### RStan Version:

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Yosemite 10.10.5

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.16.2         StanHeaders_2.16.0-1 ggplot2_2.2.1       

loaded via a namespace (and not attached):
 [1] colorspace_1.3-2 scales_0.4.1     assertthat_0.1   lazyeval_0.2.0   plyr_1.8.4       tools_3.3.2     
 [7] inline_0.3.14    gtable_0.2.0     tibble_1.2       gridExtra_2.2.1  Rcpp_0.12.8      grid_3.3.2      
[13] stats4_3.3.2     munsell_0.4.3   
```

_Copied from original issue: stan-dev/rstan#436_

**Comment by maverickg** [comment]
_From @sakrejda on July 20, 2017 19:46_

Did you guys figure out where this came from? Mostly nosy but I did look at the associate Rcpp code and could figure this out.

**Comment by maverickg** [comment]
_From @bob-carpenter on July 20, 2017 20:3_

Not that I know of.  If you could take a look, that'd be great.

**Comment by maverickg** [comment]
_From @sakrejda on July 20, 2017 20:5_

It doesn't reproduce in R 2.15.2 on my Mac but I'll update and see if it does then.

**Comment by maverickg** [comment]
_From @bgoodri on July 20, 2017 20:56_

And to clarify, this is only with the CRAN binary rstan or is it also with
a source install, e.g. `devtools::install_github("stan-dev/rstan", ref =
"v2.16.2", subdir = "rstan/rstan")`?

**Comment by maverickg** [comment]
_From @sakrejda on July 20, 2017 21:35_

Seems like also happens with source install, I'm suspicious that a stream
isn't getting flushed on line 71 or so of parser.hpp but I haven't
reinstalled yet to check. Either way it's odd.

**Comment by maverickg** [comment]
_From @bob-carpenter on July 20, 2017 21:53_

I tried that magic to install from GitHub and it spit out a lot of lines about git and then did the same thing---missing a line.

And yes, @sakrejda, there should be a `<< std::endl` after diagnostics --- it will automatically flush that way.  I'd have thought the message and everything else would do the right thing with the string stream, but apparently not.

**Comment by maverickg** [comment]
_From @bob-carpenter on July 20, 2017 21:54_

Or maybe it's a problem with string scope in exceptions?  This also looks suspicious on line 90:

```
throw std::invalid_argument(msg.str());
```

I think we should be setting that to a local std::string (which copies), then call that.  Even though it seems like that's also going to go out of scope, I seem to remember having problems with something like this before.

**Comment by maverickg** [comment]
I will take a look.

**Comment by maverickg** [comment]
It's weird.  If I added a new line (\n) to the end so it look like
```
$ od -c test.stan
0000000    d   a   t   a       {  \n           f   o   o       b   a   r
0000020    ;       }       m   o   d   e   l       {       }  \n  \n
0000037
```

Then it seems to be fine.  So I am thinking the issue lies in something other than wrongly processing the error message. 

```
$ R -q -e "library(rstan); stanc('test.stan')"
> library(rstan); stanc('test.stan')
Loading required package: ggplot2
Loading required package: StanHeaders
rstan (Version 2.16.3, packaged: 2017-07-21 02:04:11 UTC, GitRev: 901101506c4f)
For execution on a local, multicore CPU with excess RAM we recommend calling
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
Warning message:
package ‘StanHeaders’ was built under R version 3.4.1

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in 'model14a1521ca7bda_test' at line 2, column 3
  -------------------------------------------------
     1: data {
     2:   foo bar; } model { }
          ^
  -------------------------------------------------

PARSER EXPECTED: <one of the following:
  a variable declaration, beginning with type,
      (int, real, vector, row_vector, matrix, unit_vector,
       simplex, ordered, positive_ordered,
       corr_matrix, cov_matrix,
       cholesky_corr, cholesky_cov
  or '}' to close variable declarations>
Error in stanc("test.stan") :
  failed to parse Stan model 'test' due to the above error.
Execution halted
```

**Comment by maverickg** [comment]
ok, I guess now stanc requires an '\n' at the end of line.  Currently `stanc` function in rstan removes the last \n when reading code from a file and I guess this is how it behaves since the first version of rstan.   The bug can be sort of replicated with cmdstan if there is no \n at the end of the stan file. 

```
$ od -c test.stan
0000000    d   a   t   a       {      \n               f   o   o       b
0000020    a   r   ;       }       m   o   d   e   l       {   }
0000037
mmac2:cmdstan-2.16.0 jq$ ./bin/stanc test.stan
Model name=test_model
Input file=test.stan
Output file=test_model.cpp

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in 'test.stan' at line 2, column 4
  -------------------------------------------------
     1: data {
           ^
  -------------------------------------------------

PARSER EXPECTED: <one of the following:
  a variable declaration, beginning with type,
      (int, real, vector, row_vector, matrix, unit_vector,
       simplex, ordered, positive_ordered,
       corr_matrix, cov_matrix,
       cholesky_corr, cholesky_cov
  or '}' to close variable declarations>
```

**Comment by maverickg** [comment]
_From @sakrejda on July 21, 2017 15:0_

We might just want to decide what it is that stanc is supposed to take (text file or just string) and be consistent about this.  It's silly to be adding/deleting newlines.
```
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_403
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
```

**Comment by maverickg** [comment]
_From @bob-carpenter on July 21, 2017 16:3_

stanc shouldn't care if there's a final newline.  As far as I can tell, it's OK and CmdStan is OK on the output, even with a single line.

It's generally good practice to have a newline at the end, but it shouldn't disrupt any of our output or prevent having error messages for the last line.

If there's something not handling this correctly in stan-dev/stan, it should be fixed there.

**Comment by maverickg** [comment]
@bob-carpenter I can reproduce this in cmdstan.  I am pasting what I posted last time again below.  (It might not be easy to create a text file without EOL at the end as some text editor such as Vim will add one automatically.)  

```
$ od -c test.stan
0000000    d   a   t   a       {      \n               f   o   o       b
0000020    a   r   ;       }       m   o   d   e   l       {   }
0000037
mmac2:cmdstan-2.16.0 jq$ ./bin/stanc test.stan
Model name=test_model
Input file=test.stan
Output file=test_model.cpp

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in 'test.stan' at line 2, column 4
  -------------------------------------------------
     1: data {
           ^
  -------------------------------------------------

PARSER EXPECTED: <one of the following:
  a variable declaration, beginning with type,
      (int, real, vector, row_vector, matrix, unit_vector,
       simplex, ordered, positive_ordered,
       corr_matrix, cov_matrix,
       cholesky_corr, cholesky_cov
  or '}' to close variable declarations>
```

**Comment by maverickg** [comment]
In addition, I am reporting a case for which stanc does not provide any error message. 

```
$ od -c test2.stan
0000000    d   a   t   a       {  \n
0000007
mmac2:cmdstan-2.16.0 jq$ ./bin/stanc  test2.stan
Model name=test2_model
Input file=test2.stan
Output file=test2_model.cpp

PROGRAM ERROR, MESSAGE(S) FROM PARSER:

```

(I only have `data { \n` in my test2.stan.)

**Comment by bob-carpenter** [comment]
D'oh---I should've just used `echo` in the terminal.  Thanks for moving the issue.  I think the issue may be with the flush as @sakrejda pointed out earlier.  I'll check it out.

**Comment by sakrejda** [comment]
I was doing a little debug-by-print and even the 'diagnostics' variable is incomplete.

**Comment by bob-carpenter** [comment]
@sakrejda  What do you mean by incomplete?  It's not all coming back from the semantic actions, etc.?   And I assume you mean the variable defined at line 62 of `parser.hpp`?

**Comment by sakrejda** [comment]
This line:

```
        std::string diagnostics = prog_grammar.error_msgs_.str();
```

is producing a truncated error message in `diagnostics`.  If I print it directly right after this line it comes out truncated (using std::cout).  std::cout is supposed to print std::string without conversion so I think the problem is deeper that that (within `prog_grammar.error_msgs_.str()`).  I didn' thave a chance to look in there yet.


Here's the edited snippet:

```
      try {
        parse_succeeded = phrase_parse(fwd_begin, fwd_end, prog_grammar,
                                       whitesp_grammar, prog);
        std::string diagnostics = prog_grammar.error_msgs_.str();
          std::cout << "++++++++++++++++++++++++__" << std::endl;
          std::cout << diagnostics << std::endl;
          std::cout << "++++++++++++++++++++++++__" << std::endl;
        if (out && is_nonempty(diagnostics))
          *out << "DIAGNOSTIC(S) FROM PARSER:" << std::endl
               << diagnostics << std::endl;
      } catch (const expectation_failure<lp_iterator>& e) {
        std::stringstream msg;
        std::string diagnostics = prog_grammar.error_msgs_.str();
        if (out && is_nonempty(diagnostics))
          msg << "XXX SYNTAX ERROR, MESSAGE(S) FROM PARSER:" << std::endl
              << std::endl << diagnostics << std::endl;
          std::cout << "__________________________" << std::endl;
          std::cout << diagnostics << std::endl;
          std::cout << "__________________________" << std::endl;
        if (out) {
          std::stringstream ss;
          ss << e.what_;
          std::string e_what = ss.str();
          std::string angle_eps("<eps>");
          if (e_what != angle_eps)
            msg << "PARSER EXPECTED: "
                << e.what_
                << std::endl;
        }
```

Here's what gets printed:

```
SPH-KSakrejdaL:cmdstan krzysztof$ ./bin/stanc test.stan
Model name=test_model
Input file=test.stan
Output file=test_model.cpp
__________________________
  error in 'test.stan' at line 2, column 3
  -------------------------------------------------
     1: data {
          ^
  -------------------------------------------------


__________________________

XXX SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in 'test.stan' at line 2, column 3
  -------------------------------------------------
     1: data {
          ^
  -------------------------------------------------


PARSER EXPECTED: <one of the following:
  a variable declaration, beginning with type,
      (int, real, vector, row_vector, matrix, unit_vector,
       simplex, ordered, positive_ordered,
       corr_matrix, cov_matrix,
       cholesky_corr, cholesky_cov
  or '}' to close variable declarations>
```

The first time the error gets printed it's still truncated.

**Comment by sakrejda** [comment]
@bob-carpenter I'm pretty sure what's happening is that the diagnostic message is not being constructed correctly when the error occurs: where does that happen?

**Comment by bob-carpenter** [comment]
I'll take this one on and fix it.  Thanks for all the pointers.

**Comment by bob-carpenter** [comment]
The underlying problem is the way Boost extracts lines---if there's no end-of-line, it won't find the line by number as the parser's using.  To fix it, I'm just appending a newline to the end of every program that comes in, which should solve the problem in a way that's transparent to the user.

The `data {` thing is a separate error, but I'll try to fix that one in this pull request, too.
