### ISSUE TITLE
zero length simplex causes   std::bad_alloc

### ISSUE THREAD

**Issue by aaronjg** [stan-dev/stan#2365]
#### Summary:
Allocating a simplex with 0 elements causes std:bad_alloc

#### Description:
int x = 0;
simplex[x] variable;
results in at run time std::bad_alloc

#### Current Output:
std::bad_alloc

#### Expected Output:
Either a zero length vector "variable," or a more informative error. 

#### Current Version:
v2.16.0

**Comment by bob-carpenter** [comment]
There aren't any size zero simplexes, because they have to add up to one.  

We should catch zero size declarations for simplexes and throw an exception.  This has to be at runtime when we know the size.  I should also update the doc.

**Comment by bob-carpenter** [comment]
This issue was moved to stan-dev/math#580

**Comment by bob-carpenter** [comment]
This was fixed at the Stan level with the expanded scope of a `try`/`catch` block specifically to handle errors in compound declare-define --- picking up the pure define errors was a pleasant, unintended side effect!

See https://github.com/stan-dev/math/issues/580 for an explanation.
