### ISSUE TITLE
better error message for program block names which contain typos

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2367]
#### Summary:
When a Stan program has a model block name which is wrong,  e.g. `parameter` instead of `parameters`, the parser error message is misleading:
```
PARSER EXPECTED: whitespace to end of file.
FOUND AT line <n>:
```
#### Description:
At the point where the parser encounters a bad model block name,  the parse fails.  Because all model blocks are optional,  an empty file is a legal parse, hence the error message.

#### Reproducible Steps:

This program will result in the bad error message:

```
parameter {
  real x;
}

transformed parameter {
  real y = x;
}

model {
  x ~ normal(0, 1);
}
```

#### Current Output:
Current error message:
```
PARSER EXPECTED: whitespace to end of file.
FOUND AT line 1: 
```

#### Expected Output:
better error message would list allowed model block names, given model blocks already encountered.

#### Current Version:
v2.16.0

**Comment by bob-carpenter** [comment]
The only fix is going to be to the error message.  There wasn't a bug in the language for well-formed code.

**Comment by VMatthijs** [comment]
Stanc3 currently says

```
Syntax error at file "test.stan", line 1, characters 0-9, parsing error:
   -------------------------------------------------
     1:  parameter {
                  ^
     2:    real x;
     3:  }
   -------------------------------------------------

Expected "functions {" or "data {" or "transformed data {" or "parameters {" or "transformed parameters {" or "model {" or "generated quantities {".
```

**Comment by VMatthijs** [comment]
It might be possible, but it would take me a while to figure out how to capture part of the input program in Menhir's custom errors.  Changes to the parsing error messages which do not requires quoting the user program are easy to implement, however, and might amount to a better investment of our time. Quoting the user program in semantic errors is easy, on the other hand.

**Comment by madeleineth** [comment]
I'm not sure if it counts as the same issue, but I'm also seeing this message when I put the `functions` block (without a typo) after the `data` and `parameters` blocks. (rstan 2.18.2)

**Comment by rok-cesnovar** [comment]
Stanc3 outputs the following

```
Syntax error in 'examples/bugs/test_model.stan', line 1, column 0 to column 9, parsing error:
   -------------------------------------------------
     1:  parameter {
                  ^
     2:    real x;
     3:  }
   -------------------------------------------------

Expected "functions {" or "data {" or "transformed data {" or "parameters {" or "transformed parameters {" or "model {" or "generated quantities {".
```
Will close, please reopen in the stanc3 repo if this needs to be improved further.
