### ISSUE TITLE
access variable declarations from model

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2370]
### Summary:

(As @mitzimorris points out, this is going to be significantly complicated by the addition of tuples;  what's written here as simple accessors needs to be turned into some kind of variant type.)

Add functions to access variable declarations statically and with sizes and constraint bounds at runtime.

#### Description:

There's a base class for static variable information,
```
class var_decl {
  string name() const;
  string type_name() const;  // generalized to variant structure
  int num_array_dims() const;

  int num_matrix_dims() const; // all these roll into "type name" variant structure
  bool has_lower_bound() const;
  bool has_upper_bound() const;  
};
```
and a subclass that adds runtime size information and bounds:
```
class sized_var_decl : public var_decl {
  vector<int> array_dims() const;

  vector<int> matrix_dims() const;  // roll into variant structure
};
```
and a further subclass of that adding size constraints:
```
class shaped_var_decl : public sized_var_decl {
  double lower_bound() const;    // not part of tuples
  double upper_bound() const;
};
```

The model will get a new static class function to return static variable type information with flags indicating which variable blocks to include,
```
static vector<var_decl> var_decls(bool data, bool trans_data, bool params,
     bool trans_params, bool gen_quants) const;
```

Then there's a method to return dynamic variable type information sufficient to transform all parameters to and from the unconstrained scale,
```
vector<sized_var_decl> sized_var_decls(bool data, bool trans_data, bool params,
    bool trans_params, bool gen_quants) const;
```
This method requires the data (hence it can't be static), but does not require parameter values.

A final method is needed to return enough information to unconstrain all the parameters, which requires the unconstrained parameter values,
```
vector<shaped_var_decl> shaped_var_decls(bool data, bool trans_data, bool params,
    bool trans_params, bool gen_quants, const vector<double>& params_r) const;
```
The parameter argument is necessary in order to evaluate the lower and upper bound constraints. This last method can be more compute intensive as it requires calculating all variables through the transformed parameter and generated quantities blocks.

#### Current Version:

v2.16.0

**Comment by bob-carpenter** [comment]
My own preference is for (3), though any of the others would be OK.

(2) and (3) are more flexible in allowing combined returns, like parameters + transformed parameters + generated quantities.

(3) anticipates more general types systems going forward.  Returning a string for a type and sequence of integers for size will do for now, but it's not going to generalize to tuples, etc., which are coming soon.  It also returns an object general enough that the constraining and unconstraining transforms could be available as member functions (the sizes are needed).

My second choice would be (4) and I actually prefer that to (3) if there's never going to be a case where we need to combine output sequences.

So unless anyone objects, I'm going to go ahead and build (3).

**Comment by bgoodri** [comment]
What is (4)?

**Comment by bob-carpenter** [comment]
I updated the previous post if you're doing this through email.

**Comment by bob-carpenter** [comment]
In order to perform constraining and unconstraining externally, we need lower and upper bounds for constrained parameters.  Unlike block variable sizes, these can depend on parameters, as in

```
parameters {
  real L;
  real<lower = L> y;
```

To get all possible lower and upper bounds, we need to:

* read constrained parameters
    - either constrain unconstrained parameter vector or
    - read constrained parameters through a `var_context`
* evaluate the transformed parameters block, and
* evaluate the generated quantities block up through the last declaration.

We can

1.  just give up on trying to return constraints and only return sizes, or
2.  write a method that requires parameters and does all the transforms (not too hard but it could be a very compute intensive call depending on the constraints and sizes).

Any other suggestions?

**Comment by sakrejda** [comment]
Option #2 seems fine, it's still a small cost to pay even once per iteration.

**Comment by bob-carpenter** [comment]
#### Background Discussion

This is the discussion that led up to the current design included above.

**Design I** involves parallel arrays of outputs, with one function per block, for a total of fifteen simple functions.  The other designs also split out what's available statically as a class function and what's available at runtime as a member function.

I.a  variable names (static class function---static)
```
static vector<string> data_var_names();
static vector<string> transformed_data_var_names();
static vector<string> parameters_var_names();
static vector<string> transformed_parameters_var_names();
static vector<string> generated_quantities_var_names();
```
I.b.  variable types (static class function---static)
```
static vector<string> data_var_names();
static vector<string> transformed_data_var_names();
static vector<string> parameters_var_names();
static vector<string> transformed_parameters_var_names();
static vector<string> generated_quantities_var_names();
```
I.c  variable sizes (member function---dynamic)
```
static vector<vector<int>> data_var_names();
static vector<vector<int>> transformed_data_var_names();
static vector<vector<int>> parameters_var_names();
static vector<vector<int>> transformed_parameters_var_names();
static vector<vector<int>> generated_quantities_var_names();
```

**Design II** simplifies to two functions with a lot of switches.  This'd be easier overall to code generate.
```
static vector<pair<string, string>>
static_var_decls(bool data, bool t_data, bool params, bool t_params, bool gqs);
```
and one dynamic that adds sizes:
```
vector<tuple<string, string, vector<int>>>
dynamic_var_decls(bool data, bool t_data, bool params, bool t_params, bool gqs);
```

<b>Design III</b> would add an object oriented return type to design II
```
class var_decl {
private:
  const string name_;
  const string type_;
public:
  var_decl(string name, string type);
  string name() const;
  string type() const;
};

struct sized_var_decl : public var_decl {
private:
  const vector<int> dims_;
public:
  runtime_var_decl(const string& name, const string& type, const vector<int>& dims);
  vector<int> dims() const;
};
```
```
static vector<var_decl>
var_decls(bool data, bool t_data, bool params, bool t_params, bool gqs);
```
```
vector<runtime_var_decl>
sized_var_decls(bool data, bool t_data, bool params, bool t_params, bool gqs);
```

<b>Design IV</b> would have 10 functions, with tuple or object returns matching the above.

```
static vector<var_decl> data_decls();
static vector<var_decl> transformed_data_decls();
static vector<var_decl> parameters_decls());
static vector<var_decl> transformed_parameters_decls();
static vector<var_decl> generated_quantities_decls()
```
```
vector<runtime_var_decl> data_runtime_decls();
vector<runtime_var_decl> transformed_data_runtime_decls();
vector<runtime_var_decl> parameters_runtime_decls();
vector<runtime_var_decl> transformed_parameters_runtime_decls();
vector<runtime_var_decl> generated_quantities_runtime_decls()
```

**Comment by rok-cesnovar** [comment]
This is a code-gen issue that does not seem to be relevant with stanc3 anymore. Please reopen and we can move it if you feel otherwise.
