### ISSUE TITLE
Fix GP chapter typos

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/stan#2371]
#### Summary:

Fix typos in the new GP chapter

#### Description:

Several of the models need cleaning, as well as some of the text.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.16.0

**Comment by Gijs-Koot** [comment]
In particular, in **18.2. Simulating from a Gaussian Process**, in the first sample model, the manual construction of `K` involves the term `exp(-1/2)`, which is interpreted and rounded as an integer division (also noted with a warning when running), leading to an incorrect simulation.
