### ISSUE TITLE
Alegbra Solver References

### ISSUE THREAD

**Issue by charlesm93** [stan-dev/stan#2380]
#### Summary:
In response to @avehtari in issue #2300, I would like to doc which algorithm is used and reference the library we used. In addition, they are a few errors in the doc we need to correct, see http://discourse.mc-stan.org/t/algebra-solver-details/1553/8.

#### Description:
I will correct the errors Aki picked up on (mostly in the example code: need to replace a real[] with an int[] and add the function's name when calling the algebraic solver). In addition, I propose adding at the end of chapter 46, a brief section entitled "algorithmic details" with references.

#### Reproducible Steps:
NA

#### Current Output:
NA

#### Expected Output:
NA

#### Additional Information:
NA

#### Current Version:
v2.16.0

**Comment by bob-carpenter** [comment]
* [ ] add chapter about algorithm in Part VII : Built-in functions  (like the ODE chapter)
* [ ] make sure it gets added to the index

If you want to go into more detail, you could add a new chapter Part VI, Algorithms and Implementations.

**Comment by charlesm93** [comment]
- [x] add chapter about algorithm in Part VII : Built-in functions (like the ODE chapter)
- [x] make sure it gets added to the index

The chapter in Part VII was already there. I added a section, entitled algorithmic details, with the references @avehtari may have been looking for. I think I corrected all the errors, regarding the function's signature (really sorry I missed some, I really thought I had them all after @bob-carpenter 's first review).

**Comment by charlesm93** [comment]
See pull request #2382.

**Comment by charlesm93** [comment]
I'll repost here, since this has not been closed.

Michael spotted an error in the manual in the description of the Algebraic Solver. It's a minor typo in section 20.2:

```
real[] x_i) {  // data (integer)
```

Obviously, `real[]` should be `int[]`. This typo escape my last inspection. The other signatures for the algebraic solver look fine.

**Comment by bob-carpenter** [comment]
Should this issue be closed?  Will that patch in the manual be part of it?  If not, you can always report bugs or fixes for the manual in the next manual issue.

**Comment by charlesm93** [comment]
I'd say the issue can be closed once pull request #2403 has been accepted. Next time, I'll report issues in the manual issue.
