### ISSUE TITLE
tighter typing on local variables

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2395]
#### Summary:

Right now, local variables are promoted to the return type of a function or the type of a block.  But if they're data variables, this overpromotes.  

#### Description:

We could lean lean on the `data` qualifiers in function declaration to help know that variables can safely be `double` or `int`.

#### Reproducible Steps:

For example,

```
real foo(real x, real y, real z) {
  real a = y^2 + z^2;
```
will declare the local variable for `a` using the return type of the function, which is the promotion of all three types, not just `y`'s and `z`'s. 

Same situation with
```
model {
  real a = y^2 + z^2;
```
If `y` and `z` are data variables, then `a` can be declared as `double`.

#### Current Version:
v2.17.0

**Comment by VMatthijs** [comment]
@seantalts , this might interest you. This information should be statically available in the decorated ast in stanc3.

**Comment by rok-cesnovar** [comment]
Closing. Available with the optimizer in stanc3.
