### ISSUE TITLE
restrict second argument of rising- and falling-factorial to integer

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2412]
#### Summary:

The second arguments should be restricted to integer type.  

#### Description:

This is needed for stan-dev/math pull request: https://github.com/stan-dev/math/pull/636#pullrequestreview-66822019

The math library is changing to reflect this and the parser and test model 

```
src/test/test-models/good/function-signatures/math/functions/falling_factorial.hpp
src/test/test-models/good/function-signatures/math/functions/rising_factorial.hpp
```

need to be changed to reflect this.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

**Comment by mitzimorris** [comment]
file `stan/lang/function_signatures.h` also needs to be changed.
add test/test-models/bad to check that old function sig is disallowed?

**Comment by mitzimorris** [comment]
changes made and pushed on branch https://github.com/stan-dev/stan/tree/feature/2412-arg2-rising-falling-factorial

**Comment by mitzimorris** [comment]
closing, fixed in https://github.com/stan-dev/stan/pull/2413
