### ISSUE TITLE
Local variables in transformed data are not registered as data

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#2416]
#### Description:

Local variables declared in local scopes within the `transformed data`
block are not recognized as data by the parser as if local scopes
take precedence over the global scope.  Presuming that the parser
is written that the global scope can be recognized I think that it's 
more natural, and certainly more convenient, if everything defined 
in the `transformed data` block registered as data.

#### Reproducible Steps:

Try to parse this program which uses the algebraic solver to force the parser to check the status of local variables.

```
functions {
  vector target(vector y, vector theta, real[] x_r, int[] x_i) {
    vector[2] deltas;
    deltas[1] = y[1] - theta[1] - x_r[1];
    return deltas;
  }
}

transformed data {
  vector[1] y;
  {
    vector[1] y_guess = [1]';
    vector[1] theta = [1]';
    real x_r[0] = {1.0};
    int x_i[0];

    y = algebra_solver(tail_delta, y_guess, theta, x_r, x_i);
  }
}
```
#### Current Output:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

first argument to algebra_solver must be the name of a function with signature (vector, vector, real[], int[]) : vector 
second argument to algebra_solver (initial guess) must be data only and not reference parameters
fourth argument to algebra_solver (real data) must be data only and not reference parameters
  error in 'gp_prior_tune.stan' at line 17, column 60
  -------------------------------------------------
    15:     int x_i[0];
    16: 
    17:     y = algebra_solver(tail_delta, y_guess, theta, x_r, x_i);
                                                                   ^
    18:   }
  -------------------------------------------------

PARSER EXPECTED: ")"
```

#### Expected Output:

No parser error.

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
This is definitely a bug.  I'm assigning to @mitzimorris---she's been refactoring all this scope stuff recently, so hopefully it'll be an easy fix.

**Comment by mitzimorris** [comment]
fixed and tested by model in `src/test/test-models/good/parser-generator/data_qualifier_scope_xformed_data.stan`
