### ISSUE TITLE
integer arrays should be assignable to real arrays

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2419]
#### Summary:

I think this should work:

```
int[3] x = { 1, 2, 3};
real[3] y = x; // FAILS as of Stan 2.17
```

This is related to #830;  it'd be nice to provide full covariance and contravariance through containers for the `int` to `real` promotion.

#### Current Version:
v2.17.0

**Comment by rok-cesnovar** [comment]
This is doable on develop so closing.
