### ISSUE TITLE
next manual, 2.18

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2437]
#### Summary:

Corrections and suggestions for the manual after the 2.18 release should be included as comments and I'll fix them all before the next release.

#### Current Version:
v2.17.0

**Comment by bbbales2** [comment]
One of my labmates dug up a few issues.

Pg 194, Mixture Models, the model in the section "Estimating Parameters of a Mixture" needs a few updates to compile:

change ```ordered mu[K]``` to ```ordered[K] mu```
change ```real log_theta[K] = log(theta)``` to ```vector[K] log_theta = log(theta)```
change ```real lps[K] = log_theta``` to ```vector[K] lps = log_theta```

**Comment by maxbiostat** [comment]
Page 288, where it reads
> If the variable u has a distribution, then logit(u)...

it should read 

> If the variable u has a Uniform(0, 1) distribution, then logit(u)...

I think.

**Comment by Ctross** [comment]
On 27. Multiple Indexing and Range Indexing, it is stated in the manual that:
for (n in 1:N)
y[n] ~ normal(alpha[ii[n]] + beta[ii[n]] * x[n], sigma);

is equivalent to:
y ~ normal( rows_dot_product(alpha[ii] + beta[ii] , x), sigma);

is this correct?

Or should it be:
y ~ normal( alpha[ii] + rows_dot_product(beta[ii] , x), sigma);

**Comment by bob-carpenter** [comment]
Thanks, @Ctross---definitely a typo  --- the `alpha[ii]` should be on the outside.

**Comment by bob-carpenter** [comment]
From @mahaa2 in issue https://github.com/stan-dev/stan/issues/2453:

In Section 35.8 - Correlation matrix, some equations appear to be wrong.

First :
**tanh : R ─> (-1, 1)** instead of **tanh : R -> (0, 1)**

Second :
In absolute Jacobian determinant of the correlation matrix inverse transform, the partial derivatives appear to be wrong. It should read :
\dfrac{\partial tanh γ_{i, j}}{\partial γ_{i, j}} because z_{i, j} = tanh γ_{i, j}.

Third :
In correlation matrix transform (last row)
z_{i, j} = w_{i, j}*prod_{i' = 1}^{i-1} (1 - z_{i', j}^2)^{-1/2} for 1 < i < j

**Comment by bob-carpenter** [comment]
From agkim on Discourse forums:

http://discourse.mc-stan.org/t/definition-of-the-function-phi/2896

In Section 40.12 Probability-Related Functions of the User’s Guide and Reference Manual Version 2.16, for the definition of the function Phi it seems that the integral should have a lower limit of -infinity, Is the text correct or the equation correct?

(And as Ben Goodrich points out, it should be -infinity)

* [ ] fix

**Comment by bob-carpenter** [comment]
* [ ] add definition of MCMC standard error to MCMC chapter (and probably much more)

**Comment by bob-carpenter** [comment]
From @stemangiola in https://github.com/stan-dev/stan/issues/2456

I believe "normal_lpmf" should read "normal_lpdf" 

In the line `target += normal_lpmf(log(y) | mu, sigma)`;

At page 291

**Comment by bob-carpenter** [comment]
* [ ] add comment to qualify `lp__` values for `unit_vector` type.  See:  

https://github.com/stan-dev/rstan/issues/479

and Ben's comment:  

https://github.com/stan-dev/rstan/issues/479#issuecomment-357555713

Maybe we can figure out how to back out the right `lp__` value when there's a nuisance distribution like this one, but that's a Stan issue.  For now, we should add doc.

**Comment by bob-carpenter** [comment]
* [ ] add discussion of how to pull mixture assignments out once you have a mixture model

**Comment by bob-carpenter** [comment]
* [ ] indicate in circular stats chapter that you can derive angle by `atan2(xy[2], xy[1])` if `xy is unit_vector[2]`

**Comment by bob-carpenter** [comment]
From Dirk Nachbar on http://discourse.mc-stan.org/t/typo-page-77/3151

* [ ] `matirx[M, M] x;` --- should be `matrix`

**Comment by bob-carpenter** [comment]
From http://discourse.mc-stan.org/t/reparameterization-example-in-manual/3199

* [ ] `vector[K] alpha = kappa * theta;` shold be `* phi`
* [ ] thank IambicPentameter (Discourse handle) for reporting

**Comment by bob-carpenter** [comment]
* [ ] add the Ben Goodrich trick for sampling from a truncated distribution as implemented by lcomm (Discourse handle).  See:

http://discourse.mc-stan.org/t/rng-for-truncated-distributions/3122/7

**Comment by maxbiostat** [comment]
From Trung Dung at http://discourse.mc-stan.org/t/a-typo-in-the-manual/3312
"I think this sentence in the manual 2.17.0, “Stan provides elementwise matrix **division and multiplication** operations, a .* b and a ./b.” should be changed to “Stan provides elementwise matrix **multiplication and division** operations, a .* b and a ./b.”

**Comment by bob-carpenter** [comment]
* [ ] add general section in language spec on `data` declaration for arguments
* [ ] add to section 2.16 "Control Parameters for ODE Solving" the constraint that the control parameters must be data and that if they are legal values, the result is an error
* [ ] move subsection "Arguments to the ODE Solvers" in 48.3. Stiff Solver to its own section because it applies to all; 
    - [ ] add that they throw errors if the values aren't legal for the control parameters

**Comment by bob-carpenter** [comment]
*[ ] fix the conflicting doc and clarifythat it really is the algorithm, but all our algorithms respect the rejection/error distinction

From @syclik:

We've got some conflicting doc now (stan reference 2.17.0). Appendix D says

> An example warning message is an informational message about ill-formed input to an underlying function, which results in a Metropolis rejection during sampling or a reduction in step size for optimization, without causing a fatal error. An example error message is when either sampling or optimization cannot find a region of non- zero probability or when a program being parsed is ill formed. When an error arises, whatever program is running cannot continue and the entire execution must halt.

That's right, but could be made clearer. This conflicts with 26.2:

> When an index is provided that is out of bounds, Stan throws a rejection error and computation on the current log density and gradient evaluation is halted and the algorithm is left to clean up the error.

**Comment by pourzanj** [comment]
Just noticed today that in Section 20.2 Coding an Algebraic System, the real[] x_i parameter of the function system should be int[] x_i.

**Comment by jeffeaton** [comment]
Typo on page 294 of manual (in section 22.4): `alpha = L + exp(my_vec_raw);` --> `alpha = L + exp(alpha_raw);`

**Comment by bob-carpenter** [comment]
From @rbecerril on https://github.com/stan-dev/stan/issues/2469

* [ ] fix integration bound in section 49.7, "Cumulative distribution functions"---it's listed as a lower bound of 0 rather than -infinity for the normal

**Comment by bob-carpenter** [comment]
* [ ] add discussion of interpretation of Dirichlet prior from [this discourse thread](http://discourse.mc-stan.org/t/vague-proper-dirichlet-prior/3318/6)

```
data {
  int<lower = 1> K;
  real<lower = 0> alpha;
}
generated quantities {
  vector[K] theta = dirichlet_rng(rep_vector(alpha, K));
}
```

Here are the first 10 draws for alpha = 0.001.

```
iterations   [,1]   [,2]   [,3]   [,4]   [,5]   [,6]   [,7]   [,8]  [,9]  [,10]
      [1,] 3e-203  0e+00 2e-298 9e-106  1e+00  0e+00  0e+00  1e-47 0e+00 4e-279
      [2,]  1e+00  0e+00 5e-279  2e-14 1e-275  0e+00 3e-285 9e-147 0e+00  0e+00
      [3,] 1e-308  0e+00 1e-213  0e+00  0e+00  8e-75  0e+00  1e+00 4e-58 7e-112
      [4,] 6e-166  5e-65  3e-68 3e-147  0e+00  1e+00 3e-249  0e+00 0e+00  0e+00
      [5,]  2e-91  0e+00  0e+00  0e+00  1e-60  0e+00 4e-312  1e+00 0e+00  0e+00
      [6,] 1e-114  0e+00  0e+00 1e-231  1e+00 1e-302  4e-67  0e+00 0e+00  3e-16
      [7,] 3e-311  5e-53 3e-249  0e+00  1e+00 5e-309  0e+00  0e+00 0e+00  0e+00
      [8,] 9e-267  0e+00  1e+00  0e+00  4e-20  0e+00 5e-143 4e-147 2e-90  0e+00
      [9,]  1e+00  0e+00 3e-230 5e-100  0e+00 3e-234 7e-121  6e-76 0e+00  0e+00
     [10,]  0e+00 3e-173  2e-96 3e-164  1e+00  0e+00 4e-257 1e-178 0e+00  2e-06
```

Here are the first 10 draws for alpha = 1

```
iterations [,1] [,2] [,3] [,4]  [,5]  [,6]  [,7]  [,8]  [,9] [,10]
      [1,] 0.17 0.05 0.07 0.17 0.034 0.133 0.026 0.032 0.271  0.05
      [2,] 0.08 0.02 0.12 0.07 0.521 0.008 0.069 0.043 0.008  0.06
      [3,] 0.02 0.03 0.22 0.29 0.171 0.096 0.086 0.002 0.051  0.03
      [4,] 0.04 0.03 0.21 0.13 0.041 0.009 0.098 0.037 0.224  0.18
      [5,] 0.11 0.22 0.02 0.01 0.059 0.183 0.333 0.041 0.010  0.01
      [6,] 0.19 0.05 0.22 0.03 0.007 0.093 0.036 0.209 0.025  0.13
      [7,] 0.01 0.14 0.18 0.14 0.128 0.051 0.119 0.092 0.077  0.05
      [8,] 0.03 0.06 0.04 0.10 0.049 0.060 0.009 0.227 0.203  0.22
      [9,] 0.03 0.20 0.01 0.05 0.012 0.237 0.112 0.143 0.038  0.17
     [10,] 0.05 0.08 0.06 0.15 0.137 0.106 0.040 0.132 0.070  0.17
```

And here are the first 10 for alpha = 1000

```
iterations [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
      [1,]  0.1 0.10  0.1  0.1 0.10 0.10 0.10  0.1 0.10   0.1
      [2,]  0.1 0.10  0.1  0.1 0.10 0.10 0.11  0.1 0.10   0.1
      [3,]  0.1 0.10  0.1  0.1 0.10 0.10 0.10  0.1 0.10   0.1
      [4,]  0.1 0.10  0.1  0.1 0.10 0.10 0.10  0.1 0.10   0.1
      [5,]  0.1 0.10  0.1  0.1 0.10 0.10 0.10  0.1 0.10   0.1
      [6,]  0.1 0.10  0.1  0.1 0.10 0.10 0.09  0.1 0.11   0.1
      [7,]  0.1 0.10  0.1  0.1 0.10 0.09 0.10  0.1 0.10   0.1
      [8,]  0.1 0.09  0.1  0.1 0.10 0.10 0.10  0.1 0.10   0.1
      [9,]  0.1 0.11  0.1  0.1 0.09 0.10 0.10  0.1 0.09   0.1
     [10,]  0.1 0.10  0.1  0.1 0.10 0.10 0.10  0.1 0.10   0.1
```
As the parameter alpha increases, the simplexes produced are increasingly uniform.

**Comment by bob-carpenter** [comment]
Moved from #2470 submitted by Erik Erhardt:

* [ ] on pl 48 in "Partial Array Assignment" section:  "as is is y" should be "as is y"

**Comment by bob-carpenter** [comment]
* [ ] break out posterior inference chapter (?)
* [ ] explain how to compute KL divergence from posterior to arbitrary density (not sure what it'd useful for)

**Comment by bob-carpenter** [comment]
* [ ] explain @bgoodri's missing data trick

```
X == X_miss + X_obs
```
so
```
X * beta == X_miss * beta + X_obs * beta
```
and we can use `csr_matrix_times_vector` for the multiplies.

**Comment by luisdamiano** [comment]
In the preface, under the "You Can Help" section, the Google user's group is mentioned as the preferred way of communication with the Stan team. Perhaps you want to link to the discourse forums now.

**Comment by bob-carpenter** [comment]
Thanks, @luisdamiano --- I'll get rid of it.  I thought I grepped and found the last of those, but apparently not.

**Comment by trantrungdung** [comment]
In page 482, manual 2.17 "The pre-multiplication case is similar, with b * inv(m) being more efficiently coded as as a / m."

I think it should be "The pre-multiplication case is similar, with b * inv(m) being more efficiently coded as as **b** / m."

**Comment by bob-carpenter** [comment]
* [ ] fix typo:
* [ ] thank Gary Appleseed

From https://github.com/garyappleseed on https://github.com/stan-dev/rstan/issues/500:

> real[] x_i should be int[] x_i

> There is a typo showing code that won't work. This would be obvious to anyone who knew anything about these issues, but I didn't and it took me a lot of work and some guessing to get it. This was complicated by the fact that the error message wasn't very clear. Anyway, the manual has two lines in a row starting with real[], and the second one should be int[].

**Comment by lcomm** [comment]
The manual states, "The conditional operator has the same behavior as the `ifelse` function in R." However, `ifelse` in R is vectorized, while the conditional operator is not (according to [here](http://discourse.mc-stan.org/t/elementwise-ternary-operator/1598)). The statement of similarity between the two should be qualified to note this discrepancy since `ifelse` in R is used primarily for vectors.

**Comment by rleonid** [comment]
From #PR2504  Language reference section, page 279, (line 765 of language tex):
"the number of rows of \code{a}" -> "the number of columns of \code{a}".

**Comment by rleonid** [comment]
Correlation matrices, and their Cholesky factors are described before covariance matrices. Moving the sentence that motivates the use of Cholesky factors to the first part lends to better exposition:

```diff --git a/src/docs/stan-reference/language.tex b/src/docs/stan-reference/language.tex
index 6a9f0e618..ec9d9799b 100644
--- a/src/docs/stan-reference/language.tex
+++ b/src/docs/stan-reference/language.tex
@@ -792,7 +792,8 @@ unconstrained matrices, if their dimensions match, and vice-versa.
 \subsection{Cholesky Factors of Correlation Matrices}

 Matrix variables may be constrained to represent the Cholesky factors
-of a correlation matrix.
+of a correlation matrix. This is often more convenient or more
+efficient than representing correlation matrices directly.

 A Cholesky factor for a correlation matrix $L$ is a $K \times K$
 lower-triangular matrix with positive diagonal entries and rows that
@@ -827,9 +828,8 @@ $K$ is the value of the data variable \code{K}.

 \subsection{Cholesky Factors of Covariance Matrices}

-Matrix variables may be constrained to represent the Cholesky factors
-of a covariance matrix.  This is often more convenient or more
-efficient than representing covariance matrices directly.
+Akin to correlation matrices, matrix variables may be constrained to
+represent the Cholesky factors of a covariance matrix.

 A Cholesky factor $L$ is an $M \times N$ lower-triangular matrix (if
 $m < n$ then $L[m,n] =0$) with a positive diagonal ($L[k,k] = 0$) and

**Comment by rleonid** [comment]
Correct Cholesky factor variable reference in the correlation part. Also add a reference to the underlying correlation matrices and used the latex capitalized sigma even though that seems non-standard in this section of the reference, did not check the rest.

```
diff --git a/src/docs/stan-reference/language.tex b/src/docs/stan-reference/language.tex
index ec9d9799b..b10c6750b 100644
--- a/src/docs/stan-reference/language.tex
+++ b/src/docs/stan-reference/language.tex
@@ -795,7 +795,7 @@ Matrix variables may be constrained to represent the Cholesky factors
 of a correlation matrix. This is often more convenient or more
 efficient than representing correlation matrices directly.

-A Cholesky factor for a correlation matrix $L$ is a $K \times K$
+A Cholesky factor $L$ for a correlation matrix $\Sigma$ is a $K \times K$
 lower-triangular matrix with positive diagonal entries and rows that
 are of length 1 (i.e., $\sum_{n=1}^K L_{m,n}^2 = 1$).  If $L$ is a
 Cholesky factor for a correlation matrix, then $L\,L^{\top}$ is a
```

**Comment by bob-carpenter** [comment]
From @kejiashi on https://github.com/stan-dev/stan/issues/2512:

> "The marginal distribution of β when you integrate out τ is Student-t(ν , 0, 1)..."
In the following normal distribution, should it be N(beta|0,tau^{-0.5}) instead of N(beta|0,1/tau^{-0.5})?

* [ ] fix
* [ ] thank Kejia (KJ) Shi

**Comment by erikerhardt** [comment]
"blocks" to "block"

10.6. Hidden Markov Models
Calculating Sufficient Statistics
The data is declared as before, but now a transformed data **blocks** computes the sufficient statistics for estimating the transition and emission matrices.

**Comment by bbbales2** [comment]
hypergeometric_rng signature in manual is: ```int hypergeometric_rng(int N, real a, real b)```

But it should be: ```int hypergeometric_rng(int N, int a, int b)```

(source: https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/prob/hypergeometric_rng.hpp#L14)

**Comment by mdscheuerell** [comment]
In Sec 10.1 of the manual (p162), the AR(1) model is defined as

y[n] ~ normal(alpha + beta * y[n-1], sigma).

Just below there, the parameter alpha is defined as the intercept, but that is not correct. Rather, the intercept of the defined model would instead be

intercept = alpha / (1 - beta).

If you want to define the model in terms of an explicit intercept alpha, then it should be rewritten as

y[n] ~ normal(alpha + beta * (y[n-1] - alpha), sigma).

**Comment by bob-carpenter** [comment]
Thanks, https://github.com/mdscheuerell---I'll fix it for the next release.

**Comment by mitzimorris** [comment]
section Stan Modeling Language /  Expressions /  Variables / Reserved Names
should include keyword `target` (is this part of the Stan language?  implementation?)

**Comment by bob-carpenter** [comment]
Include example of sum-to-zero with standard-normal marginals:

```
parameters {
  vector[N - 1] mu_prefix;
}
transformed parameters {
  vector[N] mu = append_row(mu_prefix, -sum(mu_prefix));
}
model {
  mu ~ normal(0, inv(sqrt(1 - inv(N))));
}
```

Also, a discussion of using QR to achieve sum-to-zero by Aaron Goodman in the Stan forums.

**Comment by bob-carpenter** [comment]
From @ksvanhorn in #2525 

<b>Summary:</b>  One part of the manual says that integer division rounds towards 0, another says that it rounds down. These are inconsistent if one of the arguments is negative.

<b>Description:</b> In the intro to Section 40.1 "Integer-Valued Arithmetic Operations", it says "...integer division implicitly rounds the result... If one of the integer arguments to division is negative, the latest C++ specification (C++11), requires rounding toward zero." The example is given that `-1 / 2` evaluates to `0`

But on the next page, the documentation for `operator/(int, int)` says

```
operator/(x,y) = floor(x,y)
```

which is rounding down. That is, `-1 / 2` evaluates to `-1`.

There may also be an issue with the documentation for operator%, which states

```
operator%(x,y) = x mod y = x - y * floor(x/y)
```

**Comment by ksvanhorn** [comment]
The manual (Section 3.3, subsection "Expressions as Bounds") that "Variables used in constraints can be any variable that has been defined at the point the constraint is used." But what if the variables are declared first, then defined later in the same block? For example,

    transformed parameters {
      real alphap;
      real<lower=alphap> betap;
      alphap = sqrt(alpha);
      betap = alphap * beta;
    }

The variable alphap has been declared, but not defined, at the point where we declare betap. However, Stan seems to be fine with this; the following program using the above block compiles and runs fine:

    data {
      int N;
      vector[N] y;
    }
    parameters {
      real<lower=0, upper=1> alpha;
      real<lower=1> beta;
    }
    transformed parameters {
      real alphap;
      real<lower=alphap> betap;
      alphap = sqrt(alpha);
      betap = alphap * beta;
    }
    model {
      beta ~ pareto(1, 2);
      y ~ normal(betap, alphap);
    }

It's not clear from the manual whether this is accidental or intended. It does seem to make sense, as the transformed parameters block used above should be equivalent to

    transformed parameters {
      real alphap = sqrt(alpha);
      real<lower=alphap> betap = alphap * beta;
    }

**Comment by mitzimorris** [comment]
the key sentence here is tucked away in section `Assigning Constrained Variables`:

> Checks are carried out at the end of each relevant block of statements to ensure constraints are enforced. This includes run-time size checks

This should also be copied into the discussion in section `Constrained Data Types` and we should include the above example (or something similar).

**Comment by bob-carpenter** [comment]
Thanks, @ksvanhorn.  I'll fix as follows.

* [ ] fix language to say "declared" rather than "defined"
* [ ] provide example of what @mitzimorris is saying about checks coming at end, using @ksvanhorn's example to illustrate
* [ ] explain how parameter block is different in that the constraints define unconstraining transforms and that parameters (like data) are defined externally

**Comment by samuel-watson** [comment]
The multivariate probit model specified in the manual (pages 157-160) doesn't compile. The error (for me at least) is in the functions block:
```
functions {
  int sum(int[,] a) {
  int s = 0;
  for (i in 1:size(a))
    s += sum(a[i]);
  return s;
  }
}
```
the function is called ‘sum’, which is also something else in C++ I believe so it errors when compiling. Changing the name (and where the function is used in the transformed data block) solved the issue.

**Comment by mitzimorris** [comment]
@bob-carpenter is this a problem for the Stan compiler?
the parser incorrectly thinks `sum(a[i])` is a recursive call, even though a[i] is a 1-d array.
adding forward declaration also fixes this problem,

```
functions {
  int sum1(int[,] a);


  int sum1(int[,] a) {
  int s = 0;
  for (i in 1:size(a))
    s += sum(a[i]);
  return s;
  }
}
```

**Comment by mitzimorris** [comment]
@bob-carpenter - is this an error for Stan parser?

**Comment by mitzimorris** [comment]
the parser should recognize that fn call `sum(a[i])` has arg which is 1-d int array.
generated code suggests that parser isn't seeing indexing on `a[i]`

**Comment by samuel-watson** [comment]
Apologies that was my fault as I assumed it was just a typo in the manual naming the function!

**Comment by bob-carpenter** [comment]
@samuel-watson Please continue to report wherever you think is appropriate.  We'd rather get reports than not get them.  The devs can deal with triage and moving things around if the root cause is known to be elsewhere.

**Comment by bob-carpenter** [comment]
* [ ] fix to read `tau < y` for support
* [ ] move 3/2 into exponent

Thanks, @pasjor.  I just dove into the code and verified that indeed it requires `tau < y` because it throws an excpetion if `y <= tau`.  It also has to be that way to be consistent with the formula as written.

And that it should be exponent `3/2` --- there's a 1.5 multipler in the code to match.

I'm not sure whether to trust the code to resolve the rest of the issues.  There are calls to `sin` that I can't make line up with the formula, either.  Anyone have a definitive read on what these should be?  I only see `alpha` being squared.  

@syclik ---  The doc is a bit incomplete on this density in the code (`math/prim/scal/prob/wiener_lpdf.hpp`).  It also looks like it's missing a check for either `tau < y` or `y < tau` if that's supposed to be enforced.  It also has redundant `check_not_nan` calls.

**Comment by syclik** [comment]
Ok. Mind spawning a new issue? I've got a bunch of other things on my stack before I can look at it.

**Comment by mitzimorris** [comment]
The precedence of the range indexing operator ":" should be documented.   E.g., the sum-to-zero centering code example in section 9.7 contains expression:  `beta[1 : K - 1] = beta_raw;`
R users (and others) might think that ":" binds tighter than subtraction here, and would therefore write this as `beta[1 : (K - 1)] = beta_raw;`  - this isn't necessary, but this should be made clear in the section on range indexing.

**Comment by pasjor** [comment]
@bob-carpenter:

As far as i know there are two equivalent formulas for the density (although they really dont look similar).
The first involves sin-functions and i guess that is the implementation you refer to. It appears though that the second formula is stated in the manual. Both formulas can be found in Navarro & Fuss (2009). Fast and accurate calculations for first-passage times in Wiener diffusion models.

**Comment by bob-carpenter** [comment]
This is how it's always devolved---multiple definitions and outside references I don't have the background to fully comprehenend.  If someone can give me a definitive set of definitions for everything that match our code, I'm happy to change the doc, which is what this issue is about.

**Comment by aornugent** [comment]
I just got burned by `inv(matrix)` =/= `inverse(matrix)`.

pg. 482 describes how to use matrix division instead, but gives `inv(m) * a` as an example instead of `inverse(m) * a`

**Comment by wds15** [comment]
Is `map_rect` documented already? We need to cover the function itself, explain MPI over threading precedence and maybe even give some recommendations on using this facility? For example, it's best to calculate the log-prob and one should watch a little bit for the order of job chunks as it determines how things are scheduled.

**Comment by bob-carpenter** [comment]
@wds15  Yes, `map_rect` is documented, but not the changes to how it's configured.  Is that something done at an OS level?  I may need to have you write these sections.  Alternatively, feel free to write up what you think needs to go in there and I can just insert and format if that's easier.

**Comment by luisdamiano** [comment]
Page 518 from Stan Manual v2.17.0, section **52.3. Negative Binomial Distribution (log alternative parameterization).**

"Stan Functions" is highlighted as a new section and is rendered as a numbered section **52.4. Stan Functions**. It should be coded as an italic paragraph instead. This happens between the description for the functions _neg_binomial_2_log_ and _neg_binomial_2_log_lpmf_.

Please, let me know if I'm not being clear.

**Comment by bob-carpenter** [comment]
@yizhang-cae  The `matrix_exp` function is documented in "Linear Algebra Functions and Solvers".  You can find all the functions in the index.

**Comment by marcomarconi** [comment]
typo at page 255 v 2.17:

`y ~ bernoulli_logit(a + f);`

should be:

`z ~ bernoulli_logit(a + f);`

**Comment by Raoul-Kima** [comment]
Section 21.5, second paragraph, last sentence:

> In such cases, **replacing** the fixed prior with a hierarchical prior such as normal(mu, sigma), where mu and sigma are new parameters, with their own hyperpriors.

Either "replacing" should have been "replace", or the sentence isn't complete. Reading the paragraph is seems as if the last bit of the paragraph is missing, as the explanation for the suggested action is missing.
