### ISSUE TITLE
expose map_rect from math

### ISSUE THREAD

**Issue by wds15** [stan-dev/stan#2440]
#### Summary:

Write a new expression grammar rule for `map_rect()`.  It must generate calls to the following function in  defined as

```
template <int Id, class F, typename T_shared, typename T_job>
Matrix<typename return_type<T_shared, T_job>::type, -1, 1>
map_rect(const Matrix<T_shared, -1, 1>& shared,
         const vector<Matrix<T_job, -1, 1>>&  Job,
         const vector<vector<double>>& X_r,
         const vector<vector<int>>& X_i,
         std::ostream* msgs = 0);
```

The type `F` must denote a class with a nullary constructor and functor signature
```
template <typename T_shared, typename T_job>
Matrix<typename return_type<T_shared, T_job>::type, 1, 1>
operator()(const Matrix<T_shared, -1, 1>& shared,
           const Matrix<T_job, -1, 1>& job,
           const vector<double>& x_r,
           const vector<int>& x_i,
           std::ostream* msgs) const;
```

The calls in the code so far can be trased through the [math lib issue here](https://github.com/stan-dev/math/issues/686).

#### Description:

The Stan function will have the signature as defined in the referred issue above. As additional complication we will have to pass the user function (the respective generated functor objected) as template argument to the `map_rect` function.

#### Reproducible Steps:
NA

#### Current Output:
NA

#### Expected Output:
NA

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
Thanks for creating the issue and assigning it to me---this bit's easy.

**Comment by bob-carpenter** [comment]
OK, not so easy if you really need to pass that function by template parameter.  I'm going to try to trace through all the pointers and consolidate in some kind of spec on this issue so I know we're on the same page before implementing.

**Comment by bob-carpenter** [comment]
@wds15  How do I generate the call_id?  I can generate the template parameter for the function.

**Comment by bob-carpenter** [comment]
@wds15  I'm also unclear on why the return of the functor instantiated of class `F` is returning something that gets transposed and then the return is a matrix:

https://github.com/stan-dev/math/blob/feature/concept-mpi-2/stan/math/prim/mat/functor/map_rect_reduce.hpp

I tried to lay out the signatures in the issue itself, but am stumped about the return type for `F`.

**Comment by wds15** [comment]
Let me go by ticket in order you wrote:

1. Well, I am enforcing with this interface the requirement of a stateless functor which is fully specified by its type. If it is a real pain for you to do that, then could have `map_rect` take as first argument the functor f and then I call `map_rect_serial`/`map_rect_mpi` without the functor.

2. It does not matter how you generate it at all. You could probably even take the line number where this function gets called. It needs to be guaranteed that for a given `call_id` the data (x_r and x_i) being passed into the `map_rect` **never** changes as it is assumed to be static data such that it will only ever be distributed a single time to the workers.

3. You should look at the `prim` and the `rev` version (https://github.com/stan-dev/math/blob/feature/concept-mpi-2/stan/math/rev/mat/functor/map_rect_reduce.hpp). The main work of `map_rect` is to evaluate the function over all jobs and store things into a huge Eigen matrix. The matrix has the format such that one column defines the result from the different jobs and there are as many rows as there are outputs per result. Maybe a picture below will explain easier the layout.

N=5 jobs
S=1 shared parameters
J=3 per job parameters

So the above implies that `shared` is of size 1 and `job` is an array of length 5 and each of those elements is a vector of length 3.

Let's assume that the result of this evaluation is such that we get a single vector of length 1 per job. Then we get (if I denote with a number the output from the respective job)

- for prim a 1x5 matrix `12345`
- for rev with shared and Job varying I get a 5x5 matrix
```
12345 <- function values
12345 <- gradient for the shared parameter
12345 <- gradient for the job parameter 1
12345 <-                                                 2
12345 <-                                                 3
```

Now assume that the output is ragged such that the second and third job return 2 results and the others still a single one. Then we get:

- for prim  `1223345`
- for rev (same case as above)
```
1223345 <- function values
1223345 <- gradient for the shared parameter
1223345 <- gradient for the job parameter 1
1223345 <-                                                 2
1223345 <-                                                 3
```

I hope the logic is getting clear here. The reason to align things like this is that Eigen matrices are column major. Hence it is simple with such a layout to slice things into as many parts as needed.

**Comment by bob-carpenter** [comment]
> On Jan 31, 2018, at 11:35 AM, wds15 <notifications@github.com> wrote:
> 
> Let me go by ticket in order you wrote:

Thanks.  This I think this is enough for me to get started.


> 	• Well, I am enforcing with this interface the requirement of a stateless functor which is fully specified by its type. If it is a real pain for you to do that, then could have map_rect take as first argument the functor f and then I call map_rect_serial/map_rect_mpi without the functor.

Every function automatically gets a functor generated already, so this isn't a problem.


> 	• It does not matter how you generate it at all. You could probably even take the line number where this function gets called. It needs to be guaranteed that for a given call_id the data (x_r and x_i) being passed into the map_rect never changes as it is assumed to be static data such that it will only ever be distributed a single time to the workers.

I'll require the x_r and x_i args to be data only so they can't change.

I'll just sequentially generate a call_id then, one for each usage in the
program.


> 	• You should look at the prim and the rev version (https://github.com/stan-dev/math/blob/feature/concept-mpi-2/stan/math/rev/mat/functor/map_rect_reduce.hpp). The main work of map_rect is to evaluate the function over all jobs and store things into a huge Eigen matrix. The matrix has the format such that one column defines the result from the different jobs and there are as many rows as there are outputs per result. Maybe a picture below will explain easier the layout.
> 
> N=5 jobs
> S=1 shared parameters
> J=3 per job parameters
> 
> So the above implies that shared is of size 1 and job is an array of length 5 and each of those elements is a vector of length 3.
> 
> Let's assume that the result of this evaluation is such that we get a single vector of length 1 per job. Then we get (if I denote with a number the output from the respective job)
> 
> 	• for prim a 1x5 matrix 12345
> 	• for rev with shared and Job varying I get a 5x5 matrix
> 12345 <- function values
> 12345 <- gradient for the shared parameter
> 12345 <- gradient for the job parameter 1
> 12345 <-                                                 2
> 12345 <-                                                 3
> 
> Now assume that the output is ragged such that the second and third job return 2 results and the others still a single one. Then we get:
> 
> 	• for prim 1223345
> 	• for rev (same case as above)
> 1223345 <- function values
> 1223345 <- gradient for the shared parameter
> 1223345 <- gradient for the job parameter 1
> 1223345 <-                                                 2
> 1223345 <-                                                 3
> 
> I hope the logic is getting clear here. The reason to align things like this is that Eigen matrices are column major.

That makes sense on alignment.  I'm still not sure I understand
all the raggedness.  I'll try to work on it over the weekend and
get back to you next week for an online chat if I can't figure it out.

> Hence it is simple with such a layout to slice things into as many parts as needed.

I'll try to work through this in an example from the prim version.
