### ISSUE TITLE
Discourse site down

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/stan#2442]
#### Summary:
discourse.mc-stan.org has been down a few times over the last couple days. Is this just me, or is it affecting other folks? I was just trying to access it now and getting errors.

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
Thanks, Ben.

I'll try to hunt it down. Can I ping you to test?

It's a DNS issue where our nameserver isn't handing it up to spec, but most networks are ok with it. I'll get their support to help.

**Comment by bbbales2** [comment]
Sure. Happened to me on campus Sunday afternoon I think. frog.cs.ucsb.edu. ping/trace away if it helps. Was failing for me last night from a hotel too though.

**Comment by syclik** [comment]
The registrar just rebuilt the zone file (I don't know what that actually
means). It should have fixed the problem.

Can you try again now?

**Comment by bbbales2** [comment]
Works for me now. Leave the issue open and I'll keep trying over the next few days. This has happened a few times to me over the last couple weeks. Sunday was the longest outage I got though.

**Comment by syclik** [comment]
Thanks. If you do see it go down, please let me know. You have my email
address? (When discourse is down, can't pm me on discourse)

**Comment by bbbales2** [comment]
Google says dl2604. Is that right?

**Comment by syclik** [comment]
Nope. I'm gonna pm you.

**Comment by bob-carpenter** [comment]
Closing issue as off-topic for repo.

**Comment by bbbales2** [comment]
(Haven't had issues since the fix, so hopefully it isn't an issue anymore)
