### ISSUE TITLE
wrong error message for wrong order of blocks

### ISSUE THREAD

**Issue by maverickg** [stan-dev/stan#2443]
#### Summary:

Forgot that blocks must be in order of functions, data, transformed data, parameters, transformed parameters, model, generated quantities.  When it's wrongly ordered, the error message is not helpful.  

#### Reproducible Steps:

Run stanc on the following example code:

```
parameters {
  real y;
}
data {
    int<lower=0> N;
}
model {
  y ~ normal(0, 1);
}
```

#### Current Output:

```$ ../bin/stanc bar.stan
Model name=bar_model
Input file=bar.stan
Output file=bar_model.cpp

PARSER EXPECTED: whitespace to end of file.
FOUND AT line 4:
data {
    int<lower=0> N;
}
model {
  y ~ normal(0, 1);
}
```

#### Expected Output:

Tell me the blocks are wrongly ordered. 

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
This isn't really a bug per se, but it needs to be fixed.

I think the message needs to be that it found the `data` block, but it's out of order.  In other cases where the block name is wrong, I think we need an alternative message.

**Comment by bob-carpenter** [comment]
Another issue I just uncovered is if I use `function` instead of `functions`, it gives me an unhelpful message:

```
C++ exception with description "PARSER EXPECTED: whitespace to end of file.
FOUND AT line 1: 
function {
  vector foo(vector shared_params, vector_job_params,
             real[] data_r, int[] data_i) {
    return [1, 2, 3]';
  }
}
```

At least I knew it had found the file.  What this should say is something like:

```
expected block declaration, consisting of one of the following keywords: functions, data, transformed data, 
parameters, transformed parameters, model, generated quantities
found: function
```

**Comment by mitzimorris** [comment]
updated parser error messages when revising grammar rules -
https://github.com/stan-dev/stan/commit/ec62e7dc701bb8b4cdcc285da2538ac3f92d4a02

closing for now.

**Comment by bbbales2** [comment]
This still seems like it's an issue (https://discourse.mc-stan.org/t/a-mixture-gaussian-model-with-censoring-data/10051). Can we re-open it?

This is the output for compiling the example model for 2.19.2:

```
> stan_model("Downloads/test.stan")
PARSER FAILED TO PARSE INPUT COMPLETELY
STOPPED AT LINE 4: 
data {
    int<lower=0> N;
}
model {
  y ~ normal(0, 1);
}



Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  failed to parse Stan model 'test' due to the above error.
In addition: Warning message:
In readLines(file, warn = TRUE) :
  incomplete final line found on '/home/bbales2/Downloads/test.stan'
```

**Comment by bob-carpenter** [comment]
We're not fixing errors in the C++ parser.  We should be switching over to the OCaml version soon.
