### ISSUE TITLE
have warnings when priors are missing or appear twice

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/stan#2445]
I know it's not an error, and if I don't specify a prior I get a flat one, but it will be handy if we can get a friendly warning if I forget to put a prior (as we get one if we have a transformed parameter on the lhs). The same goes if I have two priors for the same parameter. I also know I may want that, but at least in my experience, every time I had two priors on a parameter it was because of an error.

#### Current Version:
v2.16.1

**Comment by bob-carpenter** [comment]
I added your recommendation to the Stan pedantic mode functional spec here:

https://github.com/stan-dev/stan/wiki/Stan-Parser-Pedantic-Mode

So I'm going to close this.
