### ISSUE TITLE
Features for Algebra Solver

### ISSUE THREAD

**Issue by charlesm93** [stan-dev/stan#2449]
#### Summary:
Complements issue 651 on the math repo (https://github.com/stan-dev/math/issues/651). Allow user to pass the initial guess as a vector of parameters.

#### Description:
Edit grammar files to allow x to be a vector of parameters.

#### Current Output:
Initial guess must be passed as data.

#### Current Version:
v2.17.1

**Comment by rok-cesnovar** [comment]
This was closed by https://github.com/stan-dev/math/pull/703
