### ISSUE TITLE
In rstan, log_prob != lp__ when using a unit_vector parameter

### ISSUE THREAD

**Issue by rgiordan** [stan-dev/stan#2455]
#### Summary:
The ```log_prob()``` function in ```rstan``` should return the same value as ```lp__``` from the sampler when called with the parameter values from the same iteration and chain.  But the two differ if (and only if) there is a ```unit_vector``` parameter in the model.

#### Description:
In ```rstan```, one should be able to use ```get_inits```, ```unconstrain_pars```, and ```log_prob``` to get the same value of ```lp__``` as returned from the sampler.  However, the two are not the same if and only if there is a ```unit_vector``` type in the model.

#### Reproducible Steps:
The following R code reproduces the problem for me.  I also included an example without a ```unit_vector``` type to demonstrate expected behavior.  Though not shown, I tried this with every other permissible parameter type and only the ```unit_vector``` has this problem.

```
library(rstan)

good_model_code <- "
data {}
parameters {
  real real_x;
}
model {}
"

bad_model_code <- "
data {}
parameters {
  real real_x;
  unit_vector[2] unit_vector_x;
}
model {}
"

num_chains <- 3
good_model <- stan_model(model_code=good_model_code)
bad_model <- stan_model(model_code=bad_model_code)
good_sampling_result <- sampling(good_model, chains=3, iter=1000, data=list())
bad_sampling_result <- sampling(bad_model, chains=3, iter=1000, data=list())

GetLogProbs <- function(sampling_result, iter, chain) {
  num_warmup_samples <- sampling_result@sim$warmup
  par_list <- get_inits(sampling_result, iter=num_warmup_samples + iter)[[chain]]
  par_free <- unconstrain_pars(sampling_result, par_list)
  
  return(c(
    log_prob(sampling_result, par_free, adjust_transform=TRUE),
    extract(sampling_result, pars="lp__", permute=FALSE)[iter, chain, ]))  
}

# There's nothing special about this iteration and this chain.
iter <- 10
chain <- 2

GetLogProbs(good_sampling_result, iter, chain) # The same
GetLogProbs(bad_sampling_result, iter, chain)  # Not the same
```

#### Current Output:
```
> GetLogProbs(good_sampling_result, iter, chain) # The same
[1] 0 0
> GetLogProbs(bad_sampling_result, iter, chain)  # Not the same
[1] -0.5000000 -0.1071289
```

#### Expected Output:
N/A

#### Additional Information:
I am running rstan (Version 2.17.2, GitRev: 2e1f913d3ca3).

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
This issue was moved to stan-dev/rstan#479

**Comment by bob-carpenter** [comment]
This really is a Stan issue (sorry for moving it around, Ryan).  Ben lays out the problem here:

https://github.com/stan-dev/rstan/issues/479#issuecomment-357555713

So I'm going to reopen this and close the RStan issue.  I made a note as well to comment on this in the manual.

**Comment by bob-carpenter** [comment]
I was wrong.  This isn't a Stan issue, it has to do with the constraining and unconstraining being done in RStan.  See the link to @bgoodri's discussion above.  I should've read it more closely the first time.
