### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by stemangiola** [stan-dev/stan#2456]
#### Summary:
Please provide a short couple sentence summary.

Manual 2.17 spelling (?)

#### Description:
Describe the issue as clearly as possible.

I believe "normal_lpmf" should read "normal_lpdf" 

In the line target += normal_lpmf(log(y) | mu, sigma);

At page 291

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
There's always an open manual issue for little stuff.  Just add comments and I'll fix in the next release.  I moved this there:  https://github.com/stan-dev/stan/issues/2437#issuecomment-357005563
