### ISSUE TITLE
effective_sample_size() to POD types for RStan/PyStan usage

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2462]
#### Summary:

The current interface is

```
double effective_sample_size(const Eigen::Matrix<Eigen::VectorXd,  Dynamic, 1>& samples) const;
```

which is suboptimal for interfaces because of its use of Eigen.  I don't think it's good for Stan itself because of its unconventional use of Eigen matrices.

How about something more standard like

```
double effective_sample_size(const std::vector<std::vector<double>>& samples) const;
```

Lower level, we'd get even better memory locality with

```
double effective_sample_size(const double* samples, int num_chains, int num_draws) const;
```

For the interfaces, is it better if we actually take in a 3D input and do this for each parameter?

```
double effective_sample_size(const double* samples, int num_params, 
            int num_chains, int num_draws) const;
```
#### Description:

This'll make it easier for RStan and PyStan to use the effective sample size calculations based on Stan.

To maintain backward compatibility, we just need a new function

@bgoodri and @ariddell --- would this be enough to let you use it in RStan?  

#### Current Version:
v2.17.1

**Comment by bgoodri** [comment]
For R, any of these would be fine.

**Comment by ariddell** [comment]
Ditto for Python.

Thanks for getting to this! It will be a relief to have this long-standing todo checked off.

**Comment by roualdes** [comment]
@bob-carpenter, just submit a pull request for this.  It might not be 100% what you're looking for, but it's a good start as it has the right data structures and accurate calculations.  I'll let you continue discussion here or in the pull request.  Thanks.

**Comment by bob-carpenter** [comment]
It may be a week or two before I can knock this off, so if someone else wants to do it, it shouldn't be difficult.  We usually try to open-ended discussions in Discourse, big functional specs on Wikis, and technical specs as part of the issue refinement and PR reviews.

**Comment by roualdes** [comment]
With https://github.com/stan-dev/stan/pull/2575 now merged, should we close this?
