### ISSUE TITLE
RSTAN instillation issue when install that package on ubuntu 14.04

### ISSUE THREAD

**Issue by sushilcmd** [stan-dev/stan#2464]
#### Summary:
When i install rstan package in RStudio on Ubuntu 14.04 system then it’s give error non-zero exist.

ERROR: dependency ‘bayesplot’ is not available for package ‘shinystan’

#### Description:
and when i try to install 'bayesplot' and 'shinystan' package then both are give "installation of package ‘packageName’ had non-zero exit status"

#### Current R Version:
v3.4.3

#### Current RStudio version:
v1.1.419

**Comment by bgoodri** [comment]
This sounds like a versioning problem. Since you are on Ubuntu, you can do
(in a shell)

sudo add-apt-repository -y "ppa:marutter/rrutter"
sudo add-apt-repository -y "ppa:marutter/c2d4u"
sudo apt-get update
sudo apt-get install r-cran-rstan

**Comment by bob-carpenter** [comment]
This issue was moved to stan-dev/rstan#487
