### ISSUE TITLE
Namespace and rstan.so not found when load "rstan" library

### ISSUE THREAD

**Issue by sushilcmd** [stan-dev/stan#2465]
#### Summary:
@bob-carpenter  Thank you for resolve issue #2464 .
After installing rstan when i load that library then it's give error 

#### Description:

Error snapshot
![rstanheaders](https://user-images.githubusercontent.com/10064480/35607335-93de71b2-0679-11e8-86ca-374f86caf7f0.png)

#### Current Ubuntu version
v14.04

#### Current gcc version
v4.8.4

#### Current R Version:
v3.4.3

#### Current RStudio version:
v1.1.419

**Comment by bob-carpenter** [comment]
Please don't submit install issues for stan-dev/rstan issues in the stan-dev/stan repo.  

It's easier for us to answer questions like these, which aren't necessarily bugs, on our forum: http://discourse.mc-stan.org  

It helps immensely to let us know what you tried.  "After installing" doesn't tell us what you tried to do.  Did you include dependencies, for example?  It helps if you provide the results of running `sessionInfo()` in R.

I'm going to close this pending a reproducible issue.

**Comment by bob-carpenter** [comment]
This is more an install question than a reproducible issue, so I'm closing.
