### ISSUE TITLE
Add vectorized signatures for RNGs

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stan#2467]
#### Summary:
@bbbales2 added vectorized forms for a bunch of RNGs with these PRs:  https://github.com/stan-dev/math/pull/605 https://github.com/stan-dev/math/pull/722. Now we can add their signatures to the language. We might do something in line with what happened in this vectorizing PR: https://github.com/stan-dev/stan/pull/2107 but they won't be unary, so that will be slightly more complicated.

#### Current Version:
v2.17.1

**Comment by roualdes** [comment]
@seantalts I just submit a pull request for this issue, Feature/issue 2467 vectorized signatures rn gs, please review when convenient.  Thank you.

**Comment by bob-carpenter** [comment]
Thanks.  I just reviewed.

**Comment by roualdes** [comment]
With https://github.com/stan-dev/stan/pull/2585, https://github.com/stan-dev/stan/pull/2583, https://github.com/stan-dev/stan/pull/2580, and https://github.com/stan-dev/stan/pull/2471 all merged, should we  close this?

**Comment by bob-carpenter** [comment]
Sure.  We need a second issue for the versions that look like normal_rng(N, mu, sigma) to generate an array of N i.i.d. draws from a normal_rng(mu, sigma).  Those should be really easy to add and test with C++11 lambdas able to bind normal_rng(mu, sigma) into a nullary functor that can be iterated N times.

**Comment by mcol** [comment]
There's already #1558 about generating and array of N draws, so I'm closing this.
