### ISSUE TITLE
Stan throws error with empty array

### ISSUE THREAD

**Issue by lazypanda1** [stan-dev/stan#2468]
When I run the example below with N = 0, I run into an error (also below). 

This error doesn't occur when `data` is empty but of type `real`, or when the `data` has at least one element (for both `real` and `int` types). The error message here is also unclear to me. `data` array is empty, it doesn't have `non-int` values. If array emptiness is an issue, why doesn't the program also fail for an empty `real` array?

Are all these expected?

```
data {
int<lower=0> N;
int datax[N];
}

model {
for(i in 1:N){
datax[i] ~ weibull(1.0,1.0);
}
}
```
Error message:
```bash
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_b792a2a57df879a15a969a03d556f524 NOW.
Traceback (most recent call last):
  File "driver.py", line 34, in <module>
    fit = sm.sampling(data=data, iter=1000, chains=4)
  File "/usr/local/lib/python2.7/dist-packages/pystan/model.py", line 671, in sampling
    fit = self.fit_class(data)
  File "stanfit4anon_model_b792a2a57df879a15a969a03d556f524_9077231157931774679.pyx", line 457, in stanfit4anon_model_b792a2a57df879a15a969a03d556f524_9077231157931774679.StanFit4Model.__cinit__
RuntimeError: int variable contained non-int values; processing stage=data initialization; variable name=data; base type=int
```
Environment
```
pystan 2.16.0.0
python 2.7.6
```

**Comment by bob-carpenter** [comment]
This is not a Stan issue, it's a PyStan issue.  I verified everything works fine in RStan with

```
data {
  int<lower = 0> N;
  int y[N];
}
model {
  for(n in 1:N)
    y[n] ~ weibull(1.0, 1.0);
}
```

with

```
stan("foo.stan", data = list(N = 0, y = array(0, dim=c(0))),
     algorithm="Fixed_param")
```
So I'm going to move this issue to the PyStan tracker.

**Comment by bob-carpenter** [comment]
This issue was moved to stan-dev/pystan#437
