### ISSUE TITLE
computation of normal_cdf

### ISSUE THREAD

**Issue by rbecerril** [stan-dev/stan#2469]
#### Summary:
the manual describes normal_cdf as the integral with lower limit at 0, but it is not clear how to compute the actual cdf with lower limit at -infinity

#### Description:
I am trying to model the usual a normal cdf for which the integral has an infinite lower integration limit P(y<Y). As per the manual, stan computes an integral that starts at 0 or P(0<y<Y). So I was thinking of computing the cdf by adding P(y<0) to P(0<y<Y), but to is not clear what happens when the upper integration limit Y is negative. Does stan return 0? or P(Y<y<0)? Is there an intuitive way to compute P(y<Y)?

#### Reproducible Steps:
N/A 

#### Current Output:
N/A

#### Expected Output:
N/A

#### Additional Information:
N/A

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
Thanks. That's a typo in the manual example. The general text above the example of the normal is correct. For a variable `theta`, the CDF is always `F(y) = Pr[y <= theta]`.  

I'm closing this issue.  I left a note here and will fix in the next release:

https://github.com/stan-dev/stan/issues/2437#issuecomment-366471310

**Comment by rbecerril** [comment]
Great! thanks for the prompt reply.
