### ISSUE TITLE
Doc: Sec "Partial Array Assignment": "as is is y" to "as is y"

### ISSUE THREAD

**Issue by erikerhardt** [stan-dev/stan#2470]
#### Summary:
Documentation: stan-reference-2.17.1.pdf
typo, p.48.
Section Partial Array Assignment:
"as is is y" should be "as is y"

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
Thanks!  We keep these in a running "next manual" issue and I just fix them all at once.  It's easier than dealing with reviewing and testing a gazillion little typo issues:

https://github.com/stan-dev/stan/issues/2437#issuecomment-366985230

Each run through our unit tests takes hours, and we don't yet have it instrumented to detect manual-only changes.
