### ISSUE TITLE
relax requirement on final / in include paths

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2472]
#### Summary:

The include path mechanism currently appends the file name to the path, which requires the path to end in `/`.  Instead, check if the path ends in a separator, and if not, add one.

@ahartikainen originally brought this up in:  https://github.com/stan-dev/pystan/pull/438#issuecomment-367004027

#### Current Version:
v2.17.1

**Comment by bgoodri** [comment]
Also, if it cannot find the `#include`d file, the error message should reference the file name that it did not find.

**Comment by ariddell** [comment]
Should the milestone for this be bumped? This would be great to get in.

**Comment by ahartikainen** [comment]
Hi,

could the code also ignore whitespace before and after the statement?

E.g. https://stackoverflow.com/a/216883
