### ISSUE TITLE
Stan inv_logit is unstable

### ISSUE THREAD

**Issue by lazypanda1** [stan-dev/stan#2475]
Hi,

When I run the following program using `PyStan`, the results don't converge most of the time (~50-60% of the runs).
```
data {
  int<lower=0> N; 
  int<lower=0> K;
  int<lower=0,upper=1> y[N];
  row_vector[K] x[N];  
}

parameters {
  real v;
  real b;  
  row_vector[K] theta; 
}

model {
    v ~ exponential(1.0);
    for(i in 1:K){
        theta[i] ~ normal(0.0, v);
    }
    b ~ normal(0.0, v);
    for(i in 1:N){
        y[i] ~ bernoulli(inv_logit(dot_product(theta,  x[i]) + b));
    }
}
```

But, when I use `bernoulli_logit` instead (shown below), it works perfectly and the results converge in every run. 

```
 for(i in 1:N){
        y[i] ~ bernoulli_logit(dot_product(theta,  x[i]) + b);
    }
```

From my understanding, both of these versions are equivalent and should converge. Is that not the case?
Also note that, when they converge, the results are the same.

You can reproduce the success and failure cases for the former case using the following seeds:

```python
fit = sm.sampling(data=data, iter=2000, chains=4, seed=1403913169) # success
fit = sm.sampling(data=data, iter=2000, chains=4, seed=1156365265) # failure

```
If needed, I can try to provide a link to the data set (which is quite large), if you want to work with it.

Environment:
```
pystan 2.16.0
python 2.7.6
```

**Comment by wds15** [comment]
This is expected. The point of using bernoulli_logit is that you do not have to criss-cross natural and log space. Leaving things in log space makes things a lot more stable. There is a good reason for those bernoulli_logit (or poisson_log) distributions to be around. When you can use them and the reward is numerical stability.
