### ISSUE TITLE
Extend `+=` to sliced container lvalues

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/stan#2482]
#### Summary:

Compound '+=' statement causes a parser failure although the equivalent `x = x + y` works.

#### Description

None of the matrix slicing statements (`container[int[]]`, `container[int:int]`, etc.) are currently allowed on the left-hand side of assignments.  

#### Reproducible Steps:

Try to parse

```Stan
data {
  int N;
  int J[N];
}
parameters {
  vector[N] b;
}
model {
  vector[N] mu = rep_vector(0.0, N);
  mu[J] += b[J];
}
```

#### Current Version:
v2.17.1

[edit, Bob Carpenter:  I changed the title and added a description to clarify.]

**Comment by bob-carpenter** [comment]
Thanks for reporting.  I confirmed it's an issue and updated the issue title and generalized the issue.

To fix this, we'll need to implement a sliced matrix lvalue for `+=`, which shouldn't be a huge problem.  Maybe it's time to bite the bullet after the current refactor and build a proper *lvalue* expression template system.

**Comment by wds15** [comment]
uhm... I know I should file an issue for this, but there is another issue with sliced stuff: You cannot print them as there is no streaming operator overloaded. The model is parsed, but fails to compile...

**Comment by bob-carpenter** [comment]
This is related to the slices not having streaming output implementinations:  https://github.com/stan-dev/math/issues/792

**Comment by wds15** [comment]
thanks for creating the ticket.

**Comment by mitzimorris** [comment]
#2513 - same issue, flagged as a bug

**Comment by mitzimorris** [comment]
implemented correctly as of https://github.com/stan-dev/stan/pull/2678
