### ISSUE TITLE
stanc produces invalid C++ when sqrt called on int.

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/stan#2484]
#### Summary:
If a Stan program contains an expression of the form sqrt(e), where e is an int, the generated code leads to a C++ compiler error "call to 'sqrt' is ambiguous."

#### Description:
Modern C++ compilers have different signatures for `sqrt` other than just `double sqrt(double)`, and so a call of `sqrt(_e_)`, where `_e_` is of type `int`, leads to ambiguities as to which signature is intended.

#### Reproducible Steps:
Run `stan_model` on this code:

    data {
      int x;
    }
    parameters {
      real y;
    }
    model {
      y ~ normal(sqrt(x), 1);
    }

The call fails with `error: call to 'sqrt' is ambiguous`. (Note that this error is buried deep in the output; I had to redirect output to a file to even find it.)

If I replace `int x;` with `real x;` then the `stan_model()` call succeeds.

#### Current Version:
I was running RStan 2.17.3, compiled from source.

**Comment by bob-carpenter** [comment]
Thanks for reporting.  The problem is some kind of ambiguity arising in the RStan envionment, but the fix needs to be made in the math lib, for which the issue is this:

https://github.com/stan-dev/math/issues/712

You can workaround with `x + 0.0`, too.
