### ISSUE TITLE
Stan gives incorrect results

### ISSUE THREAD

**Issue by lazypanda1** [stan-dev/stan#2488]
The following program gives incorrect output:

```
data {
int<lower=0> N;
real data91[N];
real data92[N];
}
parameters{
real p89;
real p90;
}
model {
p89 ~ gamma(97.5336792979,86.2930824295);
p90 ~ beta(44.0, 44.0);
for(i in 1:N){
data92[i] ~ normal(p89*data91[i], p90);
}
}

```
Output:
```
       mean se_mean     sd   2.5%    25%    50%    75%  97.5%  n_eff   Rhat
p89    1.26  3.5e-3   0.12   1.02   1.18   1.26   1.34   1.52 1198.0    1.0
p90  136.72    0.27  10.24 117.97 129.36 135.89 143.35 158.35 1408.0    1.0
lp__ -102.6    0.03   0.91 -105.1 -102.9 -102.3 -101.9 -101.7 1095.0   1.01
```
The results seem to be flaky as Stan does not converge most of the times.

I run it in pystan using the following code snippet:
```
data = {"data91": [-68.52534563025273, -76.09550522079039, -44.675702944439635, -96.79279758555658, 84.76543406920308], "data92": [-479.67742919921875, -532.6685180664062, -312.72991943359375, -677.549560546875, 593.3580322265625], "weight": 7, "bias": 0, "N": 5}
fit = sm.sampling(data=data, iter=1000, chains=4)
```

Running this on BUGS gives correct output though:
```
		mean	sd	MC_error	val2.5pc	median	val97.5pc	start	sample
	p1	6.999	0.002552	9.459E-5	6.994	6.999	7.004	1001	1000
	p2	5.076	0.4679	0.0337	4.125	5.092	5.929	1001	1000
```

BUGS model:
```
model {
    p1 ~ dgamma(97.5336792979,86.2930824295)
    p2 ~ dbeta(44.0, 44.0)
    for(i in 1:N){
        tmp1[i] <- p1*x[i]
        Y[i] ~ dnorm(tmp1[i], p2)
    }
}

```

**Comment by syclik** [comment]
Thanks for providing a simple example. 

There isn’t a bug in Stan. There is a difference in the parameterization of the gamma distribution between BUGS and Stan. In Stan, you can find the mathematical definitions of the distributions in the Stan manual. 

The expected mean for p89 in Stan is alpha / beta which should be about 1.1. 

For questions like this, we would prefer if they were put on the Stan forums: http://discourse.mc-stan.org.

**Comment by lazypanda1** [comment]
I looked into the definition of `gamma` in `OpenBUGS`, which is what I used for the experiments [here](http://www.openbugs.net/Manuals/ModelSpecification.html#Gamma). It seems like the same as in `Stan` manual and the standard definition as well. Both of them seems to take the same parameters.

I also tried sampling from `OpenBUGS` and `Stan`'s `gamma` distribution and I get the same result in both case.

```
parameters {
  real<lower=0> alpha;
}
model {
  alpha ~ normal(10, 0.01);
}
generated quantities {
  real beta[50];
  for (i in 1:50){
  beta[i] = gamma_rng(alpha*5.0, alpha);
  }
}
```

which gives me:
```
beta[0]    5.01    0.02    0.7   3.72   4.51   4.99   5.48    6.4   2000    1.0
beta[1]    5.01    0.02   0.71    3.7   4.55   4.97   5.45   6.51   1968    1.0
beta[2]    4.99    0.02   0.68   3.74   4.52   4.95   5.45   6.44   2000    1.0
beta[3]    5.02    0.02   0.71   3.72   4.53   4.98    5.5   6.47   2000    1.0

....

beta[49]   4.99    0.02   0.71   3.72    4.5   4.93   5.46   6.52   1905    1.0
```
In `OpenBUGS`, I try this program
```
model {
    p1 ~ dgamma(50.0,10.0)
}
```
for which I got 
```
                mean    sd      MC_error        val2.5pc        median  val97.5pc       start   sample
        p1      5.0     0.7024  0.006509        3.716   4.962   6.467   10001   10000
```

In both cases the mean is `alpha/beta`.

Is there any other difference in the way in which `Stan` handles `Gamma` distribution compared to `OpenBUGS`? Or am I missing something here?
