### ISSUE TITLE
PyStan HMC does not terminate on simple model

### ISSUE THREAD

**Issue by lazypanda1** [stan-dev/stan#2489]
Running the following wrong model using hmc causes Pystan to produce several exceptions. It does not progress after iteration 1 and keeps printing exceptions. I had to interrupt several times after waiting for 10 mins to stop it.

```python
parameters{
 real y;

}
model {
y ~ exponential(1);

}
```
Is this expected? I see a similar issue was addressed in [rstan](https://github.com/stan-dev/stan/issues/82) before.

Note that NUTS terminates and produces some output in this case.

Please let me know if you need more info.

**Comment by syclik** [comment]
> Please let me know if you need more info.

Yes. Please provide, at the very least:
- operating system
- version of python and what distribution
- version of pystan
- compiler detail (compiler and version number)
- compiler options
- how you ran this in Python, please include details about how you ran HMC including any and all parameters you set by hand

The first thing we need to do is reproduce it. Then determine if it’s a pystan or stan problem. The info above would help that effort out. If you wanted to help a little more, you could try running from CmdStan to see if you have the same behavior. (I could do the same, but I really need to know the HMC parameters you used to try.)

**Comment by maverickg** [comment]
y needs to be specified with a lower bound of zero.

**Comment by syclik** [comment]
Yes, but it should still terminate. If it doesn’t, there’s a legitimate issue.

**Comment by bob-carpenter** [comment]
@lazypanda1:  The message board for discussions and help:  http://discourse.mc-stan.org

That's a better place to ask questions than issues.  We're just going to close the issues and they're not where other users are going to look.

If this is an issue, it's an issue with the PyStan interface, not with Stan.   So I'm going to move this issue to PyStan and let @ariddell decide what to do with it.  PyStan definitely shouldn't hang on this.  It should fail right away.

**Comment by bob-carpenter** [comment]
This issue was moved to stan-dev/pystan#446
