### ISSUE TITLE
new functions break backward compatibility;  namespace fixes needed

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#249]
In generated model code, functions are brought in with using statements.  This causes conflicts with variables of the same name.  For Stan 2, every function name is treated as a reserved word.  

The problem is that every new function we add breaks backward compatibility by disallowing any variable to have that same name.

The using statements allow us to use argument-dependent lookup to find the right instance for a function involving auto-diff variables.  

One solution would be to define every Stan function in a templated way in a new namespace and then use fully qualified calls to functions.  The downside is that it adds even more work in coding and testing for new functions.

An alternative is to qualify the functions that are used, but this requires type inference in the parser and code generator to figure out which version of a function to use.  This seems like too much complexity.

**Comment by jgabry** [comment]
Is this still a problem or can this be closed?

**Comment by bob-carpenter** [comment]
Still an issue.

**Comment by bob-carpenter** [comment]
#267 will fix this, too.
