### ISSUE TITLE
normal_cdf typo in manual? 

### ISSUE THREAD

**Issue by epierson9** [stan-dev/stan#2494]
#### Summary:
In section 49.7 of the manual (cumulative distribution functions) should the lower limit on the integral for the normal CDF be negative infinity rather than 0? (See the sentences that begin "For instance, normal_cdf(y, mu, sigma) is defined by..."). 

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
Thanks for reporting.  

An easier place to record easy-to-fix typos like these is "next manual" issue.  Somebody [already caught this one](https://github.com/stan-dev/stan/issues/2437#issuecomment-366471310), so it'll be fixed i for the 2.18 release.
