### ISSUE TITLE
One data-point bug ?

### ISSUE THREAD

**Issue by mahaa2** [stan-dev/stan#2500]
#### Summary:
Trying to perform Bayesian inference with only one data-point

#### Description:
I get an error saying the dimensions mismatch

#### Reproducible Steps in R-code :

```
library(rstan)

n = 100 
F = cbind(rep(1, n), runif(n, 1, 20)) 
y = F%*%as.matrix(c(4, 7)) + 2*rnorm(n)

Σ = diag(400, 2)
µ = c(0, 0.5)

modelCode = "
data {
	int <lower=1> N;
	real y[N];
	real x[N];
	vector[3] m;
	matrix[3, 3] S;
}

parameters {
	vector[3] theta;
}

model {
	theta ~ multi_normal(m, S);
	for (i in 1:N) {
		y[i] ~ normal(theta[1] + theta[2] * x[i], exp(theta[3]));
	}
}
"
stanStruct = stan_model(model_code = modelCode)

mp = c(µ, 0); Sp = diag(c(diag(Σ), 50000))
dataset = list(N = 1, x = F[1, 2], y = y[1], m = mp, S = Sp)
post = sampling(stanStruct, data = dataset, chains = 1, warmup = 1000, thin = 10, iter = 10000)

#### Current Output:
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=y; dims declared=(1); dims found=()  (in 'model157660f81e7c_6052dc66082cf1c7d5539826b92efe3c' at line 4)
```

[edit: escaped code]

#### Additional Information:
R version 3.4.4

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
It's unfortunately awkward for users, but it's isn't a bug.  

Stan's error message is correct, but it's confusing becaue of Stan's pickiness and R's freeness with types.

What you need to use in this case is
```
y = as.array(y)
```
to make sure R knows that you're creating an array.

P.S.  Thinning loses information, so we almost never do it unless memory is a concern.  And we almost always run multiple chains to help diagnose non-convergence.
