### ISSUE TITLE
map_rect parsing odd

### ISSUE THREAD

**Issue by wds15** [stan-dev/stan#2502]
#### Summary:
Models which use a function named `map_rectsomething` are not parsed.

#### Description:
The  example below demonstrates the issue The parser exits with this error message:
```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in '/home/weberse2/work/stan/bugs/map_rect/parser-error.stan' at line 13, column 20
  -------------------------------------------------
    11: }
    12: model {
    13:   real m = map_rectfake(2);
                           ^
    14:   theta ~ normal(0, 1);
  -------------------------------------------------

PARSER EXPECTED: "("
```

#### Reproducible Steps:
```
functions {
  real map_rectfake(int i) {
    print("i = ", i);
    return 1.0;
  }
}
data {
}
parameters {
  real<lower=0,upper=1> theta;
}
model {
  real m = map_rectfake(2);
  theta ~ normal(0, 1);
}
```

#### Current Output:
See above

#### Expected Output:
I think this should just compile fine.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
Thanks, I'll fix this.  I must have forgotten the magic after a keyword to avoid it being parsed off a prefix.
