### ISSUE TITLE
roll Aki's suggestions for GP into manual

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#251]
Moved here from #211 

* [ ] add radial basis example

* [ ] update w.r.t. Aki's comments for GP

**Comment by rtrangucci** [comment]
@bob-carpenter I think this exists in the manual now. Can we close this?

**Comment by bob-carpenter** [comment]
Can you check, and if it's not, add it to the longer-term manual issue?  Thanks.
