### ISSUE TITLE
typo on stan-reference-2.17.0

### ISSUE THREAD

**Issue by kejiashi** [stan-dev/stan#2512]
#### Summary:
Typo found on page 344 last formula

#### Description:
"The marginal distribution of β when you integrate out τ is Student-t(ν , 0, 1)..."
In the following normal distribution, should it be N(beta|0,tau^{-0.5}) instead of N(beta|0,1/tau^{-0.5})?

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
Thanks.  I'll fix it in the next release.  I moved this to here:

https://github.com/stan-dev/stan/issues/2437#issuecomment-378474593

There's always a next manual issue where you can leave typos to correct.

**Comment by kejiashi** [comment]
Got it. Thanks, Bob!
