### ISSUE TITLE
Creating matrices in generated quantities is slow

### ISSUE THREAD

**Issue by bletham** [stan-dev/stan#2516]
#### Summary:
Creating medium-sized matrices as generated quantities is extremely slow.

#### Description:
I would like to do a simulation inside generated quantities that produces a bunch of samples using model parameters. I'm interested right now in doing this for an already-obtained point estimate, so I've been trying to use
```
res <- rstan::optimizing(model, data=dat, init = function(){fitted_params}, iter=0)
```
where `fitted_params` here is a list of the param values.

This seems to work, but is extremely slow when there is a large-ish matrix being defined in generated quantities. Example:
```
library(rstan)
model_code = "
data {
  int N;
  vector[N] y;
  int m;
}

parameters {
  real theta;
}

model {
  y ~ normal(theta, 1);
}

generated quantities {
  matrix[3000, m] A;
  // Some computation here to fill A.
}
"
model = stan_model(model_code=model_code)

dat <- list(N=20, y=rnorm(20, 2), m=200)
res <- optimizing(
  model, data=dat, init=function(){list(theta=2)}, iter=0
)
```
Even without doing any computation to fill `A`, this takes me 5s with `m=100`, 10s with `m=200`, etc. The optimizer is printing out immediately that optimization has terminated due to max iterations, but then takes a long time to return from the command.

I thought it might be I/O between Stan and R, but 3000x200 doesn't seem like that large a matrix for 10s of I/O. Any ideas or tips on profiling? Or is there a better way to achieve this?

Apologies if this should be an rstan issue.

#### Current Version:
v2.17.3

**Comment by bob-carpenter** [comment]
Thanks for reporting.  Two suggestions for isolating the issue:

1.  remove any computation, or maybe just a loop in column-major order to initialize to 0.

2. add  `print("finished gq")` to end of generated quantities and see if you see that right away.

If it's slow after the print, we'll know it's RStan I/O.  If not, I'd want to run the test in CmdStan to make sure RStan isn't buffering.  

I believe we have some other pull requests around RStan I/O, but @bgoodri will know for sure.  We keep meaning to add protocol buffer I/O everywhere but haven't gotten around to it yet.

**Comment by bgoodri** [comment]
I am guessing it is an RStan issue due to the way thinks are stored as a
list of lists, but I don't know why it would manifest itself especially in
the generated quantities block.

**Comment by bletham** [comment]
Thanks @bob-carpenter. 
1. The slowness is without any actual computation: setting A to 0 in column major order, or in fact even in the code block from my post where all we do is declare A.
2. A print statement at the end of the GQ block is printing prior to the "Optimization terminated normally" message, and so before the 10s wait.

It runs instantly in cmdstan, so it must be the interface. I'll move this issue to rstan. It does actually run twice as fast if I use `vector[3000 * m] A` instead of `matrix[3000, m] A`, but still slow.
