### ISSUE TITLE
stan/io/writer.hpp no unit tests for cholesky correlation matrix

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2519]
#### Summary:
No unit test for method `cholesky_corr_unconstrain`  in unit tests.

#### Description:
Need unit tests for all variable types in the Stan language.  As part of this issue check that there are unit tests for reader and writer methods for all specialized tests.

#### Reproducible Steps:
run `find src/test/unit -name "*.cpp" -exec grep -l "cholesky_corr_unconstrain" {} \;
no files found.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.1

**Comment by WardBrian** [comment]
Removed in #3177, new interface has tests
