### ISSUE TITLE
Broken constraint in transformed parameters block should generate a warning

### ISSUE THREAD

**Issue by martinmodrak** [stan-dev/stan#2521]
#### Summary:
The manual suggests that constraints in `transformed parameters` are designed for error checking. If this is really the case, unsatisfied constraints should not cause a silent rejection, but also a clear warning message.

#### Description:
Stan manual, section 6.6 (on transformed parameters block) says

> Like the constraints on data, the constraints on transformed parameters is meant
> to catch programming errors as well as convey programmer intent. They are not
> automatically transformed in such a way as to be satisfied. What will happen if a
> transformed parameter does not match its constraint is that the current parameter
> values will be rejected.
> 

However, when constraints in the `transformed parameters` block are not met, the sampler silently rejects and causes a divergence, which may be hard to understand for users (see eg. this discourse thread: http://discourse.mc-stan.org/t/imposing-constraint-in-transformed-parameters-block/3921). Instead, the sampler should generate a clear warning message.

#### Reproducible Steps:
A small reproducible example:

```
library(rstan)

model_code <- "
parameters {
  real a;
}

transformed parameters {
  real<lower=0> b = a;
}

model {
  b ~ normal(0,1);
}
"

fit <- stan(model_code = model_code)
```

#### Current Output:
```
<<SAMPLING PROGRESS>>
Warning messages:
1: There were 2008 divergent transitions after warmup. Increasing adapt_delta above 0.8 may help. See
http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup 
2: Examine the pairs() plot to diagnose sampling problems
```

#### Expected Output:
A clear warning message, something like:

```
Warning: Attempt to assign out-of-bounds value to transformed parameter "real<lower=0> b"  Count: 2008.
```

#### Current Version:
v2.17.3

**Comment by bob-carpenter** [comment]
Thanks.

This repo isn't the immediate culprit here---it's the interfaces.  So I'm going to move this to an RStan issue.  I tried this model 

```
parameters {
  real<lower = -1, upper = 1> scale;
}
transformed parameters {
  real<lower=0> scale2 = scale;
}
```

and reproduced your lack of message in RStan.  

In CmdStan, here's what you see:

```
method = sample (Default)
  sample
    num_samples = 1000 (Default)
    num_warmup = 1000 (Default)
    save_warmup = 0 (Default)
    thin = 1 (Default)
    adapt
      engaged = 1 (Default)
      gamma = 0.050000000000000003 (Default)
      delta = 0.80000000000000004 (Default)
      kappa = 0.75 (Default)
      t0 = 10 (Default)
      init_buffer = 75 (Default)
      term_buffer = 50 (Default)
      window = 25 (Default)
    algorithm = hmc (Default)
      hmc
        engine = nuts (Default)
          nuts
            max_depth = 10 (Default)
        metric = diag_e (Default)
        metric_file =  (Default)
        stepsize = 1 (Default)
        stepsize_jitter = 0 (Default)
id = 0 (Default)
data
  file =  (Default)
init = 2 (Default)
random
  seed = 714361321
output
  file = output.csv (Default)
  diagnostic_file =  (Default)
  refresh = 100 (Default)

Exception: bar_model_namespace::write_array: scale2 is -0.0758982, but must be greater than or equal to 0  (in '/Users/carp/temp2/bar.stan' at line 5)
```

Meaningful warning message, which is good, but it shouldn't be terminating.  So I'll create a new issue for CmdStan.

**Comment by bob-carpenter** [comment]
This issue was moved to stan-dev/rstan#521
