### ISSUE TITLE
improve error msg when delcaration is made after assignment

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/stan#2523]
#### Summary:
When declare after assignment the msg is not informative.

#### Description:
When declare after assignment the error msg is
`variable xxx does not exitst`
where `xxx` is the type name of the declared variable. This is not informative to beginners.

#### Reproducible Steps:
`make` a model with the following `transformed data`
```stan
transformed data {
  real x;
  x = 3.0;
  real z;
  z = 3.0
}
```

#### Current Output:
```sh
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

variable "real" does not exist.
```

#### Expected Output:
More informative information on the order of declaration & assignment.

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
Thanks---the message should definitely be improved.  The plan is to relax the language to allow that to be legal, but until then, there needs to be a better message.

**Comment by VMatthijs** [comment]
Mixing var decls and statements in any order is now allowed in stanc3, in case that addresses the issue.

**Comment by mcol** [comment]
Fixed in stanc3.
