### ISSUE TITLE
Documentation of integer division is inconsistent

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/stan#2525]
#### Summary:
One part of the manual says that integer division rounds towards 0, another says that it rounds down. These are inconsistent if one of the arguments is negative.

#### Description:
In the intro to Section 40.1 "Integer-Valued Arithmetic Operations", it says "...integer division implicitly rounds the result... If one of the integer arguments to division is negative, the latest C++ specification (C++11), requires rounding toward zero." The example is given that -1 / 2 evaluates to 0.

But on the next page, the documentation for operator/(int, int) says

"operator/(x,y) = floor(x,y)"

which is rounding down. That is, -1 / 2 evaluates to -1.

There may also be an issue with the documentation for operator%, which states

"operator%(x,y) = x mod y = x - y * floor(x/y)"

#### Current Version:
v2.17.0 (Tuesday 5th September 2017)

**Comment by bob-carpenter** [comment]
Thanks for catching that.  We just delegate straight to C++, so as you rightly surmised, that determines behavior.  I'll update to match the C++ spec.

I'm moving this over to be a comment on the next manual issue---I update them all at once before each release:

https://github.com/stan-dev/stan/issues/2437#issuecomment-390413787
