### ISSUE TITLE
Misleading error message when function multiply defined

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2526]
_From @ksvanhorn on May 25, 2018 16:47_

#### Summary:
When a function is defined twice, the error message points to the function AFTER the second definition.

#### Description:
A program defines the function "rot_matrix" twice in the "functions" block. The error message points at the beginning of the definition of a later function, "scale_matrix".

#### Reproducible Steps:

Run stanc on the following program:

    functions {
      matrix rot_matrix() {
        return rep_matrix(0,1,1);
      }
      
      matrix rot_matrix() {
        return rep_matrix(0,1,1);
      }
      
      matrix scale_matrix() {
        return rep_matrix(0,1,1);
      }
    }
    data {
      int<lower = 1> N;
      vector[N] y;
    }
    parameters {
      real<lower=0> sigma;
    }
    model {
      sigma ~ normal(0, 1);
      y ~ normal(0, sigma);
    }     

#### Current Output:

    SYNTAX ERROR, MESSAGE(S) FROM PARSER:
    
    Parse Error.  Function already defined, name=rot_matrix  error in 'model661b1902a01a_foo' at line 10, column 3
      -------------------------------------------------
         8:   }
         9:   
        10:   matrix scale_matrix() {
              ^
        11:     return rep_matrix(0,1,1);
      -------------------------------------------------
     
    Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
      failed to parse Stan model 'foo' due to the above error. 

#### Expected Output:
The caret should point at the beginning of the second definition of `rot_matrix`.

#### RStan Version:
2.17.3

#### R Version:
R version 3.4.3 (2017-11-30)

#### Operating System:
OS X 10.13.4

_Copied from original issue: stan-dev/rstan#533_

**Comment by bob-carpenter** [comment]
_From @bgoodri on May 25, 2018 18:1_

I agree this is misleading, but I am sure it applies to all interfaces so
the issue should get moved to the stan-dev/stan repo.

**Comment by VMatthijs** [comment]
stanc3 currently says

```
Semantic error at file "test.stan", line 6, characters 9-19:
   -------------------------------------------------
     4:    }
     5:
     6:    matrix rot_matrix() {
                  ^
     7:      return rep_matrix(0,1,1);
     8:    }
   -------------------------------------------------

Identifier  rot_matrix  is already in use.
```

**Comment by bob-carpenter** [comment]
This is great.  I don't like the extra spaces around `rot_matrix` --- I think identifiers should be quoted as in C++ compiler error messages.  In general, I'd follow C++ error messages because they've had a long time to think about these and get them right.

Here, I'd prefer to see something like " 'rot_matrix' is already defined".

**Comment by bob-carpenter** [comment]
In C++, this program

```
int foo(int x) { return x; }
int foo(int x) { return x; }
int main() { return 1; }
```

produces

```
cpperr.cpp:2:5: error: redefinition of 'foo'
int foo(int x) { return x; }
    ^
cpperr.cpp:1:5: note: previous definition is here
int foo(int x) { return x; }
    ^
1 error generated.
```

I like that it says "redefinition" instead of "already in use".

**Comment by VMatthijs** [comment]
> This is great. I don't like the extra spaces around `rot_matrix` --- I think identifiers should be quoted as in C++ compiler error messages. In general, I'd follow C++ error messages because they've had a long time to think about these and get them right.


Just fixed this.

**Comment by mcol** [comment]
This was fixed in stanc3.
