### ISSUE TITLE
Stan fails silently on CSV Write failure

### ISSUE THREAD

**Issue by aaronjg** [stan-dev/stan#2536]
#### Summary:
When the disk is full, stan continues to run without outputting data to the CSV file. It appears that stream_writer does not check for errors after writing to the file

#### Reproducible Steps:
I don't have a good way to reproduce this yet, but there may be a way to simulate out of disk space issues by mounting small disk images as loopback devices.

#### Current Output:
Continues to run, without outputting any data.

#### Expected Output:
Stan should raise an exception and abort once it can no longer write output, rather than continuing to compute without outputting any data.

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
Thanks for reporting.  Looks like should be setting up our [output stream](http://www.cplusplus.com/reference/ostream/ostream/) instances to [set the exceptions state flag](http://www.cplusplus.com/reference/ios/ios/exceptions/).  That should cause a write in a bad state to throw an exception, which the interface could then handle and report before exiting.
