### ISSUE TITLE
Parser Yields Empty Error Message For Missing Terminating Brace

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#2537]
#### Description:

Parser gives an empty error message when terminating `}` is missing, at least in the final block.  If the parser is capable of identifying misplaced or incomplete braces it should err out with an appropriate message.

#### Reproducible Steps:

Run 

```
transformed data {
  int N = 10;
}

parameters {
  real x;
}

model {
  x ~ normal(0, 1);
}

generated quantities {
  real y[N];
  for (n in 1:N) {
    y[n] = normal_rng(0, 1);
}
```

#### Current Output:

```
--- Translating Stan model to C++ code ---
bin/stanc  parsing_problem.stan --o=parsing_problem.hpp
Model name=parsing_problem_model
Input file=parsing_problem.stan
Output file=parsing_problem.hpp

PROGRAM ERROR, MESSAGE(S) FROM PARSER:


```

#### Expected Output:

```
--- Translating Stan model to C++ code ---
bin/stanc  parsing_problem.stan --o=parsing_problem.hpp
Model name=parsing_problem_model
Input file=parsing_problem.stan
Output file=parsing_problem.hpp

PROGRAM ERROR, MESSAGE(S) FROM PARSER:

Braces are not consistent.  Perhaps you are missing a terminating brace somewhere?
```
#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
Thanks.  I verified it's a bug and assigned to @mitzimorris, who is fixing a bunch of these for the next release.

**Comment by bob-carpenter** [comment]
Clang somehow manages that error:

```
~/temp2$ clang++ parens.cpp
parens.cpp:5:2: error: expected '}'
}
 ^
parens.cpp:1:12: note: to match this '{'
int main() {
           ^
1 error generated.
```

when given

```
int main() {
  int sum = 0;
  for (int i = 0; i < 10; ++i) {
    sum += i;
}
```

At the point we run out of input, the parser is still expecting a closing brace or a statement.  

It's really great they are able to show where the brace started.

**Comment by mitzimorris** [comment]
it's a problem with the rules for a block of statements.
note that the parser allows this:

```
parameters {
  real y;
}
model
  y ~ normal(0, 1);
```

will fix.

**Comment by mitzimorris** [comment]
the unit tests for stan/lang have a utility function which invokes the parser using an ifstream object whereas the stan/lang/compiler calls the parser with a stringstream.  the unit tests show the parser correctly reporting the expectation failure; this doesn't happen in the compiler.

cannot figure out how to fix - not sure what boost spirit qi line position iterators are doing or why.

**Comment by bob-carpenter** [comment]
The boost iterators are inputs that keep track of line number and position.  That's how we're able to print out error locations.

Have you tried using a stringstream in the unit tests to see if they then fail?  That would positively isolate the source of the problem and suggest the failure's due to the stream config.

**Comment by mitzimorris** [comment]
closing; fixed by https://github.com/stan-dev/stan/pull/2554
