### ISSUE TITLE
Adams integrator in Stan language

### ISSUE THREAD

**Issue by yizhang-cae** [stan-dev/stan#2542]
#### Summary:
Expose `integrate_ode_adams` to Stan language

#### Description:
Allow Math function `integrate_ode_adams` to be used in Stan language. The function signature and the signature of ODE high-order functions are identical to `rk45` & `bdf` integrators.

corresponding function signature test and good/bad parser tests are added.

#### Reproducible Steps:
unit tests.

#### Current Output:
n/a

#### Expected Output:
Support of `integrate_ode_adams`

#### Current Version:
v2.17.1

**Comment by wds15** [comment]
As far as I recall, the `integrate_ode_adams` in stan-math is currently setup to use a netwon solver instead of a forward-integration technique. The newton solver is numerically expensive and by sundials recommended to be used for integration of stiff problems. The adams solver is recommended by sundials for non-stiff solvers when used with the forward integration.

In short, we are using a non-recommended combination and I would be interested for which applications the `integrate_ode_adams` is useful. Is it for non-stiff or stiff problems? Why are we using the netwon solver instead of the forward integration?

I think we should understand for which use-case this solver will be good for to avoid unnecessary maintenance burden.

BTW, in boost is by now an adaptive Adams Moulton implementation as part of odeint. Since boost is much more lightweight than CVODES, we should probably at least try theirs, no?

**Comment by yizhang-cae** [comment]
@wds15 , as I mentioned last time when you asked this question, I choose to use newton because of its higher-order accuracy and stability. That's my experience talking. Here's more explanation. 

> Why are we using the netwon solver instead of the forward integration?
I'm assuming by "forward integration" you mean the functional integration in CVODES.

The `CV_FUNCTIONAL` in CVODES is just the plain fixed-point iteration. It's of lower-order convergence rate than newton. This means even though newton requires more computation per each iteration, it generally requires less number of iterations to reach solution. So it boils down to how difficult to solve the linear system from ODE vs the number of the iterations, which is the premise of the manual's recommendation. So far I've not seen any Stan applications involving a really large ODE system. These systems tend be from a PDE solution but obviously we not doing that (we will, but not using CVODES).

Directly solvers shipped in sundials is really efficient for small-size systems. So it doesn't raise flag to me to use newton. The following are wall time results of the harmonic_oscillator test in Adams' unit test, compare using newton vs functional iteration. It shows newton is actually faster, under various tolerance settings.
<img width="721" alt="screen shot 2018-06-11 at 2 19 02 pm" src="https://user-images.githubusercontent.com/33104304/41250354-a3219254-6d84-11e8-9824-e7ab27a7990d.png">

**Comment by yizhang-cae** [comment]
> BTW, in boost is by now an adaptive Adams Moulton implementation as part of odeint. Since boost is much more lightweight than CVODES, we should probably at least try theirs, no?

I don't see how this would be a tremendous advantage over sundials. Even it were, wouldn't be the BDF solver to be replaced by boost's rosenbrock first?

**Comment by wds15** [comment]
And what does the Adams-Moulton+Newton scheme buy us vs the BDF+Newton?

Differently: for which problems do you recommend the Adams-Moulton + Newton algorithm?

With the `coupled_ode_system` in stan-math we basically have the sensitivity thing for which the stiff case is particularly amenable to optimizations as I understood. This is why sundials CVODES is so good for stiff stuff. My intuition tells me that for non-stiff problems this is all not really needed and the far more lightweight boost odeint is great.

So (my intuition) would tell me that for non-stiff problems we really should prefer boost odeint as the extra-optimizations from sundials are not needed and boost integrates much better with Stan. So the Adams-Bashfort-Moulton in odeint is worthwhile to try if we want to extend the solvers.

BTW, what do you think about the BDF limit detection thing in CVODES? Is that useful? (Sorry, off topic)

**Comment by yizhang-cae** [comment]
> And what does the Adams-Moulton+Newton scheme buy us vs the BDF+Newton?

As pointed out in https://github.com/stan-dev/math/issues/734, for higher-order accuracy.

> With the coupled_ode_system in stan-math we basically have the sensitivity thing for which the stiff case is particularly amenable to optimizations as I understood. 

I don't understand this comment.

>So (my intuition) would tell me that for non-stiff problems we really should prefer boost odeint as the extra-optimizations from sundials are not needed and boost integrates much better with Stan. So the Adams-Bashfort-Moulton in odeint is worthwhile to try if we want to extend the solvers.

IIRC boost's Adams-Moulton doesn't support adaptive stepper, which means a user has to specify `dt`. Unless he knows the ODE system well enough, I'll say this would be a foot shooter.

> BTW, what do you think about the BDF limit detection thing in CVODES? Is that useful? (Sorry, off topic)

I've seen problems in computational fluid dynamics where this feature is useful.

**Comment by wds15** [comment]
The adaptive Adams-Moultn in odeint is not well documented,but it's there:

https://github.com/headmyshoulder/odeint-v2/blob/master/include/boost/numeric/odeint/stepper/adaptive_adams_bashforth_moulton.hpp

this one is already in boost.

Still: Which *stan problem* is better solved with the solver you propose? Higher-order accuracy is great... but what is it good for at the end of the day for users?

**Comment by yizhang-cae** [comment]
Do we really want to choose an undocumented new feature vs a well-documented old one?

**Comment by bob-carpenter** [comment]
What got lost from [the first issue](https://github.com/stan-dev/math/issues/734) and this one is the following:

> CVODES provides BDF (current implicit ode solver implementation) and Adams-Moulton schemes. BDF has the advantage of being highly stable, but this only applies low-order cases(order<5). For achieve higher-order accuracy up to order 12, one needs the Adams scheme.

> CVODES imposes same interface for the two schemes. The essential change in the implementation is to share the CVODES construction process and delegate the specific method to a non-type parameter template.

So it sounds to me like what we'll be recommending is:

1. Non-stiff?  Runge-Kutta 4th/5th order (`_rk45`)
2. Stiff:
    1. order <= 4?  Bacward Differentiation Formula (`_bdf`)
    2. order > 4? Adams-Moulton (`_am`)

What's the order measuring?  

Seems like this'll be pretty easy to integrate on the Stan side.  

Is everyone OK with that?  

If so, we can focus on how to implement these things.  I don't have an opinion one way or the other on Boost vs. CVODES integrators as to reliability, etc.  

The primary advantages to Boost were (a) we could autodiff through the templating, and (b) we already had the dependencies.  Now that we don't do (a) and we already have a dependency on Sundials, it's really just a matter of efficiency and flexiblity of code and ease of maintenance.

**Comment by wds15** [comment]
As I understand things, with larger order of the integrator you can do larger time-steps. At least this is the hope as this should lead to faster integration for smooth functions... but smooth functions are not stiff. This is why I don't get where the proposed scheme is good at (a harmonic oscillator is for me to textbook simple for my applications).

Moreover, the CVODES bdf integrator is already now terribly imprecise. Going with higher order will not make that better, I think.

All that said, if there is a killer application which we want in Stan where this integrator really shines ... then I am all in, but I have not yet seen one mentioned. In case this integrator works really well as judged by your experience, @yizhang-cae then also fine with me, but more clarity on when to use it would be good. We should give some guidance as to when to use what solver. I thought higher order scheme does not go well with stiff problems.

The Adams-Bashfort-Moulton in odeint should be fine to use. In the past the odeint author was amazingly quick to fix issues with the library in case there is one.

From my perspective we should try these
- adams moulton from odeint for non-stiff problems should be at least tried vs this one
- the bulrisch stoer algorithm from odeint is supposed to be very fast for the high precision (1E-12) you are getting from it. This should be beneficial to get better trajectories for NUTS.

**Comment by bob-carpenter** [comment]
@wds15:  Unless @yizhang-cae or @syclik think it's necessary, I would prefer to just go ahead with the plan @yizhang-cae has had to implement with Sundials.  I don't want to start sidetracking issues with things we might do in the future, especially after the development is nearly done.

This won't lock us into any particular implementation going forward.  So I think it would be helpful if you could break that last message into two issues:

1.  `stan-dev/math`: evaluate Adams-Moulton from odeint as alternative to Sundials for `integrate_ode_am`
2.  `stan-dev/stan`: evaluate Bulrisch-Stoer from odeint for HMC trajectories as alternative to leapfrog

Thanks!

**Comment by wds15** [comment]
Ok; will do.

**Comment by yizhang-cae** [comment]
Also, I just looked at Boost 1.67.0 and couldn't find either the src or the documentation for adaptive Adams integrator.

**Comment by yizhang-cae** [comment]
Resolved in #2543 .
