### ISSUE TITLE
typo in the doc about effective sample size

### ISSUE THREAD

**Issue by maverickg** [stan-dev/stan#2544]
#### Summary:

there should not be negative sign here?

https://github.com/stan-dev/stan/blob/develop/src/docs/stan-reference/inference.tex#L632

<img width="890" alt="screenshot 2018-06-11 14 00 26" src="https://user-images.githubusercontent.com/68500/41248753-f40cf258-6d7f-11e8-8cd3-af88d4e117a5.png">

and it's negative in rstan's code:
https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/src/chains.cpp#L379

Besides, m is used above to index chains.  To avoid confusion, how about using a different one?
#### Current Version:

develop branch

**Comment by maverickg** [comment]
@avehtari please take a look.  I am verify if the results in rstan makes sense after fixing a segfault issue.

**Comment by avehtari** [comment]
The negative sign is correct. Notice that when indexing starts from $t=1$ the zero lag is not included in the sum term and +1 is added, and when the indexing starts from $t´=0$ the zero lag is included in the sum term which is multiplied by 2 and -1 is added to remove the extra zero lag term.

I agree on possible confusion on $m$, but then changing it, will make it more difficult to compare to Geyer's work. We'll consider this while making other updates during the summer.
