### ISSUE TITLE
update manual for matrix_exp_multiply functions

### ISSUE THREAD

**Issue by yizhang-cae** [stan-dev/stan#2547]
#### Summary:
add documentation of 
```Stan
matrix_exp_multiply(matrix A, matrix B);
scale_matrix_exp_multiply(real t, matrix A, matrix B);
```

#### Description:
After #2539 is resolved, we need document these functions.

#### Reproducible Steps:
Just doc.

#### Current Output:
n/a

#### Expected Output:
function signature & usage.

#### Additional Information:
n/a

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
fixed with #2551
