### ISSUE TITLE
Output API refactor, interface side [WIP]

### ISSUE THREAD

**Issue by sakrejda** [stan-dev/stan#2559]
Based on routing signatures from #2557, (new) `writer` classes required for each algorithm type.  Most of the output is defined by the model file and logging requirements, with differences among MCMC/optimization/ADVI mostly in the algorithm parameters. 

# Signatures a base writer class must handle:

Algorithm output tends to be stages (optimization iterating vs. converged, MCMC warmup (in phases) followed by sampling, etc...) so the relay is given the stage name and times the duration in the stage and passes that information to this call.  This can be used to trigger route changes such as putting warmup and sampling in different places or changing how it is tagged, etc...
- `void Writer::write_stage(stan::stage stage, std::chrono::duration duration);`  

These sets of calls could all share implemenations
- `void Writer::write_parameter_names(std::vector<std::string> names);`
- `void Writer::write_parameters(std::vector<double> parameters);`
- `void Writer::write_parameter_gradients(std::vector<double> gradients);`
- `void Writer::write_transformed_parameter_names(std::vector<std::string> names);`
- `void Writer::write_transformed_parameters(std::vector<double> parameters);`
- `void Writer::write_generated_quantity_names_r(std::vector<std::string> names);`
- `void Writer::write_generated_quantities_r(std::vector<std::double> gq);`
- `void Writer::write_generated_quantity_names_i(std::vector<std::string> names);`
- `void Writer::write_generated_quantities_i(std::vector<std::double> gq);`

The relay also needs a logger, the logger must implement signatures for string vectors.  Each element of the string vector indicates a logically separate part of the message as a hint for formatting. 

- `void Logger::debug(std::vector<std::string>);`
- `void Logger::info(std::vector<std::string>);`
- `void Logger::warn(std::vector<std::string>);`
- `void Logger::error(std::vector<std::string>);`
- `void Logger::fatal(std::vector<std::string>);`

The writer/logger must also:
- Set up where output will go on construction and how it is handled on construction

The writer/logger are the right place to:
- Thin/ignore certain log messages
- Select parameter subsets for output

## Signatures required from interface for HMC:

- `void Writer::write_parameter_momenta(std::vector<double> momenta);`
- `void Writer::write_algorithm_parameters(std::tuple<double, double, int, double, double, int, bool>);`
- `void Writer::write_mass_matrix(Eigen::Vectord mm);`
- `void Writer::write_mass_matrix(Eigen::Matrixd mm);`

## Handling BFGS/LBFGS optimization output:

BFGS/LBFGS-specific: log_density, dx_magnitude, grad_magnitude, alpha, alpha_0, n_evals
- `void Writer::write_algorithm_parameters(std::tuple<double, double, double, double, double, double>);`
- `void Writer::write_hessian(Eigen::Matrixd mm);` (rstan does this, no reason why it can't be core in Stan)

## Handling Newton optimization output:
Newton-specific: log_density, delta_log_density:
- `void Writer::write_algorithm_parameters(std::tuple<double, double>);`
- `void Writer::write_hessian(Eigen::Matrixd mm);` (rstan does this, no reason why it can't be core in Stan)

## Handling ADVI output:

ADVI-specific: ELBO, delta_ELBO_medan, delta_ELBO_med, iteration_time, eta
- `void Writer::write_algorithm_parameters(std::tuple<double, double, double, double, double>);`

## Standard interface-side components

Some tasks on the interface side are standard:

- write text log messages
- write key-value pairs
- write homogeneous tables (names in `std::vector<std::string>` and stream of `std::vector<double> values`)
- write heterogeneous tables (names in `std::vector<std::string>` and stream of `std::tuple<T1, T2, ..., TK> values`

These should have shared implementations even when the ultimate output target is different.

## Interface responsibilities

Interfaces will need to construct a `relay` object (from writers) in order to pass to a service method.  The service methods will take a different `relay` depending on which algorithm they are going to call.  The relay types are: `hmc_relay`, `optimization_relay`, and `advi_relay` with signatures:

```
...
```

**Comment by bgoodri** [comment]
Rcpp is going to map a `std::vector<double>` to a numeric matrix and a
`std::tuple` to a list, both of which are fine.

**Comment by riddell-stan** [comment]
Ditto for PyStan. Cython maps std types in a similar fashion.

**Comment by sakrejda** [comment]
The logger thing is happening instead so this is dated, closing.
