### ISSUE TITLE
add `qr_thin_{Q,R}` to language

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2560]
#### Summary:

Stan Math now has the thin QR decomposition, but those functions have not been exposed to the Stan Language.

#### Description:

* [ ] add functions:

```
matrix qr_thin_Q(matrix);
matrix qr_thin_R(matrix);
```

* [ ] add tests (as indicated below) in the form of good model instantiations

* [ ] add doc to the function-signatures

#### Reproducible Steps:

`git grep -F "qr_thin" develop || echo "nothing found"`

#### Current Output:

`nothing found`

#### Expected Output:

```
src/docs/stan-reference/examples.tex:  matrix[K, K] R = qr_thin_R(x);
src/docs/stan-reference/examples.tex:  matrix[N, K] Q_ast = qr_thin_Q(x) * s;
src/stan/lang/function_signatures.h:add("qr_thin_Q", expr_type(matrix_type()), expr_type(matrix_type()));
src/stan/lang/function_signatures.h:add("qr_thin_R", expr_type(matrix_type()), expr_type(matrix_type()));
src/test/test-models/good/function-signatures/math/matrix/qr_thin_Q.stan:  transformed_data_matrix <- qr_thin_Q(d_matrix);
src/test/test-models/good/function-signatures/math/matrix/qr_thin_Q.stan:  transformed_param_matrix <- qr_thin_Q(d_matrix);
src/test/test-models/good/function-signatures/math/matrix/qr_thin_Q.stan:  transformed_param_matrix <- qr_thin_Q(p_matrix);
src/test/test-models/good/function-signatures/math/matrix/qr_thin_R.stan:  transformed_data_matrix <- qr_thin_R(d_matrix);
src/test/test-models/good/function-signatures/math/matrix/qr_thin_R.stan:  transformed_param_matrix <- qr_thin_R(d_matrix);
src/test/test-models/good/function-signatures/math/matrix/qr_thin_R.stan:  transformed_param_matrix <- qr_thin_R(p_matrix);
src/test/unit/lang/parser/matrix_functions_test.cpp:TEST(lang_parser, qr_thin_Q_matrix_function_signatures) {
src/test/unit/lang/parser/matrix_functions_test.cpp:  test_parsable("function-signatures/math/matrix/qr_thin_Q");
src/test/unit/lang/parser/matrix_functions_test.cpp:TEST(lang_parser, qr_thin_R_matrix_function_signatures) {
src/test/unit/lang/parser/matrix_functions_test.cpp:  test_parsable("function-signatures/math/matrix/qr_thin_R");
```

#### Additional Information:

This may introduce conflicts with the way files were moved around in #2558.  The function signatures doc stays the same, so if this only touches that and not the examples or reference manual, Git should be able to track the movements.

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
Is there a way to concatenate `qr_thin_Q(x)` and `qr_thin_R(x)` so that we don't have to do the QR decomposition twice?  Something like:

```
matrix qr_thin(matrix);
```

When we get tuples, we'll want something like:

```
(matrix, matrix) qr_thin(matrix);
```

**Comment by bgoodri** [comment]
Only with tuples because the Q and R matrices will, in general, be of
different sizes so we cannot return a std::vector of two Eigen::Matrix.
