### ISSUE TITLE
fix size boundaries for unit vectors, simplexes, correlation/covariance matrixes

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2588]
#### Summary:

Make sure these all have the right boundaries in Stan.  

They need to be addressed in this repo as the problem is in the constrained variable transform code.  It may need some coordinated fixes in Math

#### Description:

The following should throw for argument 0 but not for argument 1:

* [x] unit_vector
* [x] simplex

There is no reason the following can't work for size 0 and size 1:

* cov_matrix, corr_matrix, cholesky_factor, cholesky_factor_corr

I'm not sure if the multivariate distributions work for size 0, but the actual matrices should be OK.  For example, a correlation matrix is positive definite and has rows that sum to 1, so a size 0 one should meet those conditions.  For example, with correlation matrices of size zero, they're positive definite in the sense that all non-zero quadratic forms are non-zero and have all diagonal elements one because there are no diagonal elements.  

#### Reproducible Steps:

As is, a bunch of these fail.  I think `simplex[0]` was fixed to throw.  

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
Thanks for bringing this up again---I hadn't realized it was still an issue.  I'll prioritize fixing this.

**Comment by bob-carpenter** [comment]
@edbaskerville You were right about the cause.  A bare `return stan::math::simplex_constrain(vector(k - 1));`.  I'm fixing it now.

**Comment by edbaskerville** [comment]
Thanks for the quick turnaround!

**Comment by bob-carpenter** [comment]
Fixed with PR #2773.
