### ISSUE TITLE
Setting STAN_NUM_THREADS to illegal value should produce an error

### ISSUE THREAD

**Issue by martinmodrak** [stan-dev/stan#2591]
#### Summary:
Illegal values of STAN_NUM_THREADS now make the library use one thread. An error should be thrown instead.

#### Description:
As [discussed on the forums](http://discourse.mc-stan.org/t/map-rect-concurrent-about-to-land/4054/27?u=martinmodrak), the current behavior of using one thread when STAN_NUM_THREADS has unusable value should be changed to throwing an error. Unusable values are:
- Non-integer values (including trailing chars after an integer, e.g. `1H` should still be illegal, despite some C functions being willing to parse it to integer as `1`).
- Negative values less than -1 (-1 is reserved for as many threads as there are cores)
- Zero

#### Current Version:
v2.18.0

**Comment by wds15** [comment]
thanks for opening the issue, but we need to move this to stan-math where the change needs to be done. There is an issue mover, but I don't recall where and how.

**Comment by bob-carpenter** [comment]
This issue was moved to stan-dev/math#947

**Comment by bob-carpenter** [comment]
This is the one I use (don't know if there are more, it's not part of GitHub itself):

https://github-issue-mover.appspot.com
