### ISSUE TITLE
parser should flag use of _lxxf suffix on built-in functions in sampling statements

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2595]
#### Summary:
currently parser allows:  `foo ~ normal_lpdf(0, 1);`  due to suffix stripping logic; should flag as incorrect.

#### Description:
parser has suffix stripping logic for user-defined probability functions, but here this applies to built-in probability distributions as well.

#### Reproducible Steps:
this shouldn't compile but it does:
```
data {
  int<lower=0> N;
}
parameters {
  vector[N] foo;
}
model {
  foo ~ normal_lpdf(0, 1);
}
```

#### Current Output:
currently OK;  should get flagged as error.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by VMatthijs** [comment]
Stanc3 currently says

```
Semantic error at file "test.stan", line 8, characters 2-26:
   -------------------------------------------------
     6:  }
     7:  model {
     8:    foo ~ normal_lpdf(0, 1);
           ^
     9:  }
   -------------------------------------------------

Ill-typed arguments to '~' statement. No distribution normal_lpdf was found with the correct signature.
```

**Comment by bob-carpenter** [comment]
This one may require a bit more care as it's a common user error.  Assuming foo is real or a 1D container type, this is the right signature for normal_lpdf(foo | 0, 1).  So the function with the correct signature exists, but it shouldn't be called with the "_lpdf" suffix.  

Is there a way to catch this case when users include _lpmf or _lpdf by mistake and signal that they should remove the suffix?  Error messages are much more useful if they suggest a fix.

**Comment by VMatthijs** [comment]
OK. Just added a custom error message for these cases:

```
Semantic error at file "test.stan", line 8, columns 8-19:
   -------------------------------------------------
     6:  }
     7:  model {
     8:    foo ~ normal_lpdf(0, 1);
                 ^
     9:  }
   -------------------------------------------------

~-statement expects a distribution name without '_lpdf' or '_lcdf' suffix.
```

**Comment by bob-carpenter** [comment]
It's "lpdf" and "lpmf" (log probability { density / mass } functions).  I don't think users will be trying to use "lcdf" or "lccdf" (log {complementary / } cumulative distribution functions).

**Comment by mcol** [comment]
Fixed in stanc3. The error message is now the  following:
```
Semantic error in 'test.stan', line 8, column 8 to column 19:
   -------------------------------------------------
     6:  }
     7:  model {
     8:    foo ~ normal_lpdf(0, 1);
                 ^
     9:  }
   -------------------------------------------------


~ statement should refer to a distribution without its "_lpdf" or "_lpmf" suffix.
For example, "target += normal_lpdf(y, 0, 1)" should become "y ~ normal(0, 1)."
```
