### ISSUE TITLE
lmer emulator

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#260]
Build an lmer emulator.  lmer is part of the lme4 package:

http://cran.r-project.org/web/packages/lme4/index.html

See the Wiki for a current design doc:

https://github.com/stan-dev/stan/wiki/Max-Marginal-Optimization-%28lmer%29-Design

To-do items for it to follow.

**Comment by jgabry** [comment]
If only 2013 @bob-carpenter could see us now ;)
