### ISSUE TITLE
increase boost mpl list size to accommodate more variant types in expression

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/stan#2603]
#### Summary:
https://github.com/stan-dev/stan/blob/5b0c3b29de0313e8efc8d56b483b1a9a4bec68dc/src/stan/lang/ast/node/expression.hpp#L33-L35

`variant<...>` in `expression is about to hit default limit 20, we need override it to allow more higher-order functions.

#### Description:
With #2602, the expression's variant types is 19. The default length of MPL, on which `boost::variant`'s type list is based, is 20.  In order to allow more higher-order functions, we need increase this limit. The easier fix is to bump it up is add in compiler flags
```bash
CXXFLAGS += -DBOOST_MPL_CFG_NO_PREPROCESSED_HEADERS -DBOOST_MPL_LIMIT_LIST_SIZE=30
```

#### Reproducible Steps:
To see the problem, add three more types in expression, say
```c++
    struct expression {
      typedef boost::variant<
                             boost::recursive_wrapper<int>,
                             boost::recursive_wrapper<int>,
                             boost::recursive_wrapper<int>,
                             boost::recursive_wrapper<nil>,
                             boost::recursive_wrapper<int_literal>,
                             boost::recursive_wrapper<double_literal>,
....
```
Now build it in cmdstan
```bash
make build
```
one will get
```bash
In file included from stan/lib/stan_math/lib/boost_1.66.0/boost/variant/recursive_variant.hpp:19:
stan/lib/stan_math/lib/boost_1.66.0/boost/variant/detail/make_variant_list.hpp:40:27: error: too many template
      arguments for class template 'list'
    typedef typename mpl::list< T... >::type type;
....
```

If you have a reproducible example, please include it.

#### Current Output:
No issue. 

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by rok-cesnovar** [comment]
Closing. Cleaning up issues that were meant for the stanc written in c++ (stanc2).
