### ISSUE TITLE
Compile error using integrate_ode_rk45

### ISSUE THREAD

**Issue by cdriveraus** [stan-dev/stan#2605]
#### Summary:
Compilation fails when data arguments of integrate_ode_rk45 are constructed using rep_array

#### Description:
Args 4 and 6 of integrate_ode_rk45 must be data. When these arguments are constructed using rep_array(somedata[1],1), where somedata is already an array of reals, compilation fails. When either the rep_array function is removed, or the data call within rep_array is replaced by a numeric such as 1.0, or the data was not an array originally, compilation proceeds normally.

#### Reproducible Steps:

```
sm<-c('
functions{
  real[] ode(real time, real[] state, real[] theta, real[] xr, int[] xi){
    return state;
  }
}
data{
  int ndatapoints;
  real dT[ndatapoints]; // time intervals
  real dTsmall[ndatapoints];
}
model{
  vector[2] state;
  real theta[1];
  state=to_vector(integrate_ode_rk45(ode, to_array_1d(state), 0.0, rep_array(dTsmall[1],1 ), 
    theta, rep_array(dT[1],1), rep_array(1,1))[1,]); 
}
')

library(rstan)

stan_model(model_code = sm)
```

#### Current Version:
v2.17.3

**Comment by bob-carpenter** [comment]
Thanks for the clean issue. That's definitely a bug.  I think it may be a duplicate, but I'll leave that to @mitzimorris to sort out among all these compilation bugs: #2605, #2604, #2599, #2584, #2578, #2565

**Comment by rok-cesnovar** [comment]
Model compiles fine in cmdstan 2.22.1 with stanc3. Closing.
