### ISSUE TITLE
Don't use the word "Warning"

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2608]
#### Summary:

In src/stan/lang/grammars/semantic_actions_def.cpp (and perhaps other places), there are several strings that begin with `"Warning:"`, which are causing lots of R packages to fail their CRAN checks for non-essential reasons.

#### Description:

CRAN evidently greps stdout for the word "warning" during the installation process, and finds things such as `Warning: left-hand side variable (name=foo) occurs on right-hand side of assignment, causing inefficient deep copy to avoid aliasing.` This is not that big a deal and not worth the cost of synchronizing a release of dozens of R packages. Also, a warning in R is intended to be thrown when the results of a function are suspect, which is not the case here.

We should change `Warning:` to `Info:` or something. But since I am going to have to do it to StanHeaders 2.18 before it goes on CRAN, we might as well decide now what the first word should be for 2.19 forward

#### Reproducible Steps:

Parse this:
```
transformed data {
  real foo = 1;
  foo = cos(foo);
}
```

#### Current Output:

```
DIAGNOSTIC(S) FROM PARSER:
Warning: left-hand side variable (name=foo) occurs on right-hand side of assignment, causing inefficient deep copy to avoid aliasing.
```

#### Expected Output:

```
DIAGNOSTIC(S) FROM PARSER:
Info: left-hand side variable (name=foo) occurs on right-hand side of assignment, causing inefficient deep copy to avoid aliasing.
```

#### Additional Information:

None

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
We should definitely fix this.  And I agree that they shouldn't say warning.

Whoever does this will have to grep out all the instances of `warning` in the semantic actions for the parser and replace them.  This will require replacing all the tests that go with them, but presumably that'll be pretty easy by grep, too.

**Comment by wds15** [comment]
+1 for turning this into "Info"... many users are afraid of seeing "Warnings", but these messages are in most cases more like an FYI given how small the data sets are usually.

**Comment by bgoodri** [comment]
Is anyone not okay with sed 's/Warning:/Info:/g' semantic_actions_def.cpp ?

**Comment by bob-carpenter** [comment]
There's also `Warning (non-fatal):`.  But that covers everything I see with a grep on "arning" in all of `stan/lang`.

**Comment by mitzimorris** [comment]
I have made this change on branch issue/2608-wording-change-s-warning-info -
changed "Warning" and "Warning (non-fatal)" to "Info"
updated unit tests accordingly.

**Comment by bob-carpenter** [comment]
I'm OK with this---I was just pointing out tht the grep pattern wouldn't catch everything, so I suggested one that I found.  Please go ahead and make this change.

**Comment by mitzimorris** [comment]
fixed by https://github.com/stan-dev/stan/pull/2609
