### ISSUE TITLE
parser asserts something is an unknown variable when it is known

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2612]
#### Summary:

The parser has some `"Unknown variable"` false positives.

#### Description:

The parser has some `"Unknown variable"` false positives.

#### Reproducible Steps:

Parse this
```
functions {
  void foo_lp() {
    // does nothing
  }
}
transformed data {
  matrix[2,2] M = rep_matrix(0, 2, 2);
}
model {
  foo_lp();
  to_vector(M) ~ normal(0, 1);
}
```

#### Current Output:

```
DIAGNOSTIC(S) FROM PARSER:
Unknown variable: foo_lp
Unknown variable: to_vector
```

#### Expected Output:

Nothing

#### Additional Information:

None

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
This is a critical bug.  My guess is that there's a rule that's committing too early after trying to recognize an expression.  The void-expression-as-statement rule probably needs to come first before committing to an expectation in the parser.

**Comment by mitzimorris** [comment]
fixed by PR https://github.com/stan-dev/stan/pull/2614, closing
