### ISSUE TITLE
parser does not promote int to double when self-multiplying or self-dividing a vector

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2613]
#### Summary:

Parser should promote ints to doubles when doing `*=` and `/=` with a vector (or matrix) on the left-hand side.

#### Description:

Parser should promote ints to doubles when doing `*=` and `/=` with a vector (or matrix) on the left-hand side.

#### Reproducible Steps:

Parse this
```
functions {
  void foo(vector x) {
    vector[rows(x)] y = x;
    y *= 1.0; // legal with real
    y /= 1.0; // legal with real
    y *= 1;   // illegal with int
    y /= 1;   // illegal with int
  }
}
```

#### Current Output:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

Cannot apply operator '*=' to operands; left-hand side type = vector; right-hand side type=int
  error in 'model7cf12ef21a84_ints' at line 6, column 8
  -------------------------------------------------
     4:     y *= 1.0; // legal with real
     5:     y /= 1.0; // legal with real
     6:     y *= 1;   // illegal with int
               ^
     7:     y /= 1;   // illegal with int
  -------------------------------------------------
```

#### Expected Output:

None

#### Additional Information:

None

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
In general, `int` should be usable anywhere `real` is.  So this is a real bug and I assigned it and prioritized for next release.  This shouldn't be a blocker for RStan 2.18.

**Comment by VMatthijs** [comment]
This should be fixed in stanc3. At least, the model above works fine.

**Comment by rok-cesnovar** [comment]
Fixed in stanc3.
