### ISSUE TITLE
Add inline for effective sample size calculations

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2615]
#### Summary:

The effective sample size functions should be declared `inline` to allow use in multiple translation units.  Same for our other posterior analysis functions like autocorrelation, R-hat, etc.

Originally requested by Tal Kedar:  http://discourse.mc-stan.org/t/duplicate-symbols-error-for-compute-effective-sample-size-hpp/5188

#### Description:

This won't affect size of any Stan executables, but will make it possible to use the functions in multiple translation units.

#### Current Version:
v2.18.0

**Comment by avehtari** [comment]
There is a merged PR #2622, should this be closed?
