### ISSUE TITLE
Expose beta_proportion_lccdf/lcdf/lpdf/rng functions

### ISSUE THREAD

**Issue by roualdes** [stan-dev/stan#2616]
#### Summary:
Expose beta_proportion functions, which were added to stan-dev/math in PR https://github.com/stan-dev/math/pull/975

#### Description:
Add the following

* symbol table entries in `src/stan/lang/function_signatures.h`
* good test models in `test/test-models/good`
* doc for the functions in the function doc `src/docs/functions`

#### Expected Output:
Users should be able to use and read about

`beta_proportion_lccdf`
`beta_proportion_lcdf`
`beta_proportion_lpdf`
`beta_proportion_rng`

#### Additional Information:
None

#### Current Version:
v2.18.0

**Comment by seantalts** [comment]
See stan-dev/stanc3#148
