### ISSUE TITLE
Documentation stops mid-sentence

### ISSUE THREAD

**Issue by ryan-richt** [stan-dev/stan#2617]
I'm not sure what the rest of the sentence is supposed to be, but the suspense is killing me ;-)

FYI:

https://github.com/stan-dev/stan/blob/01a09e735e2d0f880ab9219d469afce18d1b1934/src/docs/users-guide/examples.tex#L3342

PS. I tried instead to follow this link from the contributing guidelines, but it shows zero such open issues:

https://github.com/stan-dev/stan/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3ABug%20%22next%20manual%22%20label%3ADocumentation

**Comment by bob-carpenter** [comment]
Thanks.

The next manual issue is here:  https://github.com/stan-dev/stan/issues/2552.  

It's not labeled "bug", which is why the search didn't work.

I moved this issue to a comment here, so I could close this issue:

https://github.com/stan-dev/stan/issues/2552#issuecomment-41541440
