### ISSUE TITLE
Incorrect error message when same identifier used for both fct name and var name

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/stan#2621]
#### Summary:
When the same identifier is used for both a fct name and var name, it misidentifies this as use of a reserved word.

#### Description:
I use "foo" as the name of a function in the functions block. Then I also use it as a parameter name in the parameters block. The error message says "variable identifier (name) may not be a reserved word", but "foo" is not a reserved word.

#### Reproducible Steps:
    code <- '
    functions {
      real foo(real x) {
        return 2.0 * x;
      }
    }
    data { int<lower=0> N; vector[N] y; }
    parameters {
      real foo;
    }
    model {
      y ~ normal(foo, 1);
    }
    '
    library(rstan)
    sm <- stan_model(model_code = code)

#### Current Output:
    SYNTAX ERROR, MESSAGE(S) FROM PARSER:

    variable identifier (name) may not be reserved word
        found identifier=foo
      error in 'model1219268b0a499_bf344b66bb761e274281c4862a3bdfdd' at line 9, column 7
      -------------------------------------------------
         7: data { int<lower=0> N; vector[N] y; }
         8: parameters {
         9:   real foo;
                  ^
        10: }
      -------------------------------------------------

    PARSER EXPECTED: <identifier>
    Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
      failed to parse Stan model 'bf344b66bb761e274281c4862a3bdfdd' due to the above error.

#### Expected Output:
I expect it to complain that "foo" is already being used as the name of a function.

#### Current Version:
v2.17.3

**Comment by bob-carpenter** [comment]
Definitely a bug in the error message.  We should be able to reuse the same term for a function name and variable, too.  We'll look into it and fix.  Thanks for reporting.

**Comment by VMatthijs** [comment]
Stanc3 now says

```
Semantic error at file "test.stan", line 8, characters 7-10:
   -------------------------------------------------
     6:  data { int<lower=0> N; vector[N] y; }
     7:  parameters {
     8:    real foo;
                ^
     9:  }
    10:  model {
   -------------------------------------------------

Identifier  foo  is already in use.
```

**Comment by bob-carpenter** [comment]
1.  There's too much space around "foo" in this example.  

2.  Should we be quoting identifiers in error messages?

3.  Should we say "column" rather than "characters"?

For instance, in clang++, this program:

  int main() {
    double foo;
    double foo;
    return 1;
  }

produces this error:

  cpperr.cpp:3:10: error: redefinition of 'foo'
    double foo;
           ^
  cpperr.cpp:2:10: note: previous definition is here
    double foo;
           ^
  1 error generated.

I'm not saying we need to go back to the original definition as this does!

The line numbers and columns aren't even marked, just 2:10 for line 2, column 10. I like that you're spelling it out.

- Bob

**Comment by VMatthijs** [comment]
Thanks for the feedback! I agree. I've fixed points 1-3 in stanc3.

**Comment by mcol** [comment]
Current message is:
```
Semantic error in 'test.stan', line 8, column 7 to column 10:
   -------------------------------------------------
     6:  data { int<lower=0> N; vector[N] y; }
     7:  parameters {
     8:    real foo;
                ^
     9:  }
    10:  model {
   -------------------------------------------------

Identifier 'foo' is already in use.
```
