### ISSUE TITLE
Remove _log generated probability functions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2623]
#### Summary:

Currently the generator creates `_log` forms of the probability functions.  

#### Description:

It would be nice to not have to implement `_log` forms of the probability functions for new probability distributions.  Is there a way to do this *without* breaking backward compatibility?  Otherwise, this will have to wait until Stan 3.

#### Reproducible Steps:

Write a model with an `_lpdf` form of a distribution and see that `_log` gets generated.

#### Current Version:
v2.18.0

**Comment by mitzimorris** [comment]
steps to reproduce above error message - from cmdstan, do:
`make stan/src/test/test-models/good/normal_id_glm_performance`

note that test:  `make test/integration/compile_models` only checks translation to c++, doesn't check that generated code will link.

**Comment by mitzimorris** [comment]
offending code is in parser's semantic actions, starting at line 2041:

```
      // use old function names for built-in prob funs
      if (!function_signatures::instance().has_user_defined_key(fun.name_)) {
        replace_suffix("_lpdf", "_log", fun);
        replace_suffix("_lpmf", "_log", fun);
        replace_suffix("_lcdf", "_cdf_log", fun);
        replace_suffix("_lccdf", "_ccdf_log", fun);
      }
```

**Comment by bob-carpenter** [comment]
I'm confused by the first comment.  Does this mean our tests are broken?  Does it mean we're missing implementations for `normal_id_glm`?  If so, please file relevant issues rather than commenting on another issue.  Thanks.
