### ISSUE TITLE
function `normal_id_glm` missing implementation `normal_id_glm_log`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2626]
#### Summary:
model `stan/src/test/test-models/good/function-signatures/distributions/univariate/continuous/normal/normal_id_glm.stan` fails to compile because of missing implementation `normal_id_glm_log` required by generated code.  see issue: https://github.com/stan-dev/stan/issues/2623

#### Description:
the current Stan compiler takes distribution function names and appends `_log` to the name, unless the name already ends in a known suffix, i.e. `_lpdf`, `lpmf`, `lcdf`, `lccdf`.  therefore it is necessary to implement function `distroX_log` which delegates back to function `distroX`.  see discussion in PR: https://github.com/stan-dev/stan/pull/2620

#### Reproducible Steps:
use cmdstan's make to compile and link test model `normal_id_glm.stan`, e.g.:
```
> make stan/src/test/test-models/good/function-signatures/distributions/univariate/continuous/normal/normal_id_glm`
```

#### Current Output:
```
--- Translating Stan model to C++ code ---
bin/stanc  stan/src/test/test-models/good/function-signatures/distributions/compiler_lpdf_test.stan --o=stan/src/test/test-models/good/function-signatures/distributions/compiler_lpdf_test.hpp
Compiling pre-compiled header
c++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.66.0 -isystem stan/lib/stan_math/lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem stan/src -isystem stan/lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DEIGEN_NO_DEBUG -Wno-unknown-warning-option -Wno-tautological-compare -Wsign-compare -DNO_FPRINTF_OUTPUT -pipe  -c -O0 stan/src/stan/model/model_header.hpp -o stan/src/stan/model/model_header.hpp.gch
Model name=compiler_lpdf_test_model
Input file=stan/src/test/test-models/good/function-signatures/distributions/compiler_lpdf_test.stan
Output file=stan/src/test/test-models/good/function-signatures/distributions/compiler_lpdf_test.hpp

--- Linking C++ model ---
c++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.66.0 -isystem stan/lib/stan_math/lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem stan/src -isystem stan/lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DEIGEN_NO_DEBUG -Wno-unknown-warning-option -Wno-tautological-compare -Wsign-compare -DNO_FPRINTF_OUTPUT -pipe   src/cmdstan/main.cpp  -O0 -o stan/src/test/test-models/good/function-signatures/distributions/compiler_lpdf_test -include stan/src/test/test-models/good/function-signatures/distributions/compiler_lpdf_test.hpp stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_idas.a 
In file included from <built-in>:1:
./stan/src/test/test-models/good/function-signatures/distributions/compiler_lpdf_test.hpp:117:55: error: use of undeclared identifier 'normal_id_glm_log'; did you mean
      'normal_id_glm_lpdf'?
            stan::math::assign(transformed_data_real, normal_id_glm_log(d_y_v,d_x_m,d_alpha,d_beta_v,d_phi));
                                                      ^~~~~~~~~~~~~~~~~
                                                      normal_id_glm_lpdf
stan/lib/stan_math/stan/math/prim/mat/prob/normal_id_glm_lpdf.hpp:152:1: note: 'normal_id_glm_lpdf' declared here
normal_id_glm_lpdf(const T_n &n, const T_x &x, const T_beta &beta,
^
```

#### Expected Output:
should compile and link.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by bbbales2** [comment]
@VMatthijs I'm forwarding this one to you. It probably also affects the other glms as well.

**Comment by VMatthijs** [comment]
Thanks for spotting, @mitzimorris ! I don't really understand what happened. These files are present in develop but not in the 2.18 release. What would be the best course of action here? Will there be a 2.18.1?

**Comment by VMatthijs** [comment]
Thanks, @bbbales2 ! That's what I did in develop a long time ago: https://github.com/stan-dev/math/blob/develop/stan/math/prim/mat/prob/normal_id_glm_log.hpp . I don't entirely understand why those files didn't make it into 2.18.

**Comment by bob-carpenter** [comment]
You should be able to trace it back through the 2.18 tag if you really care.  The releases just bundle up everything in the tagged version.

**Comment by VMatthijs** [comment]
I see that those files were indeed not tagged 2.18. Will there be a 2.18.1 or 2.19 any time soon?

**Comment by bbbales2** [comment]
@VMatthijs Yeah, it seems like the files are in the right places.

Yo @mitzimorris this command worked for me on the latest develop
```
make src/test/test-models/good/function-signatures/distributions/univariate/continuous/normal/normal_id_glm.hpp-test
```

Is that the right one?

**Comment by mitzimorris** [comment]
yes, that'll work on latest develop.  the `hpp-test` target compiles a model, but the target in the cmdstan makefile compiles _and links_ it - it's a link error.
```

**Comment by mitzimorris** [comment]
my bad - it seems that I hadn't properly updated the math library - it all just works now.

**Comment by VMatthijs** [comment]
Great! Thanks for checking!

**Comment by mitzimorris** [comment]
we need the mono repo!!!
