### ISSUE TITLE
Generated `write_array()` is not returning when `include_tparams__` is `false`

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#2628]
#### Summary:
`write_array` should return without evaluating the log probability function when `include_tparams__` is false. This changes how initialization is done between v2.17.0 and v2.18.0. This causes odd failures when using initialization files.

#### Description:
When `include_tparams__` is false, it should have this line (present in v2.17.0):
```
if (!include_tparams__) return;
```

after setting of the parameters. Currently, it doesn't have that line, it will evaluate the transformed parameters, then choose to include it after it's been generated.

#### Reproducible Steps:
Take any program and generate the hpp file from it. By inspection you'll see:
v2.17.0 pretty early on in `write_array()`:
```
if (!include_tparams__) return;
```

v2.18.0 (and current) this will be after everything has been generated: 
```
if (include_tparams__) {
...
}
```
#### Current Output:
This causes a model to fail initialization in v2.18 that was ok in v2.17.

#### Expected Output:
I'd expect the initialization to hold and not to have to run the generated quantities.

#### Current Version:
v2.18.0

**Comment by mitzimorris** [comment]
looking at https://github.com/stan-dev/stan/issues/2432 I see comment:  
```
when tparams__ is false and include_gqs__ is true, the currently generated code won't write out the generated quantities values.
```
but if you're going to generate the quantities, you need to transform the params, no?
will check how code got changed as part of this feature implementation.

**Comment by mitzimorris** [comment]
yes, the code was changed in https://github.com/stan-dev/stan/pull/2434/files - see changes to file  `src/stan/lang/generator/generate_write_array_method.hpp`

**Comment by syclik** [comment]
I see. Then, I think we need to return early when both include_tparams__
and include_gqs__ are both false. We don't need to be running through that
code when that's the case. Then the rest of the conditionals are correct.
Thoughts?

(more concretely, include where we used to have that original if statement
a new one that says "if (!include_tparams__ && !include_gqs) return;")

**Comment by syclik** [comment]
Just FYI, @pourzanj ran into this problem with a real example.

**Comment by mitzimorris** [comment]
yes, that would certainly work.

for the case where include_tparams is false but include_gqs is true - skip validation of tparams?
current line 88:  https://github.com/stan-dev/stan/blob/7c164f579d4a5a0c7eb5e715377ff5fc5f67eb0a/src/stan/lang/generator/generate_write_array_method.hpp#L88
could be moved to line 82 or thereabouts w/out problems, no?

**Comment by mitzimorris** [comment]
great.  will go with a belt-and-suspenders approach to the generated code - new statement:
`if (!include_tparams__ && !include_gqs) return;`  for init case,
plus move line 88 earlier to avoid validating tparams if not going to generate them.

**Comment by syclik** [comment]
Thanks! That sounds awesome. I'll leave the implementation to you. (I think
there are enough hints for me to figure it out, but I'm not gonna look at
it for a day.)

Happy to review when it's ready. I don't think there's gonna be an easy way
to test this particular change, although I'm sure we can be creative if we
really wanted.

**Comment by bob-carpenter** [comment]
@syclik and @mitizmorris:  I agree the funciton should return after parameters if there are no transformed parameters or generated quantities.

@syclik:  If I understood the above correctly, you use `write_array()` to generate random constrained parameter values from a random init.  In that context, you definitely don't want to call transformed parameters or generated quantities, so this fix sounds right.

**Comment by syclik** [comment]
Yes. That's exactly right. There may be a better way to generate the inits,
but we can patch this first since it will fix the problem now and won't be
harmful in any way that I can imagine.

**Comment by syclik** [comment]
@mitzimorris, I'm going to work on this fix now. It helps me to have it sooner than later. You'll see a PR in under an hour. (It doesn't need to be merged immediately.)

**Comment by syclik** [comment]
@mitzimorris, I had figured out how to move the transformed parameters check up, but I don't think that's quite correct. Here's what I'm thinking:

- the parameters should be valid no matter what, so that's ok.
- the generated quantities rely on the state of {parameters, transformed parameters} to be valid. I don't think we should skip the checks on transformed parameters if we don't need to write them.

That make sense? It does to me at the moment, so I'm going to leave it as is.

Any thoughts on how to test the changes? I could find some way to make sure something throws / doesn't throw when calling `write_array()`. I'm going to submit a pull request without it for now to hear your thoughts.

**Comment by mitzimorris** [comment]
> the generated quantities rely on the state of {parameters, transformed parameters} to be valid. I don't think we should skip the checks on transformed parameters if we don't need to write them.

agreed.  putting back the check `if (!include_tparams__ && !include_gqs) return;` makes sense.
