### ISSUE TITLE
remove redundant assignment to 0 in model class constructor

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2629]
#### Summary:

When we have a model like

```
data {
  int a;
}
```

the code being generated for the constructor is:

```
        // initialize member variables
        try {
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "a", "int", context__.to_vec());
            a = int(0);
            vals_i__ = context__.vals_i("a");
            pos__ = 0;
            a = vals_i__[pos__++];
```

The initial assignment `a = int(0)` is redundant here.  

#### Description:

The offending code is in `stan/lang/generator/generate_data_var_ctor.hpp`, but I'm not sure where it's called from.

#### Current Version:
v2.18.0

**Comment by rok-cesnovar** [comment]
Stanc3 doesnt have this redundant assignment. Closing.
