### ISSUE TITLE
missing text etc. in reference-manual-2.18.0.pdf 

### ISSUE THREAD

**Issue by avehtari** [stan-dev/stan#2639]
The reference manual reference-manual-2.18.0.pdf downloaded from
https://github.com/stan-dev/stan/releases/download/v2.18.0/reference-manual-2.18.0.pdf
- [ ] is missing some text at the end of page 153
- [ ] Figure 14.1 is on page 153, but the caption is on page 152

(these are probably due switch to bookdown, but I don't know how to fix these)

**Comment by bob-carpenter** [comment]
@avehtari :  You can just add comments to the next manual issue and I'll fix them for the next release.  I added this one here:

https://github.com/stan-dev/stan/issues/2552#issuecomment-422780225

so I'll close this issue.
