### ISSUE TITLE
enable move semantics for stan::mcmc::sample

### ISSUE THREAD

**Issue by kedartal** [stan-dev/stan#2646]
An explicitly defined destructor inhibits the implicit definition of the move constructor and the move assignment operator. Allowing `stan::mcmc::sample` to move cheaply - essentially, moving instead of copying the member Eigen vector---is potentially useful both inside the stan codebase as well as in client code.

**Comment by bob-carpenter** [comment]
Thanks for adding the issue for the PR.  

If one of the commits says "fixes #2646", then the issue will automatically be closed on merge.
