### ISSUE TITLE
Travis CI failing after makefile pull request

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#2648]
#### Summary:
After #2601 was merged, Travis has failed. 

#### Description:
This should be a configuration fix.

#### Current Output:
See:
https://travis-ci.org/stan-dev/stan/builds/433571134

It is failing with clang++ and g++. I believe most of it has to do with the LDFLAGS setting.

#### Expected Output:
All green.

#### Current Version:
v2.18.0

**Comment by mcol** [comment]
This must have been solved at some point.
