### ISSUE TITLE
Pb missing logistic.hpp during test_all.sh with cmdstan

### ISSUE THREAD

**Issue by vincentvalton** [stan-dev/stan#2650]
#### Summary:

I encounter an error on Stan tests from the CmdStan: 'test_all.sh'.
make build worked fine, so does the bernoulli example.

Error message is following:

> "src/test/performance/logistic_test.cpp:47:53: fatal error: test/test-models/performance/logistic.hpp

#### Description:

I recently (Sept 27th 2018) pulled a fresh install of cmdstan from github on my linux desktop (ubuntu).

I successfully ran the make build and ran the Bernoulli example that comes with cmdstan.
I then proceeded to run test_all.sh.
The CmdStan tests appear the have all worked (everything reports RUN OK and PASSED).

It fails on the following set of tests.
I don't know if this is critical to me being able to use CmdStan or not.

Ubuntu is up to date, and have tried a reboot, to no avail.

#### Reproducible Steps:
------------------------
cloning stan from github
------------------------
git clone https://github.com/stan-dev/cmdstan.git --recursive
cd cmdstan/
sudo make build
sudo make stan-update
make ./examples/bernoulli/bernoulli
examples/bernoulli/bernoulli sample data file=examples/bernoulli/bernoulli.data.R
bin/stansummary output.csv
./test-all.sh 

I tried a reboot and running ./test-all.sh again and it failed with the same error message.

#### Current Output:
[...]
g++ -std=c++1y -pthread -Wno-sign-compare     -O3 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.7.0/include -I lib/stan_math/lib/gtest_1.7.0 -I lib/stan_math/lib/gtest_1.7.0/include -I lib/stan_math/lib/gtest_1.7.0      -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_USE_OWN_TR1_TUPLE  -c src/test/performance/logistic_test.cpp -o test/performance/logistic_test.o
**src/test/performance/logistic_test.cpp:47:53: fatal error: test/test-models/performance/logistic.hpp: No such file or directory**
compilation terminated.
make/tests:13: recipe for target 'test/performance/logistic_test.o' failed
make: *** [test/performance/logistic_test.o] Error 1
make -j1 test/integration/compile_models_test test/integration/compile_standalone_functions_test test/performance/logistic_test test/unit/multiple_translation_units_test test/unit/version_test test/unit/analyze/mcmc/compute_effective_sample_size_test test/unit/callbacks/interrupt_test test/unit/callbacks/logger_test test/unit/callbacks/stream_logger_test test/unit/callbacks/stream_writer_test test/unit/callbacks/tee_writer_test test/unit/callbacks/writer_test test/unit/io/array_var_context_test test/unit/io/chained_var_context_test test/unit/io/cmd_line_test test/unit/io/dump_test test/unit/io/empty_var_context_test test/unit/io/ends_with_test test/unit/io/program_reader_test test/unit/io/random_var_context_test test/unit/io/reader_test test/unit/io/read_line_test test/unit/io/stan_csv_reader_test test/unit/io/starts_with_test test/unit/io/trim_spaces_test test/unit/io/util_test test/unit/io/validate_zero_buf_test test/unit/io/writer_test test/unit/io/json/json_data_handler_test test/unit/io/json/json_data_test test/unit/io/json/json_parser_test test/unit/lang/compiler_test test/unit/lang/parser_generator_test test/unit/lang/rethrow_located_test test/unit/lang/stanc_helper_test test/unit/lang/ast/scope_test test/unit/lang/ast/variable_map_test test/unit/lang/ast/fun/function_signatures_funs_test test/unit/lang/ast/fun/has_var_test test/unit/lang/ast/fun/indexed_type_test test/unit/lang/ast/fun/indexing_ast_test test/unit/lang/ast/fun/infer_type_indexing_test test/unit/lang/ast/fun/misc_funs_test test/unit/lang/ast/fun/ops_funs_test test/unit/lang/ast/fun/solve_funs_test test/unit/lang/ast/fun/suffixes_test test/unit/lang/ast/node/assgn_test test/unit/lang/ast/node/block_var_decl_test test/unit/lang/ast/node/expression_test test/unit/lang/ast/node/function_decl_def_test test/unit/lang/ast/node/idx_ast_test test/unit/lang/ast/node/local_var_decl_test test/unit/lang/ast/node/map_rect_test test/unit/lang/ast/node/sample_test test/unit/lang/ast/node/var_decl_test test/unit/lang/ast/sigs/function_signatures_test test/unit/lang/ast/sigs/fun_sig_ast_test test/unit/lang/ast/type/bare_expr_type_ast_test test/unit/lang/ast/type/bare_expr_type_test test/unit/lang/ast/type/block_var_type_params_total_test test/unit/lang/ast/type/block_var_type_test test/unit/lang/ast/type/local_var_type_test test/unit/lang/ast/type/specialized_block_var_type_test test/unit/lang/generator/ast_nodes_test test/unit/lang/generator/cholesky_factor_cov_var_test test/unit/lang/generator/function_var_test test/unit/lang/generator/generate_array_builder_adds_test test/unit/lang/generator/generate_cpp_test test/unit/lang/generator/generate_expression_test test/unit/lang/generator/generate_idxs_test test/unit/lang/generator/generate_model_typedef_test test/unit/lang/generator/generate_quoted_test test/unit/lang/generator/generate_var_type_test test/unit/lang/generator/local_var_test test/unit/lang/generator/log_prob_test test/unit/lang/generator/multi_dim_var_data_test test/unit/lang/generator/multi_dim_var_test test/unit/lang/generator/prim_var_test test/unit/lang/parser/if_else_deprecation_test test/unit/lang/parser/reserved_words_test test/unit/lang/parser/algebra_solver_test test/unit/lang/parser/assignment_statement_test test/unit/lang/parser/assignment_test test/unit/lang/parser/break_continue_test test/unit/lang/parser/distribution_functions_test test/unit/lang/parser/duplicate_warnings_test test/unit/lang/parser/error_messages_test test/unit/lang/parser/expression_grammar_test test/unit/lang/parser/for_statements_test test/unit/lang/parser/functions_on_lhs_test test/unit/lang/parser/functions_standalone_instantiate_test test/unit/lang/parser/functions_standalone_test test/unit/lang/parser/function_sig_errors_test test/unit/lang/parser/get_lp_test test/unit/lang/parser/indexing_test test/unit/lang/parser/integrate_ode_deprecation_test test/unit/lang/parser/lkj_cov_deprecation_test test/unit/lang/parser/lower_trunc_adjust_test test/unit/lang/parser/map_rect_test test/unit/lang/parser/math_functions_test test/unit/lang/parser/matrix_functions_test test/unit/lang/parser/ode_test test/unit/lang/parser/other_functions_test test/unit/lang/parser/other_test test/unit/lang/parser/pound_comment_deprecated_test test/unit/lang/parser/print_function_test test/unit/lang/parser/redefine_prob_functions_test test/unit/lang/parser/replace_log_funs_test test/unit/lang/parser/rng_location_test test/unit/lang/parser/statement_grammar_test test/unit/lang/parser/term_grammar_test test/unit/lang/parser/trunc_test test/unit/lang/parser/user_defined_functions_test test/unit/lang/parser/var_decls_grammar_test test/unit/lang/reject/reject_func_call_transformed_parameters_test test/unit/lang/reject/print_reject_function_gq_test test/unit/lang/reject/print_reject_function_model_test test/unit/lang/reject/print_reject_function_tdata_test test/unit/lang/reject/print_reject_function_tparams_test test/unit/lang/reject/print_reject_gq_test test/unit/lang/reject/print_reject_model_test test/unit/lang/reject/print_reject_tdata_test test/unit/lang/reject/print_reject_tparams_test test/unit/lang/reject/reject_func_call_generated_quantities_test test/unit/lang/reject/reject_func_call_model_test test/unit/lang/reject/reject_func_call_transformed_data_test test/unit/lang/reject/reject_generated_quantities_test test/unit/lang/reject/reject_model_test test/unit/lang/reject/reject_mult_args_test test/unit/lang/reject/reject_transformed_data_test test/unit/lang/reject/reject_transformed_parameters_test test/unit/mcmc/base_adapter_test test/unit/mcmc/chains_test test/unit/mcmc/covar_adaptation_test test/unit/mcmc/sample_test test/unit/mcmc/stepsize_adaptation_test test/unit/mcmc/var_adaptation_test test/unit/mcmc/windowed_adaptation_test test/unit/mcmc/hmc/base_hmc_test test/unit/mcmc/hmc/hamiltonians/base_hamiltonian_test test/unit/mcmc/hmc/hamiltonians/dense_e_metric_test test/unit/mcmc/hmc/hamiltonians/diag_e_metric_test test/unit/mcmc/hmc/hamiltonians/ps_point_test test/unit/mcmc/hmc/hamiltonians/softabs_metric_test test/unit/mcmc/hmc/hamiltonians/unit_e_metric_test test/unit/mcmc/hmc/integrators/expl_leapfrog2_test test/unit/mcmc/hmc/integrators/expl_leapfrog_test test/unit/mcmc/hmc/integrators/impl_leapfrog2_test test/unit/mcmc/hmc/integrators/impl_leapfrog_test test/unit/mcmc/hmc/nuts/base_nuts_test test/unit/mcmc/hmc/nuts/derived_nuts_test test/unit/mcmc/hmc/nuts/instantiation_test test/unit/mcmc/hmc/nuts/softabs_nuts_test test/unit/mcmc/hmc/nuts/unit_e_nuts_test test/unit/mcmc/hmc/nuts_classic/base_nuts_classic_test test/unit/mcmc/hmc/nuts_classic/derived_nuts_classic_test test/unit/mcmc/hmc/nuts_classic/instantiation_test test/unit/mcmc/hmc/static/base_static_hmc_test test/unit/mcmc/hmc/static_uniform/base_static_uniform_test test/unit/mcmc/hmc/static_uniform/derived_static_uniform_test test/unit/mcmc/hmc/xhmc/base_xhmc_test test/unit/mcmc/hmc/xhmc/softabs_xhmc_test test/unit/mcmc/hmc/xhmc/unit_e_xhmc_test test/unit/model/finite_diff_grad_test test/unit/model/gradient_dot_vector_test test/unit/model/gradient_test test/unit/model/grad_hess_log_prob_test test/unit/model/grad_tr_mat_times_hessian_test test/unit/model/hessian_test test/unit/model/hessian_times_vector_test test/unit/model/log_prob_grad_test test/unit/model/log_prob_propto_test test/unit/model/model_functional_test test/unit/model/test_gradients_test test/unit/model/indexing/deep_copy_test test/unit/model/indexing/index_list_test test/unit/model/indexing/index_test test/unit/model/indexing/lvalue_test test/unit/model/indexing/rvalue_index_size_test test/unit/model/indexing/rvalue_return_test test/unit/model/indexing/rvalue_test test/unit/optimization/bfgs_linesearch_test test/unit/optimization/bfgs_minimizer_test test/unit/optimization/bfgs_test test/unit/optimization/bfgs_update_test test/unit/optimization/lbfgs_update_test test/unit/services/diagnose/defaults_test test/unit/services/diagnose/diagnose_test test/unit/services/experimental/advi/defaults_test test/unit/services/experimental/advi/fullrank_test test/unit/services/experimental/advi/meanfield_test test/unit/services/optimize/bfgs_test test/unit/services/optimize/defaults_test test/unit/services/optimize/lbfgs_test test/unit/services/optimize/newton_test test/unit/services/sample/defaults_test test/unit/services/sample/fixed_param_test test/unit/services/sample/hmc_nuts_dense_e_adapt_test test/unit/services/sample/hmc_nuts_dense_e_test test/unit/services/sample/hmc_nuts_dense_inv_metric_test failed

#### Expected Output:
I wanted to run all tests to make sure the install of CmdStan was set up correctly.

I have run test-all.sh for every fresh install of CmdStan on this machine and always passed successfully (2.13, 2.14, 2.17.1)

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by Feezdev** [comment]
Hi Syclik,

Thanks so much for getting back to me so promptly! 

Here is my g++ version:

> g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

I'm not quite sure I understand how I got to the develop state of cmdstan.
Is there a tag I should add to get a clone of the latest stable branch?

I assumed the following would get me the latest stable version (i.e. v2.18.0) -- terribly sorry if this is a rather silly mistake: 

> git clone https://github.com/stan-dev/cmdstan.git --recursive

**Comment by Feezdev** [comment]
I have now tried to get the non-developping branch of cmdstan v2.18.0 by cloning the version v2.18.0 from github:

`git clone -b 'v2.18.0' --single-branch https://github.com/stan-dev/cmdstan.git --recursive
`
or downloading the 2.18.0 zip file.

I then ran the make build, and the bernoulli example successfully, but when I tried to run the './test-all.sh' I get the error below. The same error happens with either the git clone of v2.18.0 or the zip file.

Ps: I tried compiling and running my models and they seem to be running fine, regardless of the face that the './test-all.sh' did not run successfully till the end.

**Outcome:**

> make -j1 test/integration/compile_models test/integration/compile_standalone_functions test/performance/logistic test/unit/multiple_translation_units test/unit/version test/unit/callbacks/interrupt test/unit/callbacks/logger test/unit/callbacks/stream_logger test/unit/callbacks/stream_writer test/unit/callbacks/tee_writer test/unit/callbacks/writer test/unit/io/array_var_context test/unit/io/chained_var_context test/unit/io/cmd_line test/unit/io/dump test/unit/io/empty_var_context test/unit/io/program_reader test/unit/io/random_var_context test/unit/io/reader test/unit/io/read_line test/unit/io/stan_csv_reader test/unit/io/starts_with test/unit/io/util test/unit/io/validate_zero_buf test/unit/io/writer
find: ‘stan’: No such file or directory
find: ‘stan’: No such file or directory
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
clang++ -Wall -I . -isystem lib/stan_math/lib/eigen_3.3.3 -isystem lib/stan_math/lib/boost_1.66.0 -isystem lib/stan_math/lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DNO_FPRINTF_OUTPUT -pipe  -c -O0 -o bin/stan/lang/grammars/indexes_grammar_inst.o src/stan/lang/grammars/indexes_grammar_inst.cpp
make: clang++: Command not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
clang++ -Wall -I . -isystem lib/stan_math/lib/eigen_3.3.3 -isystem lib/stan_math/lib/boost_1.66.0 -isystem lib/stan_math/lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DNO_FPRINTF_OUTPUT -pipe  -c -O3 src/test/unit/multiple_translation_units1.cpp -o test/unit/multiple_translation_units1.o
make: clang++: Command not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
clang++ -Wall -I . -isystem lib/stan_math/lib/eigen_3.3.3 -isystem lib/stan_math/lib/boost_1.66.0 -isystem lib/stan_math/lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DNO_FPRINTF_OUTPUT -pipe  -c -O3 -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/stan_math/lib/gtest_1.7.0/include -isystem lib/stan_math/lib/gtest_1.7.0 lib/stan_math/lib/gtest_1.7.0/src/gtest-all.cc -o test/gtest.o
make: clang++: Command not found
make/tests:14: recipe for target 'test/gtest.o' failed
make: *** [test/gtest.o] Error 127
make -j1 test/integration/compile_models test/integration/compile_standalone_functions test/performance/logistic test/unit/multiple_translation_units test/unit/version test/unit/callbacks/interrupt test/unit/callbacks/logger test/unit/callbacks/stream_logger test/unit/callbacks/stream_writer test/unit/callbacks/tee_writer test/unit/callbacks/writer test/unit/io/array_var_context test/unit/io/chained_var_context test/unit/io/cmd_line test/unit/io/dump test/unit/io/empty_var_context test/unit/io/program_reader test/unit/io/random_var_context test/unit/io/reader test/unit/io/read_line test/unit/io/stan_csv_reader test/unit/io/starts_with test/unit/io/util test/unit/io/validate_zero_buf test/unit/io/writer failed
exit now (09/29/18 22:38:12 BST)
Stan Math Library tests
./test-all.sh: line 24: pushd: stan/lib/stan_math_2.15.0/: No such file or directory
./test-all.sh: line 25: ./runTests.py: No such file or directory
./test-all.sh: line 26: ./runTests.py: No such file or directory
./test-all.sh: line 27: popd: directory stack empty

**Comment by bob-carpenter** [comment]
The error message seems to indicate your program is looking for 2.15.0 for some reason:

```
./test-all.sh: line 24: pushd: stan/lib/stan_math_2.15.0/: No such file or directory
```

I have no idea what's up with that, but it looks like you're otherwise running a different Stan math lib.

**Comment by Feezdev** [comment]
Hi @bob-carpenter,

Thanks a lot for your reply, (and terribly sorry for the delay in responding)

Indeed the './test-all.sh' points to 'stan_math_2.15.0'

I've checked the github repo, and this is the current state of the file from the github repo 
See line 24: [https://github.com/stan-dev/cmdstan/blob/develop/test-all.sh](https://github.com/stan-dev/cmdstan/blob/develop/test-all.sh) also points to stan_math_2.15.0

According to github, it seems the 'test-all.sh' has not been changed in the past 2 years?

So I've edited 'test-all.sh' and changed the path on line 24 to use 'stan/lib/stan_math/'

I now get the following error:
I relaunched ./test-all.sh and am now able to pass all cmdstan tests, but still fail at the 'Stan tests' and 'Math library tests':

See errors below (ps: this is using the downloaded 2.18.0 zip file):

```
------------------------------------------------------------
Stan tests
/media/Data/Dropbox/workspace/matlab_toolboxes/cmdstan_latest/cmdstan/stan /media/Data/Dropbox/workspace/matlab_toolboxes/cmdstan_latest/cmdstan
------------------------------------------------------------
make -j1 test/integration/compile_models test/integration/compile_standalone_functions test/performance/logistic test/unit/multiple_translation_units test/unit/version test/unit/callbacks/interrupt test/unit/callbacks/logger test/unit/callbacks/stream_logger test/unit/callbacks/stream_writer test/unit/callbacks/tee_writer test/unit/callbacks/writer test/unit/io/array_var_context test/unit/io/chained_var_context test/unit/io/cmd_line test/unit/io/dump test/unit/io/empty_var_context test/unit/io/program_reader test/unit/io/random_var_context test/unit/io/reader test/unit/io/read_line test/unit/io/stan_csv_reader test/unit/io/starts_with test/unit/io/util test/unit/io/validate_zero_buf test/unit/io/writer
find: ‘stan’: No such file or directory
find: ‘stan’: No such file or directory
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
clang++ -Wall -I . -isystem lib/stan_math/lib/eigen_3.3.3 -isystem lib/stan_math/lib/boost_1.66.0 -isystem lib/stan_math/lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DNO_FPRINTF_OUTPUT -pipe  -c -O0 -o bin/stan/lang/grammars/indexes_grammar_inst.o src/stan/lang/grammars/indexes_grammar_inst.cpp
make: clang++: Command not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
clang++ -Wall -I . -isystem lib/stan_math/lib/eigen_3.3.3 -isystem lib/stan_math/lib/boost_1.66.0 -isystem lib/stan_math/lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DNO_FPRINTF_OUTPUT -pipe  -c -O3 src/test/unit/multiple_translation_units1.cpp -o test/unit/multiple_translation_units1.o
make: clang++: Command not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
clang++ -Wall -I . -isystem lib/stan_math/lib/eigen_3.3.3 -isystem lib/stan_math/lib/boost_1.66.0 -isystem lib/stan_math/lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DNO_FPRINTF_OUTPUT -pipe  -c -O3 -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/stan_math/lib/gtest_1.7.0/include -isystem lib/stan_math/lib/gtest_1.7.0 lib/stan_math/lib/gtest_1.7.0/src/gtest-all.cc -o test/gtest.o
make: clang++: Command not found
make/tests:14: recipe for target 'test/gtest.o' failed
make: *** [test/gtest.o] Error 127
make -j1 test/integration/compile_models test/integration/compile_standalone_functions test/performance/logistic test/unit/multiple_translation_units test/unit/version test/unit/callbacks/interrupt test/unit/callbacks/logger test/unit/callbacks/stream_logger test/unit/callbacks/stream_writer test/unit/callbacks/tee_writer test/unit/callbacks/writer test/unit/io/array_var_context test/unit/io/chained_var_context test/unit/io/cmd_line test/unit/io/dump test/unit/io/empty_var_context test/unit/io/program_reader test/unit/io/random_var_context test/unit/io/reader test/unit/io/read_line test/unit/io/stan_csv_reader test/unit/io/starts_with test/unit/io/util test/unit/io/validate_zero_buf test/unit/io/writer failed
exit now (10/18/18 14:33:27 BST)
/media/vvalton/Data/Dropbox/workspace/matlab_toolboxes/cmdstan_latest/cmdstan

------------------------------------------------------------
Stan Math Library tests
/media/vvalton/Data/Dropbox/workspace/matlab_toolboxes/cmdstan_latest/cmdstan/stan/lib/stan_math /media/vvalton/Data/Dropbox/workspace/matlab_toolboxes/cmdstan_latest/cmdstan
------------------------------------------------------------
make -j1 test/unit/math_c11_test test/unit/math_include_test test/unit/multiple_translation_units_test test/unit/math/fwd/arr/fun/sum_test test/unit/math/fwd/arr/fun/value_of_rec_test test/unit/math/fwd/arr/fun/value_of_test test/unit/math/fwd/arr/meta/partials_return_type_test test/unit/math/fwd/core/fvar_test test/unit/math/fwd/core/std_numeric_limits_test test/unit/math/fwd/mat/fun/accumulator_test test/unit/math/fwd/mat/fun/append_col_test test/unit/math/fwd/mat/fun/append_row_test test/unit/math/fwd/mat/fun/array_builder_test test/unit/math/fwd/mat/fun/assign_test test/unit/math/fwd/mat/fun/block_test test/unit/math/fwd/mat/fun/cholesky_decompose_test test/unit/math/fwd/mat/fun/cols_test test/unit/math/fwd/mat/fun/columns_dot_product_test test/unit/math/fwd/mat/fun/columns_dot_self_test test/unit/math/fwd/mat/fun/col_test test/unit/math/fwd/mat/fun/crossprod_test test/unit/math/fwd/mat/fun/cumulative_sum_test test/unit/math/fwd/mat/fun/determinant_test test/unit/math/fwd/mat/fun/diagonal_test test/unit/math/fwd/mat/fun/diag_matrix_test
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
clang++ -Wall -I . -isystem lib/eigen_3.3.3 -isystem lib/boost_1.66.0 -isystem lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -O3 -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -O3 -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -O3 -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -O3 -DNO_FPRINTF_OUTPUT -pipe  -c -fPIC -O3 test/unit/multiple_translation_units1.cpp -o test/unit/multiple_translation_units1.o
make: clang++: Command not found
/bin/sh: 3: clang++: not found
/bin/sh: 3: clang++: not found
clang++ -Wall -I . -isystem lib/eigen_3.3.3 -isystem lib/boost_1.66.0 -isystem lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -O3 -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -O3 -DNO_FPRINTF_OUTPUT -pipe  -c -o lib/gtest_1.7.0/src/gtest-all.o lib/gtest_1.7.0/src/gtest-all.cc
make: clang++: Command not found
<builtin>: recipe for target 'lib/gtest_1.7.0/src/gtest-all.o' failed
make: *** [lib/gtest_1.7.0/src/gtest-all.o] Error 127
make -j1 test/unit/math_c11_test test/unit/math_include_test test/unit/multiple_translation_units_test test/unit/math/fwd/arr/fun/sum_test test/unit/math/fwd/arr/fun/value_of_rec_test test/unit/math/fwd/arr/fun/value_of_test test/unit/math/fwd/arr/meta/partials_return_type_test test/unit/math/fwd/core/fvar_test test/unit/math/fwd/core/std_numeric_limits_test test/unit/math/fwd/mat/fun/accumulator_test test/unit/math/fwd/mat/fun/append_col_test test/unit/math/fwd/mat/fun/append_row_test test/unit/math/fwd/mat/fun/array_builder_test test/unit/math/fwd/mat/fun/assign_test test/unit/math/fwd/mat/fun/block_test test/unit/math/fwd/mat/fun/cholesky_decompose_test test/unit/math/fwd/mat/fun/cols_test test/unit/math/fwd/mat/fun/columns_dot_product_test test/unit/math/fwd/mat/fun/columns_dot_self_test test/unit/math/fwd/mat/fun/col_test test/unit/math/fwd/mat/fun/crossprod_test test/unit/math/fwd/mat/fun/cumulative_sum_test test/unit/math/fwd/mat/fun/determinant_test test/unit/math/fwd/mat/fun/diagonal_test test/unit/math/fwd/mat/fun/diag_matrix_test failed
exit now (10/18/18 14:33:28 BST)
------------------------------------------------------------
make -j1 generate-tests -s
make: clang++: Command not found
make/tests:111: recipe for target 'test/prob/generate_tests' failed
make: *** [test/prob/generate_tests] Error 127
make -j1 generate-tests -s failed
exit now (10/18/18 14:33:28 BST)
```

I hope I haven't done anything silly.

It seems that my cmdstan still works fine and i'm able to compile and run models (but i'd just feel better if I were able to run and pass all the tests whenever I update to a new cmdstan version).

**Comment by bob-carpenter** [comment]
Sounds like `test-all.sh` may just be dead.  We now have a `./runCmdStanTests.py` which runs the unit tests.  

@mitzimorris has been working with CmdStan recently and should know the anser to what's going on with `testall.sh` and if we should just remove it.  @syclik may also know the answer there.

Thanks for sticking with this.  We don't want to be delivering buggy old shell scripts along with CmdStan.

**Comment by Feezdev** [comment]
Hi @bob-carpenter,

Thank you so much for your prompt reply.

I'll just stick with the cmdStan tests and ignore the Stan tests and the stan math library tests then :)

**Comment by rok-cesnovar** [comment]
test_all.sh file runs fine now, but could also be removed. Its not being used anywhere. Anyhow, closing.
