### ISSUE TITLE
Some warnings in tests seem legit

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stan#2653]
Here is an example: http://d1m1s1b1.stat.columbia.edu:8080/blue/organizations/jenkins/Stan/detail/downstream_tests/182/pipeline/43#step-57-log-141

```
src/test/unit/lang/ast/node/idx_ast_test.cpp:35:34: warning: parentheses were disambiguated as redundant parentheses around declaration of variable named 'i' [-Wvexing-parse]

  EXPECT_NO_THROW(stan::lang::idx(i));

                                 ^~~
src/test/unit/lang/ast/node/idx_ast_test.cpp:35:34: note: add a variable name to declare a 'stan::lang::idx' initialized with 'i'

  EXPECT_NO_THROW(stan::lang::idx(i));

                                 ^

                                  varname

```

If this is incorrect, we should remove the parens to get rid of the warning I think.

**Comment by bob-carpenter** [comment]
I think the right fix may be `(stan::lang::idx)(i)` because presumably that's meant to be a function application or construction and it's getting interpreted for reasons I don't full understand as if it was trying to declare `i` as a variable of type `stan::lang::idx`.

**Comment by sakrejda** [comment]
Some Googling tells me that it's a combo of the ["most vexing parse" ](https://en.wikipedia.org/wiki/Most_vexing_parse) and the particular way the `gtest` macros are written... so yeah, more parens sound like the solution.  C++ is nothing if not entertaining.

**Comment by bob-carpenter** [comment]
I prefer my entertainment to be a bit more enjoyable and a bit less vexing.

**Comment by rok-cesnovar** [comment]
There is no such warning in the current stan unit tests. Closing.
