### ISSUE TITLE
Stan compiler produces C++ that does not compile

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/stan#2654]
#### Summary:
When I run `stanc` (from R) on the program below, it compiles successfully. When I run `stan_model` it fails with error output from the C++ compiler.

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Run stan_model on the following Stan program:

    functions {
      int sum_lengths(vector [] va) {
        int n = 0;
        for (i in 1:size(va))
          n += num_elements(va[i]);
        return n;
      }
      
      vector vec_append(vector [] va) {
        int n = size(va);
        if (n == 0) return rep_vector(0.0, 0);
        if (n == 1) return va[1];
        {
          int sz = sum_lengths(va);
          vector[sz] v;
          int bi;
          int ei = 0;
          for (k in 1:n) {
            bi = ei + 1;
            ei += num_elements(va[k]);
            v[bi:ei] = va[k];
          }
          return v;
        }
      }
    }
    data {
      int<lower = 1> N;
      vector[N] y;
      real<lower = 0.0> sigma_p_scale_;
    }
    transformed data {
      matrix[1, N] yy = to_matrix(y');
      real ub_0_ = 1.0;
    }
    parameters {
      real<lower = 0.0> raw_2_;
    }
    transformed parameters {
    }
    model {
      real sigma_p_ = raw_2_ * sigma_p_scale_;
      vector[6] csigma2s_0_ =
        square(sigma_p_) * to_vector({0.6, 0.6, 0.2, 0.2, 0.1, 0.1});
      matrix[1,7] Zt = rep_matrix(1.0, 1, 7);
      matrix[7, 7] T = diag_matrix(rep_vector(1.0, 7));
      matrix[1, 1] H = rep_matrix(0.1, 1, 1);
      matrix[7, 7] Q = diag_matrix(rep_vector(0.01, 7));
      vector[7] a1 = rep_vector(0.0, 7);
      raw_2_ ~ normal(0.0, 1.0) T[0.0, ];

      yy ~ gaussian_dlm_obs(Zt, T, H, Q, a1,
    	diag_matrix(
    	  vec_append({
    	    to_vector({square(sigma_p_)}),
    	    csigma2s_0_
    	  })
    	)
           );
    }

#### Current Output:
Too much to show here, but here is part of it:

    In file included from fileb15020c2ca49.cpp:8:
    In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/src/stan/model/model_header.hpp:4:
    In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math.hpp:4:
    In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/rev/mat.hpp:12:
    In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/prim/mat.hpp:149:
    In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/mdivide_left.hpp:6:
    In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/promote_common.hpp:5:
    In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/promote_elements.hpp:4:
    In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/prim/arr/fun/promote_elements.hpp:4:
    /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/prim/scal/fun/promote_elements.hpp:24:16: error: no viable conversion from returned value of type 'const stan::math::var' to function return type 'double'
            return u;
                   ^
    /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/prim/arr/fun/array_builder.hpp:37:46: note: in instantiation of member function 'stan::math::promote_elements<double, stan::math::var>::promote' requested here
            x_.push_back(promote_elements<T, S>::promote(u));
                                                 ^
    fileb15020c2ca49.cpp:412:263: note: in instantiation of function template specialization 'stan::math::array_builder<double>::add<stan::math::var>' requested here
                lp_accum__.add(gaussian_dlm_obs_log<propto__>(yy, Zt, T, H, Q, a1, diag_matrix(vec_append(static_cast<std::vector<vector_d> >(stan::math::array_builder<vector_d >().add(to_vector(static_cast<std::vector<double> >(stan::math::array_builder<double 

#### Expected Output:
Either it should compile the program, or the Stan compiler should issue an error message.

#### Additional Information:
The following modification compiles without problems:

    ...
    matrix[7,7] P1 = 
      diag_matrix(vec_append({
        to_vector({square(sigma_p_)}), csigma2s_0_
      }));
    raw_2_ ~ normal(0.0, 1.0) T[0.0, ];
    yy ~ gaussian_dlm_obs(Zt, T, H, Q, a1, P1);

#### Current Version:
rstan version 2.17.3

**Comment by bob-carpenter** [comment]
Thanks and also thank for the correction.

I confirmed it's a bug as is.

I think in this example you can just define

```
matrix[7, 7] P1 = diag_matrix(append_col([square(sigma_p)]', csigma2s_0_));
```

But that's likely to be inefficient given that it has to create a diagonal matrix---I guess there's not a `gaussian_dlm_obs` that takes the diagonal directly?

**Comment by ksvanhorn** [comment]
That's right, there's no version of gaussian_dlm_obs() that takes a diagonal matrix, and for a good reason -- if you take a look at the Kalman filter equations, you'll see that even if you start with a diagonal P1, you quickly get a non-diagonal matrix.

The T[0, ] is there because my time-series-model compiler generated the original code, and in the general case the bounds might be needed. I could put in some additional optimizations to get rid of unneeded truncation annotations in cases like this, but my guess was that the additional cost was likely to be small compared to call to gaussian_dlm_obs().

**Comment by rok-cesnovar** [comment]
This model compiles with cmdstan 2.22.1 and stanc3. Closing.
