### ISSUE TITLE
Stan language print function doesn't format multi-dim arrays of containers correctly

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2655]
#### Summary:
the Stan language built-in `print` function prints the contents of multi-dimensional arrays of a container element with linebreaks in the wrong places.

#### Description:
the `print` function is a side-effect function only designed to be used as a debugging tool during model development.  it correctly prints the contents of a multi-dimensional array of vectors, but with linebreaks in the wrong places, e.g. this model:

```
transformed data {
  vector[2] a[3,5];
  a[1][2][2] = 3.0;  // a[1,2] is 1st row, 2nd col, 2nd vector element
  a[2,1,1] = 4.0;  // a[2,1] is 2nd row, 1st col, 1st vector element
  a[3][5,1] = 5.0; // a[3,5] is last entry in array, [1] first vector element
  a[3,5][2] = 6.0; // a[3,5] is last entry in array, [2] second vector element
  print(a);
}
//  innermost element of 3 x 5 array is 2-d vector
// [[[ [nan, nan], [nan, 3], [nan, nan], [nan, nan], [nan, nan]],
//  [[4, nan], [nan, nan], [nan, nan], [nan, nan], [nan, nan]],
//  [[nan, nan], [nan, nan], [nan, nan], [nan, nan], [5, 6]]]
```

produces the following output:

```
[[nan
nan,nan
  3,nan
nan,nan
nan,nan
nan],[  4
nan,nan
nan,nan
nan,nan
nan,nan
nan],[nan
nan,nan
nan,nan
nan,nan
nan,5
6]]
```

#### Reproducible Steps:
compile the above model, run from cmdstan

#### Current Output:
see above

#### Expected Output:
see above

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by rok-cesnovar** [comment]
On develop there are no such linebreaks anymore. Closing.
