### ISSUE TITLE
Trouble running "Eight Schools"

### ISSUE THREAD

**Issue by stenknutsen** [stan-dev/stan#2660]
Description:
Went through the installation as instructed in "Installing RStan on Mac or Linux." 
Check installation step worked (I got a "10"!)
However, upon running "Eight Schools Example," the code fails and I get the error below.

Current Output:
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from file72111345e98.cpp:8:
In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/src/stan/model/model_header.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/rev/mat.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/rev/core.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/rev/core/autodiffstackstorage.hpp:4:
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/StanHeaders/include/stan/math/memory/stack_alloc.hpp:145:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (auto& bloc

[edited to add traceback]

6. | stop(paste("Compilation ERROR, function(s)/method(s) not created!", paste(errmsg, collapse = "\n")))
-- | --
5. | compileCode(f, code, language = language, verbose = verbose)
-- | --
4. | cxxfunction(sig = sig, body = body, plugin = plugin, includes = includes, settings = settings, ..., verbose = verbose)
-- | --
3. | cxxfunctionplus(signature(), body = paste(" return Rcpp::wrap(\"", model_name, "\");", sep = ""), includes = inc, plugin = "rstan", save_dso = save_dso \| auto_write, module_name = paste("stan_fit4", model_cppname, "_mod", sep = ""), verbose = verbose)
-- | --
2. | stan_model(file, model_name = model_name, model_code = model_code, stanc_ret = NULL, boost_lib = boost_lib, eigen_lib = eigen_lib, save_dso = save_dso, verbose = verbose)
-- | --
1. | stan(file = "8schools.stan", data = schools_dat, iter = 1000, chains = 4)
-- | --

RStan Version:
2.17.4

R Version:
R version 3.4.2 (2017-09-28)

Operating System:
OS X 10.13.6

**Comment by bgoodri** [comment]
https://discourse.mc-stan.org/t/compilation-error-on-mac/5933/2?u=bgoodri
