### ISSUE TITLE
Error in .shlib_internal :  C++14 standard requested but CXX14 is not defined

### ISSUE THREAD

**Issue by MarcoAndrello** [stan-dev/stan#2666]
#### Summary:
Please provide a short couple sentence summary.

Error in .shlib_internal :  C++14 standard requested but CXX14 is not defined

#### Description:
Describe the issue as clearly as possible.

I cannot run the 8schools example because of the following error

Error in .shlib_internal(commandArgs(TRUE)) : 
  C++14 standard requested but CXX14 is not defined

#### Reproducible Steps:
The error occurred when trying to execute the following code:

Sys.setenv(USE_CXX14 = 1)
library("rstan")
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
fit <- stan(file = '8schools.stan', data = schools_dat, 
            iter = 1000, chains = 4)

#### Version:
Rstan v2.17.4
Rtools v34
R v.3.5.1

Thank you

**Comment by bgoodri** [comment]
You need to have

CXX14 = g++ -std=c++1y

in your ~/.R/Makevars file and also probably need to make CXX14FLAGS the
same as CXXFLAGS .

**Comment by MarcoAndrello** [comment]
Thanks bgoodri.

I understand "~/.R/Makevars" is the name of a file, but where do I find it ?
"make CXX14FLAGS the same as CXXFLAGS": does it mean changing something in the "~/.R/Makevars" file ?

Thanks

**Comment by bgoodri** [comment]
It is at whatever
```
normalizePath("~/.R/Makevars")
```
evaluates to (note there is a period before the R)

**Comment by MarcoAndrello** [comment]
Thanks bgoodri.

I have launched the command, but it seems that no Makevars file is present:

> normalizePath("~/.R/Makevars")
[1] "C:\\Users\\Marco Andrello\\Documents\\.R\\Makevars"
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/Marco Andrello/Documents/.R/Makevars": The system cannot find the file specified

Maybe something went wrong in the Installation of Rtools, or Stan ?

**Comment by MarcoAndrello** [comment]
Yes, but I had overlooked the step to create the Makevars file !
I didi it. Now it works. Thanks very much for your help !
