### ISSUE TITLE
function hypergeometric_lpmf() considers the case n=N as invalid

### ISSUE THREAD

**Issue by famuvie** [stan-dev/stan#2667]
#### Summary:
The function `hypergeometric_lpmf(int n | int N, int a, int b)` stops when `n=N` claiming that it should be `n<N` strictly. However, the case of sampling n=N successes in N trials should be valid.

#### Description:
It seems a small error in some validation step. 

#### Reproducible Steps:
``` r
library(rstan)
code <- "
  functions {
   real log_dhyper(int n, int N, int a, int b) {
      real lp;
      lp = hypergeometric_lpmf(n | N, a, b);
      return lp;
    }
  }
"
expose_stan_functions(stanc(model_code = code))
log_dhyper(10, 10, 50, 50)
#> Error in log_dhyper(10, 10, 50, 50): Exception: hypergeometric_lpmf: Draws parameter is 10, but must be greater than 10  (in 'unknown file name' at line 5)
```

<sup>Created on 2018-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

#### Current Output:
``` r
#> Error in log_dhyper(10, 10, 50, 50): Exception: hypergeometric_lpmf: Draws parameter is 10, but must be greater than 10  (in 'unknown file name' at line 5)
```

#### Expected Output:
```r
log(dhyper(10, 50, 50, 10))  ## note that the second and fourth arguments switched places
#[1] -7.429609
```

#### Current Version:
v2.18.1

**Comment by mcol** [comment]
I'm working on a fix for this. Should this issue be moved over to stan-dev/math before I submit a PR? I think nowadays this can be done [directly within github](https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository).

**Comment by mcol** [comment]
This can be closed.

**Comment by bob-carpenter** [comment]
Thanks, @mcol.  I added you to the `maintainer` group on `stan-dev` so you should be able to do this yourself in the future for most of our repos.

**Comment by mcol** [comment]
Awesome, thanks Bob!
