### ISSUE TITLE
Bug: Incorrect sampling from a multivariate Gaussian

### ISSUE THREAD

**Issue by dpsimpson** [stan-dev/stan#2671]
#### Summary:
There is a small bug in the Cholesky sampling routine in `stan/src/stan/mcmc/hmc/hamiltonians/dense_e_metric.hpp`.

Bug noticed by user fehiepsi[ on the discourse](https://discourse.mc-stan.org/t/issue-with-sample-p-method/6018)

#### Description:
Line 61 of the above file reads 
```
  z.p = z.inv_e_metric_.llt().matrixL().solve(u);
```
It should say 
```
z.p = z.inv_e_metric_.llt().matrixU().solve(u);
```

If we write `z.inv_e_metric` as the matrix A, then `z.inv_e_metric.llt()` performs the Cholesky decomposition A = LL^T. The next part of the call constructs z.p = L^{-1}u, where u~N(0,I). The covariance matrix of z.p is E(z.p z.p^T) = L^{-1}E(uu^T)L^{-T} = (L^TL)^{-1}. This is not A^{-1}, so the code is wrong.

In Eigen, the `matrixU()` routine returns the upper triangular matrix L^T.

#### Current Version:
v2.18.0

**Comment by rok-cesnovar** [comment]
Fixed long ago.
