### ISSUE TITLE
fix parser warnings for semicolons in function arguments

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2676]
#### Summary:

The parser is producing a confusing warning for the following ill-formed Stan program:

```
transformed data {
  real x = atan2(2 ; 3);
}
```

See [the Discourse topic](https://discourse.mc-stan.org/t/confusing-parser-warning/782/5) for more examples

#### Current Output:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
 error in '/Users/carp/temp2/confusing.stan' at line 2, column 17
  -------------------------------------------------
     1: transformed data {
     2:   real x = atan2(2 ; 3);
                        ^
     3: }
  -------------------------------------------------

PARSER EXPECTED: "("

```

#### Expected Output:

Something like "expected , or )" pointing before the semicolon. 

#### Current Version:
v2.18.0

**Comment by csetraynor** [comment]
Hi,
maybe an error that only an R user a bit newb in Stan would do. But the same confusing parser warnings appears if one tries passing an int[] type to a function without declaring and expecting that it will work as it would in R... for example as following:
```
functions{
vector construct_eta(matrix X, vector b, int[] loc, int sK, int[] b_K, int N){
    vector[N] eta;
     if(sK > 0) {
      eta = X[loc, K] * b[b_K];
    } else {
      eta = rep_vector(0.0, N);
    }
    return(eta);
  }
}
data{
int nSubjects
}
...
transformed parameters{
for(j in 1:nSubjects){
eta = construct_eta(predictors, beta, start[j]:end[j], sK, b_K, N);
}
}
```
I do not know how hard might be to catch this error, but in any case I also leave the comment here for future reference.

**Comment by VMatthijs** [comment]
Stanc3 says the following on @bob-carpenter 's example model (top):
```
Syntax error in 'temp.stan', line 2, column 17 to column 18, parsing error:
   -------------------------------------------------
     1:  transformed data {
     2:    real x = atan2(2 ; 3);
                           ^
     3:  }
   -------------------------------------------------

Ill-formed function application. Expect comma-separated list of expressions followed by ")" after "(".
```
and the following for @csetraynor 's model:
```
Syntax error in 'temp.stan', line 9, column 4 to column 13, parsing error:
   -------------------------------------------------
     7:  }
     8:  data{
     9:  int nSubjects
                      ^
    10:  }
    11:  ...
   -------------------------------------------------

Only top-level variable declarations are allowed in data and parameter blocks.
```
after which we can add the missing semi-colon to get the following error:
```
Syntax error in 'temp.stan', line 13, column 38 to column 46, parsing error:
   -------------------------------------------------
    11:  transformed parameters{
    12:  for(j in 1:nSubjects){
    13:  eta = construct_eta(predictors, beta, start[j]:end[j],  b_K, N);
                                                       ^
    14:  }
    15:  }
   -------------------------------------------------

Ill-formed phrase. We found an L-value. Parse failed on token after the L-value.
```

Are these considered informative enough? It's sometimes hard to give a very informative error, like in the last case, because that parse rule appears in many different contexts (meaning it's hard to give an error message that is not entirely generic). Of course, it's possible to many the grammar more complicated to get more specific error messages, but it's a matter of weighing cost and benefit then.

**Comment by VMatthijs** [comment]
Does it make sense to label this `Won't fix until stanc3`?

**Comment by csetraynor** [comment]
Hi @VMatthijs yes
`Ill-formed phrase. We found an L-value. Parse failed on token after the L-value.`
would be informative enough for a user. my opinion as a current user.

**Comment by mcol** [comment]
Fixed in stanc3.
