### ISSUE TITLE
Target should be reserved keyword

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stan#2679]
#### Summary:
Given its central role in the language, `target` should be a reserved keyword and should not be free to use as a variable.

#### Description:
`target` should only be usable to access (increment or read off) the log-density. We should not be overloading this critical key word.

#### Reproducible Steps:
Currently, the following is a valid Stan program 

```
functions {
  vector target(vector y, vector theta, real[] x_r, int[] x_i) {
    vector[2] deltas;
    deltas[1] = y[1] - theta[1] - x_r[1];
    return deltas;
  }
}
```

It shouldn't be.

#### Current Output:
Parser does not complain.

#### Expected Output:
Parser complains about illegal use of `target`.

#### Additional Information:
(I would expect the same of `get_lp`, but I guess that's been deprecated.)

#### Current Version:
v2.18.0

**Comment by mcol** [comment]
Fixed in stanc3.
