### ISSUE TITLE
Printing without semi-colon should not be allowed

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stan#2680]
#### Summary:
We should require that the user write a semi-colon after a print-statement, just like after any other statement.

#### Description:
Currently, print statements without semi-colons are valid.

#### Reproducible Steps:
The following is a valid Stan program currently:

> model {
>   print("Hello")
> }

It should not be. Only the following should be valid:
> model {
>   print("Hello");
> }

#### Current Output:
No syntax error.

#### Expected Output:
A syntax error saying that a semi-colon is expected.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
Thanks.  Definitely a bug.

**Comment by rok-cesnovar** [comment]
Fixed in stanc3.
