### ISSUE TITLE
expose full preprocessed .stan program through compiler

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2681]
#### Summary:

The `stan::lang::compile` function should have a `std::string&` argument that gets instantiated to the fully expanded .stan file after preprocessing.

#### Current Version:
v2.18.0

**Comment by bgoodri** [comment]
@paul-buerkner I think I'll just wait for this and take the thing out of **rstan**

**Comment by paul-buerkner** [comment]
Sounds good to me.

**Comment by VMatthijs** [comment]
I'd be happy to implement this in stanc3.

**Comment by rok-cesnovar** [comment]
done in stanc3
