### ISSUE TITLE
stan/io/json parser doesn't handle NaN

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2686]
#### Summary:
the JSON spec on the Stan wiki and in the CmdStan guide specifies that "NaN" will be recognized but this isn't implemented in the current parser.

#### Description:
The string "NaN" should be treated as c++ value `std::numeric_limits<double>::quiet_NaN();`

#### Current Version:
v2.18.0

**Comment by mitzimorris** [comment]
looking at JSON generated by R and python to see what JSON might look like - 
JSON generated by python:

```
import json
foo = { 'a':10, 'b':None, 'c':float('inf'), 'd':float('-inf'), 'e':float('nan')}
with open('foo_pydump.json', 'w') as outfile:
    json.dump(foo, outfile, sort_keys=True)
```
generates output:
```
{"a": 10, "b": null, "c": Infinity, "d": -Infinity, "e": NaN}
```

R using library `jsonlite`:
```
library(jsonlite)
foo2=data.frame(a=10, b=NA, c=Inf, d=-Inf, e=NaN);
cat(toJSON(as.list(foo), auto_unbox=TRUE, force=TRUE), file="foo2.json")
```
generates output:
```
{"a":10,"b":null,"c":"Inf","d":"-Inf","e":"NaN"}
```

given this, parser should recognize both quoted and bare versions `NaN`, quotes around `Inf` and bare `Infinity`.  it should also recognize and flag `NA` and `null` as missing values.

**Comment by bob-carpenter** [comment]
Is bare Infinity well-formed JSON?  I'd rather not
go outside of well-formed JSON.

Is jsonlite the most popular way to deal with JSON
in R?

**Comment by mitzimorris** [comment]
overall, I think that the stan/io/json reader should be able to handle JSON inputs generated by R and python, therefore it should be robust enough to recognize bare tokens `Infinity` and `NaN` if these are commonly used in the wild.

> bare Infinity well-formed JSON?

it looks like the de facto answer is yes, that "inf" is positive infinity, just as 1 is positive integer 1.

> recommended practice is to encode these as strings

except that python's json library doesn't seem to do this.
