### ISSUE TITLE
Truncation should have reserved keyword

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stan#2689]
#### Summary:
Truncating probability distributions is a key feature of the language and it deserves a(n) (informative) keyword. The current notation using the unprotected symbol `T` is confusing, especially as `T` can and is also used as a variable name.

#### Description:
Using `~` notation, a distribution can be truncated (presuming it has cdf's implemented) using the notation `T[--bounds go here--]`. I believe this is confusing as someone new to the language may have no idea what `T` means. This is made worse by the fact that `T` is not protected and that we also use it as a variable name in our examples.

#### Reproducible Steps:
The following is a valid Stan program:

```
model {
  real T[1,1] = {{42.0}};
  1 ~ normal(0, 1) T[1, T[1,1]];
  print(T[1,1]);
}
```

I find that confusing.

#### Current Output:
No complaints from the parser.

#### Expected Output:
I propose to deprecate the notation `T` and replace it with the more informative `truncate` and to make that a protected keyword. In the proposed, notation, the above example would be written

```
model {
  real T[1,1] = {{42.0}};
  1 ~ normal(0, 1) truncate[1, T[1,1]];
  print(T[1,1]);
}

```

and any attempt to name a variable `truncate` would lead to a syntax error.

#### Current Version:
v2.18.0

**Comment by wds15** [comment]
This is coming from the BUGS language. So for people coming from that ground are all good with this.

(I don't mind changing as you suggest, just as an FYI)

**Comment by VMatthijs** [comment]
Ah, thanks for clarifying! Still, the question then is whether we'd want to keep `T` as a keyword, in which case we should not allow variables to have the name `T`, I think, or whether we should replace it with something more informative.

**Comment by sakrejda** [comment]
I'm against making T a reserved keyword because I (and other people) have reams of Stan code for time-series models that use T as the max time index... it would be a breaking change for a lot of code.

**Comment by bob-carpenter** [comment]
As @sakrejda says, we can't really afford ot make `T` a reserved word.

If `T[, ]` gets replaced with something else, we'll need to implement in Stan 2 and deprecate the existing ersion for Stan 3.    At least I'd very much like to go down that route with backward-compatibility breaking eatures.

There was a lengthy debate initially about `[ , ]` vs. `( , )` because of openness.  The `int` types make it subtle as do the numerical underflow/overflow leading to boundary values even when the pure math function never produces boundary values for finite input.

**Comment by VMatthijs** [comment]
How would you feel about using the keyword `trunc` instead of `T`? Currently, that's a Math library function that does the same thing as `floor` as far as I can tell. Any idea why we have both?

**Comment by bob-carpenter** [comment]
> Any idea why we have both?

Yes, `trunc` is a holdover from BUGS whereas `floor` is a C++ standard library function.

I think changing `T` to `trunc` wouldn't be worth the hassle of breaking backward compatibility (presumably we'd deprecate `T` and then remove it for Stan 3).  But this is a good thing to discuss at a meeting.  If there's a strong wave of support, I won't try to hold it back.

**Comment by rok-cesnovar** [comment]
Closing this. If we still want to address this, please open a stanc3 issue, though since this was carried over to stanc3 there is no more issue here?
