### ISSUE TITLE
generate_function_instantiation.hpp does not generate a function instantiation for undefined functions

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2696]
#### Summary:

src/stan/lang/generator/generate_function_instantiation.hpp does not work for functions that are declared but not defined. Presuming the definition is included later calling those functions should be valid.

#### Description:

https://github.com/stan-dev/stan/blob/develop/src/stan/lang/generator/generate_function_instantiation.hpp#L33

returns early on forward declarations. It should still be writing `out << "// [[stan::function]]" << EOL;` and making a call to a function inside the namespace.

#### Reproducible Steps:

Call `rstan::expose_stan_functions` with the `includes` argument specified
```
functions {
  real foo();
}
```

#### Current Output:

`foo` is not exposed

#### Expected Output:

A function named `foo`

#### Additional Information:

None

#### Current Version:
v2.18.0

**Comment by martinmodrak** [comment]
Just stumbled on this and it is (mildly) blocking my progress. Is there any reason to NOT implement this as @bgoodri suggests? If not, I'd be happy to try to make it work.

**Comment by martinmodrak** [comment]
Also, I figured out a workaround:

```
function_code <-
  '
functions {
  real func_defined_in_cpp();
  real wrapper() {
    return func_defined_in_cpp();
  }
}
'

func_compiled <- stanc(model_code = function_code, model_name = "func_test",
                               allow_undefined = TRUE)

expose_stan_functions(func_compiled,
                      includes = paste0('\ndouble
func_defined_in_cpp(std::ostream* pstream__) { return 6;}\n'))


wrapper() #Works, shows 6
func_defined_in_cpp()  #Errors
```

**Comment by bob-carpenter** [comment]
Thanks for posting the workaround.  I have no idea why this is a problem, but we indeed need to figure it out.  So if you have any ideas, by all means jump in with a pull request.

**Comment by bgoodri** [comment]
Thanks for the workaround. I think the ultimate solution is to 

1. Not code-generate structs https://github.com/stan-dev/stan/issues/2703
2. Always generate the code to call declared functions inside the namespace, even if they are defined externally.

**Comment by bgoodri** [comment]
Also, @martinmodrak your workaround seems to run into the problem described at
https://discourse.mc-stan.org/t/problem-implementing-zipf-power-law-distribution-external-c/7570/28?u=bgoodri
when the function is called with `vars`. Did you find a workaround for that too?
