### ISSUE TITLE
Remove manuals from this repo (are now in repo `docs`)

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2706]
#### Summary:
Remove source files for Stan documentation set from repo `src/docs` and remove related `make` tasks.

#### Description:
The  repo `stan-dev/docs` is now the repo for the Stan reference manual and functions reference.   
The src files in this repo should be deleted in order to prevent folks from editing dead versions of the documentation.  This will also reduce the amount of work needed to do for integration, testing, and releases.

We also need to document how the docs will be built and bundled as part of the release process.

#### Current Version:
v2.18.0

**Comment by mitzimorris** [comment]
@seantalts - why does circleci run every time I push the branch for this issue?
https://circleci.com/gh/stan-dev/stan/340?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
the circleci task needs to be removed altogether - can we turn it off now?

**Comment by seantalts** [comment]
Yes, we can turn it off (and this seems like a good issue # to do it under) - you can just delete the .circleci directory and all its contents, that should do it.
