### ISSUE TITLE
Contributing new functions wiki page is incorrect

### ISSUE THREAD

**Issue by andrew-matteson** [stan-dev/stan#2709]
#### Summary:
In the [Contributing New Functions](https://github.com/stan-dev/stan/wiki/Contributing-New-Functions-to-Stan) wiki page, the steps to modify the new function signatures file are incorrect.

#### Description:
The instructions say to add `foo` with types `DOUBLE_T`; however, I think this is supposed to be `bare_expr_type(double_type())`. There may be other points that differ (I'm still wading through the process)

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
Thanks.  We should definitely update it so it matches current practices.

I'm pinging @mitzimorris, because I think she was the one to change the `function_signatures.h` structure.

**Comment by mitzimorris** [comment]
agreed.  wiki page is very out of date.  looking at it.

**Comment by mitzimorris** [comment]
updated wiki page.

**Comment by andrew-matteson** [comment]
@mitzimorris @bob-carpenter Thank you so much! This is really helpful.
