### ISSUE TITLE
Incorrect type checking for truncations

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stan#2715]
#### Summary:
The type checking for truncations in stanc2 does not always work.

#### Description:
Some models where the truncation bounds should be integers, get accepted even if the bounds are real.

#### Reproducible Steps:
Try to compile the model
```
model { 1 ~ bernoulli(0.2) T[0, 1.1]; }
```

#### Current Output:
This should throw a type checking error, as the 1.1 should be of type int.

#### Expected Output:
Instead, it compiles just fine.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by VMatthijs** [comment]
This has been fixed in stanc3.

**Comment by mcol** [comment]
Yes, stanc3 reports the following:
```
Semantic error in 'test.stan', line 1, column 8 to column 37:
   -------------------------------------------------
     1:  model { 1 ~ bernoulli(0.2) T[0, 1.1]; }
                 ^
   -------------------------------------------------

Truncation is only defined if distribution has _lcdf and _lccdf functions implemented with appropriate signature.
```
