### ISSUE TITLE
Recursive includes are not processed

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stan#2716]
#### Summary:
Currently, includes of more than 1 level deep are ignored. This seems impractical.

#### Description:
Currently, you can include one Stan file a.stan from another b.stan. But we cannot have a.stan includes b.stan includes c.stan. The include of c.stan in b.stan will then be silently ignored by the current parser. At the very least, an error should be thrown if that is the desired behaviour.

#### Reproducible Steps:
Write file `a.stan` with content
```
model {
#include b.stan
}
```
`b.stan` with content
```
int y;
#include c.stan
```
`c.stan`with content
```
int y;
```.


#### Current Output:
This parses fine.


#### Expected Output:
I would expect an error saying that the variable y is declared twice.


#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by VMatthijs** [comment]
Stanc3 fixes this by allowing arbitrary hierarchies of includes. It throws an error if a cyclical include structure is detected (e.g. `a.stan` includes `b.stan` includes `a.stan` again).

**Comment by rok-cesnovar** [comment]
Fixed in stanc3.
