### ISSUE TITLE
Set up clang-format to run automatically on Jenkins on this repo

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stan#2718]
#### Summary:
It is very hard to download precisely the correct version of clang-format such that cpplint passes on my local machine. Currently, I have to spend so much time formatting my code manually. I think that if we insist on a specific formatting style, it would be helpful to do the formatting automatically for the developers.

#### Description:
This already works on stan-math and it's great. I'd love to see something similar on this repo.

#### Reproducible Steps:
On ubuntu, download clang-format-5.0. Format your cpp code using it, submit a PR to stan-dev/stan and see your build fail on Jenkins because of cpplint.

#### Additional Information:

One consideration for this issue is whether we'd like to do it before or after we switch to a monorepo.

#### Current Version:
v2.18.0

**Comment by rok-cesnovar** [comment]
I believe this isnt an issue anymore. clang-format 6.0.0 is used across the board.
