### ISSUE TITLE
unknown variable: segment

### ISSUE THREAD

**Issue by tpapp** [stan-dev/stan#2724]
Summary: using `segment` causes a (hopefully spurious) warning.

MWE (almost straight from the user guide):
```sh
$ stanc --version
stanc version 2.18.1
$ stanc segment.stan 
Model name=segment_model
Input file=segment.stan
Output file=segment_model.cpp
DIAGNOSTIC(S) FROM PARSER:
Unknown variable: segment
Warning: left-hand side variable (name=pos) occurs on right-hand side of assignment, causing inefficient deep copy to avoid aliasing.
```

Minimal model code: 

```stan
data {
  int<lower=0> N;
  int<lower=0> K;
  vector[N] y;
  int s[K];
}
parameters {
  real mu[K];
  real<lower=0> sigma;
}
model {
  int pos;
  pos = 1;
  for (k in 1:K) {
    segment(y, pos, s[k]) ~ normal(mu[k], sigma);
    pos = pos + s[k];
  }
}
```

**Comment by tpapp** [comment]
Incidentally, not getting a warning for updating `pos` would also be nice, should I open a separate issue?

**Comment by mcol** [comment]
This doesn't seem to be an issue with stanc3. @seantalts could you confirm?

**Comment by seantalts** [comment]
I think we should just close any true bugs on the old compiler - chances are pretty small we reproduced them as-is. Anything else around what the spec should be can stay open.
