### ISSUE TITLE
Feature request: apply functions along matrix/array axes without loops

### ISSUE THREAD

**Issue by ShaunMcDonald1021** [stan-dev/stan#2734]
#### Summary:
The ability to automatically apply vector functions across the rows or columns of a matrix in Stan without the explicit use of for-loops, similar to the apply() function in R.

#### Description:
The conventional Stan advice is to avoid loops as much as possible in favour of vectorization. However, currently loops are sometimes inevitable. For instance, if I have a matrix A and I want to create a vector consisting of the log_sum_exp of each column, currently I'd have to do
```
vector[n_col] logsumexp;
for(j in 1:n_col){logsumexp[j] = log_sum_exp(A[,j]);
```

According to the manual, `log_sum_exp(A)` will return a single number since it sums up all (exponentiated) elements in A.

This is addressed in R with the apply function: `apply(A, axis = 2, fun = log_sum_exp)`. Perhaps some equivalent to this in Stan would be useful - a way to automatically apply vector functions along one axis of a matrix to return an appropriate vector. Would it be possible to implement this in a way that was more efficient than the explicit loop? I imagine that doing it sans-loop would speed up autodiff (in this case, depending on how I subsequently incorporated the `logsumexp` vector into the model), but I'm not knowledgeable enough about what's happening under the hood to be certain.

#### Current Version:
v2.18.1

**Comment by bob-carpenter** [comment]
Thanks for proposing this.  

Functionally, I agree we need something like this.  There are some limited cases of this, but not any higher-order applies.  

Technically, It's going to be much easier to add when we finish the OCaml parser rebuild as we'll be adding higher-order types.  As is, it would require special handling in the parser.

I'm going to close this issue until there's a concrete specification of the function that someone might implement.  

We're trying to keep design discussions on Discourse, then move to issues when there's a concrete to-do item that someone can pick up and follow the directions. This one's going to require too much judgement in its current state.

**Comment by bob-carpenter** [comment]
P.S.  There are two reasons to vectorize Stan code:

1.  Cut down on autodiff expression graph with vectorizations with analytic gradients (for example, scalar times vector should be more efficient than a loop).

2.  Make the code easier to read and less error prone to write.
