### ISSUE TITLE
add GP covariance functions to language

### ISSUE THREAD

**Issue by drezap** [stan-dev/stan#2736]
#### Summary:
Now that we have support in the math library for some more common covariance functions, I would like to update the `function_signatures.h` file to expose these functions to users for the next release.

#### Description:
edit `function_sigantures.h` to includes the new covariance functions:

Already merged:
gp_exp_quad_cov (ard), gp_matern52_cov (ard), gp_periodic_cov, gp_dot_prod_cov.

Pending review or implementation:
gp_matern32_cov, gp_exponential_cov,

the Matern set, besides exponential, need to be specialized for reverse mode for performance. 

#### Reproducible Steps:
Not applicable. 

#### Current Output:
Only smooth GPs

#### Expected Output:
New covariance functions.

#### Additional Information:
N/A.

#### Current Version:
v2.18.1

**Comment by bbbales2** [comment]
This issue was closed with https://github.com/stan-dev/stan/pull/2739. The docs are still missing though: https://github.com/stan-dev/stan/issues/2744

**Comment by olatunjijohnson** [comment]
Is the documentation of the function now available?

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/stan/issues/2744#issuecomment-534869252

current documentation:  functions reference chapter 21.4, 21.5, and 21.6:

https://mc-stan.org/docs/2_22/functions-reference/multivariate-gaussian-process-distribution.html

**Comment by bbbales2** [comment]
Nah. It'll go here when it is: https://mc-stan.org/docs/2_22/functions-reference/covariance.html

Is there a particular covariance function you want to code up?

**Comment by olatunjijohnson** [comment]
I will like to have the Matern family where I can vary the smoothness parameter.

**Comment by bob-carpenter** [comment]
matern32 and matern52 exist on the `develop` branch in
`stan/math/prim/fun/gp_maternXX_cov.hpp`

**Comment by bbbales2** [comment]
Converting the c++ here: https://github.com/stan-dev/math/blob/develop/stan/math/prim/fun/gp_matern52_cov.hpp

This function at least compiles. I didn't debug it or anything. Maybe give this a go and if you have trouble ask a question about it on https://discourse.mc-stan.org/

```
matrix gp_matern52_func(real[] x, real sigma, real length_scale) {
  matrix[size(x), size(x)] cov;

  real sigma_sq = sigma^2;
  real root_5_inv_l = sqrt(5.0) / length_scale;
  real inv_l_sq_5_3 = 5.0 / (3.0 * length_scale^2);

  for (i in 1:size(x)) {
    cov[i, i] = sigma_sq;
    for (j in (i + 1):size(x)) {
      real sq_distance = (x[i] - x[j])^2;
      real dist = sqrt(sq_distance);
      cov[i, j] = sigma_sq
                  * (1.0 + root_5_inv_l * dist + inv_l_sq_5_3 * sq_distance)
                  * exp(-root_5_inv_l * dist);
      cov[j, i] = cov[i, j];
    }
  }
  return(cov);
}
```

@bob-carpenter I think the functions are actually exposed. Just not doc'ed. If you try to make this function name ```gp_matern52_cov```, for instance, you get an error.

**Comment by olatunjijohnson** [comment]
Thanks

**Comment by rok-cesnovar** [comment]
The following signatures are in the compiler: 

```
matrix gp_dot_prod_cov(real[], real)
matrix gp_dot_prod_cov(real[], real[], real)
matrix gp_dot_prod_cov(real[], real[], real)
matrix gp_dot_prod_cov(vector[], real)
matrix gp_dot_prod_cov(vector[], vector[], real)
matrix gp_exp_quad_cov(real[], real, real)
matrix gp_exp_quad_cov(real[], real[], real, real)
matrix gp_exp_quad_cov(vector[], real, real)
matrix gp_exp_quad_cov(vector[], real, real[])
matrix gp_exp_quad_cov(vector[], vector[], real, real)
matrix gp_exp_quad_cov(vector[], vector[], real, real[])
matrix gp_exponential_cov(real[], real, real)
matrix gp_exponential_cov(real[], real[], real, real)
matrix gp_exponential_cov(vector[], real, real)
matrix gp_exponential_cov(vector[], real, real[])
matrix gp_exponential_cov(vector[], vector[], real, real)
matrix gp_exponential_cov(vector[], vector[], real, real[])
matrix gp_matern32_cov(real[], real, real)
matrix gp_matern32_cov(real[], real[], real, real)
matrix gp_matern32_cov(vector[], real, real)
matrix gp_matern32_cov(vector[], real, real[])
matrix gp_matern32_cov(vector[], vector[], real, real)
matrix gp_matern32_cov(vector[], vector[], real, real[])
matrix gp_matern52_cov(real[], real, real)
matrix gp_matern52_cov(real[], real[], real, real)
matrix gp_matern52_cov(vector[], real, real)
matrix gp_matern52_cov(vector[], real, real[])
matrix gp_matern52_cov(vector[], vector[], real, real)
matrix gp_matern52_cov(vector[], vector[], real, real[])
matrix gp_periodic_cov(real[], real, real, real)
matrix gp_periodic_cov(real[], real[], real, real, real)
matrix gp_periodic_cov(vector[], real, real, real)
matrix gp_periodic_cov(vector[], vector[], real, real, real)
```

**Comment by benearnthof** [comment]
> The following signatures are in the compiler:

Is it possible to call these functions through RStan? 
Using 
`cov = gp_matern52_cov(x, sdgp, lscale[1]);`
Yields the following error in RStan 2.19.3: 
`No matches for: 

  gp_matern52_cov(vector[ ], real, real)

Function gp_matern52_cov not found.`

**Comment by rok-cesnovar** [comment]
Unfortunately not, they are only available through cmdstan for now but will be available with the next RStan.

**Comment by benearnthof** [comment]
I will look into cmdstan then, thank you for the quick reply!

**Comment by rok-cesnovar** [comment]
If you are accustomed to rstan, your easiest way to start would be cmdstanr - https://github.com/stan-dev/cmdstanr

Its still in pre-beta phase but it covers more or less all cmdstanr features.
