### ISSUE TITLE
stan-functions.txt is not created anymore

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2740]
#### Summary:

The make target to create the stan-functions.txt file used in RStan and RStudio was eliminated when we went to the RMarkdown-based documentation.

#### Description:

The make target to create the stan-functions.txt file used in RStan and RStudio was eliminated when we went to the RMarkdown-based documentation.

#### Reproducible Steps:

```
find . -type f -name "stan-functions.txt" -print
```

#### Current Output:

Nothing

#### Expected Output:

Nothing but we used to create it

#### Additional Information:

None

#### Current Version:
v2.18.1

**Comment by mcol** [comment]
Is this still wanted or were the changes discussed in https://github.com/stan-dev/docs/issues/42 enough?

**Comment by bob-carpenter** [comment]
This can be closed when https://github.com/stan-dev/docs/pull/128 is merged.

**Comment by mcol** [comment]
Fixed by https://github.com/stan-dev/docs/pull/180.
