### ISSUE TITLE
Index to Functions Reference is not right

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2746]
#### Summary:

The index to the functions reference manual in the PDF is missing many functions and is off by several pages.

#### Description:

https://discourse.mc-stan.org/t/functions-lookup/7993/8?u=bgoodri

#### Reproducible Steps:

1. Open https://mc-stan.org/docs/2_19/functions-reference-2_19.pdf
2. Go to the index
3. Read

#### Current Output:

https://discourse-cdn-sjc2.com/standard14/uploads/mc_stan/original/2X/e/e047921bbae3f1a195a28887832f6042a6291dd0.png

#### Expected Output:

https://discourse-cdn-sjc2.com/standard14/uploads/mc_stan/optimized/2X/d/de749c0bfc3b53e07d3d01646dffe0b674e1bed8_2_500x500.png

#### Additional Information:

The underlying .Rmd files are missing postfixes in their index entry metadata.

#### Current Version:
v2.19.0

**Comment by ode33** [comment]
What is the consensus solution for this?

**Comment by bob-carpenter** [comment]
See https://github.com/stan-dev/docs/issues/37

Closing here.
