### ISSUE TITLE
generator bug - matrix indexing after refactor is inefficient

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2748]
#### Summary:
models compiled with Stan 2.19.0 which do a lot of matrix element access are running 10x slower than same model compiled with Stan 2.18.1

see: https://discourse.mc-stan.org/t/cmdstan-slower-than-pystan/8332/11

#### Description:
The parser/generator code refactor went in with the 2.19 release, which is what introduced this bug.   The culprit is in file `src/stan/lang/generator/generate_indexed_expr.hpp`.

#### Reproducible Steps:
See model and file referenced in discourse post.
Running compiled model with supplied data from command line using unix `time` command
under cmdstan 2.18.1 and cmdstan 2.19.0 shows consistent difference in time.
On a MacBook Pro w/ 2 cores, for 2.18.1 1 chain with all defaults runs in 24s, 2.19.0 takes just under 4 minutes - 240 seconds.

#### Current Output:
Running compiled model with supplied data from command line using unix `time` command
under cmdstan 2.18.1 and cmdstan 2.19.0 shows consistent difference in time.
On a MacBook Pro w/ 2 cores, for 2.18.1 1 chain with all defaults runs in 24s, 2.19.0 takes just under 4 minutes - 240 seconds.

#### Expected Output:
2.19.0 should run as fast or faster.

#### Current Version:
v2.19.0

**Comment by mitzimorris** [comment]
multiple indexing semantics described here:
https://mc-stan.org/docs/2_19/reference-manual/language-multi-indexing-section.html

further examples in test model:
https://github.com/stan-dev/stan/blob/develop/src/test/test-models/good/assignments.stan

in particular, note semantics for indexing on arrays of matrices:

```
matrix[5,6] m2[2,3];
matrix[5,6] m3[2,3,4];
row_vector[6] tz;
tz <- m2[1,1,1];
tz <- m3[1,1,1,1];
```

**Comment by seantalts** [comment]
I think I added the model to example-models to a new "regressions" directory and updated the performance-cmdstan-tests to make sure we run it. That job will run here: http://d1m1s1b1.stat.columbia.edu:8080/job/CmdStan%20Performance%20Tests/job/master/590/
