### ISSUE TITLE
Allow initial time and time vector to be var in ode functions

### ISSUE THREAD

**Issue by wds15** [stan-dev/stan#2757]
#### Summary:
All time arguments (initial and time vector) in the integrate ode functions allow vars by now. The parser should allow that to compile.

#### Description:
Stan programs are allowed to now call the integrate functions with var argument to the time (initial and time point vector) arguments

#### Reproducible Steps:

This model is a variation of the "good" reference model for the parser and it should now allow also this to pass:

```stan
functions {
  real[] sho(real t,
             real[] y, 
             real[] theta,
             real[] x,
             int[] x_int) {
    real dydt[2];
    dydt[1] = y[2];
    dydt[2] = -y[1] - theta[1] * y[2];
    return dydt;
  }
}
data {
  int<lower=1> T;
  real y0_d[2];
  real t0;
  real ts[T];
  real theta_d[1];
  real x[0];
  int x_int[0];
}
parameters {
  real y0_p[2];
  real theta_p[1];
}
transformed parameters {
  real ts_p[T] = ts;
  real t0_p = t0;
}
model {
  real y_hat[T,2];
  y_hat = integrate_ode_rk45(sho, y0_d, t0, ts, theta_d, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_d, t0, ts, theta_p, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_p, t0, ts, theta_d, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_p, t0, ts, theta_p, x, x_int);
  // let t0 be a parameter
  y_hat = integrate_ode_rk45(sho, y0_d, t0_p, ts, theta_d, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_d, t0_p, ts, theta_p, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_p, t0_p, ts, theta_d, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_p, t0_p, ts, theta_p, x, x_int);
  // let ts be a parameter
  y_hat = integrate_ode_rk45(sho, y0_d, t0, ts_p, theta_d, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_d, t0, ts_p, theta_p, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_p, t0, ts_p, theta_d, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_p, t0, ts_p, theta_p, x, x_int);
  // let both time arguments be parameters
  y_hat = integrate_ode_rk45(sho, y0_d, t0_p, ts_p, theta_d, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_d, t0_p, ts_p, theta_p, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_p, t0_p, ts_p, theta_d, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_p, t0_p, ts_p, theta_p, x, x_int);
}
generated quantities {
  real y_hat[T,2];
  y_hat = integrate_ode_rk45(sho, y0_d, t0, ts, theta_d, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_d, t0, ts, theta_p, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_p, t0, ts, theta_d, x, x_int);
  y_hat = integrate_ode_rk45(sho, y0_p, t0, ts, theta_p, x, x_int);
}
```

#### Current Output:
This is currently not allowed and leads to a parser error.

#### Expected Output:
This should compile just fine now.

#### Current Version:
This only works for develop as of 2019 05 17

**Comment by wds15** [comment]
@mitzimorris or @bob-carpenter I hope the above is clear enough to describe what's needed. The above Stan programs will work now that the time-arguments are allowed to be parameters.

I have never touched the parser so it would be great if parser expert can take this on.

**Comment by charlesm93** [comment]
I've just been looking at the parser tests. The ODE unit test I found, `ode_test.cpp`, only tests one good model, namely `ode.stan`. Shouldn't it also test the models `integerate_ode_*.stan`? As far as I can tell, these good models are not tested anywhere.

**Comment by charlesm93** [comment]
Ok, I made the requisite changes and I also expanded the unit tests for the bdf, adams, and rk45 integrators. Once I have an answer to my above query -- and I'm sure I edited the right unit tests -- I can submit a PR.

**Comment by charlesm93** [comment]
... actually, I also need to update the documentation. Do we still update the user manual in the Stan repo, or does this happen on a separate repo, i.e. under stan-dev/doc?

**Comment by bob-carpenter** [comment]
Yes, the doc should go into stan-dev/docs.  No PR for Stan should be approved without pointing to the appropriate stan-dev/docs issue.  The docs issue should mention it depends on the stan-dev/stan PR before merging, as we don't want doc to get ahead of functionality.

**Comment by wds15** [comment]
All done. Thanks @charlesm93 ! Finally we can have varying time in ODEs ... wonderful.
