### ISSUE TITLE
Stan ESS computation documentation wrong

### ISSUE THREAD

**Issue by nowozin** [stan-dev/stan#2762]
#### Summary:
Section 15.4.1 in the Stan documentation,
https://mc-stan.org/docs/2_18/reference-manual/effective-sample-size-section.html
defines the autocorrelation and then simplifies the equation by removing the means.  This simplification is wrong mathematically.

#### Description:
I am confident the implementation in Stan is correct, this issue is only about the documentation.

The issue is with the claim that the autocorrelation integral term (t-mean)(s-mean) simplifies to t*s, but it actually simplifies to t*s - mean^2, and the derivation in Section 15.4.1 ommits the squared mean.

The correct simplified autocorrelation equation should read

```
\rho_t = \frac{1}{\sigma^2} \int_{\Theta} \theta^{(n)} \theta^{(n+t)} d\theta - \frac{\mu^2}{\sigma^2}.
```

#### Current Version:
v2.19.1

**Comment by avehtari** [comment]
Thanks for reporting this! We'll fix it.

**Comment by roualdes** [comment]
Does anyone mind if I assign myself to this?

There should also be a `p(\theta)` inside the integral, right?

**Comment by mcol** [comment]
This was fixed by https://github.com/stan-dev/docs/pull/74.

**Comment by avehtari** [comment]
Good catch, this mistake was still in Rhatv5 and ESS paper, too. I now just removed that equation and the sentence before that from the paper as they are are actually used or needed.
