### ISSUE TITLE
Unit tests on Linux done with CXX=g++

### ISSUE THREAD

**Issue by serban-nicusor-toptal** [stan-dev/stan#2763]
#### Summary:  

Hey, I'm trying to update the Jenkinsfile to run Unit & Integrations tests for all 3 Operating Systems ( win, mac, linux )

I'm running into trouble when running linux tests `src/test/unit` with `g++`

#### Description:

When running the tests with `CXX=g++` inside `make/local` I'm getting the following:

```
src/test/unit/io/random_var_context_test.cpp:6:10: fatal error: test/test-models/good/services/test_lp.hpp: No such file or directory
 #include <test/test-models/good/services/test_lp.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make/tests:13: recipe for target 'test/unit/io/random_var_context_test.o' failed
make: *** [test/unit/io/random_var_context_test.o] Error 1
make: *** Waiting for unfinished jobs....
```

When running the exact thing as above locally on Ubuntu WSL ( Ubuntu on Windows Subsystem for Linux ) the test does not throw that error tho.

```
python runTests.py -j16 src/test/unit/io/random_var_context_test.cpp
------------------------------------------------------------
make -j16 test/unit/io/random_var_context_test
make: 'test/unit/io/random_var_context_test' is up to date.
------------------------------------------------------------
test/unit/io/random_var_context_test --gtest_output="xml:test/unit/io/random_var_context_test.xml"
Running main() from lib/stan_math/lib/gtest_1.8.1/src/gtest_main.cc
[==========] Running 9 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 9 tests from random_var_context
[ RUN      ] random_var_context.contains_r
[       OK ] random_var_context.contains_r (0 ms)
[ RUN      ] random_var_context.vals_r
[       OK ] random_var_context.vals_r (0 ms)
[ RUN      ] random_var_context.dims_r
[       OK ] random_var_context.dims_r (0 ms)
[ RUN      ] random_var_context.contains_i
[       OK ] random_var_context.contains_i (0 ms)
[ RUN      ] random_var_context.vals_i
[       OK ] random_var_context.vals_i (0 ms)
[ RUN      ] random_var_context.dims_i
[       OK ] random_var_context.dims_i (0 ms)
[ RUN      ] random_var_context.names_r
[       OK ] random_var_context.names_r (0 ms)
[ RUN      ] random_var_context.names_i
[       OK ] random_var_context.names_i (0 ms)
[ RUN      ] random_var_context.construct
[       OK ] random_var_context.construct (0 ms)
[----------] 9 tests from random_var_context (1 ms total)

[----------] Global test environment tear-down
[==========] 9 tests from 1 test case ran. (2 ms total)
[  PASSED  ] 9 tests.
```

#### Reproducible Steps:

Run the following command to execute the test
`python runTests.py -j16 src/test/unit/io/random_var_context_test.cpp`

#### Additional Information:

You can find the Stan PR [here](https://github.com/stan-dev/stan/pull/2761)
The above tests succeed if using clang

#### Current Version:
v2.19.1

**Comment by syclik** [comment]
What version of `g++` are you running? Unfortunately, it matters. You're getting into the depths of where make meets c++ compiler dependency generation. I think I've put branching in the makefile for the versions of `g++` we claimed we were testing against. I'm not sure it's written appropriately for all versions of `g++` (but that was never the goal). I'll link to the exact lines in the makefiles in the next comment.

**Comment by syclik** [comment]
You'll have to dig into the generated dependencies. It's crazy that the compilers actually don't follow their own doc, but they don't.

Here are the lines to look at:
https://github.com/stan-dev/stan/blob/develop/make/tests#L23
https://github.com/stan-dev/stan/blob/develop/make/tests#L26
https://github.com/stan-dev/math/blob/develop/make/dependencies#L4

Essentially, what's happening when you run 
```
python runTests.py -j16 src/test/unit/io/random_var_context_test.cpp
```

is that it calls
```
make test/unit/io/random_var_context_test.o
```

This target, `test/unit/io/random_var_context_test.o`, has a make dependency which generates a dependencies file, `src/test/unit/io/random_var_context_test.d`. You can actually just generate that without going through everything else:

```
make src/test/unit/io/random_var_context_test.d
```

If you look inside that file when it's generated by clang++, it should have inside a line with:
```
  test/test-models/good/services/test_lp.hpp \
```

Our makefiles know how to build that target: we find the `test_lp.stan` and generate a `test_lp.hpp` from it. If you look at that file that's generated with whatever version of g++ you have, I bet it doesn't specify that target appropriately. When I use `g++-8` (`g++-8 (Homebrew GCC 8.3.0) 8.3.0`), it does not work... it doesn't generate the `test_lp.hpp` dependency appropriately. So... we either need to append that target to the file, add it manually to the target, or find some way to have `g++` respect the flags to generate the dependencies.

Anyway, you'll need to be more specific about the g++ version to make progress here.

**Comment by serban-nicusor-toptal** [comment]
Good morning.

`gcc -v` on the Jenkins Linux Machine
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
```

`gcc -v` on the Local Ubuntu WSL Machine

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04)
```

**Comment by seantalts** [comment]
Is this still happening? And just to be clear we're only using gcc on Linux, right? We should be aiming for the one in here: https://github.com/stan-dev/stan/wiki/Supported-C---Compilers-and-Language-Features (looks like GCC 5).

**Comment by serban-nicusor-toptal** [comment]
Forgot to mention it here but the linux issues are gone.
Windows seems to have some problems.

**Comment by serban-nicusor-toptal** [comment]
('stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr.stan', 1.01)
('stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss.stan', 0.99)
('stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl.stan', 0.98)
('stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs.stan', 0.98)
('stat_comp_benchmarks/benchmarks/eight_schools/eight_schools.stan', 0.99)
('stat_comp_benchmarks/benchmarks/gp_regr/gp_regr.stan', 1.0)
('compilation', 1.02)
('stat_comp_benchmarks/benchmarks/arK/arK.stan', 0.99)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix_collapse/low_dim_gauss_mix_collapse.stan', 1.0)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.stan', 1.0)
('stat_comp_benchmarks/benchmarks/sir/sir.stan', 1.0)
('stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs.stan', 0.77)
('stat_comp_benchmarks/benchmarks/garch/garch.stan', 0.99)
('stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data.stan', 1.02)
('stat_comp_benchmarks/benchmarks/arma/arma.stan', 0.99)
Result: 0.98242302359
Commit hash: d52531c66e40911a42dc7613fc6a1cf36fc26a13

**Comment by serban-nicusor-toptal** [comment]
@seantalts Can the failure on windows [here](https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/PR-2761/13/pipeline) be related to [this bug ](https://github.com/stan-dev/cmdstan/issues/720)
