### ISSUE TITLE
integrate_1d not documented?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/stan#2767]
There’s a question about integrate_1d on discourse

https://discourse.mc-stan.org/t/how-to-use-integrate-1d/9218/11

and I don’t think we have any doc to point them to. I can’t find integrate_1d in the functions reference at all. Am I missing the doc or did it somehow get merged with no documentation? I don’t know enough about the function to document it myself but it shouldn’t be released if it’s not in the functions reference. (Sorry if I just missed it somewhere).

**Comment by bob-carpenter** [comment]
This is the wrong repo.  The issue for this is https://github.com/stan-dev/docs/issues/48

**Comment by jgabry** [comment]
Thanks @bob-carpenter. I forgot about stan-dev/docs!

**Comment by yanivabir** [comment]
Sorry to bother you here, but I'm having trouble finding the reference for integrate_1d in stan-dev/docs. Any hints as to where should I be looking? I can only find a [note about the syntax](https://github.com/stan-dev/docs/blob/accc8169e22346ae74c0647fa677b81e55e1babd/src/reference-manual/syntax.Rmd), but not more.

**Comment by mitzimorris** [comment]
> Sorry to bother you here, but I'm having trouble finding the reference for integrate_1d in stan-dev/docs. Any hints as to where should I be looking? I can only find a [note about the syntax](https://github.com/stan-dev/docs/blob/accc8169e22346ae74c0647fa677b81e55e1babd/src/reference-manual/syntax.Rmd), but not more.

this is now being handled by https://github.com/stan-dev/docs/issues/48 - 

there was doc written in Aug 2018 that got lost in the transition from latex to markdown - I've tracked it down and will add it into the online docs.
