### ISSUE TITLE
Typo in Stan reference manual v2.19.1 (PDF page 125)

### ISSUE THREAD

**Issue by lamhm** [stan-dev/stan#2771]
#### Description:
On the 4rd lines of page 125 in the PDF document (BNF Grammars section), the text should be:
`assignment_op ::= '<-' | '=' | '+=' | '-=' | '*=' | '/=' | '.*=' | './='`

instead of:
`assignment_op ::= '<-' | '=' | '+=' | '-=' | '*=' | '/=' | '.*=' | '/*='`
(notice the last operator).

#### Current Version:
v2.19.1

**Comment by roualdes** [comment]
Thanks, @lamhm.  I believe documentation issues are going in https://github.com/stan-dev/docs these days.  Would you mind moving this issue?

**Comment by bob-carpenter** [comment]
Thanks for spotting that.  @roualdes ---there's no more auto issue mover, so I moved it manually to: https://github.com/stan-dev/docs/issues/50
