### ISSUE TITLE
add `add_diag` to language

### ISSUE THREAD

**Issue by drezap** [stan-dev/stan#2778]
#### Summary:
Add `add_diag.hpp` to language

This has been implemented for a while, I just never added it to language.

#### Current Version:
v2.19.1

Copywrite 2019 Andre Zapico

**Comment by charlesm93** [comment]
Any progress on this front? I'm happy to take care of this.

**Comment by drezap** [comment]
yeah, it just needs to be reviewed. Mind giving me a review and we can merge this once it passes tests?

https://github.com/stan-dev/stan/pull/2779

**Comment by charlesm93** [comment]
Looks like @bob-carpenter beat me to reviewing this.

**Comment by bob-carpenter** [comment]
It was only a few lines.  Please ping me for the final review.  Thanks.

**Comment by drezap** [comment]
merged
