### ISSUE TITLE
integrate_1d tolerance isn't actually optional (but it should be)

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/stan#2786]
#### Summary:
The tolerance parameter to integrate_1d isn't optional but it should be.

#### Description:
There are two signatures in the docs, but only the second works (the one with the tolerance) works: https://mc-stan.org/docs/2_19/functions-reference/functions-1d-integrator.html .

#### Reproducible Steps:
Here is an example model for the signature without the tolerance:
```
functions {
  real integrand(real x, real xc, real[] theta, real[] x_r, int[] x_i) {
    return 0.0;
  }
}

data {
}

transformed data {
  real x_r[0];
  int x_i[0];
}

parameters {
  real x[1];
}

model {
  real y = integrate_1d(integrand, 0, 1, x, x_r, x_i);

  x ~ normal(y, 1.0);
}
```

If you change
```
real y = integrate_1d(integrand, 0, 1, x, x_r, x_i);
```

to

```
real y = integrate_1d(integrand, 0, 1, x, x_r, x_i, 1e-8);
```

The model compiles.

#### Current Output:

The first model doesn't compile

#### Expected Output:

Both models should compile

#### Current Version:
v2.19.1

**Comment by seantalts** [comment]
Should integrate_1d return a real? In the manual it returns a vector: https://mc-stan.org/docs/2_19/functions-reference/functions-1d-integrator.html

**Comment by bbbales2** [comment]
It should definitely be a real.

**Comment by mcol** [comment]
The compilation problem has been fixed. Docs will be fixed by https://github.com/stan-dev/docs/pull/151.
