### ISSUE TITLE
target += 

### ISSUE THREAD

**Issue by xqian777** [stan-dev/stan#2788]
Hi,
I am not very sure where the results saved after using target +=. 
for example, if I writ:
 target += bernoulli_lpmf(x[n] | rate[n]);
I would like to get the number of  bernoulli_lpmf(x[n] | rate[n])/100, so what should I write next is right, can I write as following directly:
 target += bernoulli_lpmf(x[n] | rate[n])/100;

thanks

**Comment by bob-carpenter** [comment]
Thanks for engaging with the Stan community.

I'm afraid this isn't a Stan issue---it's a question about programming in Stan.  So I'm going to close it here.

I would suggest [the Stan forums](https://discourse.mc-stan.org) or even Stackoverflow for questions like this.
