### ISSUE TITLE
Mismatch between implementation and doc in signatures of falling_factorial and rising_factorial

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stan#2792]
#### Summary:
There is a mismatch between implementation and doc in signatures of falling_factorial and rising_factorial. The language restricts the second argument to be integer, but this is not documented. Also, log_falling_factorial and log_rising_factorial do not have this restriction. Is that intentional?

#### Description:
See above.

#### Reproducible Steps:
Try to compile

```
model {
  real x;
  print(falling_factorial(x, x));
}
```

#### Current Output:
This does not compile and complains that the second argument needs to be integer.

#### Expected Output:
Based on the doc, this should compile.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.20.0

**Comment by bob-carpenter** [comment]
The functions aren't technically restricted to integers.  I don't
know the intended use case.  But whatever it is, the log and
linear versions should match in domain.

**Comment by mcol** [comment]
The difference between the linear and log versions is that the first uses `boost::math::rising_factorial`, which is limited to integers (https://www.boost.org/doc/libs/1_72_0/libs/math/doc/html/math_toolkit/factorials/sf_rising_factorial.html), while the log version is `lgamma(x + n) - lgamma(x)` which is not limited to integers.

Unless there is a need to change the implementation of the linear version, what remains to be done is to clarify the documentation.

**Comment by mcol** [comment]
The documentation bug was fixed in https://github.com/stan-dev/docs/pull/138. If a change in implementation is required, let's open a new issue.
