### ISSUE TITLE
Reserved words compilation error -- opaque error message

### ISSUE THREAD

**Issue by cdriveraus** [stan-dev/stan#2802]
Setting up the following functions for easier integer indexing gives a compile error, seemingly due to using an integer called 'not'. This is mentioned in the reference manual but the problem is unclear (to me at least) from the error message. 

> Error in compileCode(f, code, language = language, verbose = verbose) : 
>   Compilation ERROR, function(s)/method(s) not created! In file included from C:/Users/driver/Documents/R/win-library/3.6/BH/include/boost/random/detail/integer_log2.hpp:19:0,
>                  from C:/Users/driver/Documents/R/win-library/3.6/BH/include/boost/random/detail/int_float_pair.hpp:26,
>                  from C:/Users/driver/Documents/R/win-library/3.6/BH/include/boost/random/exponential_distribution.hpp:27,
>                  from C:/Users/driver/Documents/R/win-library/3.6/BH/include/boost/random/gamma_distribution.hpp:25,
>                  from C:/Users/driver/Documents/R/win-library/3.6/StanHeaders/include/stan/math/prim/mat/prob/dirichlet_rng.hpp:5,
>                  from C:/Users/driver/Documents/R/win-library/3.6/StanHeaders/include/stan/math/prim/mat.hpp:292,
>                  from C:/Users/driver/Documents/R/win-library/3.6/StanHeaders/include/stan/math/rev/mat.hpp:12,
>                  from C:/Users/driver/Documents/R/win-library/3.6/StanHeaders/include/stan/math.hpp

```
s<-'
functions{  
  int[] vecequals(int[] a, int test){ //do indices of a match test condition?
    int check[size(a)];
    for(i in 1:size(check)){
      check[i] = (test==a[i]) ? 1 : 0;
    }
    return(check);
  }
  
  int[] whichequals(int[] b, int test, int not){  //return array of indices of b matching test condition
    int bsize = size(b);
    int check[bsize] = vecequals(b,test);
    int whichsize = sum(check);
    int which[whichsize];
    int counter = 1;
    for(i in 1:bsize){
      if(check[i] == not){
        which[counter] = i;
        counter += 1;
      }
    }
    return(which);
  }

}'

sm <- stan_model(model_code = s)
```

#### Current Version:
v2.20.0

**Comment by rok-cesnovar** [comment]
stanc3 error message:

```
Semantic error in 'examples/bugs/test_model.stan', line 10, column 43 to column 46:
   -------------------------------------------------
     8:    }
     9:    
    10:    int[] whichequals(int[] b, int test, int not){  //return array of indices of b matching test condition
                                                    ^
    11:      int bsize = size(b);
    12:      int check[bsize] = vecequals(b,test);
   -------------------------------------------------

Identifier 'not' clashes with reserved keyword.
```
Closing.
