### ISSUE TITLE
Const Logic Wrong in ESS Calc

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#2820]
#### Description:

The recent update to the effective sample size code included logic to return NaNs when all of the draws across all of the chains were equal to the same constant value.  The implementation of that logic incorrectly implies that all single chains are constant with NaN effective sample sizes.

#### Reproducible Steps:

Compute effective sample size from a single chain.

#### Current Output:

`nan`

#### Expected Output:

Not `nan`

#### Current Version:

develop

**Comment by roualdes** [comment]
The same logic is used in [compute_potential_scale_reduction.hpp](https://github.com/stan-dev/stan/blob/develop/src/stan/analyze/mcmc/compute_potential_scale_reduction.hpp).  Should I file a new issue to get that logic cleaned up too?

**Comment by betanalpha** [comment]
Yes, please!
