### ISSUE TITLE
Const Logic Wrong in Rhat Calc

### ISSUE THREAD

**Issue by roualdes** [stan-dev/stan#2824]
#### Summary: 

const logic in Rhat in [compute_potential_scale_reduction.hpp](https://github.com/stan-dev/stan/blob/6e7d8cb71b0f31a34a34fe34412d329397967fd5/src/stan/analyze/mcmc/compute_potential_scale_reduction.hpp) is wrong.

#### Description:

The recent update to the Rhat code included logic to return NaNs when all of the draws across all of the chains were equal to the same constant value. The implementation of that logic incorrectly implies that all single chains are constant.  This follows in similar spirit to issue https://github.com/stan-dev/stan/issues/2820, which was fixed in PR https://github.com/stan-dev/stan/pull/2822.

#### Reproducible Steps:

Compute Rhat from a single chain.

#### Current Output:

`nan`

#### Expected Output:

Not `nan`

#### Current Version:
develop

**Comment by mcol** [comment]
Ths was fixed by #2830.
