### ISSUE TITLE
Integration tests are crashing Ubuntu 18.04

### ISSUE THREAD

**Issue by serban-nicusor-toptal** [stan-dev/stan#2844]
#### Summary:
Integration tests are crashing the machine on Ubuntu 18.04

#### Description:
After a clean clone of the repository and the proper setup, when running the integration tests it gets to a point where it simply gets the machine stuck for good. ( can't stop the tests or do anything on it )

#### Reproducible Steps:
```
git clone https://github.com/stan-dev/stan.git
cd stan

make math-revert
make clean-all
git clean -xffd

echo "CXX=g++ -Werror" > make/local

./runTests.py -j16 src/test/integration
```
#### Current Output:
Right after this is printed to the console the machine gets stuck.
```
g++ -Werror  -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare     -I lib/stan_math/lib/tbb_2019_U8/include -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.69.0 -I lib/stan_math/lib/sundials_4.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1 -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1      -DBOOST_DISABLE_ASSERTS        -c -o /dev/null -include test/test-models/good/function-signatures/distributions/univariate/continuous/exp_mod_normal/exp_mod_normal_log_1.hpp test/test-model-main.cpp
```

For the complete log please see: [Jenkins log](https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/PR-2761/16/pipeline/135)

#### Expected Output:
Tests should either fail or complete but in no way they should terminate a machine.

#### Additional Information:
```
+ printenv
PARALLEL=16
SHELL=/bin/bash
N_TESTS=350
OPENCL_DEVICE_ID=1
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/TeX/texbin:/usr/local/bin:/Library/TeX/texbin
LANG=C.UTF-8
CXX=/usr/local/opt/llvm@6/bin/clang++
SHLVL=3
HOME=/Users/jenkins
GCC=g++
JAVA_ARCH=x86_64
MPICXX=mpicxx
```

#### Current Version:
v2.21.0

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal is this one still an issue? I am almost sure its not, but not completely.

**Comment by serban-nicusor-toptal** [comment]
I've just [tested](https://jenkins.mc-stan.org/job/TEST/82/) and it's working properly.
