### ISSUE TITLE
Extend gaussian_dlm_obs to allow time-varying system matrices

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/stan#2854]
#### Summary:
Feature Request. Currently gaussian_dlm_obs allows only time-invariant system matrices. This is only a special case of the more general dynamic linear model.

#### Description:
The general dynamic linear model allows the system matrices F, G, V, and W to vary over time. This is useful in certain implementations of (quasi)periodicity, in handling missing observations, in dealing with time steps where it is known that something unusual happened, in implementing long-tailed distributions for the disturbances, etc. Stan should have a version of gaussian_dlm_obs that can handle such time-varying system matrices.

**Comment by mcol** [comment]
Already posted as https://github.com/stan-dev/math/issues/1466, which is the correct repository for this.
