### ISSUE TITLE
How to configure stamath in vs2017？

### ISSUE THREAD

**Issue by caofeng19950925** [stan-dev/stan#2859]
#### Summary:
Please provide a short couple sentence summary.
How to configure stamath in Vs2017？

#### Description:
Sorry, I'm a beginner, but recently encountered a program designed to stanmath, and I haven't touched it before, so I encountered big trouble when configuring Vs2017.
I would like to ask how to configure the stanmath on Vs2017.

**Comment by mitzimorris** [comment]
hello,  please ask your question on the Stan Forums on discourse https://discourse.mc-stan.org 
or consult the Stan math wiki page: https://github.com/stan-dev/math/wiki

this is not an actionable issue.
