### ISSUE TITLE
Compilation error computing stan

### ISSUE THREAD

**Issue by LucaBenazzoli** [stan-dev/stan#2884]
#### Summary:
I have used Rstan on Rstudio with my Windows 10 after a week. After some update of packages, i tried to run my previous model (that didn't have any problem) and now it gives me a problem in the compilation Error. I tried everything, also uninstalling everything of R, Rstudio, but it was useless

#### Current Output: That's the error it returns
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! g++.exe: error: base/Documents/R/win-library/3.6/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp: No such file or directory
g++.exe: error: base/Documents/R/win-library/3.6/StanHeaders/include: No such file or directory
g++.exe: error: base/Documents/R/win-library/3.6/RcppEigen/include: No such file or directory
make: *** [C:/PROGRA~1/R/R-36~1.2/etc/x64/Makeconf:215: file480c619142e6.o] Error 1

#### Expected Output:
It hadn't had any error before, everything was fine.

#### Current Version:
v2.22.0

**Comment by mcol** [comment]
Do you have the `StanHeaders` and `RcppEigen` packages installed? If so, could you try reinstalling them and see if it helps. In any case I'm closing as you should post support questions to https://discourse.mc-stan.org/.
