### ISSUE TITLE
Error massages 

### ISSUE THREAD

**Issue by melagha** [stan-dev/stan#2892]
#### Summary:
Error messages when running stan examples. 

#### Description:
Hello,
I am using MacBook  Pro with 8 GB memory. 
I am new to stan and started learning using the materials provided on your website. I keep receiving error messages and the runs as follows from running  "fxaInhibitAvg" example.

" error occurred during calling the sampler; sampling not done"

here are whatever error messages were returned
[[1]]
Stan model 'fxaInhibitAvg' does not contain samples.
[[2]]
Stan model 'fxaInhibitAvg' does not contain samples.
[[3]]
Stan model 'fxaInhibitAvg' does not contain samples.
   

Best regards.

**Comment by mcol** [comment]
I suggest asking this on https://discourse.mc-stan.org/, where in general you'll get pretty quick support. This is not the correct venue, so I'm closing.
