### ISSUE TITLE
test good_vec_constraints is not being run.

### ISSUE THREAD

**Issue by peterwicksstringfield** [stan-dev/stan#2895]
#### Summary:
One of the tests is left out of the testing process.

#### Description:
Looks like
src/test/test-models/bad/lang/good_vec_constraints.stan
isn't being run. I see this code:
```
TEST(lang_parser, good_trunc) {
  EXPECT_TRUE(is_parsable("src/test/test-models/bad/lang/good_trunc.stan"));
}

TEST(lang_parser, good_vec_constraints) {
  EXPECT_TRUE(is_parsable("src/test/test-models/bad/lang/good_trunc.stan"));
}
```
in
src/test/unit/lang/parser/other_test.cpp
.

#### Reproducible Steps:
Break the test and watch
./runTests.py src/test/unit/lang/parser/other_test.cpp
pass.

#### Current Output:
Test is not run and can be broken.

#### Expected Output:
Test is run and breaking it breaks CI.

#### Additional Information:
None.

#### Current Version:
v2.22.0

**Comment by rok-cesnovar** [comment]
`/lang` tests were removed as stanc2 is no longer in this repo so we can close this.
