### ISSUE TITLE
Follow up of issue #826/not yet implemented in rStan

### ISSUE THREAD

**Issue by ForeverK87** [stan-dev/stan#2903]
I am writing regarding the issue #826 that till then it was not yet implemented in rStan. What I would like to do is run a Stan model and use its estimates taken by get_inits function. Then I would like to use these estimates in a second Stan model as initial values but I also need the model to resume from where it was. So far I have not found a way to do so. Has it already been implemented or is there another way to do so? 
Thank you!

**Comment by mitzimorris** [comment]
per discussion in #826, follow-up issue #1706, you can specifiy both the initial metric and the step size.  however, the state of the RNG will not be known, so it depents on what you mean by

>  I also need the model to resume from where it was.

**Comment by ForeverK87** [comment]
> per discussion in #826, follow-up issue #1706, you can specifiy both the initial metric and the step size. however, the state of the RNG will not be known, so it depends on what you mean by
> 
> > I also need the model to resume from where it was.

So I basically want to do what the update function does for JAGS. I have a model fitted twice. The second time I use the estimates from the previous model as initial values. But I want the sampling in my second run to continue from where the first run stopped. Does this make sense?

**Comment by mitzimorris** [comment]
in CmdStan, you must specify the following args:
```
sample num_warmup=0 num_samples=<your desired sample size> adapt engaged=0 algorithm=hmc metric_file=<your saved metric> stepsize=<your saved stepsize>
```

the values for the stepsize and metic come from the csv files, e.g., this is from the CmdStan guide explanation of the output from the example model which has exactly one parameter `theta`, and therefore a  1x1 inverse mass matrix, diagonal is a vector of length 1:

```
# Adaptation terminated
# Step size = 1.81311
 # Diagonal elements of inverse mass matrix:
 # 0.415719
```

this will let you run another chain using the specified stepsize and metric.

**Comment by mitzimorris** [comment]
closing this - this is a documentation, not an implementation issue - https://github.com/stan-dev/docs/issues/95
