### ISSUE TITLE
Expose functions suite for hmm

### ISSUE THREAD

**Issue by charlesm93** [stan-dev/stan#2919]
#### Summary:
This complements issues stan-dev/math#1648 and stan-dev/math#1846. Expose the signature for the following three functions:

* `hmm_marginal_lpdf()`
* `hmm_latent_marginal_prob()`
* `hmm_latent_rng()`

#### Current Version:
v2.23.0

**Comment by SteveBronder** [comment]
I think this needs to be in stanc3?

**Comment by charlesm93** [comment]
I raised the question on the forum: https://discourse.mc-stan.org/t/exposing-functions-stan-or-stanc3/15074

**Comment by wds15** [comment]
I don’t think there is a question. New Stan language stuff is a stanc3 matter.
