### ISSUE TITLE
for loop over vector slice causes error in windows with pystan

### ISSUE THREAD

**Issue by chvandorp** [stan-dev/stan#2920]
#### Summary:
When I iterate over a vector slice, the Stan program and python script exits without any warning

#### Description:
This problem happens only on Windows, not on Linux. When I use a for loop over a slice of a vector:
```stan
// parameters
vector[10] x;
// model
for ( xi in x[:] ) { /* do something with xi */ }
```
the stan model stops without any warning and the python script from which I run the model also exits. I don't have any problems with for loops over vectors `for ( xi in x ) { /* ... */ }`.

#### Reproducible Steps:
The following script should demonstrate the problem

```python
## stan-slice-bug.py
import pystan

stan_model = """
parameters {
    vector[10] x;
    vector[10] y;
}
model {
    // This works fine
    for ( xi in x ) {
        xi ~ normal(0,1);
    }
    
    // Runtime error
    for ( yi in y[:] ) {
        yi ~ normal(0,1);
    }
}
"""

## model compiles correctly
sm = pystan.StanModel(model_code=stan_model)

print("start sampling...")

## using multiple chains causes the script to "hang" indefinately
sam = sm.sampling(chains=1)

## this will not be printed
print("sampling complete!")
```

#### Current Output:
When I run the script from a Anaconda environment, I get the following output:

```
(stan_env) PS C:\Users\chris> python .\stan-slice-bug.py
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_27c062035bd8b9f475a8223ee848653d NOW.
start sampling...

Gradient evaluation took 0 seconds
1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
(stan_env) PS C:\Users\chris>
```

#### Expected Output:
Note that `sampling complete!` is never printed to the screen.

#### Additional Information:
I'm using pystan version 2.19.1.1 python version 3.7.7. I installed pystan on windows 10 using these instructions: https://pystan.readthedocs.io/en/latest/windows.html

**Comment by bob-carpenter** [comment]
Thanks for reporting with a clean reproducibl example, @chvandorp.  And sorry about the bug!

I verified that this is

1.  broken in the current release of RStan, and
2. fixed on the current develop branch of CmStan.  

So I'm going to close this issue.  The fix should percolate to the interfaces when they catch up with develop.
