### ISSUE TITLE
Unexpected integer overflow for index variables

### ISSUE THREAD

**Issue by adwasser** [stan-dev/stan#2923]
#### Summary:

Integers derived from index variables can have unexpected overflow properties.

#### Description:

Index variables (e.g., `i` in the statement `for (i in 1:N) print(i);`) should be integer types (according to the [docs](https://mc-stan.org/docs/2_23/reference-manual/for-loops.html), and thus I would expect that they follow normal [overflow rules](https://mc-stan.org/docs/2_23/reference-manual/numerical-data-types.html).

However, computing `-i` in the body of the loop for the case i = 1 seems to overflow to 18446744073709551615 (or 2^64 - 1).

#### Reproducible Steps:

Example stan code:

```stan
data {}

transformed data {
  
  int N = 3;
    
  for (i in 1:N) {
    
    print("i        = ", i);
    print("-i       = ", -i);
    print("-1 * i   = ", -1 * i);
    print("-(i + 0) = ", -(i + 0));

    int j = i;
    print("j        = ", j);
    print("-j       = ", -j);
    print("-1 * j   = ", -1 * j);
    print("-(j + 0) = ", -(j + 0));
  }
}

model {}
```

#### Current Output:

```
method = diagnose
  diagnose
    test = gradient (Default)
      gradient
        epsilon = 9.9999999999999995e-07 (Default)
        error = 9.9999999999999995e-07 (Default)
id = 0 (Default)
data
  file =  (Default)
init = 2 (Default)
random
  seed = 822442927 (Default)
output
  file = output.csv (Default)
  diagnostic_file =  (Default)
  refresh = 100 (Default)

i        = 1
-i       = 18446744073709551615
-1 * i   = 18446744073709551615
-(i + 0) = 18446744073709551615
j        = 1
-j       = -1
-1 * j   = -1
-(j + 0) = -1
i        = 2
-i       = 18446744073709551614
-1 * i   = 18446744073709551614
-(i + 0) = 18446744073709551614
j        = 2
-j       = -2
-1 * j   = -2
-(j + 0) = -2
i        = 3
-i       = 18446744073709551613
-1 * i   = 18446744073709551613
-(i + 0) = 18446744073709551613
j        = 3
-j       = -3
-1 * j   = -3
-(j + 0) = -3
TEST GRADIENT MODE

 Log probability=0

 param idx           value           model     finite diff           error

```

#### Expected Output:

I'm pretty sure that `-i` should evaluate to a negative integer.

#### Additional Information:

If it's not a bug, I'm happy to figure out how to modify the docs to specify this behavior.  There's an easy work around (shown in the code example), as one just has to cast `i` to an explicitly declared `int` variable before proceeding.

#### Current Version:

CmdStan commit `309601f91c0d94ac8d6ef218f24ef44b5f4e4b38`
Stan commit `6f500ebc6915570d16086b1cb2912b85d8f1a2b7`

v2.23.0

**Comment by wds15** [comment]
This just got fixed on the stanc3 repo. Can u have a look at the bug of ternary if ticket there? If that’s a duplicate, we can close this. Thanks.

**Comment by wds15** [comment]
Here is the link to the issue: https://github.com/stan-dev/stanc3/issues/536

The bug reported there is tickled by exactly this overflow issue as you noticed.

**Comment by rok-cesnovar** [comment]
The fix was merged.

**Comment by adwasser** [comment]
That worked!  Thanks for the quick response!
