### ISSUE TITLE
service generate_quantities can't handle vector[1] 

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2930]
#### Summary:

Generate_quantities method throws error if model has container variable with column of length 1.

discussion here:
https://discourse.mc-stan.org/t/generated-quantiles-sampler-in-r-with-parameter-vector-of-length-1/16134/4

#### Description:
investigate problem with param parsing and for all container objects.

#### Reproducible Steps:

Model to fit parameter given data:
```
transformed data {
  int N = 5;
  int K = 1;
  int<lower=0,upper=1> y[5] = {1, 1, 1, 1, 0}; 
  matrix[5,1] X = [[1], [1], [1], [1], [1]];
}
parameters {
  vector[K] b;
}
generated quantities {
    vector[N] y_est = rep_vector(0,N);
    {
      y_est = X*b;
    }
}
```
Model with corresponding generated quantities block:
```
transformed data {
  int N = 5;
  int K = 1;
  int<lower=0,upper=1> y[5] = {1, 1, 1, 1, 0}; 
  matrix[5,1] X = [[1], [1], [1], [1], [1]];
}
parameters {
  vector[K] b;
}
model {
  y ~ bernoulli_logit(X*b);
}
```

1. compile, run first model with arg `method=sample output file=fitted_params.csv`

2. compile, run second model with args `method=generate_quantities fitted_params=fitted_params.csv`

should succeed, currently fails because vector of length 1 messes up generate_quantities logic.

#### Current Output:
Error message from step 2:  
`Mismatch between model and fitted_parameters csv file "stan/src/test/test-models/good/services/bug_2390_fitted_params.csv"`

#### Expected Output:
This should run and produce valid Stan csv output file with columns for `y_est`.

#### Current Version:
v2.23.0

**Comment by lrossouw** [comment]
There is a test case on the forum link in @mitzimorris description.
