### ISSUE TITLE
Should log_prob_grad be recovering memory?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stan#2936]
#### Summary:

For [`log_prob_grad`](https://github.com/stan-dev/stan/blob/develop/src/stan/model/log_prob_grad.hpp#L70) should we be recovering memory both when the function exits and when the function leaves normally? Right now it's only recovering memory when there's an exception

#### Description:

This

```cpp
template <bool propto, bool jacobian_adjust_transform, class M>
double log_prob_grad(const M& model, Eigen::VectorXd& params_r,
                     Eigen::VectorXd& gradient, std::ostream* msgs = 0) {
  using stan::math::var;
  using std::vector;

  Eigen::Matrix<var, Eigen::Dynamic, 1> ad_params_r(params_r.size());
  for (size_t i = 0; i < model.num_params_r(); ++i) {
    stan::math::var var_i(params_r[i]);
    ad_params_r[i] = var_i;
  }
  try {
    var adLogProb = model.template log_prob<propto, jacobian_adjust_transform>(
        ad_params_r, msgs);
    double val = adLogProb.val();
    stan::math::grad(adLogProb, ad_params_r, gradient);
    return val;
  } catch (std::exception& ex) {
    stan::math::recover_memory();
    throw;
  }
}
```

Should be

```cpp
template <bool propto, bool jacobian_adjust_transform, class M>
double log_prob_grad(const M& model, Eigen::VectorXd& params_r,
                     Eigen::VectorXd& gradient, std::ostream* msgs = 0) {
  using stan::math::var;
  using std::vector;

  Eigen::Matrix<var, Eigen::Dynamic, 1> ad_params_r(params_r.size());
  for (size_t i = 0; i < model.num_params_r(); ++i) {
    stan::math::var var_i(params_r[i]);
    ad_params_r[i] = var_i;
  }
  try {
    var adLogProb = model.template log_prob<propto, jacobian_adjust_transform>(
        ad_params_r, msgs);
    double val = adLogProb.val();
    stan::math::grad(adLogProb, ad_params_r, gradient);
    return val;
  } catch (std::exception& ex) {
    stan::math::recover_memory();
    throw;
  }
  stan::math::recover_memory()
}
```

#### Current Version:
v2.23.0

**Comment by wds15** [comment]
Recovery of memory should be just before the return inside the try block. Even better would be to return Val after the try block to avoid try blocks being recursively being nested.

**Comment by bob-carpenter** [comment]
Yes!  Good catch.  

The catch clause should also be just `catch (...)` to catch arbitrary exceptions.  We want to clean up memory no matter how we throw.

 I miss the `finally` construction from Java, which was basically just using

```
try A finally B;
```

as syntactic sugar for

```
try A
catch (...)
  B;
  throw ...;
}
B;
```

**Comment by wds15** [comment]
If we use the nested approach based on RAII, then we don't need to bother with the exception stuff any more. We should search the entire stan repo for this pattern and replace it with the nested_rev approach which takes care of all of this.

**Comment by SteveBronder** [comment]
Is there noticeable overhead to having everything be nested? Or should we make a little class that handles the memory recovery for us like nested has?

Either way I'll submit a PR today to add recover memory here

**Comment by wds15** [comment]
I don’t think nested is an issue performance wise.

**Comment by SteveBronder** [comment]
For now I just added the recover_memory but we can benchmark nested to make sure it's fine here

**Comment by bbbales2** [comment]
> but we can benchmark nested to make sure it's fine here

Ooops, was that pull waiting on another test? It looked finished over there.
