### ISSUE TITLE
Stan and Cmdstan 2.24 release

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stan#2941]
The next release of Stan and Cmdstan (2.24) is nearing. The feature freeze will happen on the 20th of July (anywhere on earth) with the actual release planned for the 27th (if no major bugs are discovered during the freeze period). 

During the feature freeze, we should only merge bugfix PRs. Use this issue thread for discussing everything related to the release of Stan and Cmdstan (this issue is for both to consolidate the discussion).

Stan release notes: 

```
- `std::chrono` is now used for all timing purposes
- fixed a bug with generated quantities for vectors of length 1
- added `recover_memory` for normal exit of `log_prob_grad`
- replaced the use of `boost::` functions/metaprograms in favor of `std::` where applicable
```

**Comment by mitzimorris** [comment]
I'm struggling with the CmdStan makefile right now - testing changes to `stansummary` is slow because of the makefile requires a full rebuild of all the libraries - https://github.com/stan-dev/cmdstan/issues/904  - is this a makefile bug?

**Comment by rok-cesnovar** [comment]
I can not replicate this on Ubuntu, so it must be a Mac issue. You can try changing the build rule to:
`$(LINK.cpp) -fvisibility=hidden $^ $(BOOST_PROGRAM_OPTIONS_LIB) $(LDLIBS) $(OUTPUT_OPTION)`
but I have no idea if that would work.

**Comment by mitzimorris** [comment]
found and fixed problem with CmdStan file `make/command` - added as part of PR https://github.com/stan-dev/cmdstan/pull/907, which needs a re-review, ideally from Stevo, but he might be working on RStan/Windows emergency, in which case  @rok-cesnovar, if you have free cycles you're welcome to review.

**Comment by mitzimorris** [comment]
for CmdStan, the remaining tasks are to build out unfinished corners of new User's Guide - standalone QG section needs more, and then change stansummary section to match above-mentioned changes.
for documentation, https://github.com/stan-dev/cmdstan/pull/908 needs to be approved.

**Comment by bbbales2** [comment]
We should bump the version number on stanc2 in this repo:

```
:~/tmp/cmdstan-2.24.0-rc1$ bin/stanc2 --version
stanc version 2.23.0
```

**Comment by rok-cesnovar** [comment]
@bbbales2 at release time, Nic updates these version numbers. Maybe we should update them for RCs also next time.

This post is a last call for reporting any bugs/issues with the 2.24 release candidate. If nothing new arises, the release will happen at the end of the day today.
