### ISSUE TITLE
out-of-bounds vector access in constructor

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/stan#2948]
The Stan code ``data {int N;} parameters {real y;} model {y ~ normal(0,1);}`` generates an hpp file with the following lines in the constructor:

```
    try {
      
      pos__ = 1;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      
      current_statement__ = 3;
      N = context__.vals_i("N")[(1 - 1)];
    } ...
```
If the var_context (``context__``) is empty, the line `context__.vals_i("N")[(1 - 1)];` will segfault because `operator[]` does not do any checking. One needs to use `std::vector::at()` to raise an exception, so `context__.vals_i("N").at((1 - 1))`.

I believe this is what is causing a segfault in pystan 3, see https://github.com/stan-dev/pystan-next/issues/137

**Comment by rok-cesnovar** [comment]
@ariddell PR open: https://github.com/stan-dev/stan/pull/2949

If you want this urgently, please review or find someone to review.
