### ISSUE TITLE
Simulated states from hidden Markov model should be sampled from {1, 2,...,N} (rather than 0,1,2,...,N-1)

### ISSUE THREAD

**Issue by vianeylb** [stan-dev/stan#2957]
#### Summary + Description:

For the new hidden Markov model functionality, hmm_latent_rng() uses the foward-filtering backward-sampling algorithm to simulate from the joint posterior distribution of the underlying state process, implemented in the generated quantities block below. Given an N-state HMM, the underlying states should be drawn from {1, 2, ..., N} at each point in time, rather than {0, 1, ..., N-1} as is implemented now. This facilitates using the states as indices when generating draws from the posterior predictive distribution of the observations. 

#### Reproducible Steps:

Stan code for an HMM using the functionality in CmdStan. 

data {
  int<lower = 0> N;  // number of states
  int<lower = 1> T;  // number of observations
  real y[T];
}

parameters {
  simplex[N] theta[N];  // N x N tp
  ordered[N] mu;  // state-dependent parameters
  vector<lower=0>[N] sigma;
  simplex[N] init_dist;
}

transformed parameters {
  
  matrix[N, T] log_omega;
  matrix[N, N] Gamma;

  // build log_omega
  for (t in 1:T)
    for (n in 1:N) log_omega[n, t] = normal_lpdf(y[t] | mu[n], sigma[n]);

  // build Gamma
  for (n in 1:N) Gamma[n, ] = theta[n]';

}

model {
  
  // priors
  mu ~ normal(2, 3);
  sigma ~ normal(0.5, 1);  
  
  target += hmm_marginal(log_omega, Gamma, init_dist);
  
}

generated quantities{

  matrix[N, T] states_prob = hmm_hidden_state_prob(log_omega, Gamma, init_dist);
  int states_pred[T] = hmm_latent_rng(log_omega, Gamma, init_dist);

   vector[T] y_pred;
   for (i in 1:T)
     y_pred[i] = normal_rng(mu[states_pred[i] + 1], sigma[states_pred[i] + 1]);

}

#### Current Output:

Currently, my defined states_pred object in generated quantities stores a sequence of underlying states that *could* include 0. For instance, for a 3-state HMM, we could have the underlying posterior draw: 

states_pred = c(0, 0, 1, 1, 2, 0, 1, 2) 

However, this means that I need to add a 1 if I would like to use the predicted states as indices, as shown below: 
`for (i in 1:T)
     y_pred[i] = normal_rng(mu[states_pred[i] + 1], sigma[states_pred[i] + 1]);`

#### Desired Output:

It would be great to not have to add a 1, so rather than the code above, I could write: 

`for (i in 1:T)
     y_pred[i] = normal_rng(mu[states_pred[i] ], sigma[states_pred[i]]);`

#### Current Version:
v2.24.0

**Comment by bob-carpenter** [comment]
Thanks for reporting.  I marked it as a bug and assigned @charlesm93 who wrote most of the code.  Should be easy to fix for the next release.  We should also make sure the documentation matches.

**Comment by charlesm93** [comment]
Posting this issue under stan-dev/math#2112.

**Comment by rok-cesnovar** [comment]
Closed by https://github.com/stan-dev/math/pull/2113
