### ISSUE TITLE
Jenkins builds are stuck? 

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stan#2971]
https://jenkins.mc-stan.org/ 

I'm seeing a bunch, including the develop build and some from #2970 as having been executing for the past 10 hours, which I think means something is off. Tagging @serban-nicusor-toptal in case he knows what's up.

**Comment by serban-nicusor-toptal** [comment]
Hey, they're not stuck but rather in a long queue for gelman-mac.

**Comment by seantalts** [comment]
Are you sure? For example, this started 12 hours ago and is taking up an executor on a Linux box (because it claims it's running linux integration tests, I think): https://jenkins.mc-stan.org/job/Stan/job/develop/704/

**Comment by seantalts** [comment]
Oh yeah, in the blue ocean build you can see that this build hasn't actually spent that long executing. Something seems a little off though, this is a lot of backlog. Was something stuck on the Mac?

**Comment by rok-cesnovar** [comment]
We had issues with the integration tests on Linux running out of tests and there were a lot of math PRs waiting on tests (like 7-8) which created a huge backlog after we restarted them.

**Comment by rok-cesnovar** [comment]
Mac is a bottleneck because we now also run Stan integration tests on PRs and we only have a single Mac agent. Maybe we should only run those on merges. Its an unlikely scenario where Linux integration tests pass and Mac integration tests do not. And unlikely scenarios can be covered by merge tests I guess.

**Comment by serban-nicusor-toptal** [comment]
For now I think we're fine, usually the queue is not this big but before the weekend we had some job failures in Stan and downstream Stan tests. I've restarted quite a lot of jobs across the projects and that spiked the queue to ~40, they're all waiting now for gelman-mac. It will take a bit longer but it should soon clear out.
