### ISSUE TITLE
how to replace inf or Na with 0 under rstan generated quantities?

### ISSUE THREAD

**Issue by FarhaU** [stan-dev/stan#2980]
#### Summary:
I got Inf or Na in my mean summary result from rstan output (see screenshot).

#### Description:
What code to write under rstan block generated quantities to replace Inf or Na with 0 in the iteration samples of parameters?

#### Reproducible Steps:
I have used the following code and the output is attached.
generated quantities{
for (i in 1:19) {
u[i]=beta_rng(p,q);
yff[i]=muf[i]*(tgamma(p)*tgamma(q)/((tgamma(p+1/a)*tgamma(q-1/a))))*(u[i]/(1-u[i]))^(1/a);
}
}

![Capture1 output](https://user-images.githubusercontent.com/52852623/100447338-81aa8b80-3104-11eb-8340-8f024b900718.PNG)

#### Expected Output:
I want to use the following code under the rstan generated quantities block with above code so it give mean value after replace Inf or Na with 0 in iteration posterior samples:
yf[i]=yff[i.[which(!is.na(yff[i]))]
yf1[i][which(yf[i] < Inf)]
 
PLease help and let me know any concerns for more details.

**Comment by FarhaU** [comment]
No one available to resolve

**Comment by rok-cesnovar** [comment]
Hi, this type of question is more suited for the Stan Forums. I believe you already posted a question there: https://discourse.mc-stan.org/t/replace-inf-with-0-under-generated-quantities-block-rstan/19530 and have a suggested solution.
