### ISSUE TITLE
Move remaining tests on Travis CI to Github Actions

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stan#2982]
#### Summary:

Travis CI recently changed their free tiers a bit: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

I am not sure if the /stan repo can hit the limits here, but I would still think we want to move the remaining few tests to Github Actions. GA is native to Github and both Math & Cmdstan use it, so it makes it easier for developers with fewer different CI types.

The tests are on linux using clang++ 6. Just the following suffices:
`./runTests.py src/test/unit`

That is it.

@serban-nicusor-toptal do you want to handle this one? This is not urgent in any way. 

#### Current Version:
v2.24.0

**Comment by storopoli** [comment]
@rok-cesnovar I can help with GitHub Actions. I've done some projects using GitHub Actions and also I hosted a webinar at my university teaching students on how to use it. I need some information:

1. When will the tests run? Every commit on `develop` branch? Every `pull request`? I can also set a cron job for once every X days/week etc.
2. What kind of machine will it be run? I can use a docker image and `sudo apt-get install` the clang++ 7 and python3 (or 2?) to run the `./runTests.py src/test/unit`

PS: regarding the limits. GitHub Actions is "limitless" for public repositories. We can how many jobs we want (a job must have a maximum of 6h running time) and an action (`.yml` file) must have a maximum of 72h runtime.

**Comment by serban-nicusor-toptal** [comment]
Hey I must have not gotten a notification for this, right now I'm working on some Github Actions for cmdstanpy so I can take this one too.

**Comment by storopoli** [comment]
@serban-nicusor-toptal let me know if you need any help

**Comment by serban-nicusor-toptal** [comment]
Sure will do, thanks @storopoli !

**Comment by rok-cesnovar** [comment]
Thanks to both!

> When will the tests run? Every commit on develop branch? Every pull request? I can also set a cron job for once every X days/week etc.

Every pull request or push (both to either develop or master).

Prior to the tests, it should install clang++-6.0, set "CXX=clang++-6.0" and run `runTests.py src/test/unit` . Not sure how much time these take, but I think it should not be more than an hour.

> What kind of machine will it be run? 

Using ubuntu-latest should be fine (+ installing clang++-6.0).

**Comment by storopoli** [comment]
How do I configure the tests?

```bash
./runTests.py src/test/unit
make: *** No rule to make target 'test/test-models/expressions/simple_udf.hpp'.  Stop
```

**Comment by rok-cesnovar** [comment]
Make sure you have cloned the submodule as well. I think if you dont clone math that pops up.

**Comment by storopoli** [comment]
Great, I think I got it working now! 

Just one more thing. The `ubuntu-latest` GitHub machine has 2 cores, see[GitHub Documentation here](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners):

---
Hardware specification for Windows and Linux virtual machines:

2-core CPU
7 GB of RAM memory
14 GB of SSD disk space
---


You want `-j 2`?

**Comment by rok-cesnovar** [comment]
Yeah, though 7GB of RAM for 2 processes is on the limit.
