### ISSUE TITLE
Starting a Wiki page for Stan's Google Summer of Code proposals

### ISSUE THREAD

**Issue by stablemarkets** [stan-dev/stan#2998]
Hi. I'm on Stan's governing body and currently working to submit a proposal for Stan to participate in Google Summer of Code (GSoC) under the NumFOCUS umbrella.

NumFOCUS expects us to host our proposal as a Wiki page so that they can link to it here: https://github.com/numfocus/gsoc/blob/master/2021/ideas-list.md 

I thought I'd start an issue and just check if there is some process for starting such a Wiki page here.

**Comment by syclik** [comment]
No process for starting a wiki page. Do you have permissions? If not,
someone can get them to you.

**Comment by stablemarkets** [comment]
I don't believe I have the necessary permissions, so that would be great!

**Comment by SteveBronder** [comment]
If it's too annoying / not allowed then totally fine to have as a wiki page, but this might sit nicer under a projects folder in the [`design-docs`](https://github.com/stan-dev/design-docs) repo. I find that we tend to throw stuff up on the wiki, then it gets stale, people forget where to find it, etc. etc.

But if it's just a one shot thing then I think it's fine

**Comment by stablemarkets** [comment]
That should be fine! I doubt NumFOCUS would mind as long as they can link to it. Do I need any special permissions to add an .md file in the designs folder? I read the usual PR procedure, but it probably doesn't apply in this setting since it's not really a design doc?

**Comment by syclik** [comment]
@stablemarkets, you should have a GitHub notification about having permissions on this repo.

**Comment by stablemarkets** [comment]
Thanks @syclik! I accepted the invite to stan-dev/stan. To do what @SteveBronder suggested do I also need permission for stan-dev/design-docs ?

**Comment by stablemarkets** [comment]
Closing this issue. As I've started working on [design-docs](https://github.com/stan-dev/design-docs) as suggested. Thanks so much for the suggestions and help!
