### ISSUE TITLE
[FR] add bool template parameter to *_constrains in

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stan#3005]
#### Summary:

In the Stan compiler stuff can be written like

```cpp
      local_scalar_t__ sd_1 = in__.scalar();
      current_statement__ = 5;
      if (jacobian__) {
        current_statement__ = 5;
        sd_1 = stan::math::lb_constrain(sd_1, 0, lp__);
      } else {
        current_statement__ = 5;
        sd_1 = stan::math::lb_constrain(sd_1, 0);
      }
```

But `jacobian__` is known at compile time so we can have a `reader.*_lb_constrain<>(...)` that takes in a bool template parameter so the above can just become 

```cpp
      local_scalar_t__ sd_1 = in__.scalar_lb_constrain<jacobian__>(0, lp__);
```

for matrices things like that will matter a good bit

#### Current Version:
v2.26.0

**Comment by SteveBronder** [comment]
@rok-cesnovar I wrote this up over [here](https://github.com/stan-dev/stan/compare/feature/reader-constrain-template). But if you writing the `rep_array<>()` thing should these also have the same return type as the first tempalte parameter thing so you can reuse that scheme in the compiler? Haven't written tests for this yet so pretty easy for me to flip it around and do that

**Comment by rok-cesnovar** [comment]
Yes, that would be great! I am working on adding rep matrix atm , for both matrix_cl and varmat.
