### ISSUE TITLE
runTests.py fails

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [stan-dev/stan#3015]
[jw@cn05 stan]$ python3 runTests.py tests
------------------------------------------------------------
make -j1 tests
make: *** No rule to make target 'tests'.  Stop.
make -j1 tests failed
exit now (03/05/21 10:49:01 CET)
[jw@cn05 stan]$

**Comment by rok-cesnovar** [comment]
Hi, you need to run with a specific folder. For example:

`python3 runTests.py src/test/unit/model`

**Comment by LutzWeischerFujitsu** [comment]
I see. But can you give a concrete working example? I don't have a directory 'src'.

**Comment by rok-cesnovar** [comment]
Not sure I understand. This tests are meant for the Stan source code, meaning that you cllone the repository which has the src directory: https://github.com/stan-dev/stan/tree/develop/src

**Comment by SteveBronder** [comment]
```
git clone --recursive https://github.com/stan-dev/stan
cd stan
./runTests.py src/test/unit/model/indexing/rvalue_test.cpp
```

**Comment by LutzWeischerFujitsu** [comment]
Understood. :-)
