### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by adamConnerSax** [stan-dev/stan#3020]
Is this the appropriate place to post corrections/issues with the documentation?

In https://mc-stan.org/docs/2_26/stan-users-guide/coding-mrp-in-stan.html#coding-binary-groups

I think the example bits might need a "to_vector" (or something?) around the ```{epsilon, -epsilon}[sex]``` term in the vectorized model expression.  Otherwise, at least when I try, I get a compiler error about the types given to "+" when I add the scalar (real) alpha.  Adding ```to_vector``` fixes this.

**Comment by SteveBronder** [comment]
See below

https://github.com/stan-dev/docs

**Comment by adamConnerSax** [comment]
Thanks!  Will raise there.
