### ISSUE TITLE
`std_normal_lcdf` can't be used

### ISSUE THREAD

**Issue by martinmodrak** [stan-dev/stan#3038]
#### Summary:

Using `std_normal_lcdf` (and `std_normal_lccdf`) in a Stan program results in an error.

#### Description:

Stan expects the `(x | something)` syntax for `_lcdf` functions. As `std_normal` has no parameters, this seems to pose issues for the parser.

#### Reproducible Steps:

Compiling the below model:

```stan
parameters {
  real mu;
}

model {
  target += std_normal_lpdf(mu); //No problem
  target += std_normal_lcdf(mu); //Error
}

```

#### Current Output:

An error 
```
Probability functions with suffixes _lpdf, _lupdf, _lpmf, _lupmf, _lcdf and _lccdf, require a vertical bar (|) between the first two arguments.
```

#### Expected Output:

Compiles and gives the same results as if using `normal_lcdf(mu | 0, 1);`

#### Additional Information:

I am very glad you all are putting all this hard work into Stan.

#### Current Version:
v2.26.1

**Comment by rok-cesnovar** [comment]
Thanks for the report. This was reported in https://github.com/stan-dev/stanc3/issues/854 and will be addressed once https://github.com/stan-dev/stanc3/pull/863 is merged.

**Comment by martinmodrak** [comment]
Ah, my bad, didn't realize this should have been in the `stanc3` repo. Thanks!

**Comment by martinmodrak** [comment]
Should also add that actually `std_normal_lcdf(mu |)` appears to be valid code and compiles...

**Comment by rok-cesnovar** [comment]
Yeah, that is the only workaround for now. 

This was addressed separately for std_normal_lpdf() a few versions ago but not for (l)(c)cdf.
