### ISSUE TITLE
Riemannian HMC

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#304]
There are three main updates necessary for an efficient implementation of Riemannian HMC (the algorithm is currently prototyped in feature/rhmc.  @bob-carpenter and @syclik please added specific tasks under each update.

- [x] Algorithm implementation (feature/rhmc)
- [ ] #363 
- [ ] Expose higher-order autodiff, wrapping functor into user-friendly function taking in model object
- [ ] Implement higher-order autodiff for probability distributions (gaussian, Cauchy, Jacobians first)
- [ ] Speed up higher-order autodiff

**Comment by jgabry** [comment]
This issue is very old and has had no updates. Is this still the issue for tracking RHMC or has that moved elsewhere? If the latter let's close this to reduce the number of open issues.

**Comment by betanalpha** [comment]
This is still active and waiting on some refactor decisions before
being implemented in Stan.

**Comment by bhargavvader** [comment]
Is anyone working on RMHMC for Stan, at the moment? Is this project still being pursued?

**Comment by syclik** [comment]
The algorithm implementation is done! It has been for quite some time.
Michael coded it up a long time ago.

Where we need help is extending automatic differentiation to 2nd and 3rd
order for all the math functions. If you have calculus skills + some coding
experience, we'd love to get some more help.

**Comment by bhargavvader** [comment]
Is the completed code here - https://github.com/betanalpha/jamon ?
I would love to help, but don't have the time right away - I was hoping to work on RMHMC for pymc3 as part of the GSoC 2017 program, but would be glad to help with the Stan implementation soon after!

**Comment by betanalpha** [comment]
No, literally coded up in Stan, 

https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/hamiltonians/softabs_metric.hpp <https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/hamiltonians/softabs_metric.hpp>
https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/hamiltonians/softabs_point.hpp <https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/hamiltonians/softabs_point.hpp>
https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/integrators/impl_leapfrog.hpp

See also the associated tests.  We just haven’t exposed it yet due to the potential fragility of
the higher-order autodiff.
