### ISSUE TITLE
Gaussian Random walk as prior

### ISSUE THREAD

**Issue by andrybicio** [stan-dev/stan#3042]
I am not able to implement a Gaussian Random walk as prior for a vector. Every element of a vector is sampled and depends on the previous one, in such a way that the dynamics is described with a Gaussian RW.

The R code for this, would be:

```{r}
#simulate a Gaussian random walk
#N  :  number of steps
#x0 :  initial offset
#mu :  drift velocity
#variance : step size
Gauss_RandomWalk <- function(N, x0, mu, variance) {
  z <- cumsum(rnorm(n=N, mean=mu, sd=sqrt(variance)))
  t <- 1:N
  x <- (x0 + t*mu + z)
  return(x)
}
```
Which, setting as parameters (N, 0, 0, 0.035**2) would return something reasonable, like:

```{r}
[1]  0.040703269  0.009159686  0.052360030  0.059352074  0.092739218  0.098240752  0.113957813  0.064187776
[9]  0.062757728  0.063948224  0.034591074  0.004828493  0.019809969  0.032135111  0.025692763 -0.031678858
[17] -0.048033007 -0.020708105 -0.032231674  0.004917305  0.030961430  0.099054042  0.043441737 -0.010513085
```

My stan codes for doing what I mentioned above are:
```{stan}
// model to be fitted
model {
  sqrtQ ~ student_t(2, 0, 0.035);
  // here we define the random walk for the log_Rt parameter
  log_Rt[1] ~ normal(0. , 0.035);
    for (t in 2:number_days) {
        log_Rt[t] ~ normal(log_Rt[t-1], sqrtQ);
  }
  print(log_Rt);
```

or alternatively:
```{stan}
// model to be fitted
model {
  // here we define the random walk for the log_Rt parameter
  log_Rt[1] ~ normal(0. , 0.035);
    for (t in 2:number_days) {
        log_Rt[t] ~ normal(log_Rt[t-1], 0.035);
  }
  print(log_Rt);
```
The way I implemented it is taken from [this](https://github.com/juhokokkala/kalman-stan-randomwalk/blob/master/randomwalk_naive.stan). 

But the outputs are way different (there are even jumps about 80 sigmas, which statistically is impossible...)
>Chain 1: [0.382303,-0.489057,0.33374,-0.839043,1.91956,0.249953,-1.88793,1.61106,1.11189,-0.725063,-0.513174,1.79012,1.57758,0.75819,0.525524,1.44762,1.19118,0.485563,-1.48318,-1.36389,1.96355,0.321416,-0.365132,-0.644287,0.0981577,1.02943,-1.27993,-1.98085,-1.75191,-1.76489,1.60888,1.48925,-0.0452427,-0.92583,-1.21594,-0.906329,-0.700237,-0.208039,0.493656,0.490295,-1.61091,1.94587,0.758567,-1.02318,-1.92659,-0.999492,1.78042,0.214125,-0.0158054,-0.753422, .......

Any hints or suggestions?

I'm running stan in a Docker container that has RStudio in it.

#### Current Version:
v2.26.1

**Comment by SteveBronder** [comment]
https://discourse.mc-stan.org/

**Comment by bob-carpenter** [comment]
The user's guide discusses how to code random walks.  They're instances of the AR(1) model mentioned here:  https://mc-stan.org/docs/2_26/stan-users-guide/autoregressive-section.html
