### ISSUE TITLE
FR: set random seed in transformed data

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/stan#3047]
Associated with work to include synthetic data sets in posteriordb, we're thinking that it'd be good to have said data generated by cmdstan itself from a stan program with generated quantities. To ensure that all users of posteriordb obtain the same data through this process, we **_could_** simply have a fixed seed (say, 1) that the posteriordb docs guide users to supply as the `random seed=` argument to cmdstan, but it also occurs to us that there doesn't seem like there'd be any high likelihood of negative unintended consequences of cmdstan itself permitting setting the random seed in the `transformed data` block. That way there's one less source of possible error in generating the data replicably. Or have we overlooked a negative consequence to such a feature?

**Comment by mitzimorris** [comment]
not possible, given current api - this would require a rewrite of the services layer interfaces.
the random seed is passed into the model constructor and all of the calls to the services methods.
the transformed data block is transpiled into work done in the model constructor.

a system for replicated data is useful; it should be built on top of core Stan, not into it.
