### ISSUE TITLE
Write a NegativeBinomial model with zero inflated  

### ISSUE THREAD

**Issue by StromTroopers** [stan-dev/stan#3061]
Hello, first I would like to thank you for the stan dev, it is very useful for users like me. 

I'm writing this post because I am new to the stan language and I would need help in order to write a specific Stan model.

**The biological  question** 

The idea of the model is modeling the number of Bones (`NbBones` : discret continuous count) according to `Orders` (3 different discret orders) and `Time` (continuous). And then show that The `Orders 2` has a number of bones greater than the other Orders. 

**The Baysian model** 

I'm trying to write a `GLM negative binomial` model with `zero inflated` data since the mean of `NbBones` is not equal to the variance because of a huge number of zeros, and since within these zeros, I have a proportion `p` that is coming from a specific category (Bones was destroyed and then is not observable, and bones was not find because it never existed (but observable). 

So far I wrote this model such as (In Rjags) :

    model
    {
      for(i in 1 : N) 
      {
        observable[i] ~ dbern(p)
        NbBones[i] ~ dpois(nu[i] * theta[i] * observable[i])  
        theta[i] <-  intercept + Coef_Orders[Orders[i]] + Coef_Time*Time[i] 
        nu[i] ~ dgamma(1/alpha, 1/alpha)
      }
      p ~ dunif(0, 1)
      alpha ~ dunif(0, 10)
      Coef_Orders[1] <- 0
      Coef_Orders[2] ~ dexp(1)
      Coef_Orders[3] ~ dexp(1) 
      Coef_Time~ dexp(1)
      intercept ~ dexp(1)
    }

*Where in the negative binomial model with excess zeros, it is considered that only a proportion p of individuals are likely to have bones (observables). For observable individuals (p %), the number of bones follows a negative binomial distribution (allowing 0's, as an observable individual may not have any bones). Unobservable individuals (1 -p %) have a number of bones following a Poisson distribution with an expectation of 0 (so their number of bones is necessarily zero).* 

**My question** 

But I cannot manage to write it on stan, can someone help me ? (I found this package ): 

    stan_glm1 <- stan_glm(NbBones ~ Orders * Time,
                          data = data, family = neg_binomial_2,
                          prior = normal(0, 2.5),
                          prior_intercept = normal(0, 5),
                          seed = 12345)

But it does not include the zero inflated model... 

Thanks a lot for your help and time :-) 

Here are the head of the data : 

      Orders    Time NbBones
    1      1 0.21771       0
    2      1 0.08723       0
    3      1 0.03911       0
    4      1 0.08236       2
    5      1 0.08744       6
    6      1 0.00417       1

SO far I tried: 

    //Declare the data 
    data{
      int<lower=0> N;//
      real Time[N]; //
      real NbBones[N]; //
    }
    //Declare the parameters 
    parameters{
      real  theta; //continuous unconstrained variable 
      real<lower=0>observable;//constrained to not be negative 
    }
    //Model block - declare the likelihood and priors 
    model{
      //likelihood
      for(i in 1 : N){
        NbBones[i] ~poisson(theta[i] * observable[i]);
        theta[i] <-  intercept + Coef_orders[Orders[i]] + Coef_Time*Time[i];
        observable[i] ~ bernoulli(p);
      }
      //Priors 
      p ~ uniform(0, 1);
      alpha ~ uniform(0, 10);
      Coef_orders[1] <- 0;
      Coef_orders[2] ~ exponential(1);
      Coef_orders[3] ~ exponential(1) ;
      Coef_Time  ~ exponential(1);
      intercept ~ exponential(1);
    }

In dput format if you want a toy example :

$

**Comment by bob-carpenter** [comment]
Thanks for joining the conversation, @StromTroopers.  

See [Section 5.6, Zero-inflated and hurdle models](https://mc-stan.org/docs/2_27/stan-users-guide/zero-inflated-section.html) in the _User's Guide_.  The same approach as is used for a Poisson there can be used to zero inflate a negative binomial.  The key is treating it as a mixture model where one component is discrete.

If you'd like more help with model programming in Stan, we recommend the [Stan Forums](https://discourse.mc-stan.org).

Given that this isn't an issue for the devs to solve in the Stan software, I'm going to close.
