### ISSUE TITLE
FR: better error message on dimension mismatch 

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/stan#3063]
With cmdstan 2.27.0, the following stan code:
```stan
transformed data{
	int n=1;
	int m=2;
	matrix[n,m] x ;
	for(i_n in 1:n){
		for(i_m in 1:m){
			x[i_n,i_m] = std_normal_rng();
		}
	}
	matrix[n,m] z = transpose(x) ; // throws error bc should be matrix[m,n]
}
```
passes syntax checks (inc. pendantic) but yields the unhelpful error at runtime:
```
stan/lib/stan_math/lib/eigen_3.3.9/Eigen/src/Core/DenseBase.h:256: void Eigen::DenseBase<Derived>::resize(Eigen::Index, Eigen::Index) [with Derived = Eigen::Map<Eigen::Matrix<double, -1, -1> >; Eigen::Index = long int]: Assertion `rows == this->rows() && cols == this->cols() && "DenseBase::resize() does not actually allow to resize."' failed.
```
Would there be any avenue for a more informative error message calling out the line number in the original stan code where the dimension mismatch arises?

**Comment by bob-carpenter** [comment]
Currently, our assignment operation has a bug where this allowed:

```
array[2, 3] a;
a[1] = {1, 2, 3};  // conforming assignment allowed
a[2] = {4, 5}; // non-conforming assignment also allowed
```

@bgoodri is relying on this bug for rstanarm.  We can clean this all up when we get ragged arrays.  I don' know if the assign @rok-cesnovar points to in `assign.hpp` is the one with the bug we need to preserve.  

An intermediate solution would be to do the size check and print a warning.

**Comment by bgoodri** [comment]
I don't think I am relying on that bug in rstanarm. We do call user-defined
functions with arrays that are created on the fly but don't assign them.

**Comment by rok-cesnovar** [comment]
Oh right, now that you mention that Bob, I remembered we had this discussion already: https://github.com/stan-dev/stanc3/issues/523

**Comment by rok-cesnovar** [comment]
Given that https://github.com/stan-dev/stan/issues/3084 is the same issue, will close this one.
