### ISSUE TITLE
Compilation errors related with stan::math::arena_matrix

### ISSUE THREAD

**Issue by crespofabian8012** [stan-dev/stan#3085]
Hello

I translated a stan model using stanc3(CMDSTAN 2.28.1). I included the .hpp file in Xcode(MacOSX Mojave). I have Eigen 3.4 installed, Sundials, Boost , TBB 2020.3

I am getting compilation errors:

No member named 'adj' in 'stan::math::arena_matrix<Eigen::Matrix<stan::math::var_value<double, void>, -1, 1, 0, -1, 1> >'

No member named 'val' in 'stan::math::arena_matrix<Eigen::Matrix<stan::math::var_value<double, void>, -1, 1, 0, -1, 1> >'

**Comment by crespofabian8012** [comment]
Thanks @bob-carpenter and @rok-cesnovar. Yes, I  am having the same issue with /examples/bernoulli.stan when translated with stanc. I am using Eigen 3.4, because I use some new features in Eigen 3.4 like Eigen::SeqN( for even and odd positions).

**Comment by rok-cesnovar** [comment]
Probably the easiest workaround is to just include `path_to_stan_math/stan/math/prim/fun/Eigen.hpp` in the g++ compile call as the first include.
Something like: `g++ -I path_to_stan_math/stan/math/prim/fun/Eigen.hpp ... `

There is also a branch in Stan Math `update/eigen-3.4` that has Eigen 3.4, but its failing in CI.

**Comment by SteveBronder** [comment]
Until we bump to 3.4 I would not use it.  There's a lot that has changed internally in eigen and we have to update a good bit for that

**Comment by alecjacobson** [comment]
fwiw, I fixed this in my project by making sure #include <stan/math.hpp> cam before any #include <Eigen/ lines
