### ISSUE TITLE
why include `stan/mcmc/fixed_param_sampler.hpp` in services methods that do have params?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#3110]
#### Summary:
A bunch of the services methods include the stan::mcmc::fixed_param_sampler class - why?

#### Description:
```
~/github/stan-dev/cmdstan/stan/src/stan/services ((v2.29.1))> find . -name "*.hpp" -exec grep -l "stan/mcmc/fixed_param_sampler.hpp" {} \;
./sample/hmc_nuts_dense_e_adapt.hpp
./sample/hmc_nuts_diag_e_adapt.hpp
./sample/hmc_static_diag_e_adapt.hpp
./sample/hmc_static_diag_e.hpp
./sample/hmc_static_unit_e_adapt.hpp
./sample/fixed_param.hpp
./sample/hmc_static_unit_e.hpp
./sample/hmc_nuts_diag_e.hpp
./sample/hmc_static_dense_e_adapt.hpp
```

#### Current Version:
v2.29.1

**Comment by mitzimorris** [comment]
just cleaned out this include from the following:
```
	modified:   src/stan/services/sample/hmc_nuts_dense_e_adapt.hpp
	modified:   src/stan/services/sample/hmc_nuts_diag_e.hpp
	modified:   src/stan/services/sample/hmc_nuts_diag_e_adapt.hpp
	modified:   src/stan/services/sample/hmc_static_dense_e_adapt.hpp
	modified:   src/stan/services/sample/hmc_static_diag_e.hpp
	modified:   src/stan/services/sample/hmc_static_diag_e_adapt.hpp
	modified:   src/stan/services/sample/hmc_static_unit_e.hpp
	modified:   src/stan/services/sample/hmc_static_unit_e_adapt.hpp
```
ran default sampler - hmc_nuts_diag_e_adapt  - and everything just works.  recommend this as a code cleanup

**Comment by syclik** [comment]
That looks like a mistake. I'm guessing it can be removed from the includes
safely.

**Comment by mitzimorris** [comment]
doing code cleanup on includes in the headers in `stan/src/stan/services` -
why is `math.prim` included?  (not everywhere)

**Comment by mitzimorris** [comment]
`#include <stan/math/prim.hpp>`
or
`#include <stan/math/prim/fun/Eigen.hpp>` 

is more required here than Eigen?

**Comment by rok-cesnovar** [comment]
In most cases its just Eigen, in some cases we also need other stuff like https://github.com/stan-dev/stan/blob/7b291dac8d7c9509bf11db540f5efde7a649d410/src/stan/io/writer.hpp#L122

These headers were previously more narrow, but that proved to be problematic when moving stuff around in Math (particularly when we did the Math folder flatten - removed scal/arr/mat). If we just include prim.hpp, it's much less likely a Math change will require a change in Stan. As all these files have header guards this doesn't cause any slowdowns really and we will include the entire Math library at some point anyway (it gets included in the model_header.hpp anyway, so for the purpose of a CmdStan model, this has no effect).

**Comment by mitzimorris** [comment]
in this case, there are no direct calls to the math library - just EigenXd objects being passed around.
some of the services methods use the general include, others use the more specific one.
let's be consistent - which should it be?

**Comment by rok-cesnovar** [comment]
I would just include `#include <stan/math/prim.hpp>` everyhwere.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/stan/pull/3111
