### ISSUE TITLE
Why does log_prob_propto promote the input params to var types?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stan#3113]
#### Summary:

Looking at the code for `log_prob_propto` I'm just wondering why we need to promote the values to `var` types, since in that function we never call anything for the gradients. I think it would be a good bit faster to not do the conversion here so we can just use doubles.

https://github.com/stan-dev/stan/blob/develop/src/stan/model/log_prob_propto.hpp#L81

#### Current Version:
v2.29.2

**Comment by syclik** [comment]
I believe if we don't use `stan::math::var` (and use `double` instead) and a user has specified their model using unnormalized distributions (e.g. `y ~ normal(mu, sigma)`), then this function will trivially return `0`.

In the math library, we use the type to indicate what should be included as part of the log prob term, not just for the gradient.

**Comment by SteveBronder** [comment]
Would it be better in the model if we had a `log_prob` specialization for double that just always computed things with propto = false so that for doubles we get something back? Or is it correct / good to just get back 0 if the user is using the normalized distribtuions?

**Comment by bob-carpenter** [comment]
> Looking at the code for log_prob_propto I'm just wondering why we need to promote the values to var types, 

Here's what gets dropped in all four conditions.

* `var`, `propto = true`: drop only normalizing constants
* `double`, `propto = true`: drop everything (result is 0)
* `var`, `propto = false`: don't drop anything
* `double`, `propto = false`: don't drop anything

So the only way to get the same value as the Stan program, which uses `var`, `propto = true`, is to do the promotion.  Now you could figure out what the constant is once and then use the `double` that doesn't drop anything and then subtract out that constant in the end.  But I don't think it's worth it.

Given that this is the answer to the question, I'm closing the issue.  If you want to do something differently, we can open another issue.
