### ISSUE TITLE
generated quantities block returns zeroes for ALL quantities if there's a problem with one

### ISSUE THREAD

**Issue by fergusjchadwick** [stan-dev/stan#3114]
#### Summary:
All generated quantities in block are set to zero if there is a problem with estimating one quantity, even when they are unrelated.

#### Description:
If there's an impossible calculation (e.g. something that violates stated constraints/enough to throw a warning) on any generated quantity then zeroes are returned for all quantities, even those which have unrelated (conditional on model) calculation. This feels undesirable as zeroes have meaning and it seems odd to lose all output due to a mistake in a single calculation.

#### Reproducible Steps:

Obviously these are not sensible generated quantities but when I run this theta2 and thetaimp are both returned as zeroes, thetaimp is impossible but even though theta2 is a simple calculation and unrelated, both are returned as zeroes. 

```
data {  
  int<lower=0> N;  
  int<lower=0,upper=1> y[N];  
}  
parameters {  
  real<lower=0,upper=1> theta;  
}  
model {  
  theta ~ beta(1,1);  // uniform prior on interval 0,1  
  y ~ bernoulli(theta);  
}  
generated quantities {  
  real<lower=0,upper=1> theta2;  
  real<lower=0,upper=1> thetaimp;  
  theta2 = theta^2;  
  thetaimp = theta/0;  
}  
```

#### Current Output:

Model summary:
```
variable   mean median    sd   mad      q5    q95  rhat ess_bulk
  <chr>     <dbl>  <dbl> <dbl> <dbl>   <dbl>  <dbl> <dbl>    <dbl>
1 lp__     -7.29  -7.01  0.745 0.358 -8.79   -6.75   1.00    1685.
2 theta     0.252  0.234 0.122 0.125  0.0824  0.478  1.00    1316.
3 theta2    0      0     0     0      0       0     NA         NA 
4 thetaimp  0      0     0     0      0       0     NA         NA
 ```

#### Expected Output:

Model summary:
```
variable   mean median    sd   mad      q5    q95  rhat ess_bulk
  <chr>     <dbl>  <dbl> <dbl> <dbl>   <dbl>  <dbl> <dbl>    <dbl>
1 lp__     -7.29  -7.01  0.745 0.358 -8.79   -6.75   1.00    1685.
2 theta     0.252  0.234 0.122 0.125  0.0824  0.478  1.00    1316.
3 theta2    0.0784  0.0546 0.0739 0.0536  0.00678  0.228  1.00    1316
4 thetaimp  NA      NA     NA     NA      NA       NA     NA         NA
 ```

#### Additional Information:
I've tried this using cmdstanr on Mac and Ubuntu. I'd hoped to do some more exploration to be more informative but ran out of time. Incidentally, having a constrained variable declared in generated quantities but not used also throws warnings which can be frustrating when debugging (e.g. to find out which line of your code is sending everything else to zeroes)

#### Current Version:
cmdstan version 2.28.2 (Mac) and (2.29.2)
cmdstanr 0.3.0

**Comment by fergusjchadwick** [comment]
@rok-cesnovar Yes, this is what I meant, thanks for putting it so clearly! I will try to mimic in my next issue.

Only thing that is perhaps contentious here is whether `d` needs to be returned NaN as any generated quantity that relies on `c` will naturally fail thanks to it being returned as `NaN`

**Comment by rok-cesnovar** [comment]
My opinion is that returning it as NaN is better than the current behaviour of returning zeros as that could be misleading as you noted above.

**Comment by nhuurre** [comment]
The linked PR is concerned with recovering from exceptions in the generated quantities and fills any missing values with NaN.
Note that constraints aren't checked until the end of the block. The following program has always been legal
```stan
generated quantities {
  real<lower=0> a = -1; // constraint not checked yet
  real b = a; // b < 0 because a < 0 here
  a = 2; // a > 0 at the end of the block, it's fine
}
```
If people want to enforce the constraint I think the most reasonable solution is to add `write_checked_*` methods that check the constraint and write NaNs on failure to `stan::io::serializer`. The serializer already has `write_free_* ` methods that interact with the contraints so why not.

**Comment by WardBrian** [comment]
Would it be possible to have the serializer initialize to `nan` instead of 0? I think that would solve the bulk of this, and then the only question is if we want to report values for things computed before the error

**Comment by bob-carpenter** [comment]
> @WardBrian: Would it be possible to have the serializer initialize to nan instead of 0?

The place that doesn't work is with discrete values, but there's no type checking in the output, so we can return NaN even for things that should be int.  I don't know if that's going to mess up downstream plans to be more type conscious on our integer vs. floating point output.

> @nhuurre: Note that constraints aren't checked until the end of the block.

That's the only way we could figure out how to do it given the allocate and then set pattern in the early versions of Stan.  Now that we can compound declare/define, we could add things like constant values that got range checked on construction.  If I had it to do all over again, I'd use more comprehensions and insist on this pattern almost everywhere, but that's a different issue, so to speak.

**Comment by bob-carpenter** [comment]
Here's a program where the constraint is satisfied roughly half the time.

```stan
generated quantities {
  real a = normal_rng(0, 1);
  real<lower = 0> b = a;
}
```

With cmdstanr, it just fails, with

```
> fit <- mod$sample(chains=1, iter_warmup=5, iter_sampling=5)
Running MCMC with 1 chain...

Chain 1 Model contains no parameters, running fixed_param sampler, no updates to Markov chain 
Chain 1 Iteration: 1 / 5 [ 20%]  (Sampling) 
Chain 1 Exception: foo_model_namespace::write_array: b is -0.690206, but must be greater than or equal to 0.000000 (in '/var/folders/b3/6h4t41094vz281j7nn48ws900001jv/T/RtmpMtpqn0/model-13e575270d379.stan', line 3, column 2 to column 24) 
```

And there's nothing in `fit`.

**Comment by WardBrian** [comment]
> The place that doesn't work is with discrete values, but there's no type checking in the output, so we can return NaN even for things that should be int

This is a good point and would need a solution for if/when we have a better output format. That said, for the time being I think it is probably better to do NaN for everything than 0, and give ourselves that problem to sort out later when we need to. The lack of a sentinel value for integers will be an issue either way, since 0 is obviously the wrong answer in that regime too

**Comment by SteveBronder** [comment]
Just want to check that we are all on the same page. 

We always want `write_array` to always return the parameters, and then if any of the transformed parameters or generated quantities fails we want `write_array` to return NaN for all those transformed parameters or generated quantities. Is that correct?

**Comment by bob-carpenter** [comment]
@SteveBronder:  yes, I think that's the safest behavior

**Comment by SteveBronder** [comment]
Okay then I just put up a PR in stanc3 that should do that behavior 

https://github.com/stan-dev/stanc3/pull/1165

**Comment by rok-cesnovar** [comment]
To summarize (please correct me if I am wrong) we have two solutions for this issue: 

a) Steve's fix where all transformed parameters and GQs are written as NaN
b) Niko's fix where only the quantities that don't pass the checks and subsequent parameters/quantities are written as NaN

I would prefer b) given that also looks to be rather simple.

**Comment by fergusjchadwick** [comment]
@rok-cesnovar - just a run-of-the-mill user here but b) is what I was hoping for. 

It's much more informative about where the problem is occurring and for longer run models you might still want to interpret successfully calculated quantities.

If possible, in the generated quantities block it would be great to have only quantities that don't pass the checks reported as NaNs (which would propagate through values which are related downstream) as not every subsequent quantity will be related to the bad calculation (and if it is, having an NaN should mean the subsequent calculation also returns NaN).

**Comment by WardBrian** [comment]
I think your final request (having subsequent but unrelated variables not be NaN) would be nice to have but my understanding is that would be significantly more complicated. The way the checks and everything work (even with Niko’s changes?) mean that the NaNs wouldn’t propagate in the same way you’d expect automatically

**Comment by fergusjchadwick** [comment]
Thanks for clarifying @WardBrian, makes sense!

**Comment by betanalpha** [comment]
Just wanted to add that I've always interpreted, and taught, that the constrained types outside of the `parameters` block act as unit tests that are performed at the end of the block.

Checking at the end of the block offers more flexibility than checking at each declaration because it doesn't require inline declarations.  For example
```
generated quantities {
  real x; // Defaults to NaN
  real<lower=x> y; // Will always fall
  
  x = ... // Value derived in complicated code
}
```
would not be possible if constraints were checked inline.

In my opinion inline checks would be viable only if we allow variables to be declared anywhere in the program so that earlier variables can be fully defined in multiple lines if necessary before dependent constrained variables are declared.

Way back in the day constraint violations in the `generated quantities` block lead to the sampler failing immediately so there was nothing to write.  I'm missed when this behavior changed, but I don't think that the failure behavior is documented anywhere.

From the other threads it sounds like `NaN` is the current choice, which I think makes sense for real variables as that is the default initialization.  It would be great to default integer variables to the default initialization of `-MAX_INTEGER` as well so that we have a policy of variables not being updated from their default initialization if a constraint is ever violated.

**Comment by WardBrian** [comment]
We've merged https://github.com/stan-dev/stanc3/pull/1165, which initializes the vector to be written to `NaN` first. 

At the moment, all the values in write_array are written as doubles. As we think more about IO which actually differentiates between real and integer values, I think @betanalpha's suggestion of using `-MAX_INT` for integers is probably the best.
