### ISSUE TITLE
+jacobian option for optimizers & service functions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#3149]
#### Summary:

Add options to include Jacobian correction for optimizers and related service functions in order to allow max a posteriori (MAP) estimates as well as the existing penalized maximum likelihood estimates (MLE).

#### Description:

* Add a boolean template parameter `jacobian` to each of the optimizers  in `src/stan/optimization` at the entry point for the optimization service functions;  a value of `true` uses Jacobian and value of `false` turns off Jacobian adjustments;  this should be the final template parameter and should default to `false`.

* Add a boolean template parameter `jacobian` to the optimization service functions in `src/stan/services`;  a value of `true` uses Jacobian adjustment and value of `false` turns it off; this should be the final template parameter and default to `false`.  The value set here should be passed as a template parameter to the optimization functions.

#### Current Output:

Hard codes the Jacobian turned off.

#### Expected Output:

MLE or MAP estimates as specified.

#### Additional Information:

By making the new template parameter the last in the chain, this should be backward compatible.

#### Current Version:
v2.30.0

**Comment by WardBrian** [comment]
Closed by https://github.com/stan-dev/stan/pull/3152
