### ISSUE TITLE
Typo on wiki: prior choice recommendation for correlation

### ISSUE THREAD

**Issue by MPRdthal** [stan-dev/stan#3235]
#### Summary:
The wiki for prior choice recommendation has a typo in the boundary-avoiding prior section for a correlation parameter.

#### Description:
The line reads "For a correlation parameter, a Beta(2,2) parameter on 2*(rho - 1/2) will keep the point estimate [...]"
a) the second instance of "parameter" should instead be "prior"
b) this line uses the inverse of the transformation rather than the transformation itself

Instead I believe the line should read:
"For a correlation parameter, a Beta(2,2) prior on rho/2 + 1/2 will keep the point estimate [...]"
or 
"For a correlation parameter, a 2*(Beta(2,2)-1/2) prior on rho will keep the point estimate [...]"

**Comment by bob-carpenter** [comment]
Thanks for filing.  Can you edit the wiki?   And yes, that's should be f(x) = (x + 1)/2 to map (-1, 1) to (0, 1).

**Comment by bob-carpenter** [comment]
I just went ahead and made the change.  Thanks again.
