### ISSUE TITLE
Add resampling options for multi-Pathfinder

### ISSUE THREAD

**Issue by avehtari** [stan-dev/stan#3242]
1. Currently, multi-Pathfinder always resamples. When the approximation is far from the true target and especially in case of high dimensional posteriors, one weight can dominate and resampling returns only copies of a single draw. Furthermore, in edge cases, Pareto-smoothing or computation of weights can fail and produce completely unexpected results. To allow 1) further diagnostics in such problematic cases and 2) have more unique draws to initialize MCMC to improve MCMC convergence diagnostics
 - [ ] add boolean option `resample` with default value `TRUE`, and value `FALSE` disabling the resampling

2. For cases where we don't care about doing further diagnostics, but want a minimum number of unique draws, allow resampling without replacement (and then set `num_draws` to the number of unique draws needed, e.g. for initializing MCMC)
 - [ ] add boolean option `with_replacement` with default value `TRUE`, and value `FALSE` using without replacement resampling

**Comment by WardBrian** [comment]
What is returned when resample is false?

**Comment by avehtari** [comment]
When resample is false, return the draws from the normal approximations (skip lines 173-186 and index with consecutive numbers on line 188 of multi.hpp)

**Comment by WardBrian** [comment]
I still don't think I understand how this is different from setting `save_single_paths` to true and using those draws

**Comment by avehtari** [comment]
- I wasn't aware of `save_single_paths` option (after looking the doc, I think it's not well documented (one part gives an impression of that it saves the paths and not the draws), and also it's not currently working in CmdStanR (https://github.com/stan-dev/cmdstanr/issues/878#issuecomment-1870108851)
- `save_single_paths` saves also the paths, which I'm not interested in, and to load the draws from the individual csv's would require additional code from the user or method in CmdStanR, so it would not be as clean solution

**Comment by WardBrian** [comment]
#3249
