### ISSUE TITLE
Write metric as JSON - add field "metric_type"

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#3247]
#### Summary:

PR https://github.com/stan-dev/stan/pull/3230 produces metric in JSON; add field `metric_type` to output; values will be string `dense`, `diag`, or `unit`.

#### Description:
Describe the issue as clearly as possible.

see example in design doc - https://github.com/stan-dev/design-docs/blob/8eede8b68afd8456df437c9b90281dc82107074b/designs/0032-stan-output-formats.md?plain=1#L199-L202

#### Current Version:
v2.33.0

**Comment by WardBrian** [comment]
#3248
