### ISSUE TITLE
How to use stan::math::hypergeometric_2F1 in stan?

### ISSUE THREAD

**Issue by MSQ-123** [stan-dev/stan#3253]
I was trying to call my stan model by using rstan in R. It seems like stan does not has built-in hypergeometric_2F1 function. This function is only available in stan math. Is there any way to import stan math function directly into stan model? thanks a lot!

**Comment by WardBrian** [comment]
There is an open issue about exposing this function to the language here: https://github.com/stan-dev/stanc3/issues/1285

Further discussion should be had there. I believe the only thing preventing it was some questions for the implementer @andrjohns.

If you'd like to use it in the mean time, you could likely use [RStan's ability to use "external" C++](https://mc-stan.org/rstan/articles/external.html)
