### ISSUE TITLE
Replace all non-finite lp__ and lp_approx__  with -Inf

### ISSUE THREAD

**Issue by avehtari** [stan-dev/stan#3290]
When drawing from Laplace, variational, or Pathfinder approximation, in rare cases we see NaN or Inf for `lp__` or `lp_approx__` written in csv. From the further usage point of view, it would be useful if all NaN and Inf would be converted to -Inf.

The downside is that it may sometimes make it more difficult to find out numerically unstable computation in code (ie observing NaN or Inf gives non-zero information where the issue might be).

**Comment by SteveBronder** [comment]
imo I've found that receiving back NaN or +/-Inf gave me different info about debugging the program. If we give back a user -inf instead of NaN
