### ISSUE TITLE
Unexpected behaviour (to me) with declaring multiple transformed data

### ISSUE THREAD

**Issue by mhollanders** [stan-dev/stan#3307]
Hi,

I was working on a function where I wanted to declare multiple variables as `positive_infinity()` at the same time in a program called `infinity.stan`:

```
transformed data {
  real x, y = positive_infinity();
  print(x);
  print(y);
}
```

Running this yields the following confusing outcome, where only `y` is `inf` but `x` is `nan`. Is this expected behaviour?

```
> mod2<- cmdstan_model("infinity.stan")
Compiling Stan program...

> fit2 <- mod$sample(fixed_param = T)
Running MCMC with 4 sequential chains...

Chain 1 nan 
Chain 1 inf
```

Thanks!

Matt

**Comment by WardBrian** [comment]
Yes, this is expected. What you have written is equivalent to

```
real x;
real y = positive_infinity();
```

And Stan leaves un-initialized values as NaN

The syntax for declaring multiple variables of the same type at once does not allow initializing all of them to the same value while doing so, but you could write 

`real x = something(), y = something();`

**Comment by mhollanders** [comment]
Thanks @WardBrian, surprisingly this issue has never caused problems before because I've been doing this for ages. Thanks, and sorry for the non-issue.
