### ISSUE TITLE
BFGS to Inits Converter

### ISSUE THREAD

**Issue by Ctross** [stan-dev/stan#347]
For some models having reasonable initial values might help MCMC convergence. The BFGS engine appears to be working quite well for the models I am running; however, the output file is not easily put into the dump format needed for init specification. Would It be possible to have the optimization engines create a second data file, which dumps the posterior modes of the parameters, but not transformed parameters, in a way that can be directly read as inits for sampling?

**Comment by bob-carpenter** [comment]
This will all get rolled into cleaning up the I/O in Stan 3 and in the ongoing refactor before that.
