### ISSUE TITLE
Refactor Manual

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#354]
We really need to refactor the manual so that we have separate sections describing our samplers/optimizers and their configurations.  I'm thinking a chapter after "Introduction" called something like "Algorithms" with details on HMC, adaptation, optimization, and potential pitfalls in practice, which would leave the configuration doc in the "Commands" chapter much cleaner.

I assign myself since I know the most about the samplers.

**Comment by bob-carpenter** [comment]
absorbed into #2103
