### ISSUE TITLE
Define Stan I/O

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#357]
Define the specification, and the format in which it is defined, for Stan I/O.  At the moment input is implicitly defined by the argument code while output is implicitly defined by the csv output.

**Comment by davharris** [comment]
Is there a specification for the CSV output these days?

My main interest is in having more flexibility about what parts of the file to read in than is currently provided by `read_stan_csv` in R.  I'd feel better writing such a function if I had a clearer sense of how the files can be structured.

If there isn't a spec, I'd be happy to write a preliminary one.  If there's already an unofficial specification somewhere, then perhaps I could start there?

Thanks

**Comment by bob-carpenter** [comment]
The CmdStan manual provides details, but
the CSV part of it's just a header line for
each parameter (either model parameter or parameter
of the algorithm such as NUTS) along with a line
for each draw.  You can set it up to include or
not include warmup "draws".

Other things are encoded in a much more ad-hoc way
in comments.

This is all likely to change around in Stan 3.
For example, we print the adaptation parameters as
comments now for HMC, but will probably put those in
a proper standalone file going forward.

- Bob

**Comment by jgabry** [comment]
I think this can be closed. If not feel free to reopen.
