### ISSUE TITLE
Automated Model Checking

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#359]
Implement automated calculation of WAIC (DIC would be redundant, unless there is a strong argument otherwise).

- [ ] #361 
- [ ] Algorithm implementation
- [ ] Modeling language specification
- [ ] I/O

**Comment by jgabry** [comment]
This hasn't been touched since 2013 and discussions along these lines have popped up elsewhere in issues and on stan-dev so I'm going to close this in the effort to reduce the number of open issues.
