### ISSUE TITLE
Nested Sampling

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#360]
- [ ] #361 
- [ ] Algorithm code
- [ ] Tests
- [ ] Argument configuration
- [ ] gm/command.hpp

**Comment by syclik** [comment]
@betanalpha, want to move this to the wiki?

**Comment by betanalpha** [comment]
We might as well drop it until after we implement Adiabatic Monte Carlo.

**Comment by syclik** [comment]
I added a line to the longer term wiki page.
