### ISSUE TITLE
Separate Prior and Likelihood Specification

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#361]
Allow specification of separate prior and likelihood blocks, with the model returning log_prior, log_likelihood, and log_posterior = log_prior + log_posterior.

Possibly allow arbitrary model blocks with tags,

model prior {
...
}

model aux {
...
}

which would auto-generate, for example,

log_model_prior(), log_model_aux, log_posterior() { return log_model_prior() + log_model_aux() }

Should be fully backwards compatible.

**Comment by jgabry** [comment]
The topics discussed in this issue are now being discussed in many other issues and on stan-dev so I'm going to close this as there hasn't been any action in quite some time.
