### ISSUE TITLE
Ensemble Samplers

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#362]
Admit generic ensemble sampling within Stan's sampler engine.

Allows running multiple chains internally that can communicate with each other, possibly useful during adaptation.  Allows ensemble samplers such as DREAM.
- [ ] Ensemble architecture
- [ ] Ensemble initialization
- [ ] Ensemble output
- [ ] Argument configuration
- [ ] Algorithms

**Comment by bob-carpenter** [comment]
see discussion in #774

**Comment by syclik** [comment]
I'm closing this issue. I think the evaluation that Peter did was sufficient to close this issue.
