### ISSUE TITLE
Request: robust function to compute log(Phi(x)) 

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/stan#377]
In implementing a hierarchical tobit model I ran into some initialization problems that I finally tracked down to the following line:

    lp__ <- lp__ + log(Phi(...))

where the quantity (...) can be large and negative. What happens is that Phi(...) rounds down to zero, so lp__ becomes negative infinity. You'll get this problem unless your initial parameter values are such as to make EVERY zero in the data sufficiently probable. To avoid the need to fine-tune the initial parameter values, it would be really nice if there were a robust function to compute log(Phi(x)), as log(Phi(x)) is representable as a double even when Phi(x) is not.

I ended up working around the problem by using the identity

    log(Phi(-x)) = log(Phi(-x)/phi(x)) + log(phi(x))
        = log((1 - Phi(x)) / phi(x)) - 1/2 * (x^2 + log(2 * pi))

and then using the following Taylor series for (1 - Phi(x))/phi(x):

    1/x - 1/x^3 + 3/x^5 - 15/x^7 + 105/x^9 + O(1/x^11).

**Comment by syclik** [comment]
I'm closing this issue: Bob's fix has made this more stable and we haven't seen it pop up recently.
