### ISSUE TITLE
Null space type

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#380]
Implement a vector type that satisfies

A \* u = 0

for a given (k by n) matrix A.

Algorithmically, we need to compute the SVD of A then store the (n - k) rightmost vectors of V, v_{i}.  The unconstrained parameters are then the coefficients of the expansion

u = sum_{i} \alpha_{i} v_{i}.

Because A is constant, the Jacobian is constant and the gradients are simple.

@bob-carpenter, can we have this derive from the current vector type so that it can be used in the usual linear algebra manipulations?

**Comment by syclik** [comment]
@betanalpha, this still a good idea?

**Comment by betanalpha** [comment]
Could be useful, but there hasn’t been much recent interest.

**Comment by syclik** [comment]
Thanks. I'm going to close this and add it to our wiki of longer term issues.
