### ISSUE TITLE
guarantee deletes for pointers in gm/command.hpp

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#397]
In the current state of gm/command.hpp, the deletes at the end of the big function for `sample_stream`, `diagnostic_stream` and `valid_arguments` are not guaranteed to be esecuted because of the possibility of early returns and exceptions.  

The two ways I know how to fix this are to

1.  instead of return, do a labeled break out to the cleanup routines and wrap everything in a try/catch, with cleanup inside the catch and outside at the labeled break, or

2.  use references instead of pointers, which are automatically cleaned up when they go out of scope.

I would prefer option (2), but I'm not sure it's very feasible given the current design of command.

**Comment by syclik** [comment]
`command.hpp` now lives in CmdStan. Closing the issue.
