### ISSUE TITLE
upgrade our PRNG

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#403]
Ben Goodrich suggested this lib to replace our Boost RNG:

http://numbercrunch.de/trng/ 

It uses a more recent parallel-friendly PRNG by L'Ecuyer than the one we're using.  It also has an efficient discard for use in parallel. 

The license is 3-clause BSD, which is perfect for Stan (it's what Stan's license is).

The strategy should be to wrap up the trng lib into a class implementing the Boost generator concept:

http://www.boost.org/doc/libs/1_55_0/doc/html/boost_random/reference.html#boost_random.reference.concepts.pseudo_random_number_generator

This will let us use our existing [0,1] uniform generators and normal(0,1) generators in the samplers and all the RNG functions for distributions.

Ben also noted this reference as another parallel friendly, modern RNG that might get into Boost:

http://lists.boost.org/Archives/boost/2012/01/189293.php

**Comment by betanalpha** [comment]
http://www.pcg-random.org -- Nice lightweight C++ code is provided, but it's Apache licensed with may cause problems.

**Comment by bob-carpenter** [comment]
Apache license shouldn't be a problem unless it's incompatible
with GNU.

- Bob

**Comment by bob-carpenter** [comment]
Given we haven't had any RNG-related issues ever, I'm going to close this.
