### ISSUE TITLE
Refactor src/stan/gm/command.hpp: debugging is difficult as is.

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#405]
Issues like #379 are masked by the structure of src/stan/gm/command.hpp. Here are some things that should be done:

- [ ] consistent use of return codes. Use the values in src/stan/gm/error_codes.hpp
- [ ] remove switch in command()
    - use of `sampler_select` is opaque. Too hard to see which sampler is actually being called.
- [ ] double check all exit codes
    - currently, there are no tests for how this exits

We should shift focus of this code and favor clarity and maintainability. This code should be Stan's interface to be utilized by CmdStan, RStan, and PyStan. (CmdStan and RStan currently does this. I'm not sure about PyStan.)

**Comment by betanalpha** [comment]
Switch removed in https://github.com/stan-dev/stan/tree/feature/issue-1361-writer_callback.

**Comment by syclik** [comment]
We'll fix this with #1361.

**Comment by syclik** [comment]
I'm closing this issue. It's being addressed in other issues and the file has moved to CmdStan.
