### ISSUE TITLE
mark-recapture and occupancy ecology model examples

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#451]
* [x] simple one-step mark-recapture
* [x] compound, fixed-time Cormack-Jolly-Seber (CJS) mark-recpature
* [x] Bonner-Schwarz individual-level model with varying times and R simulator
* [ ] mark-recapture model with predictors (could also use Schofield et al.'s examples)

#### References

* basic model: http://en.wikipedia.org/wiki/Mark_and_recapture
* nice class notes with overview and compound models: http://www.montana.edu/rotella/502/CJS.pdf
* Bonner and Schwarz 2006.  http://www.simon.bonners.ca/PDFS/142-149_biom_399.pdf
* Matt Schofield et al.'s CJS mark-recapture model at individual level in BUGs: http://www.maths.otago.ac.nz/~rbarker/BUGS/ 
* Matt Schofield's Ph.D. thesis for nice expository definitions of the various models: http://www.maths.otago.ac.nz/home/resources/theses/PhD_Matthew_Schofield.pdf

**Comment by jgabry** [comment]
@bob-carpenter Can this be closed? The only remaining checkbox is for mark-recapture models with predictors, but I think we at least have an example of that somewhere now, right?

**Comment by bob-carpenter** [comment]
Yes, they're all getting added in the translations in example-models.  Very cool!
