### ISSUE TITLE
suppress output in Stan samplers

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#453]
Andrew reports on stan-users that he'd like to be able to run Stan without any output at all, i.e., silently.  

I see three ways to do this:

1.  rewrite everything in terms of stream references, then pass in no-op streams;

2.  pass in a stream pointer,  allow it to be null (0) to suppress printing, and then embed each call in a conditional (we're using this idiom elsewhere); or

3.  carry around a no-op flag and embed each call to std::cout in a conditional.

**Comment by syclik** [comment]
We're taking care of this from the interfaces.
