### ISSUE TITLE
create an index for the manual

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#454]
This should be done using LaTeX's indexing mechanism.  

Should the function index be kept separate as it is now?

**Comment by jgabry** [comment]
You're talking about a topic index here right? That would be great. Was this idea rejected or just a casualty of too little man power?

**Comment by syclik** [comment]
Too little man power.

**Comment by bob-carpenter** [comment]
Yes, topic index.  But the manuals are going to be broken apart, and we can make new issues then that arise, like formatting for web and PDF.
