### ISSUE TITLE
cache results of expensive matrix calcs

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#463]
Introduce some mechanism for distributions to keep track of calculations that can be reused.  The main issue I see is how to calculate 

From Marcus Brubaker on stan-dev:

The issue of Sigma = var \* ConstantMatrix is more interesting and potentially promising if we can fix it in a general way.  I'd like to propose that we think about adding a mechanism whereby distribution functions can precompute properties of constant parameters and store them somewhere.  This could include things like matrix factorizations, determinants, normalizing constants, validity checks, etc.  Then during sampling/optimization they can be re-used.  This could benefit a significant number of models.

Then replying to a question from Michael Betancourt about just specializing *:

The expensive part of this isn't the multiplication, although that's not exactly free.  It's that every time Sigma is passed to, e.g., multi_normal_log, its Cholesky factorization has to be recomputed even though it's exactly the same except that it's rescaled.  Part of this can be fixed by a special distribution, e.g., multi_normal_scaled_covar_log(y,mu,var,C) or something like that.  But ultimately, when Sigma is a large enough matrix, that repeated factorization really hurts.

In the past we've generally ignored wasted computation like this because it was usually dwarfed by the autodiff costs but now that we've got that somewhat under control through the use of custom vari's, things like this are now showing up at the top of the profiles in these models.

**Comment by syclik** [comment]
This would be great, but I'm not sure how we could keep around the values. Is this something we would do in the generator? 

We'd need to add a lot of things to the math library to make this work.

**Comment by bob-carpenter** [comment]
We've talked about it before and I have no idea how to do it.  I'm going to move it to the longer-term issues wiki.
