### ISSUE TITLE
Don't Allow Parameters In If Statements

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#468]
One has to be really careful when using parameters in the condition of an if statement -- essentially this allows for piecewise posteriors which are hard to make smooth.  Ignoring the discontinuity is actually worse than most people realize since it introduces a delta function to the gradient which should perturb the trajectory every time it is passed, not just any time the trajectory lands on the discontinuity exactly.

Only allowing data in the conditionals would remove this issue, and it would allow us to reuse the autodiff stack for significantly faster execution of derivatives.

**Comment by syclik** [comment]
Mind if we close this for now? I don't think we're going to apply this to Stan anytime soon.

**Comment by betanalpha** [comment]
I guess -- it will just come up again when we considering bringing Nomad in,

**Comment by bob-carpenter** [comment]
I think we should bring this up for potential Stan 3 changes,
since it's a major backward-compatibility breaker.

It'd be a relatively clean change to make in the language and
it wouldn't even be too hard to have a flag that let them go
through or not.

- Bob
