### ISSUE TITLE
catch uses of uninitialized variables

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#477]
We set real local values to NaN, so they usually cause a problem when used, though not an obvious one. But integer values are initialized at 0, which means they're well formed when used, for example, in a Bernoulli or binomial.

What we should be doing is looking throgh the abstract syntax tree that's generated and make sure

1.  every local variable is set before it's used

2.  every transformed data and transformed parameter is set 

I don't think it'll be that hard to do, but requires writing some code to walk over the syntax trees after they're generated to test things like this before code generation commences.

**Comment by syclik** [comment]
Closing this issue. Maybe this is something for the syntax checker.

**Comment by bob-carpenter** [comment]
Is there a wiki page this should be pointing to?
