### ISSUE TITLE
monitor subset of parameters to reduce output size/memory

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#487]
It would be nice to be able to monitor only a subset of parameters.  It could save a lot of disk on output to CSV from CmdStan and a lot of memory when called from RStan or PyStan.  It will also speed up print() in RStan and bin/print in CmdStan.  

We usually want to monitor all variables required for convergence monitoring, but there are often nuisance parameters or reparameterizations where we only care about monitoring the reparameterizations.  Also, we might eliminate monitoring for non-identified parameters or parameters that are constant (e.g., diagonals of correlation matrices).

**Comment by alexpkeil1** [comment]
I'm sorry to resurrect this, but this is one of the more important features (for my work) that is not implemented yet. I use the "generated quantities" to get record level predictions of certain variables. I often later summarize these across all records, but, in the effort of creating "mean_xpred" for a 25000 record dataset I am then stuck with output of "xpred[1]" through "xpred[25000]" in the csv file that are a complete nuisance. In some cases, I can modify my code to avoid this, but I haven't found a general solution.

Is this still a direction you will be going with stan? It's a pretty big usability issue for me. I have found stan to be fantastic in all other respects.

**Comment by bob-carpenter** [comment]
There isn't a good general solution because of the way
scoping's set up from parameters to generated quantities.

Subsetting the variables to save (by variable) is still on
our to-do list for the Stan 3 refactor.  Then it'll get
pushed out to CmdStan, RStan, PyStan.  We've been reluctant
to add new features to CmdStan in the interim, which leaves
us in a bit of a bind.

I think we'd all be amenable to someone adding this functionality
to CmdStan, as long as they understood we are going to refactor
a lot of the code around it.

- Bob

**Comment by betanalpha** [comment]
Just use a local scope,

generated quantities {
  real mean_xpred; // Only declarations here get saved
  {
    real xpred[25000];  // These are temporary variables in the local scope and don’t get saved
    xpred <- compute_values;
   mean_xpred <- mean(xpred);
  }
}

**Comment by alexpkeil1** [comment]
That was embarrassingly easy - sorry if that was hidden in the manual and I missed it. That certainly solves a large chunk of this problem for me. Thanks!

**Comment by betanalpha** [comment]
I'd consider local scopes a slightly advanced technique -- don't worry about it.  But do close the issue if you're satisfied.

**Comment by azvoleff** [comment]
I don't think the local scopes approach solves the original issue. The original issue relates to monitoring a subset of model parameters. I don't believe a local scope can be used to limit monitoring of variables from the parameters or transformed parameters blocks that need to be used in the model block, can it?

**Comment by betanalpha** [comment]
No.  But the original problem was misspecified -- what was filling up the output wasn't parameters but temporary local variables.  We might also have an issue open already for this.

**Comment by syclik** [comment]
I'm closing this. It's already implemented in RStan. It's easy to do this with writers now. It's an interface issue.
