### ISSUE TITLE
propto control in sampling statements

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#496]
We should allow users to control whether constants are dropped in the model.  Right now,

```
y ~ foo(theta1,...,thetaN);
```

will drop any terms in `log foo(y | theta1,...,thetaN)` that are constant, whereas

```
increment_log_prob(foo_log(y, theta1,...,thetaN))
```

will not.  We could add controls so that either one can be used either way.  It should be simple to implement because it's just a boolean template parameter to the same underlying function.  I'm not sure what the syntax should be, but maybe something as simple as `foo_propto_log()` for the functions and `foo_full()` for the sampling statements.  (It's unfortunate that the defaults are different, but I'd hate to break backward compatibility by changing that at this point.)

**Comment by bob-carpenter** [comment]
See #1299 for access in function definitions.

**Comment by syclik** [comment]
I'm bumping milestones up on this issue. Since we've introduced `target +=`, it makes sense that we want to have this control on our functions.

**Comment by rok-cesnovar** [comment]
Closing. see https://github.com/stan-dev/stanc3/issues/253
