### ISSUE TITLE
generate transformed parameters and generated quantities from parameters

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#513]
Suggestion from John Hall on stan-users:

Provide functionality to read in parameters (say in an output CSV file) and generate the transformed parameters and generated quantities.  

For generated quantities, we should specify a new random seed --- so it won't be totally replicable because the generated quantities are generated interleaved with the other random variates right now.

**Comment by syclik** [comment]
This issue was moved to stan-dev/cmdstan#513

**Comment by syclik** [comment]
I moved this to CmdStan.
