### ISSUE TITLE
random number generation with truncation

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#515]
Would be nice if it had the same syntax as sampling, but not sure how that would work for a function.

```
y <- normal_rng(mu,sigma) [L,U];
```

vs. the way we do it for things like the variable transforms, with three parallel functions:

```
y <- normal_rng_lb(mu,sigma,L);
y <- normal_rng_ub(mu,sigma,U);
y <- normal_rng_lub(mu,sigma,L,U);
```

**Comment by bgoodri** [comment]
There is an issue in stan-dev/math for this.

**Comment by jan-glx** [comment]
[This](https://github.com/stan-dev/math/issues/214) is the issue in question. ( I case you end up here from google wondering if this is implemented in stan. (It is not :( ))
