### ISSUE TITLE
Log Riemann Zeta plus Zipf distribution

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#551]
It'd be nice to have the Zipf distribution in Stan:

See:  http://mathworld.wolfram.com/ZipfDistribution.html

The pmf is involves the Riemann zeta function, which is available from Boost:

http://www.boost.org/doc/libs/1_55_0/libs/math/doc/html/math_toolkit/zetas/zeta.html

so we could add it directly with auto-diff.  But auto-diffing these numerical 
approximations to functions isn't ideal.  

Plus, we really need `log_zeta` for Stan, and then we'd want a direct scheme 
for evaluating  both
```
log(zeta(s)
```
and
```
  d/ds log(zeta(s)) = 1/zeta(s) d/ds zeta(s).
```

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#28
