### ISSUE TITLE
catch bac_alloc for out-of-memory in commands and print diagnostics

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#604]
It'd be nice if instead of crashing with an exception dump facing the user if bin/print and the actual commands to run the model would catch bad allocs and report that there's an out-of-memory error.  

Whether this feature request should be moved to CmdStan is going to depend on where the catch is done.

**Comment by syclik** [comment]
This issue was moved to stan-dev/cmdstan#514

**Comment by syclik** [comment]
Moved to CmdStan.
