### ISSUE TITLE
Expose gradient

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#605]
One thing that we may be able to do within weeks rather than months that would allow Andrew to do more of this in Stan proper is to expose a score function (which might be somewhat useful for other purposes too), a.k.a. the gradient of the log-likelihood 

http://en.wikipedia.org/wiki/Score_%28statistics%29

Thus, the estimated variance-covariance matrix of the estimates could be obtained via the Outer Product of Gradients method, see equation (14-18) in

http://pages.stern.nyu.edu/~wgreene/NUI2011/Greene-Chapter-14.pdf

That way Andrew could write a generated quantities block like this

```
generated quantities {
  matrix[K,K] H;
  vector[K] draws[SIMS];
  vector nald[SIMS]
  vector pll[SIMS]

  H <- rep_matrix(0.0,K,K)
  for (i in 1:N) H <- H + tcrossprod(score(foo_log(y[i], ...));
  H <- H / N;
  V <- inverse_spd(H);
  for (i in 1:SIMS) {
    draws[i] <- normal_rng(theta, V);
    nald[i] <- normal_log(draws[i], theta, V);
    pll[i] <- /* rebake penalized log-likelihood evaluated at draws[i] */
  }
}
```

**Comment by ariddell** [comment]
This would be useful for PyStan. I'll reopen the issue. If there's a better place for this, I'd be happy to migrate it.

**Comment by syclik** [comment]
@ariddell, I think this is a language issue.

@bgoodri, are you envisioning something like this only happening in generated quantities?

**Comment by bgoodri** [comment]
On Wed, Nov 30, 2016 at 10:23 AM, Daniel Lee <notifications@github.com>
wrote:

> @bgoodri <https://github.com/bgoodri>, are you envisioning something like
> this only happening in generated quantities?


No; the likelihood can be a function of partial derivatives.

**Comment by syclik** [comment]
Hmm... that makes it much more of a pain, but I don't think it's impossible. We'd need to add the `score()` function to the math library that does the nested autodiff, right? Then expose that through the language?

**Comment by bgoodri** [comment]
On Wed, Nov 30, 2016 at 11:11 AM, Daniel Lee <notifications@github.com>
wrote:

> Hmm... that makes it much more of a pain, but I don't think it's
> impossible. We'd need to add the score() function to the math library
> that does the nested autodiff, right? Then expose that through the language?
>
Something like that

**Comment by simeoncarstens** [comment]
I assume it is still not possible to expose the log-likelihood gradient w.r.t. the parameters in, say, the `transformed parameters` block? If so, I'd love to +1 this issue - it would allow a much more flexible use of Stan. In my case, for now I would like to use Stan to just evaluate log-{posterior, likelihood, prior} probabilities and their gradients for a given Stan model and use them for a custom sampler / inference method.

**Comment by andrjohns** [comment]
Accessing those within the blocks of a Stan model is not likely to available any time soon. 

> In my case, for now I would like to use Stan to just evaluate log-{posterior, likelihood, prior} probabilities and their gradients for a given Stan model and use them for a custom sampler / inference method.

If I'm reading this correctly, you can already accomplish this in R (via `grad_log_prob` in `rstan` or `cmdstanr`), or through other interfaces via BridgeStan: https://discourse.mc-stan.org/t/bridgestan-1-0-0-released/29742

**Comment by simeoncarstens** [comment]
Oh wow, I did not know about BridgeStan! That looks super useful for my use case - I am currently using `httpstan` (and not even `pystan` :facepalm:) to access the log-posterior probability and its gradient, which is very, _very_ slow. BridgeStan should be much faster for this purpose. Thanks a lot for that hint!

As for my specific question above, BridgeStan or other interfaces indeed allow to access the log-probability and the gradient, but, if I'm not mistaken, only for the posterior. What I would love to have is access to the gradients of the log-likelihood and the log-prior(s) _separately_.
I think I can access the log-likelihood separately by implementing it manually in the `transformed parameters` section and accessing it in BridgeStan via `param_constrain`, setting `include_tp` to true. But that does not give me the gradient :slightly_frowning_face:

**Comment by bob-carpenter** [comment]
Sorry, @simeoncarstens, but Stan models don't separate prior and likelihood.  

What you can do, in a pinch, is write two Stan models, one with the likelihood and one with the prior.  You could even get clever with includes to not duplicate code, but it gets messy.

Or, you can write the log prior in a conditional,

```stan
data {
  bool include_prior;
}
...
model {
  ...
   if (include_prior) { ... prior ... }
}
```

Then you can use the same model including the data value as 1 to include the prior and 0 to exclude it.  Then there's just one model, but it's a bit messier.  You can do the same with the likelihood to evaluate *only* the prior if you'd like.

**Comment by bob-carpenter** [comment]
I've been thinking more about tempering algorithms lately and this is a missing feature in Stan.  It'd be nice to be able to have data in a Stan program be set dynamically.  Then we could temper the likelihood, for example for sequential Monte Carlo applications.
