### ISSUE TITLE
Low priority: Fix travis-ci and add code coverage

### ISSUE THREAD

**Issue by ido** [stan-dev/stan#607]
Very low-priority issue, mostly a placeholder so I don't forget later on.

Add code coverage metrics.  One possibility is to use Coveralls:
http://coveralls.io/

Travis-CI hasn't been building.  This is probably very low priority to fix:
https://travis-ci.org/stan-dev/stan

**Comment by syclik** [comment]
@bgoodri, if you've set up the travis job for RStan, can you try setting up Stan's travis config?

**Comment by syclik** [comment]
If you need permissions, just drop me a note.

**Comment by maverickg** [comment]
I can configure the travis ci a bit.  But one job can only last at most 30 mins though we can do multiple jobs. 

@syclik can you turn stan-dev/stan on in travis-ci.com if we are going to use it?  It looks like it was turned off.
