### ISSUE TITLE
Convert build system to CMake 

### ISSUE THREAD

**Issue by mbrubake** [stan-dev/stan#628]
It would be good to convert the build system to CMake.  This should make the build  system more modular and easier to maintain.  It should also allow for some nice features that are either not possible or too cumbersome to implement with the current build system like: generated build scripts (e.g., in CmdStan a script stan_build which takes a model file straight through to an executable), "installed" versions of Stan, building against system libraries, etc.  This issue is targeted at getting a CMake/CTest build system to feature parity with the current build system.

The beginnings of a conversion has been done in the feature/cmake branch.  Things that are left to do include:
- [x] Build the doxygen documentation
- [x] Build the manual
- [ ] Finish syntax-only model compile tests
- [ ] More CMakeLists.txt files throughout the source tree
- [ ] Stop using file(GLOB ...) to get source file lists
- [ ] Move models so that they're in the directories they're being used in
- [x] Convert CmdStan commands and docs
- [ ] Convert CmdStan tests
- [ ] Jenkins integration (@syclik what is required for this?)
- [ ] Windows testing
- [ ] Wiki documentation on how to use the new build system

**Comment by syclik** [comment]
bump.

We've simplified the makefiles in Stan, so hopefully this is much easier. It looks like to use other tools, we'll need CMake. I don't have the bandwidth to learn CMake well enough to implement it, but once we switch, I'll pick it up.

**Comment by bob-carpenter** [comment]
What other tools are you talking about?

- Bob

**Comment by bob-carpenter** [comment]
Also, can we use CMake without having to go through the
auto-configuration dance?  It has never ever worked for me in
anything I've ever tried to build based on CMake.  

Now maybe they were doing it wrong, but I'm afraid of CMake
for that reason.  

I think Boost's non-header-only compiles use CMake, so that
might be a model we could use if it works without going in and
fiddling with paths, etc., in the configuration scripts. 

- Bob

**Comment by syclik** [comment]
I was thinking of coveralls.io (Ido brought it up), but that doesn't
strictly depend on CMake. I happened to be looking at a tutorial that did.

So... I take back my original comment.

**Comment by syclik** [comment]
I also haven't had much success with other CMake systems. With the separate test script, our make files have gotten simple enough where I think CMake should be able to handle it.

**Comment by syclik** [comment]
Hi all, anyone object to me closing this issue? I don't think we'll be moving to CMake anytime soon. I haven't seen any real uses where CMake has made things easier.

**Comment by syclik** [comment]
If someone gets serious about cmake, we can create a new issue.
