### ISSUE TITLE
Save uniform draws from Metropolis acceptance tests

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#641]
Casella and Robert (1996)
http://scholar.google.com/scholar?cluster=11140625573835543967&hl=en&as_sdt=1,33
derives a Rao-Blackwell procedure that utilizes the random uniform draws produced by a Metropolis sampler when deciding whether to accept the proposal at that iteration. I guess the first step would simply be for Stan to save these so that users could do the Rao-Blackwellization themselves but down the line, we might think about whether the uniforms produced by the slice sampler would also be useful and whether to do Rao-Blackwellized calculations for the within-chain and between-chain variance.

**Comment by betanalpha** [comment]
I'm going to close this for now.  Adding Rao-Blackwellized Metropolis would require a complete change to the sample output and Monte Carlo estimator code.  This might make for a good project later once the code has been substantially cleaned up.
