### ISSUE TITLE
Tagging Variables

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#679]
@bob-carpenter and I spec'ed out a preliminary tagging scheme that will admit maximum marginal likelihood.  Comments welcome.

Tags are strings with no spaces declared in the Stan model, with either a prefix,

```
@tag real var;
```

or a suffix,

```
real var; @tag
```

Both are equally feasible to implement but offer different UX.  Any thoughts?

`stanc` will not take an argument specifying the active tag, and each interface will be responsible for designing how this argument is specified by the user.  The parser reorders the parameters such that the tagged parameters are first, and then defines constant indices, `n_tag_constrained` and `n_tag_unconstrained` where these tags end in the constrained and unconstrained parameter vectors, respectively.

This will allow us to define Eigen template expressions,

```
constrained_head(VectorXd& x) { x.head(n_tag_constrained); }
constrained_tail(VectorXd& x) { x.head(x.size() - n_tag_constrained); }
unconstrained_head(VectorXd& x) { x.head(n_tag_unconstrained); }
unconstrained_tail(VectorXd& x) { x.head(x.size() - n_tag_unconstrained); }
```

(plus the generalizations for Hessians) for the efficient slicing and dicing necessary for algorithms like Maximum Marginal Likelihood.

**Comment by bob-carpenter** [comment]
I'm closing this until we come up with an application and a design.
