### ISSUE TITLE
Matrix exponential

### ISSUE THREAD

**Issue by chjackson** [stan-dev/stan#680]
Feature request for a matrix exponential function, as raised recently on the stan-users list.

**Comment by jpritikin** [comment]
The most recent method is due to Higham,

http://epubs.siam.org/doi/abs/10.1137/090768539

**Comment by cdriveraus** [comment]
I've been working on an R package for estimating continuous time dynamic models, it would be great to be able to include an option to estimate using STAN. As far as I can see the only thing missing is the matrix exponential...

**Comment by wds15** [comment]
The matrix exponential would be extremely relevant for analytic solvable ODE systems when the solution is then exp(A*t). Here A is the coefficient matrix of the ODE system at hand. The catch is that the matrix must be evaluated repeatedly. The ODE systems which matter for PK systems fall into the class of "almost non-negative", i.e. only the diagonal entries are negative and all others are positive. These matrices apparently have some nice properties with respect to the solution of exp(At) which are documented here:

http://www.mscf.uky.edu/~qye/reports/expENM.pdf

I hope this helps for an implementation in Stan.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#32
