### ISSUE TITLE
Switch to C++11

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#714]
We should consider forcing `-std=c++11`. This would make g++-4.6.3 the oldest supported compiler and cause at least the following problems:

* llvm-g++-4.2 would not work on OS X prior to Mavericks
* g++-4.5 and lower would not work on RHEL
* VS 2008 and lower would not work on Windows

See https://wiki.apache.org/stdcxx/C++0xCompilerSupport

**Comment by bgoodri** [comment]
@ariddell Where do we stand on C++11 with Python / Windows? RTools is going to support g++-4.9 on Windows in about a month. See https://github.com/rwinlib/r-base#readme

**Comment by ariddell** [comment]
C++11 is go in Python.

**Comment by sakrejda** [comment]
This is magical.

**Comment by bgoodri** [comment]
With MSVC only on Windows? If so, we should try to unit-test with MSVC also.

**Comment by ariddell** [comment]
For PyStan on Windows it's MSVC 14.0.

**Comment by syclik** [comment]
We have a wiki page for this. We can open this again when we are ready.
