### ISSUE TITLE
Functions With Improper Derivatives

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#731]
Right now the Stan autodiff implements functions with improper derivatives (i.e. the derivatives do not exist at certain points), which is formally improper.  We have seen issues where people use functions like step, floor, and ceil in their models and the resulting sampling is very poor.

Personally I'd prefer to limit Stan to functions with proper derivatives only, but in any case we should have the discussion.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#33
