### ISSUE TITLE
remove all double and leading underscores in generated code

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#795]
- [ ] remove all double underscores and replace them with something else obscure (this technically breaks backward compatiblity, but probably won't be an issue in practice);  suggestions for replacements welcome

See:

http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier

which quotes this piece of the C++ spec:

```
17.4.3.2.1 Global names [lib.global.names]

Certain sets of names and function signatures are always reserved to the implementation:

    • Each name that contains a double underscore (_ _) or begins with an underscore followed by an uppercase letter (2.11) is reserved to the implementation for any use.
    • Each name that begins with an underscore is reserved to the implementation for use as a name in the global namespace.165
```
- [ ] replace leading underscores, like those in `optimization/bfgs.hpp`

**Comment by syclik** [comment]
This one is easy. Should be a 5 minute fix for someone.

**Comment by syclik** [comment]
I lied. This one is not easy.

It requires getting into the code generator to make a proper fix.

**Comment by bob-carpenter** [comment]
Let's fix that in a separate issue.  That's all tied up with
the name mangling issue, which we should also do.

**Comment by syclik** [comment]
Unfortunately, it's tied together through `src/stan/model/prob_grad.hpp`.

That's the only place that our code has double underscores as identifier names. The rest are in tests, which are easy to deal with. If I were leaving `src/stan/model/prob_grad.hpp` alone, it would really be quick.

**Comment by rok-cesnovar** [comment]
Closing this issue as its a code-generation issue made for stanc2. If this is still desired please reopen and we can transfer to stanc3.
