### ISSUE TITLE
include what you use in models

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#811]
Alexey Stukalov reports that on a distributed filesystem, Stan models take 2 minutes to build, whereas on a local system, the same model takes 13 seconds.

To cut down these builds, our best strategy is probably to figure out how to include only what we need rather than the entire model header include.

To make this work, we won't be able to include all of Eigen or large swaths of Boost, either, because the number of Stan files is minimal compared to those libs.

If a function uses a matrix argument, it needs the relevant matrix libs.  If it doesn't, then you don't need to bring those in.  But all the matrix lib gets imported for densities anyway.  And we need most of the matrix libs now for running Stan because MCMC and optimization moved to Eigen for parameter vectors.

**Comment by bob-carpenter** [comment]
Install this (from #225):

http://code.google.com/p/include-what-you-use/

**Comment by bob-carpenter** [comment]
* [ ] remove all the header files that just include whole directories and include what you need directly

**Comment by ariddell** [comment]
I was wondering about this. So is the plan to remove those directory-level include-alls? While it's not pretty, icwyu seems to work rather well.

**Comment by bob-carpenter** [comment]
Yes, the directory level includes aren't so useful because
they're organized by directory structure, not by functionality.
So just including, say math/rev.hpp doesn't give you all of
reverse-mode autodiff, because it's missing memory and things
defined in math/prim/ that aren't directly included.  And there
are further order dependencies (at least for now) that are
hard to maintain by directory.

The plan's to have each file more directly include what it
uses and then provide top-level API includes similar to our
model-header now, but for external use.

- Bob

**Comment by ariddell** [comment]
Got it.

I didn't realize it was such a performance issue. I had already run icwyu on the PyStan and RStan model header wrappers but had put the result to one side..

**Comment by bob-carpenter** [comment]
Overincluding is mainly a performance issue for reading in files on
non-SSD computers or over networks. 

The motivation for include-what-you-use is more to keep the
dependencies clearly identified and minimal.

The motivation for getting rid of the file-based directories is
that they're not doing anything other than requiring maintenance.
And in fact some of them are buggy in that they don't respect
ordering requirements on the recursive metaprogram includes.

- Bob
