### ISSUE TITLE
List of backward incompatibilities for Stan 3.0

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#812]
Feel free to add expected/desired changes directly to the issue.

#### Argument Configuration
- [ ]  "file" to "source"
- [ ]  Something better than "engine"

#### Model
- [ ] Rename write_array method

**Comment by jgabry** [comment]
Nothing has been added to this and the Stan 3 discussions have moved elsewhere, so I'm going to close this to reduce open issues. Feel free to reopen if you think it shouldn't be closed.
