### ISSUE TITLE
reduce duplicate operations in probability functions

### ISSUE THREAD

**Issue by PeterLi2016** [stan-dev/stan#819]
See issue #706 for full details [mostly reproduced below].

Comments from Bob:

19.  (src/stan/prob/distributions/univariate/continuous/chi_square.hpp, green 352) this line `const T_partials_return Pn = 1.0 - gamma_p(alpha_dbl, beta_dbl * y_dbl);` followed by 
`ccdf_log += log(Pn);` is bad.  this should at least be using log1m(...).  But ideally, we shold have different, more accurate formulas for ccdfs --- that's the whole point of having them defined.  This isn't urgent, but long term, it'll help with stability.

23.  (src/stan/prob/distributions/univariate/continuous/exp_mod_normal.hpp) lots of repeated subexpressions

24.  (same file, green 232)  this kind of line break is very confusing:
```
scaled_diff * SQRT_2 - deriv_2 
* sigma_dbl * SQRT_2
```
Code should follow the same conventions as mathematics typesetting, where this would be rendered as
```
scaled_diff * SQRT_2 
- deriv_2  * sigma_dbl * SQRT_2
```
That way, the line break reinforces the operator precedence rather than confusing it.  Same thing on line green 235 (and elsewhere if you find other instances).  Similarly, I would break the lines starting on green 239,
```
operands_and_partials.d_x4[n] += exp(0.5 * v_sq - u) 
             * (SQRT_2 / sqrt_pi * 0.5 * sigma_dbl 
                * exp(-(v / SQRT_2 - scaled_diff) * (v / SQRT_2 - scaled_diff)) 
                - (v * sigma_dbl + mu_dbl - y_dbl) * erf_calc) / cdf_;
```
as
```
operands_and_partials.d_x4[n] 
  += exp(0.5 * v_sq - u) 
     * (SQRT_2 	/ sqrt_pi * 0.5 * sigma_dbl 
        * exp(-square(v / SQRT_2 - scaled_diff))
        - (v * sigma_dbl + mu_dbl - y_dbl) * erf_calc)
     / cdf_;
```
No big deal not updating these, though I think it does make the code much easier to read.

27.  (src/stan/prob/distributions/univariate/continuous/exp_mod_normal.hpp, green 467)  this is another log1m situation --- maybe just searching for log(ccdf) will find them all --- it's one nice benefit of consistent naming.  Oh, and I see the same thing with log(Pn) in the beta and gamma distribution code, and in 23 other places I'm not going to try to enumerate.

28. (src/stan/prob/distributions/univariate/continuous/exponential.hpp, green 160 and elsewhere)  The expression `1.0 - exp(...)` is going to be very prone to unnecessary underflow as the inner term approaches 0, because the smallest value 1 - exp(...) can return is around 1e-14, whereas double-precision floating point should be able to accomodate closer to 1e-300.  It should be more stable to return -expm1(...).  

29. (gumbel.hpp, line 286 green):  The built-in function log1m_exp(...) is more robust than evaluating log(1 - exp(...)) directly or even log1m(exp(...)).

30  (green 736, grad_F32_test.cpp)
To test within 1e-5, it's not necessary to have this many digits:
`EXPECT_NEAR(0.415359887777218792995404669803015764396172842233556866773418,grad1[0],1e-5);`

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#37
