### ISSUE TITLE
(multivariate) normal operating on sufficient statistics

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#822]
Joshua N. Pritikin mentioned on stan-users that the <a href="http://openmx.psyc.virginia.edu">OpenMx package</a> has a multivariate normal that works on sufficient statistics:

<blockquote>
In OpenMx, multi_normal has two implementations. One implementation  handles data in the form of 1 case per row. The other implementation handles data as a covariance matrix (and means). These two approaches are equivalent for certain data (no missingness, etc).
</blockquote>

I would think the second implementation would be much more efficient because the sufficient statistics could be computed just once.

Does anyone know what the density over the sufficient stats would look like?

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#38
