### ISSUE TITLE
modeling language "cheat sheet"

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#868]
- [ ] Create a one or two-page "cheat sheet" for the Stan modeling language

Suggested by Tamas Papp on stan-users, with examples
- http://clqr.boundp.org/ for Common Lisp, and
- https://www.stat.auckland.ac.nz/~stat782/downloads/auctex.pdf for AUCTeX.

I particularly like Eigen's "Quick reference guide":
- http://eigen.tuxfamily.org/dox/group__QuickRefPage.html

**Comment by syclik** [comment]
This issue was moved to stan-dev/propaganda#1

**Comment by syclik** [comment]
I just moved this to the stan-dev/propaganda repo.
