### ISSUE TITLE
enhnaced print statement

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#880]
Tamas Papp suggests on stan-users adding an enhanced print function specialized for variables.
#### Printing arguments to the print call

Instead of writing

```
print("i = ", i, ", x[i] = ", x[i], ", y[i] = ", y[i]);
```

there could be a function printvars which would be called as

```
printvars(i, x[i], y[i]);
```

This would print its arguments, too, followed by values, separated by commas. In Lisp-like languages one would implement printvars as a macro, since it needs to see the variable names it was called with, and I don't know if the parser of Stan retains this information.

When printvars encounters a literal string, it could just print that as
is, eg 

printvars("debugging inner loop", i, x[i], y[i]);

would be equivalent to

print("debugging inner loop", "i = ", i, ", x[i] = ", x[i], ", y[i] = ", y[i]);
#### Interpolating, similar to printf

I guess there is no need to explain. Would extend current print in an upward-compatible way (except if one uses `%` in strings).
#### Interpolating version of printvars

Literal strings that have formatting directives would just gobble as many of the following arguments as needed, but otherwise it would work as printvars.

**Comment by syclik** [comment]
@bob-carpenter, should we keep this open? If so, I'll rename the issue to "add printf() function"

**Comment by bob-carpenter** [comment]
I hate to close this because it's actually a reasonably well-formed and concrete feature request, but:

* I don't think it's worth having a new function `print_vars` just to print vars with names

* I think `printf()` is a bad idea because it causes runtime errors that can't be caught at compile time

So I'm closing this reluctantly because I don't think we want to do it.

**Comment by syclik** [comment]
Thanks.

I'm guessing we can't think of something as concrete that we want to do?
