### ISSUE TITLE
reorganize files in agrad/rev

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#886]
* [ ] rename directory `internal` to something more informative.  I'd like to reserve "internal" for things that won't ever be used by someone using the C++ API as a C++ API

* [ ] File `calculate_chain.hpp` is a utility for the functions involving log-sum-exp in directory `functions`;  at the very least, move that method down to the functions directory

**Comment by syclik** [comment]
This was fixed with #1222.
