### ISSUE TITLE
`increment_log_prob` only allowed in the `model` section

### ISSUE THREAD

**Issue by tpapp** [stan-dev/stan#889]
Running

``` stan
parameters {
  real<lower=0> y;
}
transformed parameters {
  real<lower=0> y_inv;
  y_inv <- 1 / y;
}
model {
  y ~ gamma(2,4);
}
```

from the manual using rstan (Version: 2.4.0, Date: 2014-07-20), I get the error message

```
TRANSLATING MODEL 'gamma' FROM Stan CODE TO C++ CODE NOW.
Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  failed to parse Stan model 'gamma' with error message:
EXPECTATION FAILURE - DIAGNOSTIC(S) FROM PARSER:

sampling only allowed in model.


LOCATION OF PARSING ERROR (line = 8, position = 21):

PARSED:

transformed parameters {
  real<lower=0> y;
  y <- 1 / y_inv;
  // change
  increment_log_prob

EXPECTED: <eps> BUT FOUND: 

( -2 * log(y_inv) );
  // adjustment
}
```

Moving `increment_log_prob` to the `model` section resolves the issue, but the manual says it should be allowed in `transformed parameters`, too (and many examples have it there).

**Comment by ksvanhorn** [comment]
I'd like to note that the Stan compiler and the manual are still in disagreement on this issue. Section 25.2 of the Stan 2.8.0 Reference Manual states that 

    "Statements in the transformed parameter block and model block can have an effect on the log probability function defined by a model."

and

    "The total log probability is initialized to zero. Then statements in the transformed parameter block and model block may add to it. The most direct way this is done is through the log probability increment statement,..."

whereas the Stan compiler gives an error if you use increment_log_prob in the transformed parameters block.

**Comment by tpapp** [comment]
Responding to the mention on the mailing list. Since I opened the original issue, I have been thinking about this. I think that there are two, almost orthogonal, issues here:

1. what additions to the final log (posterior or likelihood) function is enabled for which mode (ML or Bayesian).

2. what variables are recorded. Eg transformed parameters are. But sometimes it would make sense to save the posterior sample for some intermediate variables. Or even disable saving some parameters, if one wants to make the resulting file smaller.

(1) is about `~` (or equivalently incrementation) statements, while (2) is about variables.

IMO Stan should have semantics for designating this information in a stan file.

@bob-carpenter: I would rather dispense with the `transformed parameters` block altogether, and have everything in the `model`. The user would just declare variables, make transformations, and then designate that some variables are recorded, some aren't. By default all params would be recorded, and nothing else (except generated quantities). The user could change this for all variables, eg at the declaration:
```stan
parameters {
  real x discarded;
  real y; // kept by default
}
model {
  real z saved;
  real v; // discarded by default
}
```
Blocks like
```stan
jacobian_adj {
}
prior {
}
```
would designate the semantics of pieces of code.

**Comment by joshchang** [comment]
Hi, at the moment is there any workaround to prevent Stan from storing certain variables? I have a high-dimensional random matrix that I am marginalizing over and I cannot figure out how to keep Stan from storing it.

**Comment by bob-carpenter** [comment]
This comment isn't relevant to this issue.  It looks like someone's removed
it already for that reason.  So feel free to remove this one, too.

**Comment by tpapp** [comment]
Is there any chance of fixing this issue (ie allowing `increment_log_prob` statements in the `transformed_parameters` block) in 2.10?

**Comment by bob-carpenter** [comment]
2.10 is frozen awaiting the release, so no new features.

It should be a relatively easy patch because the
code runs in the same C++ context.  I should be able to
get it out in 2.11.

Is the the motivation is that you have local variables
in the transformed parameters block that you want to include
in an increment_log_prob statement?  If not, the code can just
move down to the model block.

First we need to see if it's something everyone thinks
is a good idea.  As I've said before, it was my original
intent to allow it because it seemed the natural place to
put Jacobian adjustments.

- Bob

**Comment by tpapp** [comment]
The motivation is the following (very simplified): there is a parameter μ ∈ [0,1], which I am transforming to some α, which I need to record, and also they are on the LHS of some `~` statements (the parameter of interest is α, but transformations from μ are required because of censoring). However, during the transformation I calculate a large set of interim quantities, let's call them Λ, which are needed to increment the lp.

The cleanest, ideal solution would be defining a function `mu2alpha_lp`, which computes α from μ, **and** increments the lp at the same time, make α a transformed parameter, deal with corresponding `~` statements in the model block. This is currently ruled out by what I perceive as an arbitrary restriction.

The second best, which I am using currently, is have a `mu2alphaLambda` return an extra element in the vector it calculates, which is the sum of the log Λs. This I then extract in the `model` block, and increment lp accordingly. Code is somewhat ugly as a result.

My impression is that many nontrivial calculations follow this pattern: interim quantities during the transformation can be reused for Jacobian adjustments. A common pattern for me is transformations which involve fractions, eg when α = x/(x+μ) for some x (which is data), then I can reuse the denominator.

If I was not using functions, I could define an `lp_kitchen_sink` transformed parameter, accumulate all the Jacobian adjustments there, and use it in the model block in a single step. However, since functions in Stan cannot return multiple values and the variable would not be in scope for them, I would have to go through the same kind of acrobatics cutting up vectors do implement it.

**Comment by bob-carpenter** [comment]
Thanks for the overview.  Yes, I imagine that's not an uncommon
pattern.  We usually recommend making everything local in the model
block then recomputing as necessary in generated quantities, which is
roughly free computationally for a model of any complexity (no derivatives
and only computed once per iteration).

There's a more general feature request:

  https://github.com/stan-dev/stan/issues/1289

and also a more specific one that you created 2 year ago:

  https://github.com/stan-dev/stan/issues/889

I'll take a shot at getting these done soon as long as there
aren't convincing objections from the dev team.

- Bob

**Comment by sakrejda** [comment]
On Wed, May 18, 2016 at 2:19 PM Bob Carpenter

**Comment by bob-carpenter** [comment]
See #1289
