### ISSUE TITLE
sparse Matrix as new data type

### ISSUE THREAD

**Issue by andrepfeuffer** [stan-dev/stan#890]
distribution functions in STAN take great benefit of being vectorized. However, there exists some characteristic problem where these matrices contain many 0's. Thus in terms of speed it would be favoriable to have both the vectorized version and a sparse representation who avoid's the many useless 0 terms.

**Comment by rtrangucci** [comment]
@syclik did we take care of this with csr_extract functions?

**Comment by bob-carpenter** [comment]
No, but it should be moved to the longer-term issues if it's not alread there.  We need a proper data type for sparse matrices to replace the hack with arrays (not that the hack isn't super useful in the interim!).

**Comment by syclik** [comment]
I'm closing this for now. It's on our wiki: https://github.com/stan-dev/stan/wiki/Longer-Term-To-Do-List#sparse-matrices. We don't really have a good path forward yet.
