### ISSUE TITLE
foo.hpp includes all of directory foo

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#941]
For consistency, I'd like to have all of our encapsulated include files, to bring in everything under the directory for which they're named.

Two violations I know of:

1.  `src/stan/agrad/rev.hpp` doesn't bring in `src/stan/agrad/rev/error_handling/**` or `src/stan/agrad/rev/matrix/**`.  Either those directories should be moved or `rev.hpp` should bring it all in.  

2.  `src/stan/agrad/rev/error_handling.hpp` does not bring in `src/stan/agrad/rev/error_handling/matrix/**`

In both of these cases, I think the desire is to have something that brings in `agrad/rev` without matrices.  That's fine, but to stay consistent, we need a new directory structure.

No rush on this one.

**Comment by syclik** [comment]
This was fixed with #1411.
